---
title: "Appendix 1: The Manuscripts"
---

Accessing medieval manuscripts is never without challenges. While advancements in digitization and cataloging have made many manuscripts more visible than ever, researchers still face significant barriers and unforeseeable obstacles. Under normal circumstances, every Version T manuscript may be consulted by researchers in person, but my attempts to access the sole copy housed at the British Library highlight the precariousness of even the best-laid plans for in-person consultation. My first visit to the BL in late September 2022 was curtailed by the closure of public buildings for the funeral of Queen Elizabeth II, limiting my time with MS Additional 36614 to less than an hour. A second trip in late November 2023 — meticulously planned almost a year in advance — again proved fruitless in the aftermath of the October 2023 cyberattack on the British Library.^[ An incident review of the October 2023 cyber attack was released by the British Library in March 2024. The report provides information regarding the nature of the attack, its scope, the immediate response, and the Library’s plans for recovery and prevention. https://www.bl.uk/home/british-library-cyber-incident-review-8-march-2024.pdf/
] For months, this attack not only made it impossible to retrieve manuscripts for consultation in the reading room but also limited access to the detailed information of the library’s digital and analog records, and this attack has made it impossible to purchase any reproductions of manuscripts from the BL’s Image Licensing Department. Despite the staff’s best efforts to help me make the most of my visit in 2023,^[ In addition to MS Additional 36614, I was hoping to consult five other manuscripts held at the BL. It was impossible under the circumstances to retrieve the original manuscripts, but I was offered the possibility of consulting the microfilms, which could be found using their card catalog. Out of the six manuscripts I hoped to see, only one (MS Old Royal 20 D VI, which contains a copy of Version Z of *La vie de sainte Marie l’Égyptienne*) was available in this format. I was told not to go out and buy a lottery ticket any time soon by a sympathetic staff member.
] this one T-manuscript remained out of my reach. These experiences underscore the critical value of supplemental resources: while not every interested reader can consult their manuscripts firsthand, many benefit from the carefully recorded observations of those lucky enough to work with these precious objects.  

This appendix aims to bridge gaps in accessibility by providing detailed information about each manuscript in the T corpus. Drawing on my own direct observations — conducted generally under more favorable conditions than those described above — as well as the invaluable work of previous catalogers and editors,^[ These works include digitized and microfilm reproductions, detailed catalog records both online and in print, and other useful studies.
] I describe the current state of the corpus of Version T manuscripts, offering a thorough commentary on each of the manuscript’s current location, condition, and accessibility. In particular, I build on Peter Dembowski’s edition of *La vie de sainte Marie l’Égyptienne*, which, though now almost fifty years old, still serves as the cornerstone of all existing scholarship on the French Mary the Egyptian legend and continues to be an incredibly useful launchpad for further inquiry. While Dembowski provides a broad overview of the entire French tradition of the *Vie*,^[ Dembowski’s edition of less than three hundred pages covers a great deal of ground. His introduction situates the French tradition of the *Vie* within the broader context of the legend. His edition provides edited transcripts of thirteen versions (T, X, V, W, N, O, O^1^, Z, U, Y, L^1^, L^2^, and L^3^), each based on a single manuscript copy, and includes notes on textual variants across the manuscript copies. Notably, Dembowski’s corpus includes all French versions of the *Vie* except for Rutebeuf’s Version R, which he acknowledges but does not himself edit. He also offers brief descriptions of all forty-two of the known manuscript copies containing these many versions (excluding those containing R), while noting the existence of one additional copy of Version O — Basel, University Library, Comites Latentes 102 (formerly Phillipps 3660) — which he reports was accessible only for a cursory examination at the time (“n’est accessible que pour un examen superficiel,” 173), and so, he excludes it from his table of manuscripts and variance notes and provides no description of it.
] my focus on Version T allows for more detailed descriptions of each manuscript’s provenance, material characteristics, and unique features, as well as the aggregation of new metadata not previously available in his edition, such as the existence of digitized and microfilm reproductions. By gathering and synthesizing this information, this appendix offers a resource for other scholars, fostering deeper engagement with the material record of Version T but also pointing toward new areas of investigation that remain to be explored.  

## The Corpus of Version T Manuscripts^[The initials used to identify each of these manuscript copies were assigned by Alfred Baker in the fourth chapter (“Les manuscrits de la vie rimée” pp. 182-187) of his edition. At the time however, Baker was unaware of the Manchester fragment as it would not be uncovered until 1923, and so, he labeled the Damascus fragment simply F. Dembowski adopted Baker’s use of these identifying initials, adding superscript numbers to distinguish between the two fragments.]  
There are, in all, eight known manuscripts of Version T, including two fragments:  

**T-A**: Paris, Bibliothèque nationale de France (hereafter BnF), Français 23112, ff.334v-344r. Late 13th century, provenance pre-17th century unknown.  
**T-B**: Oxford, Bodleian, Canonici Miscellaneous 74, ff.109r-120r. Early 13th century, provenance pre-18th century unknown.  
**T-C**: Oxford, Corpus Christi College, 232, ff.35r-64v. Early 14th century, from Canterbury.  
**T-D**: Paris, BnF, Français 19525, ff.15r-26v. Second half of 13th century, from Oxford.  
**T-E**: Paris, BnF, Arsenal, 3516, ff.113v-117v. 1267/1268, from Artois.  
**T-L**: London, British Library, Additional 36614, ff.271v-282v. Second half of 13th century, provenance pre-19th century unknown.  
**T-F^1^**: Manchester, John Rylands Library, French 6, ff.8r-8v. Second half of 13th century, provenance pre-19th century unknown.  

> At least folios 1-8 of French 6 were originally part of London, British Library, Egerton 2710. Second half of the 13th century, provenance pre-15th century unknown.

**T-F^2^**: The location of the original fragment — dated to the second half of the 12th century and most likely originating in Europe — is unknown, but a photographic copy may be found here:\

> Berlin, Staatsbibliothek, *Photographien von ausgewählten Fragmenten aus der Omayyaden-Moschee in Damaskus in verschiedenen Sprachen*, 1908. Mss simulata orientalia 6, Orientalische Handschriften digital, Photographs 89 (verso) & 101 (recto), http://resolver.staatsbibliothek-berlin.de/SBB000074F100000000.  

For the most part, these manuscripts are legendaries containing the Lives of numerous other saints and other texts of religious interest, though there are some exceptions, such as T-L, which pairs the Life of Mary the Egyptian with a compilation of texts centered on Chrétien de Troyes’s *Perceval*. The distribution of these manuscripts is primarily centered in France and the UK, with three manuscripts housed in the Bibliothèque nationale de France (BnF), two at the University of Oxford, one in the John Rylands in Manchester, and one in the British Library (BL) in London. The only known records of the smallest fragment of Version T, T-F^2^, are located in the Staatsbibliothek of Berlin.  

None of the T manuscripts have exact dates or places of origin, but the date range of this set of manuscripts spans from the second half of the twelfth century to the early fourteenth century, with most (T-A, T-D, T-L, and T-F^1^) landing somewhere in the second half of the thirteenth century. The earliest suggested dating among these manuscripts is for T-F^2^, and T-C is considered the latest copy. The provenance of a few (T-C, T-D, and T-E) have been more precisely localized, but based on their linguistic and paleographic characteristics, we can comfortably say that the manuscripts of this corpus — with the possible exception of the now lost T-F^2^ fragment whose provenance is more obscure — originate geographically from the area spanning northern France and southern England.  

The physical size of these manuscripts vary. The largest manuscript in this corpus both by height and width and by the number of its parchment folios is T-E. T-A, T-E, and T-L are each about the size of a coffee table book, while the smallest manuscript (excluding the fragmentary copies) by its height and width is T-B, which is about the size of a mass market paperback novel, and the smallest by its folio count is T-C, making this copy similar in size to a DVD case. At 225x155mm, T-D is a larger but still quite portable size, similar to most modern hardcover bestsellers. The height and width of fragment T-F^1^ is 275x190mm — about the size of the average iPad —, but it offers only one folio containing Version T bound together with other fragmentary texts to form a thin volume. The lost fragment T-F^2^ likewise only offers one full leaf of Version T, but its dimensions were exceptionally small, measuring only 70x50mm — or about the size of a matchbox. In comparing these manuscripts to more familiar modern day objects, I do not intend to assign any particular value to these codices based on their size. Rather, I wish to draw attention to a physical aspect that can be too easily overlooked in traditional catalog descriptions, and which may greatly inform our understanding of these objects by giving us basic evidence as to who read them, in what context they were read, and for what function they served.^[For example, the dimensions of the only extant manuscript copy of *Marie l'Égyptienne* - Version Y (Lille, Bibliothèque municipal, 795) are 390x280mm, but the physical reality of these numbers is much harder to conceptualize and remember than imagining the average sized oval dutch oven, which can be of very similar dimensions. With 589 folios, MS 795 is also quite a stout volume — measuring 145mm in depth, or about the length of an iPhone — and is too heavy for one person to lift and move comfortably. Thinking about all this size data more concretely helps us to more immediately understand that this was obviously not a particularly portable volume.
]  

Among the T manuscripts, there are no images — neither miniatures nor historiated initials — to be found. Only copy T-E would have included a miniature (approximately 80x65mm) of Mary the Egyptian — most likely depicting the scene in which Zozimas gives her his cloak, based on the surviving miniatures from manuscripts containing other versions of the *Vie* —,^[There are sixteen extant medieval manuscript images associated with full French texts of *La vie de sainte Marie l’Égyptienne*. Among these, seven depict the encounter between Zozimas and Mary the Egyptian in which the holy man offers the nude Mary his cloak. For example in the miniature of a late thirteenth-century copy of Version U (Lyon, Bibliothèque municipale, 867, f.71v), Zozimas is shown shyly looking away as he gives his cloak to Mary who stares back at him. Her nude body is entirely enveloped by her long hair, and their hands meet in the center of the miniature.
] but this image has been lost due to the mutilation of the manuscript.  

In terms of accessibility, at time of writing, five of the manuscript copies of T have been digitized and are freely accessible online to anyone with an internet connection. These are T-A, T-D, T-E, T-F^1^, and T-F^2^. Two of these, though, are not available in color as T-A’s digitized copy was produced from its black and white microfilm and T-F^2^’s online copy is a digitization of the photographic reproduction of the lost fragment. The only T manuscripts that have not been digitized are all located in the UK. These are T-B, T-C, and T-L.^[There is an ongoing effort at the British Library to digitize more and more of their manuscript collections, but according to their most recent list of fully digitized manuscripts released in 2022, T-L has not yet been digitized. This list is available via Calum Cockburn’s blog post for the *Medieval manuscripts blog* of the British Library on 18 January 2022.] Four of the T manuscripts (T-A, T-C, T-D, and T-E) are available at their respective libraries on microfilm, and there is also a microform copy of T-L available at the Van Pelt Library at the University of Pennsylvania.^[ Unfortunately, I became aware of this microform copy too late to make use of it directly to inform this dissertation. The microforms held at the Van Pelt may be consulted on site in the library’s Microtext Department in Philadelphia, but the reproduction and interlibrary loan of any Van Pelt microforms would require the permission of the repository holding the original manuscript — in this case the BL. A complete list of the Van Pelt microforms may be found here: https://guides.library.upenn.edu/MedievalMSSmicrotext]  Taken together, all of this means that T-B is the only Version T copy whose full contents may only be considered in person in the reading room.^[In the reading room at the Bodleian, readers are permitted to take their own images for research purposes, and so I have been able to inform this dissertation with images of T-B that I took in the fall of 2022. However at the British Library, readers are not permitted to take pictures of certain manuscripts, including manuscript T-L.] While the availability of these manuscripts varies — from in-person consultation to digitized copies or microfilm — this appendix consolidates and contextualizes the scattered information about this corpus in one place, adding particular aspects of the manuscripts that have either not been discussed or systematically treated elsewhere. By preserving and synthesizing these details, this appendix supplements existing modes of access, offering a comprehensive resource for understanding the extant material record of Version T.  

## T-A
### Paris, BnF, Français 23112. ff.334v-344r. Late 13th century, provenance pre-17th century unknown.
This manuscript, housed at the Richelieu site of the BnF, is a late thirteenth-century codex comprised of 344 parchment folios with some additional front and back laid paper pages.^[These paper pages have visible chainlines and watermarks. The innermost front paper page features a watermark resembling a cluster of grapes, and the outermost back paper page has a watermark of a fleur-de-lis with the initials “CB” on a banner underneath.] The manuscript’s exact provenance before the seventeenth century is not known, but it is known to have been in the possession of Cardinal Richelieu, as noted in the BnF’s online catalog description and confirmed by Ginguené, who mentions that the manuscript was one of those given to the Sorbonne by Richelieu.^[“Ce manuscrit est un de ceux qui furent donnés à la maison de Sorbonne par le cardinal de Richelieu” (112).] The stamp of the Bibliothèque de Sorbonne may be seen in the bottom right corner of f.1r. Following the prayer written in rhyming couplets that concludes this manuscript,^[This prayer begins in the line immediately following the Life of Mary the Egyptian on f.344r with a parted blue and red initial “B” that is two lines high.] there is a date offered on f.344v — written within the text block and in the same hand as the scribe — reading “Explicit iste liber / anno d[o]m[ini] M CC”, but according to the online BnF catalog, “Cette date ne paraît pas être celle de la transcription du manuscrit, dont l’écriture présente tous les caractères du XIIIe siècle.”^[https://archivesetmanuscrits.bnf.fr/ark:/12148/cc52450n]  
The scribe who copied the text of *Marie* has not been identified, but the manuscript is written in a dialect that includes some Picard elements, such as the use of “le” for the feminine singular article and “jou” as a variant spelling of “je.”^[In his edition, Dembowski says the language is “fortement picardisée” (25), but he does not elaborate with many linguistic details.] The scribe carefully avoided the medieval sewing repairs in the parchment when copying, and the writing on each page begins above the top ruling line, which supports the dating of this manuscript to the thirteenth century. The line breaks on each page respect the verse structure of each text. For each line, there is initial letter separation with all of the initial letters of each line written in majuscule and all other letters of the text block written in minuscule. In terms of glosses, the manuscript contains minor corrections throughout, added by a hand other than the original scribe. These corrections combined with the careful formatting of the text throughout the codex suggest that the manuscript was carefully prepared for the purpose of reading.  

The codex contains a total of sixty-three texts, including, of course, Version T of *La vie de sainte Marie L’Égyptienne*, which is the last text in this collection and is preceded by a Life of Catherine of Alexandria. Français 23112 offers 1,526 verses of T without any significant lacunae — making it the most complete of the thirteenth-century copies — and serves as the base copy for Dembowski’s edition.^[On his choice of base copy, Dembowski writes, “Ce choix est grandement simplifié du fait que, comme nous l’avons déjà vu, les mss. B et D donnent des versions très abrégés du récit et que les mss. E et L ont des lacunes considérables. Il ne nous reste donc que A et C. Vu que C est plus récent que A, vu que C a un nombre de leçons inférieures à A, vu que le scribe de A donne un texte très soigné, vu enfin que le texte de C est connu grâce à l’édition de Baker (sans mentionner celle de Cooke), le choix de A s’impose” (30).] In his description, Dembowski offers this short list of other contents in this manuscript: “Il contient aussi une partie du *Poème moral, li Livres de la mort* (en vers) attribué à Helinand, *l’Aventure au chevalier* (en vers) et *li Miracles du clerc de Roem* (en vers) attribué à Thibaut de Vornon, en tout 63 morceaux” (25). Among the many saints’ Lives included in this manuscript, we also find that of another penitent saint from Egypt: Saint Thaïs. The Life of Mary the Egyptian is introduced in the first column of f.334v by the red-ink rubric “Chi [com]mence le vie de marie egyptiene,” and it concludes in the first column of f.344r with the explicit “De nos ames au jugem[en]t. Am[en].” Folio 344 has been cut along its bottom outer corner, resulting in the loss of some text from the manuscript’s concluding prayer, but this damage does not interfere with the Life of Mary the Egyptian.  

The overall dimensions of the manuscript are 325x230mm, with a writing space of 240x175mm on each page. The text is arranged in two columns per page, with each column measuring 79mm in width and typically containing 40 lines of text, most of which have an average line height of 6mm. There is no visible pricking on the folios, and the pencil ruling is rarely discernible throughout the manuscript. Français 23112 features catchwords as well as quire signatures (in the form of Roman numerals in black ink) at the bottom center margin of the last verso of each quire. On some rectos, such as f.3r for example, running titles in faded black ink and medieval foliation numbers in the form of Roman numerals are sometimes still visible in the top margin, but on most folios these have been cut off. However, the texts are still clearly numbered in a medieval hand using Roman numerals centered in the top margin above the text block in alternating red and blue ink. Otherwise, the foliation of this manuscript is modern with Arabic numerals written in pen in the top right corner of each recto.  

The manuscript’s decorative elements are limited but noteworthy. It does not contain any illustrations, nor is there any space left blank for anticipated miniatures, but highly detailed pen-flourished initials are executed in alternating red and blue ink throughout the manuscript. Occasionally visible under these intricate initials are the scribe’s note to the rubricator as to what letter should be added. Most of these initials are only two lines high, but much larger initials — as tall as 10 lines in height — indicate the beginning of each text. The parted initial “O” of this copy of *La vie de sainte Marie l’Égyptienne* is six lines high, and its width causes the first six verses of the text to bulge out into the center margin of the page.  

The manuscript is bound in red moroccan leather with the arms of Richelieu in gold on the front and back cover. These arms bear the phrase, “HIS FULTA MANEBUNT” (or roughly “They will remain supported by them”). The spine offers the title “VIE DES / SAINCTS” in gold lettering. The current binding, is of course, not original to the manuscript, and a modern table of contents is found on the verso of the frontmost parchment folio (a parchment folio that is not included in the foliation count), facing f.1r. The binding is quite tight, making it difficult to read the text closest to the gutter throughout the codex. This tightness would likely make it difficult to execute a full color digitization from the codex. During the restoration of the manuscript, some patches were added to repair holes, such as on the outer edge of f.174 near the bottom corner. On f.200r, there is a nearly invisible slice, which seems to have been the result of an accident, through the parchment that runs about 40mm long near the bottom of the outer text column. The parchment throughout the codex is arranged with hair-side facing hair and flesh-side facing flesh.  

## T-B
### Oxford, Bodleian, Canonici Miscellaneous 74. ff.109r-120r. Early 13th century, provenance pre-18th century unknown.
Canonici Miscellaneous 74 is a small but significant codex safely datable to at least the early thirteenth century,^[Campbell notes that the hands are all recognizable as thirteenth-century (236).] possibly dating to the late twelfth century, making it the oldest extant copy of Version T.^[Cruz-Sáenz writes, “...its dialectal traits allow us to say it might have been written even in the late twelfth century. It is undoubtedly the oldest extant text of the poem” (23).] Offering 1,327 verses of *La vie de sainte Marie l’Égyptienne*, T-B serves as the base text of Cruz-Sáenz’s edition and has informed the works of Emma Campbell, Amy Ogden, and Erik Rankka.^[At 1,327 verses, B is the shortest among the full copies of Version T.] In addition to the Life of Mary the Egyptian, this manuscript also contains the Lives of Saints Alexis (ff.1r-19r), Julienne (ff.62r-84v), Euphrosine (ff.87r-108v), and André l’Apôtre (ff.120r-131r) — with Mary the Egyptian coming between these last two saints — as well as the *Poème moral* (ff.19r-62r) in quatrains and *Li ver del juïse* (ff.131r-138r).  

The manuscript is composed of 138 parchment folios,^[Emma Campbell calls the writing support “vellum” (236).] with two front paper pages and one paper endpage, undoubtedly inserted at the time of its modern rebinding.^[Emma Campbell says the binding is eighteenth-century, and she provides a transcription of the modern table of contents (236).] The binding is reddish-brown leather with yellow-gold detailing and a deep green rectangle on its spine that reads “VITE / DI SANTI / IN LINGUA / PROVENZ / COD. MEM.” The codex measures 180x110mm, with a writing space of 133x85mm. The text block is written in a single column, with twenty-nine lines per page and an average line height of 5mm. For the Life of Saint Mary the Egyptian, each line has both initial and final letter separation (except when the poetic lines are too long to allow space before the final letter), and each contains two poetic lines separated by a midline punctus. The pricking has not been trimmed away, and the ruling, though faint, is visible throughout. The foliation is modern, written in pencil in the top right corner of each recto. There are, also, a few visible quire signatures in this manuscript, but for the most part, quire signatures are not observable.  

Canonici Misc. 74 is a minimally decorated manuscript. It does not contain any illustrations, but it features some large initials — typically two or four lines high — executed in red, and occasionally light blue, ink. The red initial “O” of *La vie de sainte Marie l’Égyptienne* is about four lines high and is lightly accented with faded pen floriations. There is no rubric within the ruled text block for our text, but the title “de marie egipcienne” is written across the top margin on f.109r. where the text begins. There are some examples of red ink rubrics used elsewhere in the manuscript, such as the rubric for the Life of Andrew the Apostle on f.120r.  

The origin of Canonici Misc. 74 prior to the eighteenth century is unknown, but it was acquired by the Italian Jesuit and bibliophile Matteo Luigi Canonici (1727-1805) who passed it along with most of his vast collection (of about 3,500 manuscripts) to his brother Giuseppe (d.1807) who, then, passed the collection on to his nephew Giobanni Perissinotti. The collection was ultimately purchased by the Bodleian in 1817.^[This provenance is summarized on the webpage “Canonici” on the Digital Bodleian.]  

The identities of the scribes of Canonici Misc. 74 are likewise unknown, but we can say that the language of this manuscript contains Picard features such as the typical use of “le” for the feminine singular article. An obvious shift in hands occurs on f.120r from the end of the Life of Mary the Egyptian to the beginning of the Life of Saint Andrew the Apostle, but Cruz-Sáenz agrees with Baker’s assertion that there are, in fact, three distinct hands in this manuscript writing, “the first copyist wrote the *Alexis*, the *Poème moral*, and the *Juliane*; the second wrote the *Euphrosine* and *Marie l’Égyptienne*; and the third wrote the *Andrier* and *Juïse*” (23).^[See also Ogden, *Hagiography* 27-33, and Campbell, *Gift* 205ff., on the compilation of the manuscript.]  

## T-C
### Oxford, Corpus Christi College, 232. ff.35r-64v. Early 14th century, from Canterbury.
Another rather small codex like Canonici Misc. 74, Corpus Christi College 232 is only slightly larger, measuring 190x125mm overall with a writing space of 147x70mm. Despite its size, CCC 232 offers 1,532 verses of Version T, making it the longest extant manuscript of this text.^[T-E would be the longest copy were it not for the lacuna of approximately sixty verses lost due to mutilation. Dembowski notes in his edition that copy T-C “a été remanié au commencement et des vers y ont été ajoutés à plusieurs reprises” (26), but also, C is lacking in some verses otherwise found in A. Dembowski writes, “La conclusion du poème est plus abrupte dans C; il y manque 17 vers en comparaison avec A” (30n121).] CCC 232 is, also, likely the latest medieval copy of Version T with an approximate dating to the early fourteenth century.^[T-F^1^ is also dated to this period, but T-C may be considered the latest full copy.]  

Barker-Benfield’s edition of the fifteenth-century St. Augustine’s Abbey, Canterbury catalog^[Barker-Benfield notes that this late medieval catalog, which has been made available in print thanks to the Corpus of British Medieval Library Catalogues initiative, “may have taken almost a century to reach its existing late fifteenth-century form” (vol. 1, l).] provides a thorough description of CCC 232, noting also that CCC 260 f.84b was formerly CCC 232’s front flyleaf.^[The flyleaf was apparently separated from the manuscript after it left Canterbury. “The stray flyleaf is bound into the *Collectanea* of Brian Twyne, vol. 7” (Barker-Benfield, vol. 2, 1428).] It is at the bottom of this stray flyleaf that the pressmark of St. Augustine’s Abbey may be found, providing greater clarity for CCC 232’s provenance, though it is unclear if this particular manuscript was a product of the abbey’s own scriptorium or an outside acquisition.^[In his introduction, Barker-Benfield describes how the late medieval trend toward lay book production affected the abbey’s collection:  "The evidence for books at StA during the later 12th and 13th cent. echoes the general pattern of European book-production, when the monastic scriptoria were being overtaken by lay producers. As if through privatization, the abbey’s library came to be stocked less from its own communal scriptorium than from the scholarly activities and acquisitions of individual monks. The books so acquired were much more likely to have been made outside the abbey or obtained second-hand" (vol. 1, lxiii).] CCC 232’s movement out of Canterbury was likely triggered by the dissolution of the abbey by Henry VIII, but as Barker-Benfield describes, “Even after 1538, the library itself seems to have maintained a shadowy half-life for another few decades, with books apparently abandoned on site (whether or not in the old Library Room) and gradually dispersed by the later secular inhabitants” (vol. 1, lii). Sometime after leaving Canterbury, the manuscript became a part of the collection of John Dee (1527-1608/9), court astronomer and advisor to Elizabeth I (1533-1603) and antiquarian.^[The latest available date we have linking Dee to CCC 232 is 1583 as the manuscript appears in the catalog of his library that year (Thomson 117).] Dee’s diary reveals that his home and collection was, sadly, “plundered by the populace” (Halliwell-Phillipps vii) while he was away traveling. Eventually, CCC 232 was in the possession of Brian Twyne (d.1644), who was himself educated at the college in Oxford. He appears to have left the manuscript — along with many others — to Corpus Christi College upon his death. Matthew Cooke’s 1852 edition of T-C was quite useful to subsequent researchers in the identification of other copies of Version T. For instance, it is thanks to Cooke’s work that Tobler was later able to identify T-fragment F^2^ among the many Damascus fragments sent to Berlin at the turn of the twentieth-century to be photographed and studied.^[“Die Namen Zosimas und Maria ließen sofort erkennen, daß es sich um das Leben der h. Maria aegyptiaca handelte, und bei weiterem Nachsehn ergab sich, daß man es weder mit Adgars noch mit Rustebuefs Gedicht über diesen Gegenstand zu tun hatte, sondern mit demjenigen, das nach einer Handschrift von Corpus Christi College in Oxford Cooke in London 1852 veröffentlicht hat in, *Robert Grossetete’s Chasteau d’amour, to which are added «La Vie de Sainte Marie Egyptienne» and an English version of the Chasteau d’amour. Now first edited by M. Cooke’ (Publications of the Caxton Society)*...” (Tobler 967).]  

In terms of its structure, CCC 232 is composed of 92 parchment folios with two additional paper pages added to both the front and the end of the codex at the time of its modern rebinding. The manuscript’s parchment is arranged with hair-side facing hair and flesh-side facing flesh. Pricking is still visible on many folios, and the penciled ruling remains clear throughout the codex. The text block is formatted with either one or two columns per page and as many as 44 lines per column, depending on the text. On the folios containing *La vie de sainte Marie l’Égyptienne*, however, the layout is single-column with 26 lines each. The average height of each line is 5mm. The single-column sections have a column width of 72mm, while the two-column sections have a width of 50mm per column. The foliation is modern, marked in Arabic numerals in the top right corner of every recto. CCC 232 lacks catchwords and quire signatures, and its rubrication is inconsistent; while the Life of Mary the Egyptian is rubricated in red ink,^[The rubric reads “Ici come[n]ce la vie sainte marie legipciene.” on a single line.] other texts in this codex have different styles. The text of *La vie de sainte Marie l’Égyptienne* also includes pilcrows in red ink to indicate sections of the narrative. The manuscript does not contain any illustrations, but it features some bold initials in red and black ink.  

In this copy of T, there is initial letter separation with each initial letter accentuated with red ink. The line breaks respect the ends of verses, and punctus marks at the end of every second line indicate the end of each couplet. The scribe of T-C maintained a neat bookhand and left generous space in the ruled column, contributing to this copy’s readability. The scribe is unknown, but Dembowski agrees with Baker’s assertion that the scribe had an apparently clumsy knowledge of French (Dembowski 26). In terms of glosses, there appear to be the tips of manicules in the upper right margins of both f.41r and f.42r mostly lost due to trimming, but otherwise, there are no glosses in this copy.  

The manuscript’s binding is modern with a brown leather cover and yellow-gold lettering. The spine reads “GROSTETE / ETC” in reference to the other contents of this manuscript, which include Robert Grosseteste’s *Chastel d’Amour* (ff.1r-35r), a Latin mass for William Longsword, earl of Salisbury (d. 1250) in leonine verse (ff.64v-66v), *The Miracle of Sardenai* in French verse (ff.67r-71r), three Latin poems by Walter of Wimborne (ff.73v-82r), and various other Latin poems. *La vie de sainte Marie l’Égyptienne* appears second in this manuscript; it follows the *Chastel d’Amour* and precedes the Latin mass. There is a modern table of contents in the front pages.  

## T-D
### Paris, BnF, Français 19525. ff.15r-26v. Second half of 13th century, from Oxford.
Like Français 23112, manuscript Français 19525 may be found at the Richelieu site of the BnF. Dated to the second half of the thirteenth century, this copy of Version T offers 1,442 verses of *La vie de sainte Marie l’Égyptienne* as well as many other Lives of saints in verse and in prose including Saints Laurent (ff.1r-8r), Jean le Baptiste (ff.36r-38v), and Marguerite (ff.141v-145r). This codex also includes other religious texts like *Li ver del juïse* (ff.43v-46v) and *Le Besant de Dieu* (ff.96r-125r), which have received editorial attention from Erik Rankka and Pierre Ruelle respectively.^[Both editors briefly describe Français 19525 in their editions (Rankka 39-41; Ruelle 12-13).] The Life of Mary the Egyptian is preceded in this manuscript by *La Vision de saint Paul* (ff.12v-15r) and is followed by *La vie de sainte Alexis* (ff. 26v-30v). In his edition, Dembowski suggests that the scribe of T-D had a poor understanding of metrics,^[“En effet, le scribe comprenait très mal la métrique. Il a considérablement abrégé le poème surtout dans la partie finale (v. 1115 et suiv.)” (26)] but the scribe has copied the text in a clean book hand using initial letter separation and few abbreviations, making this copy rather easy to read.  

The provenance of Français 19525 has been extensively documented on the BnF online record. The digital catalog suggests that the manuscript was copied by many hands^[A: ff.1-66v; B: ff.67-122, ff.133-202; C: ff.123-132; and a later fourteenth/fifteenth-century hand on f.204] and links the codex to the atelier of William de Brailes, an English illuminator active in Oxford between 1230 and 1260. The manuscript was later purchased by Louis de Bruges (1427-1492), seigneur de Gruuthuse, whose arms are painted in the center of the lower margin of f.1r. Also visible in the upper margin of f.1r is the inscription of the poet Philippe Desportes (1546-1606). In the seventeenth century, the codex entered the library of chancellor Pierre Séguier (1588-1672) and later passed to his grandson, Henri-Charles de Cambout de Coislin (1665-1732), the Bishop of Metz. Français 19525 — along with the rest of the Coislin collection — was left to the Abbey of Saint-Germain-des-Prés on 1 May 1731 and entered the abbey’s collection in 1735. This acquisition is documented in the manuscript on f.1r on the right side of the bottom margin with the inscription “S.G. 1856” — the former shelf mark of the manuscript. In the midst of the French Revolution, the BnF acquired Français 19525 along with the thousands of other manuscripts of Saint-Germain-des-Prés in 1796.^[Delisle describes this history of the BnF’s acquisition of more than 9,000 volumes from the Saint-Germain-des-Prés collection in his chapter “Suite du Régime révolutionnaire — La bibliothèque de Saint-Germain-des-Prés” (40-58). Français 19525 was one among approximately 2,800 other French, Italian, and Spanish manuscripts from the library of Séguier (Delisle 50).]  

Measuring 225x155mm, Français 19525 is composed of 204 parchment folios, along with four paper front pages and four paper back pages, added sometime during its modern rebinding. The writing space measures 145x120mm, with up to three columns per page — though Version T is consistently copied on two-column pages — and typically thirty-two lines per column. The average height of each line is 5mm. Although pricking is rarely visible due to trimming, some evidence of pricking remains, notably on the lower outer edge of f.151, where there is also a marginal note to the rubricator indicating the need for a floriated initial “e” in the text block. The parchment leaves feel rather thin and are arranged with hair-side facing hair and flesh-side facing flesh. Penciled ruling is present throughout most of the manuscript, except on ff.123-132, and the text is written above the top ruled line on each page, which supports the dating of this manuscript to the thirteenth century. The foliation is modern, with Arabic numerals in ink at the top right corner of each recto. While catchwords are absent from this manuscript — perhaps also lost due to trimming —, quire signatures in the form of Roman numerals can be seen in the center of the bottom margins of the first half of the codex. The manuscript’s rubrication is incomplete; space has been left for rubrics at the start of each text, but the rubrics themselves were never added. However, in the margins at the beginning of each text, there are faded ink notes — likely contemporary to the scribe — meant for the rubricator, indicating the subject matter of each text. For example in the bottom margin of f.15r, we can clearly read “Gypciene,” indicating the need for a rubric for the Life of Mary the Egyptian. A modern hand has also added Arabic numerals to number the texts in this codex (The Life of Mary the Egyptian is the fourth text in this manuscript.), and occasionally, modern titles are provided in thin pen ink. There is a modern table of contents on the facing page of f.1r.  

There are other notable physical oddities of this manuscript. For instance, there is a small triangular hole in the bottom outer corner of f.50, with a little green tassel (about 5mm long) still attached to the slight tab of parchment formed by this hole. The tassel seems to be a bookmark of some kind, appearing at the beginning of the Gospel of Nicodemus. The scribes of Français 19525 were careful to copy around the occasional preexisting holes in the parchment, such as those found on f.105. This folio (f.105) has also suffered extensive damage, apparently from scraping, with the text on the verso especially affected.^[About forty lines of text — the last four lines from the recto and some thirty-six lines scattered across the verso — are almost entirely unreadable with the naked eye.] Given that the damage is isolated to f.105, it is possible that it was inflicted intentionally, perhaps to remove an unwanted portion of text. On f.105, there is also an approximately 60mm vertical cut running from the top margin down the outer edge of the writing space on the recto. This cut disrupts the alignment of the text at the top of the first column on the verso of f.105 as the scribe chose to squeeze the first nine lines to the right of the cut. Folio 204 — the last medieval folio of this manuscript — is a fragment with the bottom two thirds of the folio having been torn away. In the remaining recto of f.204, musical notation has been added by a late medieval hand along with the charming doodle of a bird-like creature with a bearded human’s face looking up to the musical tune.  

In terms of binding and decoration, the cover is made of a brown marbled calf leather with a red leather spine featuring the monogram of Louis XVIII in gold, and the spine reads “VIE / DE / LAURENT &C.” Apart from several historiated initials (f.67r, f.141v, f.145r, and f.153r), decoration in Français 19525 is modest, lacking any other illustrations. However, there are many beautifully floriated initials throughout the codex executed in alternating red and blue ink.  

## T-E
### Paris, BnF Arsenal, 3516. ff.113v-117v. 1267/1268, from Artois.
This manuscript is the only copy of Version T located at the Arsenal site of the BnF — though a copy of Version U (MS 3706, fifteenth century) may also be found in the Arsenal collection. Arsenal 3516 is composed of 357 parchment folios, with the addition of a paper front page and a paper endpage inserted at the time of the codex’s modern rebinding.^[According to a sticker included in its back cover, this manuscript was restored at Richelieu in 2009.] Its dimensions are 330x255mm — making it the largest copy of Version T —, with a writing space of 242x205mm. The binding of Arsenal 3516 is not featured in the digitized version available online, but the BnF record notes that it is a “Reliure en veau fauve.” The folios of the manuscript are all formatted with either three or four columns with fifty lines per column. The average height of each line is 5mm. Pricking is visible on the outer edges of the folios as well as along the bottom edge, which was used to set the width of the columns. The penciled ruling is also still plainly visible throughout the manuscript. The manuscript features both medieval and modern foliation with medieval Roman numerals appear in the the top margin of the verso in ink, while modern Arabic numerals are written in pencil in the top right corner of each recto. However, these numbers do not always agree due to the removal of thirteen leaves from throughout the codex.^[There are two leaves missing from between folios 3 and 4; one between folios 7 and 8; one between folios 34 and 35; one between folios 42 and 43; three missing from between folios 47 and 48; one between folios 296 and 297; and four missing from between folios 349 and 350.] Additionally, folios 23, 222, and 336 are all significantly smaller pieces of parchment — each about half the dimensions of the rest of the folios in this codex — that have been tipped in.^[It is difficult to visualize the size and positioning of folios 23, 222, and 336 based solely on the digitization of Arsenal 3516 available on Gallica. Online, each of these folios appear isolated against a white background and are the same size as all of the other folio images, but when viewed in-person, these folios are an obvious disruption with the larger, neighboring folios peaking out significantly from behind. Folio 23 has a single column layout with 27 lines on its recto and 28 on its verso; folio 222 has a two column layout with 40 lines on each side; and folio 336 has two columns of 40 lines each on its recto and one column of 35 lines on its verso.] Catchwords can be found in the bottom right corner of the last verso of some quires (e.g. f.91v), along with both medieval and modern quire signatures. The medieval quire signatures are Roman numerals in ink appearing in the center of the bottom margin on both the last verso and first recto of each quire (e.g. ff.115v-116r), while a modern hand has penciled in a quire count on the first recto of each quire. The modern quire count was apparently added at some point after the digitization of Arsenal 3516 was produced as these numbers do not appear online but were present during my visit to the Arsenal in January 2024.  

Guggenbühl hypothesizes that Arsenal 3516 may have originally belonged to a wealthy bourgeois of Saint-Omer or perhaps to one of two brothers of King Louis IX: Charles I of Anjou, who might have received it as a wedding gift on the occasion of his marriage to Marguerite of Tonnerre, or Robert II of Artois, who could have acquired it at the time of his knighting.^[“Il pourrait s'agir, ..., soit d'un riche bourgeois de Saint-Omer, soit de deux frères du roi Louis IX: Charles Ier d'Anjou, qui pourrait l'avoir reçu en cadeau à l'occasion de son mariage avec Marguerite de Tonnerre, fille d'Études, duc de Bourgogne; ou Robert II d'Artois, lors de son adoubement” (qtd. in Françoise Laurent et al. 36-37).] There is some slight debate as to the precise year this manuscript was produced, but it certainly originates from Artois and dates to the late 1260s.^[Based on the calendar featured in the beginning of the manuscript (ff.1r-2v) Dembowski offers a dating of 1265, but Guggenbühl offers an extensive justification to situate the entirety of Arsenal 3516 to the years 1267/1268 (5-14). Likewise, in the introduction to Blacker, Burgess, and Ogden’s edition of Wace’s *Life of St Margaret*, we have the description “Probably completed in 1267 or 1268 and could have been copied at Hesdin, at the court of the counts of Artois” (Blacker et al. 149).]  

While the language of the anonymous author of Version T is Anglo-Norman, the language of this manuscript is heavily colored by an apparently Picard copyist.^[“... il est à mettre sur le compte d’une intervention fautive d’un copiste picard à cet endroit” (Françoise Laurent et al. 47). A thorough analysis of the language in Arsenal 3516 is offered in this edition of Wace as well (46-66).] For example, we have the typical Picard use of “le” for the feminine singular article, but we also see features like the use of the vowels “eu/e” in place of “o/e” in preterites.^[This trait is observable in the verse “ou ele soloit faire les geus” (v.690), which in T-E reads “ou ele seut faire ses gieus.”]  

Arsenal 3516 contains both religious and secular texts in verse and prose, including many saints’ Lives, Biblical excerpts, scientific explanations of nature and a bestiary. A medieval table of contents, which has some minor, clarifying glosses written in pen, appears on f.3v. Throughout the manuscript, each text is introduced and concluded with rubrications in red and blue ink, and each begins with an elaborate floriated initial of the same colors. *La vie de sainte Marie l’Égyptienne* is positioned between the Lives of Saints Thaïs (ff. 109v-113v) and Juliane (ff.117v-121r).^[The medieval table of contents neglects to list the Life of Saint Juliane, which may lead one to mistakenly believe that the text immediately following Mary the Egyptian is the Life of Saint Catherine (ff.121r-125r) especially since these texts have lost their identifying rubrics as a result of the cut out miniatures.]  

The manuscript was originally lavishly decorated with at least one miniature per text, but most of these have been cut out. While T-E is the only T manuscript that would have included a miniature of Mary the Egyptian, this miniature has also been lost. However, two frontispieces in this manuscript remain: one on f.154v depicting the Second Coming and another on f.217v depicting five mounted knights and a castle ablaze. The miniatures on folios 198v-212v associated with the bestiary are still intact as are the circular diagrams of various sizes on ff.157r-173v, 179r/v, and 180v. Glosses found throughout the manuscript, including corrections, marginal notes, and pen trials, suggest that it was usefully read by its various owners over time.  

In terms of *La vie de sainte Marie l’Égyptienne*, this manuscript offers 1,489 extant verses, though approximately sixty verses near the end of the narrative are missing due to the mutilation of f.117. This copy is mostly presented in a four-column format, though f.113v where the Life of Mary the Egyptian begins has a three-column format. The line breaks respect the verses almost entirely, but in the first column of f.117v two verses have been split over four lines. Due to the mutilation of this folio, it is not possible to say definitively why the scribe chose to divide these verses in this way, but it was likely a decision made to ensure the text would conclude on the appropriate line in the third column without leaving any empty space that might disrupt the aesthetics of the page layout. Overall, the word spacing in T-E is rather inconsistent, and the text is quite abbreviated, making it a more challenging copy to read with fluidity.  

## T-L
### London, British Library, Additional 36614. ff.271v-282v. Second half of 13th century, provenance pre-19th century unknown.
Add. 36614 is in many ways a unique manuscript among the Version T corpus. Unlike the other codices containing Version T of the Life of Mary the Egyptian, which feature collections of various texts, the contents of Add. 36614 are limited to a suite of texts centered around Chrétien de Troyes’s *Perceval, ou le Conte du Graal* (ff.7v-84r) — including the *Bliocadran* (ff.1v-7v) and two continuations: the anonymous *Continuation Gauvain* (ff.84r-163r) and the *Continuation du Conte du Graal* by Wauchier de Denain (ff.163r-268r) — and *La vie de sainte Marie l’Égyptienne* (ff.271v-282v). In place of the typical first four verses (and their minor variants) found in all other T copies, T-L begins with these fourteen unique verses:  

<div style="width: fit-content; margin: 0 auto; text-align: left;">
> Tot li home & totes les femes.\
> Q[ui] vuelent pendre penita[n]ce.\
> doivent bie[n] escouter la vie.\
> de l[’]egipciene marie\
> par tot le mo[n]t ta[n]t co[m] est ample.\
> I poieent p[r]endre g[ra]nt essample.\
> Ele fu molt bele & m[o]lt ge[n]te.\
> & pecha molt en sa jovente.\
> Mais puis qu[’]ele se porpensa.\
> A damledeu se retorna.\
> & ensable o lui s[’]ajosta.\
> Si q[ue] ja mais n[’]en severra.\
> & tot cil q[ui] sa vie orront\
> Gra[n]t essample pre[n]dre i porro[n]t.\

</div>

Because circumstances have prevented me from consulting this manuscript in more detail, my own observations of T-L are limited compared to the data I have collected from the other T manuscripts. I cannot independently confirm the exact number of verses of T contained in Add. 36614, but in his edition, Dembowski reports that this copy is missing 240 verses due to missing folios (26),^[“Notre poème a une lacune considérable, car les feuillets qui devaient porter les numéros 282 et 283 ont été arrachés. Il manque ainsi 240 vers” (26).] and the 1907 catalog of the British Museum says that this manuscript contains “about 1,350 lines” (156). This copy of Version T begins without title or rubric, but the initial “T” is drawn in red and is about three lines tall. The word spacing is not entirely consistent in this copy; occasionally, we see the use of initial letter separation, but this practice is not consistent. T-L appears to have been copied entirely by the same scribe, who makes regular use of abbreviations. Roach suggests that this copy of Mary the Egyptian was the addition of a fourteenth-century hand, but Dembowski does not confirm this suggestion.^[On the topic of scribal hands in Add. 36614, Roach writes, “Several hands are involved: Chrétien’s *Perceval* was copied by a scribe who wrote in Francian with a Picard inmixture; the Continuations show at least two hands, the first of which is more definitely Picard; the intercalated *Bliocadran* is by a northeastern scribe; and finally a fourteenth-century hand has added in the last twelve folios a *Vita Mariae Aegyptiacae* in French verse.” (xx)] In terms of dialect in Add. 36614, Micha notes, “Dialecte francien avec influence picarde pour *Perceval le Vieil*” (62), but Version T in this manuscript does not demonstrate the same Picard influence.  

The manuscript’s provenance is not known, but the codex is dated to the second half of the thirteenth century.^[This dating is agreed upon by Micha (62) and Roach (xx) in their respective editions.] The modern history of this manuscript, which is wrapped up in the actions of the controversial bookdealers Joseph Barrois (1785-1855)^[It seems Barrois may either be referred to as “Joseph” or “Paul”; the Ashburnham Library catalog of the auction of the Barrois manuscripts says the collection was “formed by M. Paul Barrois” (iii).] and Guglielmo Libri (1802-1869), is documented in Williman and Corsano’s chapter “In the British Royal Library.” In brief, the fourth Earl of Ashburnham (1797-1878) purchased a collection of more than 700 manuscripts, including Add. 36614 (formerly MS Barrois 1), from Barrois in 1849. Following the Earl’s death, the Barrois Manuscripts of the Ashburnham Library were sold at auction, with Add. 36614 listed as Lot #463. At the time of this auction, the manuscript’s binding is described as “Modern boarded blue morocco, with rich gilt ornaments, joints, g. E. WITH A VERY ANCIENT CARVING IN IVORY (7 ¼ by 3 ½ in.), REPRESENTING THE DEATH OF THE EMPEROR SEPTIMUS SEVERUS, INSERTED IN THE COVER” (Ashburnham Library 171). By the time of the British Museum’s 1907 catalog, this ivory panel has been separated from the rest of the codex and is reidentified as “representing the death of Jacob,” (157). The ivory panel has since been dated to the tenth/eleventh century, and while MS Add. 36614 is housed in the British Library, the ivory panel is kept in the British Museum. The panel is not currently on display there, but it has been photographed and may be consulted online.^[https://www.britishmuseum.org/collection/object/H_1901-1230-1]  

In terms of structure, Add. 36614 is made up of 282 parchment folios, arranged hair-hair-flesh-flesh, with some front and end pages likely inserted when the manuscript was last rebound. The manuscript folios are formatted with two columns per page, and each column has thirty lines with an average height of 7mm each. The width of each column is 74mm. The manuscript has modern foliation written in pencil in the top right corners of the rectos. Some folios have medieval Roman numerals as well, but these appear on a minority of pages. The dimensions of the manuscript are 310x220mm, with a ruled writing space of 240x150mm. The ruling of Add. 36614 was apparently done in pencil and is present throughout the manuscript, but on the folios containing the Life of Mary the Egyptian, this ruling has been almost entirely erased. Add. 36614 lacks quire signatures and rubrics, and there is no medieval table of contents. The manuscript also has no miniatures or frontispieces, but in the empty space of f.268r at the end of the *Conte du Graal* there are the “armes au lion de Flandre, et au-dessus, la devise : ‘Flandres : au : lion’” (Micha 62). Added glosses throughout the codex suggest this manuscript was actively read.  

## T-F^1^
### Manchester, John Rylands Library, French 6. f.8r-8v. Second half of 13th century, provenance pre-19th century unknown.
French 6 is a collection of twelve parchment folios, “réunis sous une couverture moderne de vélin blanc et portant au dos le titre ‘VIE DES SAINZ. CIRC. 1320’” (Fawtier & Fawtier-Jones 321), containing ten incomplete texts that were bound together sometime in the nineteenth century. According to Ker’s description, French 6 was “bound for Lord Crawford in stiff parchment in the same style as Rylands Lat. 26” (453).^[In addition to the 12 parchment folios, which the John Rylands record refers to as “vellum”, French 6 is also bound with 2 paper front pages and 24 end paper pages. The front pages are included in the digitization of this manuscript, but the end pages are not included in the digitization. These pages feature chainlines and unidentified watermarks.] The overall dimensions of this manuscript are 272x190mm, with a writing space of approximately 190x129mm, though slight variations in this writing space occur across the manuscript. Fawtier and Fawtier-Jones suggest the folios of this manuscript originate from two or three source manuscripts with folios 1-8 dating to the first half of the fourteenth century (321), though because the first line of writing in these folios is above the top ruled line, I would suggest pushing this dating somewhat earlier. Folios 9-12, which Fawtier and Fawtier-Jones date to the second half of the thirteenth century, have been cropped at the bottom, resulting in a significant loss of the bottom margin, though the writing space remains intact. The manuscript has modern foliation, added in pencil just below the bottom right corner of the text block of each recto in the form of Arabic numerals. Otherwise, French 6 does not contain any glosses on the parchment folios. Only the initial letter “A” of French 6 is painted and illuminated with gold. All other major initials in this manuscript are drawn in red or blue ink with some minor fine-lined flourishes in red or blue ink. Apart from the initial “A” in French 6 which features the figure of a haloed saint and a bird, there are no other illustrations in this manuscript. There is an inconsistent presence of pricking in this manuscript, unsurprisingly as the fragments were all most likely trimmed down for its current binding. Each folio is formatted with two columns per page and either forty-one or forty-two lines per column. The average height of each of these lines is 4mm, and the width of each column is 68mm. As French 6 is a fragmentary manuscript, there is, of course, no medieval table of contents, but there is also no modern table of contents. The ten fragmentary texts of French 6 are all religious in nature and include: Maurice de Sully’s *Explication du Pater* (ff.3r-3v); Adam de Ross’s *Vision de saint Paul* (ff.3v-5r), *La vie de saint Jean-Baptiste* (in prose) (ff.5r & 2v); *Passion de Saint Paul* (in prose) (ff.2v & 1r-1v); *Li ver del juïse* (ff.1v & 8r); *La vie de sainte Catherine d’Alexandrie* (ff.9r-10r); *La vie de sainte Alexis* (ff.10r-10v); *Poème sur l’Antéchrist* de Henri d’Arci (ff.11r-12r); *Les Quinze Signes* (f.12r); and of course, *La vie de sainte Marie l’Égyptienne*, which sits between *Li ver del juïse* and the Life of Saint Catherine.^[Fawtier and Fawtier-Jones provide descriptions of each of these.]  

In his edition, Dembowski notes that this fragment of Mary the Egyptian was not publicly known until Fawtier & Fawtier-Jones published on it in 1923 in *Romania*, and so Baker was unaware of its existence at the time of his own study (27). By my count, T-F^1^ offers the first 163.5 verses of T.^[Dembowski refers to it as “un petit fragment anglo-norman de 162 vers correspondant aux 168 premiers vers de notre édition” (27).] The text is introduced with red ink rubrication. Interestingly, the aesthetic formatting of this rubric matches the preceding text with its initial letter separation and verse-aligned line breaks, and the rubric has been composed to match the octosyllabic rhyming couplets of Version T. It reads:  

>D   e seinte marie legyptien\
>D   irrum ore lestorie bien.\

But T-F^1^ itself has been copied in the style of prose: the text fills the ruled space without regard for either the verse or word separation. The scribe does, however, indicate the end of each verse with a punctus and the start the each verse with red ink, and each word that is separated by a line break is marked with a slash at the end of the line. It is unclear why the scribe would abandon the formatting of the preceding text (initial letter separation and verse-aligned line breaks), for this copy of Version T. Perhaps the scribe was navigating a shortage of space or perhaps our text was of less importance to whoever commissioned the original volume? In any case, the scribe makes the metrical structure and rhyme scheme of T-F^1^ clear to the reader by establishing both in the rubric.  

The provenance of French 6 is a subject of considerable interest. The fragment was likely purchased by Lord Crawford in the Libri sale of 1859 and became part of the Rylands collection in 1901.^[Russell recounts this chain of acquisition in his bulletin (41) based on the descriptions of both Ker (433) and Fawtier and Fawtier-Jones who also note that French 6 may have been Lot #1119 of the Libri auction based on that lot’s description (322).] French 6’s origins prior to the 19th century are not entirely known, but Russell’s 1989 bulletin meaningfully fills in some of these gaps and builds significantly on the initial 1923 *Romania* notice. Fawtier and Fawtier-Jones make clear the fact that the first eight folios of French 6 are a quire that has been rebound out of order (321). These folios should appear in the following order: 3-4-5-2-1-6-7-8, and Russell supplies a clear motivation for this incorrect arrangement:  

> The reason for the displacement of the original central bifolium by those responsible for the present order is obvious when one considers the fragment. … the perpetrators of this change have found a way to place the beginning of a text at the beginning of the manuscript fragment, to give the impression that the fragment is a complete entity in itself. Furthermore, this text, the ‘Passion de saint Paul,’ is the only one in [MS French 6] which has an initial letter decorated in golf leaf, and is by far the most attractive introductory capital letter of any found in this fragment. (42)  

But from what manuscript was this quire excised? Russell suggests that at least folios 1-8 of French 6 were originally part of British Library Egerton 2710 — a legendary dating to the second half of the thirteenth century —, a claim which he supports convincingly with both physical and textual evidence. First, there are no catchwords in French 6, but there is one medieval quire signature “XX” at the very bottom of the center margin of f.8v. Russell makes use of this quire signature to support his argument that French 6 is a continuation of Egerton 2710, which is incomplete following its own quire signature “XIX.” More compellingly, when rearranged in the proper order, f.3 of French 6 is a perfect continuation of the incomplete *Explication du Pater* of Maurice de Sully found in Egerton 2710 (43). Furthermore, Russell highlights the fact that the contents of Egerton 2710 are “very close” (44) to that of BnF Français 19525, the manuscript containing copy D of Version T of the Life of Mary the Egyptian, and in his edition, Dembowski himself suggests T-F^1^ “semble suivre de très près le même texte que le ms. D” (27). The text of copies T-D and T-F^1^ are quite similar,^[There are minor spelling differences between these copies, though T-F^1^ has been more extensively abbreviated by the scribe. T-D and T-F^1^ only noticeably differ in verse 164 where copy D offers “N’out onkes tele meschine” and copy F^1^ offers “N’out el chef plus bele crine.”] but the dimensions, formatting, decorative elements, and material evidence of BnF Français 19525 and Egerton 2710 merit closer attention before drawing any more definitive conclusions about the possible relationship between these codices.^[Based on my own observations of BnF Français 19525 and on the description of Egerton 2710 available on *Arlima* (https://arlima.net/no/4668), BnF Français 19525 is smaller than Egerton 2710, which measures 265x180mm with 40-42 lines per column.] Both BnF Français 19525 and John Rylands French 6 may be consulted online and in the reading room, but at time of writing, access to Egerton 2710 at the British Library is still limited. The likeness between BnF Français 19525 and the first folios of John Rylands French 6, originating from Egerton 2710, merits further attention elsewhere.^[It is difficult to draw definitive conclusions about how any of these Version T copies are related to one another, but Duncan Robertson offers a scheme based on what little we do know of the origins of Version T in which T-E and T-C seem to have a shared source, T-B and T-L seem to have a shared source, and T-A, T-D, and the two fragments seem to be related to one another with T-D and T-F1 the most closely linked (“The Anglo-Norman Verse Life” 30).]  

The folios that would follow f.8 of French 6 are still undiscovered, leaving the door open to the exciting possibility that the missing folios of T-F^1^ could be recovered elsewhere among the unidentified jumbled fragments of some other manuscript collection. Such a discovery would allow for a more elaborate analysis of the possible relationship between copies T-D and T-F^1^, and such a discovery would undoubtedly bring the discoverer the same satisfaction Russell himself describes, “...the satisfaction one gains from discovering the source of a manuscript fragment which has remained separated from its original manuscript for several centuries, stems no doubt from the feeling that one has, in a very small way, reversed the process of time” (46).  

## T-F^2^
### The location of the original fragment — dated to the second half of the 12th century and most likely originating in Europe — is unknown, but a photographic copy may be found here:
> Berlin, Staatsbibliothek, Photographien von ausgewählten Fragmenten aus der Omayyaden-Moschee in Damaskus in verschiedenen Sprachen, 1908. Mss simulata orientalia 6, Orientalische Handschriften digital, Photographs 89 (verso) & 101 (recto), http://resolver.staatsbibliothek-berlin.de/SBB000074F100000000.


Giannini and Minervini provide devastating clarity as to the current status of T-F^2^, “Up to the beginning of the twentieth century, four Old French pieces were stored in the Qubbat al-khazna adjacent to the Umayyad Mosque in Damascus. All of them are now nowhere to be found” (331).^[The other Old French fragments found in the Damascus geniza include an apologetic poem against Judaic criticisms, a bifolium of *Fierabras*, and scraps of *Enfances Godefroi*.]  Of the Old French fragments documented in Damascus, Adolf Tobler says that T-F^2^ is of less importance than the bifolium of *Fierabras*,^[“Von geringerer Bedeutung noch als die Stücke des *Fierabras* ist, was wir auf den zwei Seiten eines nicht ganz unbeschädigten Pergamentblättchens…” (966)] but T-F^2^ is of great importance to the study of Version T of *La vie de sainte Marie l’Égyptienne* as it represents the only physical, textual evidence that the T poem traveled as far as the Middle East. While the original parchment fragment of T-F^2^ is currently considered lost — perhaps surviving undocumented in either Damascus or possibly Istanbul —^[In their introduction to *The Damascus Fragments* (2020), D’Ottone Rambach, Hirschler, and Vollandt provide a detailed account of the last known locations for the full corpus of the fragments of the Qubbat al-khazna, and they reframe this history in such a way that the role of the Ottomans in managing this research is made much clearer and more active. They write, “In particular, when it comes to the temporary loan of some of the fragments to Germany, it appears very clear that the Ottomans, both in Damascus and in Istanbul, made all the efforts needed in order to document the fragments through photographs and ensure that they would get them back” (38). In addition to recounting the return of the collection of fragments photographed in Berlin to Damascus in 1909, they describe the existence of a handlist and a duplicate set of photographs first produced by the Ottomans prior to loaning the fragments to the Germans to ensure the return of all the loaned fragments. Like the original fragments themselves though, the location of this handlist and set of photographs is also unknown.] its contents are preserved through the photographs taken by German philologists at the turn of the twentieth century. These photographs are housed in the Staatsbibliothek of Berlin and have been digitized, allowing for continued study.  

T-F^2^ is a single parchment folio offering thirty-eight verses of Version T, with twenty verses on the recto and eighteen verses on the verso. Dembowski notes that these verses correspond to vv. 967-1004 of his edition (27), and in his own published description, Adolf Tobler compares this fragment to vv. 979-1016 of copy T-C (Oxford Corpus Christi College 232),^[This set of verse numbers are based on Cooke’s 1852 edition.] which he includes side-by-side with his own transcription of the Damascus fragment.  

According to Tobler, who examined the parchment fragment when it was on loan in Germany, T-F^2^ is remarkably small, measuring just 70x50mm, with the text arranged in a single column within a writing space of 52x32mm.^[Even the photographic reproductions of  T-F^2^ are rather small, with the verso photograph (no. 89) measuring 107x65mm and the recto photograph (no. 101) measuring 107x155mm.] Tobler notes these unusually small proportions are likely due to the damaging effects of moisture on the parchment over time, which have caused the leaf to shrink considerably.^[“...und das Pergament unter der Wirkung von Feuchtigkeit stark verschrumpelt ist” (966). The original size of the fragment prior to this damage is unclear, but Giannini and Minervini reiterate Tobler’s account in their own description: “The folium on parchment shown on photographs nos. 101 (right [recto]) and 89 (verso) of MSS simulata orientalia 6 measured “7 Centimeter Höhe und 5 Breite”, and the lines (twenty for recto, eighteen for verso) were laid out across one column inside a frame provided with 52x32mm ruling. These measurements are skewed by the considerable shrinkage the folium suffered before 1903, ‘unter der Wirkung von Feuchtigkeit’ (under the effect of moisture), which also makes its content harder to read” (336).] The fragment’s tight spacing makes it exceptionally difficult to transcribe, and due to a rip in the parchment at the bottom left corner of the recto, the initial letters of the three verses at the bottom of that page have been lost entirely.^[Through comparison with the other Version T copies, these gaps can be filled in as follows:  
[Nos]tre sires l’aveit si chere\
[Q]ue plus que dos piez e demie\
[A]veit entre la tere e le]  

In their recent publication concerning T-F^2^ and the other fragments of Old French recovered from the Damascus geniza, Giannini and Minervini make use of the available paleographic and linguistic evidence to conjecture — based both on the fragment’s size and the roughness of the scribal hand therein^[An obvious feature of T-F^2^ is the sudden change in ink and thickness of the letters that occurs on the thirteenth line of the recto onward.] — that T-F^2^ may represent a rare, surviving example of the sort of loosely bound booklet through which texts commonly traveled in the medieval period (351).^[“... the portable unbound or roughly assembled booklets meant not for preservation, but for fast-paced and poorly organised circulation, having made it to the modern age thanks to nothing but exceptional and fortuitous circumstances… In the face of such an imposing body of preserved material, we sometimes tend to forget that the true vehicle of circulation of medieval literature, the *libellus* or booklet… which was meant to be sewn roughly and often left without a cover [and] is utterly off limits to us by virtue of its inability to cross the barrier of time without the rare help of exceptional circumstances (the Damascus geniza, for example)” (351).] Furthermore, Giannini and Minervini offer a dating of T-F^2^ to the second half of the twelfth century, suggesting that the writing is reminiscent of the rough draft style used in England in that period.^[Giannini and Minervini provide an in-depth analysis of the available fragment image and conclude that the fragment was most likely produced in Europe as it does not “share any grapho-phonetic or lexical peculiarities with the Outremer French *scripta*” (345). Radiciotti and D’Ottone likewise point to a twelfth-century, European origin story for the Old French pieces present among the Damascus fragments (“I frammenti della Qubba” 58).] Based on this dating, T-F^2^ is not just the most well-traveled but also significantly the earliest witness to the T poem. If more unknown pieces of T-F^2^ could somehow be recovered from the dispersed corpus of the Damascus fragments, invaluable insights into the earliest iterations of Version T could be revealed.  

Although Giannini and Minervini cannot say with any certainty how or when T-F^2^ first entered the treasure of the Great Mosque of Damascus (342), their thoughtful speculation on this fragment’s journey east invites curiosity as to why someone might choose this specific text to carry with them:  

> …the story of the Egyptian prostitute who chose, after visiting the Church of the Holy Sepulchre in Jerusalem, to become a penitent hermit in the Transjordanian desert, had an immediate appeal among Western pilgrims on their way to the holy places. The saint, moreover, was venerated in the Orthodox and Coptic churches, thus representing an element of cultural convergence between the Franks and the local Christians. (346)  

The fragmentary yet invaluable witness of T-F^2^ underscores the significance of examining each manuscript that preserves *La vie de sainte Marie l'Égyptienne*. Through careful attention to the textual, paleographic, and material details of these manuscripts, we gain a deeper understanding not only of the text’s transmission but also of its reach and resonance across disparate cultural and geographic contexts. Together, the histories of these eight manuscript witnesses illuminate the diverse audiences — monastics (T-C), nobles (T-E), collectors (T-F^1^), scholars (T-B), travelers (T-F^2^) — whose own interests have intersected the enduring work of the T-poet.


