---
title: "The Portraits"
format:
  html:
    page-layout: full
---

Each of these columns features an edited transcription and English translation of the two portraits of Mary the Egyptian as they appear in each of the T manuscripts. Copy T-L is not included on this page due to lack of access to the original manuscript at the British Library. The two fragmentary copies of Version T (T-F^1^ and T-F^2^) do not offer any lines of either portrait, and so, they have also been excluded from this page.

To read these passages in translation, hover over each column with your cursor.

::: {.column-page-outset}
::: {layout="[[20,20,20,20,20]]"}

::: {.portrait-column}
## T-A
<div class="text-container">
  <div class="default-text">
.....<br>
De se biaute de se figure<br>
Si com ele est en escriture<br>
Vueil -i- peu dire le samblant<br>
Anchois que je trespas avant<br>
Car a cel tans en icel regne<br>
Ne vit nus hom plus bele feme<br>
Ne onc contesse ne roine<br>
Nen ot el front plus bele crine<br>
Reondes avoit les oreilles<br>
Mais blanches erent a merveilles<br>
Les iex clers & sosrians<br>
les sorchix noir & avenans<br>
bouche petite par mesure<br>
& pie le regardeiue<br>
Le face tenrre & coloree<br>
Com le rose qui sempre est nee<br>
Ja el nes ne el menton<br>
N'aperceussies mesfaichon<br>
En som le col blanc com ermine<br>
li undoit le bloie crine<br>
Les mameles de cele dame<br>
N'estoient menrres d'une pome<br>
Desous le goule en le poitrine<br>
Ert blanche conme flor d'espine<br>
blans bras avoit & blances mains<br>
Les dois reons grailles & plains<br>
Gent cors avoit & bien molle<br>
Sous l'aissele lonc le coste<br>
El n'iert trop grant no trop petite<br>
Ja se faichon n'en iert escrite<br>
Ja le biaute de ceste dame<br>
Nen iert escrite par nul home<br>
Tant iert cortoise de parler<br>
Riens n'i avoit que amender<br>
A plaindre fait tel criaature<br>
Quant del Creator n'avoit cure<br>
El recevoit plusors presens<br>
S'en acatoit bons vestemens<br>
Bons dras avoit . & avenans<br>
Por mix plaisir a ses amans<br>
Ele n'avoit soing de dras de lainne<br>
Au pior jor de le semainne<br>
Bon bliaut avoit d'ostorin<br>
& affubloit mantel d'ermin<br>
Soullers bien pains de cordouam<br>
Cauchoit a tous les jors de l'an<br>
Le citoien de le cite<br>
L'amoient tout por se biaute<br>
Li anchien home & li saige<br>
disoient tout Dex quel damage<br>
Com mar fu onc ceste dolante<br>
Tant fait a plaindre se jovente<br>
Tant mar fu onques le siue vie<br>
Quant si est plainne de folie<br>
Tout disoient par le cite<br>
Qu'ele estoit de haut parente<br>
Car a tos respondoit raison<br>
& tant iert bele de fachon<br>
ke li fix d'un empereor<br>
Le peust prendre a grant honor<br>
.....<br>
Tant ala par jor & par nuit<br>
A faim & a soif & a dur lit<br>
Que tant parfont fu el boscaige<br>
Toute devint illuec salvaige<br>
Mais ele ne s'oublioit mie<br>
De deprier sainte Marie<br>
Sovent li menbroit de l'ymaige<br>
Que ele avoit mis en ostaige<br>
Si souller furent tout use<br>
& tout si drapel deschire<br>
Li cors de li remaint tout nu<br>
N'avoit drapel ne fust rompu<br>
Li chars de li mua coulor<br>
Qui ains iert blance conme flor<br>
Que por yver que por este<br>
Tout li noircirent li coste<br>
Coulor mua se bloie crine<br>
Blanche devint com une hermine<br>
Le bouce li fu tenevie<br>
& environ toute noirchie<br>
& avoit tant noir le menton<br>
Conme s'il fust taint de carbon<br>
Atenerge furent li oel<br>
N'i avoit ore point d'orguel<br>
Se vos veissies les oreilles<br>
Molt par vos presist grans merveilles<br>
Car noire estoit & decrevee<br>
Le blanche char toute muee<br>
Noire & muee ert le poitrine<br>
A escorce samblant d'espine<br>
N'avoit plus char en ses traians<br>
Ne mais com il a en uns gans<br>
Les bras les mains & les lons dois<br>
Avoit plus noirs que nule pois<br>
Ongles avoit longes & grans<br>
Ele les retailloit a ses dens<br>
Li ventres li estoit caoit<br>
Petit de despensse i metoit<br>
Li pie li erent decreve<br>
En plusors lius erent navre<br>
Car ele ne se gardoit d'espine<br>
Quant ele aloit par le gastine<br>
Che li ert vis sien esciant<br>
Que ele n'i failloit nient<br>
C'uns de ses pekies li caoit<br>
Quant une espine le pongnoit<br>
Por chou estoit ele molt lie<br>
Quant ele souffroit le hasquie<br>
N'est merveille se iert noirchie<br>
Car molt demenoit aspee vie<br>
Plus de xl. ans ala nue<br>
N'iert merveille se iert moussue<br>
Povre despense avoit o li<br>
Or ait Jhesus de li merchi<br>
.ii. pains avoit ne gaires grans<br>
De chiaus vesqui par plusors ans<br>
El premier an devinrrent dur<br>
Com se fust pierre de mur<br>
Cascun jor en usoit Marie<br>
Mais che iert petite partie<br>
Quant ele ot tot son pain use<br>
Puis esrachoit l'erbe del pre<br>
Quant autre beste le mengoit<br>
de rien ne se confortoit<br>
As mains buvoit l'iaue el ruissel<br>
Quant ele n'avoit autre vaissel<br>
Ne font a plaindre li pechie<br>
Dont li cors fu si castie<br>
D'erbe vesqui & de rachines<br>
Xvii. ans. par les gastines<br>
Puis fu .xxx. ans onc ne menga<br>
Se angeles ne li aporta<br>
Li diables le an premier<br>
Le soloit sovent essaier<br>
Tout che li faisoit remembrer<br>
Qu'ele soloit tos jors amer<br>
Les bons mengiers & les biax lieus<br>
Ou ele soloit faire les geus<br>
Or fu ichi boneuree<br>
Qu'ele de tout fu obliee<br>
Onques puis en toute se vie<br>
Ne li souvint mais de folie<br>
Ne ainc en trestot le boscaige<br>
Ne li vint puis beste salvaige<br>
Ne autre vive creature<br>
Par le gaut va toute seure<br>
En plusors lius prist son ostel<br>
Se vie ert tote esperitel<br>
.....<br>
  </div>
  <div class="hover-text">
.....<br>
Of her beauty, of her figure<br>
as it is in the written source<br>
I want to say a little about her appearance<br>
before I go too far.<br>
For at that time in that reign,<br>
no man saw a more beautiful woman.<br>
Never countess nor queen<br>
had over her brow more beautiful hair.<br>
She had round ears.<br>
What's more, they were marvelously white,<br>
her eyes bright and smiling,<br>
her eyebrows black and becoming,<br>
her little mouth mild,<br>
and pious her gaze,<br>
her face tender and blushing<br>
like the rose that is always in bloom.<br>
Indeed neither on her nose nor on her chin<br>
would you be aware of any defect.<br>
Her neck was white like ermine too.<br>
There flowed her blonde hair.<br>
The breasts of this lady<br>
were no smaller than apples.<br>
Above the cleavage of her chest,<br>
it was white like hawthorn flower.<br>
She had white arms and white hands,<br>
her fingers shapely, slender, and smooth.<br>
She had a fine body and well molded<br>
from her underarm along her rib.<br>
She was neither too big nor too small.<br>
Her frame could never be written.<br>
The beauty of this lady<br>
could never be written by any man.<br>
She was so courteous of speech.<br>
There was nothing to improve.<br>
Such a creature makes one lament<br>
when she does not care about the Creator.<br>
She received many presents<br>
and bought herself good garments.<br>
She had good and fitting clothes<br>
to better please her lovers.<br>
She did not care for woollen cloth.<br>
On the worst day of the week,<br>
she had a fine purple silk bliaut<br>
and adorned herself with an ermine mantle.<br>
Well-painted shoes of Cordovan leather<br>
she put these on all the days of the year.<br>
The citizens of the city<br>
loved her entirely for her beauty.<br>
The old men and the wise<br>
would all say, "God, what a shame!<br>
Oh alas evermore for this suffering!<br>
There is much to bemoan of her youth.<br>
Alas evermore for her life<br>
as it is so full of folly."<br>
Everyone in the city would say<br>
that she was of high parentage<br>
for she answered all with reason<br>
and had such a beautiful frame<br>
that the son of an emperor<br>
could have taken her with great honor.<br>
.....<br>
So she went by day and by night<br>
hungry, thirsty, and on hard beds.<br>
She was so deep in the wood<br>
that she became entirely wild there,<br>
but she never forgot<br>
to pray to saint May.<br>
Often she remembered the image<br>
on which she had made her pledge.<br>
Soon her shoes were worn out,<br>
and soon her clothes were all torn up.<br>
Her body was left totally naked.<br>
She did not have clothing that was not in tatters.<br>
Her own flesh changed color,<br>
that which before was white like a flower.<br>
From winter as from summer,<br>
her sides blackened entirely.<br>
The color of her blonde hair changed.<br>
It turned white like an ermine.<br>
Her mouth was thinned,<br>
and all around it blackened,<br>
and her chin was so black<br>
as though it were dyed with charcoal.<br>
Thinned were her eyes.<br>
There was not a shred of pride now.<br>
If you saw her ears,<br>
you would really take in a great marvel.<br>
for they were black and cracked.<br>
Her white flesh changed entirely<br>
Black and changed was her chest.<br>
It seemed like thorny bark.<br>
There was no more flesh in her breasts,<br>
no more than there is in a glove.<br>
Her arms, her hands, and her long fingers<br>
were blacker than any pitch.<br>
She had long and large nails.<br>
She reshaped them with her teeth.<br>
Her stomach was sunken.<br>
She put little provisions in there.<br>
Her feet were split.<br>
In many places, they were wounded<br>
for she did not protect herself from thorns<br>
as she went through the wilderness.<br>
It seemed to her, in her mind,<br>
she was not wrong about this at all,<br>
that one of her sins fell away<br>
when a thorn pricked her.<br>
For this, she was so pleased<br>
as she suffered hardship.<br>
It was no marvel that she was blackened<br>
for she led such a severe life.<br>
After more than forty years in the nude,<br>
it was no marvel she was wooly.<br>
She had poor provisions with her.<br>
Pray, may Jesus have mercy on her.<br>
She had two breads of no great size.<br>
On these, she lived for many years.<br>
In the first year, they became hard<br>
as though they were building stones.<br>
Each day, Mary ate some,<br>
but this was a small portion.<br>
As soon as she had eaten up all her bread,<br>
then she plucked the grass nearby.<br>
Like other beasts she ate it.<br>
She provided herself with nothing else.<br>
On her hands, she drank the water from the stream<br>
as she had no other vessel.<br>
She does not bemoan her sins<br>
as her body is so chastised.<br>
On grass she lived and on roots<br>
for seventeen years in the wilderness.<br>
Then for thirty years, she ate nothing<br>
unless an angel brought it to her.<br>
In the first year, the devil<br>
often used to tempt her,<br>
making her remember all<br>
that she used to always love.<br>
The good eats and the beautiful places<br>
where she was used to playing games.<br>
Now, she was so blissful<br>
that she had forgotten all.<br>
Never then in all her life<br>
did she think more of folly.<br>
Never in all the wood<br>
did any wild beast come to her thereafter<br>
nor any other living creature.<br>
Through the forest, she goes completely safe.<br>
In many places, she took shelter.<br>
Her life was entirely spiritual.<br>
.....<br>
  </div>
</div>
:::

::: {.portrait-column}
## T-B
<div class="text-container">
  <div class="default-text">
.....<br>
de sa biate de sa figure.<br>
si com ele est en l'escriture<br>
Vos vuel dire de se senblant.<br>
ancois que je trespas avant<br>
Ans en cest mont ne en cest regne.<br>
Ne vit nuz hom plus bele feme<br>
Onques ducoise ne roine.<br>
ne n'ot el cief plus bele crine<br>
Reondes avoit les orelhes.<br>
Mais blanches erent a mervelhes<br>
Les sorciz noirs & avenanz.<br>
& les olz clers & sorrianz<br>
La face tenre en celee.ee.<br>
Com la rose ki or est nee<br>
Les dens ot blans & bien menuz.<br>
plus bele boce ne vit nuz<br>
mut avoit piue regardure.<br>
& cler le vis & le faiture<br>
Je cui el neis ne el menton.<br>
n'avoit un point de mesfacon<br>
Soz la boce sor le poitrine.<br>
ert plus blanche ke flors d'espine<br>
& si avoit beles mameles.<br>
mut bien seans petiz & beles<br>
blans bras avoit & blanches mains.<br>
& les dois grailes lons & plains<br>
Gent cors avoit & bien moleit.<br>
desoz l'aisselle & le costeit<br>
tant ert cortoise de parler<br>
n'i avoit rien ke amendeir<br>
N'ert pas trop grant ne trop petite.<br>
Ja se facons n'en iert descrite<br>
Ja le beate de ceste toise.<br>
N'iert descrite se n'i at proise<br>
a plendre fait tel creature.<br>
cant de se Creator n'at cure<br>
ele recivoit grans presenz.<br>
s'en achatoit chier garnimenz<br>
bon dras avoit & avenanz.<br>
por miez plaissir a ses amanz<br>
& ne vestoit pas dras de laine.<br>
Le peior jor de la samaine<br>
Vestoit bon bliat d'osterlin.<br>
& affiebloit mantel d'ermin<br>
Solers biens poins de corduan.<br>
chacoit par toz les jors de l'an<br>
Li citain de la citeit.<br>
L'amoient tuit por sa bialteie<br>
& li viel home & li sage.<br>
disoient tuit Deus kel damage<br>
tant mar fut iceste dolente.<br>
mut fait a plendre sa jovente<br>
mar fut onques la sue vie.<br>
que tant est plane de folie<br>
car a toz respondoit raison.<br>
tant ert de bele afaitison<br>
Que li fiz d'un empereor.<br>
la poist prendre par honor<br>
.....<br>
tant errat par nuiz & par dis.<br>
a fain a soit & a durs lis<br>
Que tant i fut en le boscage.<br>
qu'ele devint tote salvage<br>
Senpres furent si drap useit.<br>
& soi soler tot depaneit<br>
tant par l'iver tant par l'esteit.<br>
tot li noicirent li costeit<br>
Se tenre car muat color.<br>
qui ans eret blance cum florr<br>
Color muat sa bele crine.<br>
blance devint conme l'ermine<br>
desoz la face eret brulee.<br>
del soloilh & de la jalee<br>
La boche li ert atenevie.<br>
& environ la cars norcie<br>
& tant avoit noir le menton.<br>
com se fuist li chies d'un tison<br>
atenevit erent li oilh.<br>
or n'i avoit il point d'orgoilh<br>
se vos en veissiez l'orelhe<br>
mut vos venist a grant mervelhe<br>
car maigre ert mut & degregue.<br>
& de blanc poilh tote mossue<br>
Noire & polhue ert la poitrine.<br>
sembloit scorce de noire spine<br>
Li ventres li ert toz caoiz.<br>
nient ne manjoit & si ert droiz<br>
Les ongles avoit ele granz.<br>
ele les retalloit az danz<br>
Les piez maigres & decrevez.<br>
& par plusors lius mut navrez<br>
car ele nes gardoit d'espine.<br>
cant el aloit par le gastine<br>
Ans li ert vis son escient.<br>
& ele ni faloit nient<br>
cant une spine li poindoit.<br>
uns des pechiez jus li chaoit<br>
Ne fat a plaindre li pechiez.<br>
dont li cors est si castoiez<br>
N'ert mervelhe s'ele ert mossue.<br>
karante ans alat tote nue<br>
Dous pains avoit ne gaire granz.<br>
de ces viscat par plusors anz<br>
Le premier an devinrent dur.<br>
com ce fust piere de mur<br>
cascun jor en usoit Marie.<br>
mais ce astoit mut povre vie<br>
cant ele ot toz ses pains useiz.<br>
puis esragat herbes des prez<br>
com altre beste le manjoit.<br>
de rien ne se desconfortoit<br>
Ades bevoit ens el ruisel.<br>
ele n'avoit altre vaissel<br>
d'erbes vivoit & de racines.<br>
dis & uit ans par la gastines<br>
Puis fut vint ans que ne manja.<br>
sel angeles Deu ne li porta<br>
Diables li vint devant premier.<br>
que mut le soloit anoier<br>
que li faissoit ramembrer.<br>
kanque soloit jadis ameir<br>
Les biaz deliz & les biaz giuz.<br>
u soloit faire ses deduiz<br>
Mut fut bieneuree.<br>
ki de tot ce fut obliee<br>
unques puis en la sue vie.<br>
Ne li menbra jor de folie<br>
Marie vat par le boscage.<br>
Onques n'i vit beste salvage<br>
Ne nule vive creature.<br>
par le forest vat bien segure<br>
en plusors lius fut ses ostaz.<br>
sa vie astoit spirituaz<br>
.....<br>
  </div>
  <div class="hover-text">
.....<br>
Of her beauty, of her figure<br>
as it is in the written source<br>
I want to tell you about her appearance.<br>
before I go too far.<br>
In this world and in this reign,<br>
no man saw a more beautiful woman.<br>
Never duchess nor queen<br>
had on her head more beautiful hair.<br>
She had round ears.<br>
What's more, they were marvelously white,<br>
her eyebrows black and becoming,<br>
and her eyes bright and smiling,<br>
her face tender and covered<br>
like the rose that has only just bloomed.<br>
Her teeth were white and quite small.<br>
A more beautiful mouth no one ever saw.<br>
She had such a pious gaze,<br>
and her look and her features bright.<br>
I believe on her nose and on her chin<br>
there was no defect at all.<br>
Above the bump on her chest,<br>
it was whiter than hawthorn flower,<br>
and of course she had beautiful breasts,<br>
so well set, small, and beautiful.<br>
She had white arms and white hands,<br>
and her fingers slender, long, and smooth.<br>
She had a fine body and was well molded<br>
beneath her underarm and her rib.<br>
She was so courteous of speech.<br>
There was nothing to improve.<br>
She was neither too big nor too small.<br>
Her frame could never be described.<br>
The beauty of these proportions<br>
could neither be described nor appraised<br>
Such a creature makes one lament<br>
when she does not care about her Creator.<br>
She received great presents<br>
and bought herself expensive garments.<br>
She had good and fitting clothes<br>
to better please her lovers,<br>
and she did not wear woollen cloth.<br>
The worst day of the week,<br>
she wore a fine purple silk bliaut<br>
and adorned herself with an ermine mantle.<br>
Well-painted shoes of Cordovan leather<br>
she put these on all the days of the year.<br>
The citizens of the city<br>
loved her entirely for her beauty,<br>
and the old men and the wise<br>
would all say, "God, what a shame!<br>
Alas for this suffering!<br>
There is much to bemoan of her youth.<br>
Alas evermore for her life<br>
is so full of folly."<br>
As she answered all with reason<br>
and had such a beautiful frame,<br>
the son of an emperor<br>
could have taken her with honor.<br>
.....<br>
So she roamed by night and by day<br>
hungry, thirsty, and on hard beds.<br>
Like that, there she was in the wood,<br>
and so, she became entirely wild.<br>
Soon, her clothes were worn out,<br>
and soon her soles were torn up.<br>
As much from winter as from summer,<br>
her sides blackened entirely.<br>
Her tender flesh changed color,<br>
which before was white like a flower.<br>
The color of her beautiful hair changed.<br>
It turned white like the ermine.<br>
Under that, her face was burned<br>
from the sun and from the frost.<br>
Her mouth was thinned,<br>
and her flesh around it blackened,<br>
and her chin was so black<br>
as if it were the head of a firebrand.<br>
Thinned were her eyes.<br>
There was not a shred of pride now.<br>
If you saw her ears,<br>
you would come upon a great marvel<br>
for they were so skinny and degraded<br>
and all wooly with white hairs.<br>
Black and hairy was her chest.<br>
It seemed like black thorny bark.<br>
Her stomach was all sunken.<br>
She ate nothing and so that was right.<br>
She had large nails.<br>
She reshaped them with her teeth.<br>
Her feet were skinny and split,<br>
and in many places were so wounded<br>
for she did not protect them from thorns<br>
as she went through the wilderness.<br>
So it seemed to her, in her mind,<br>
and she was not wrong about this at all,<br>
as a thorn pricked her,<br>
one of her sins fell down from her.<br>
She does not bemoan her sins<br>
as her body is so chastised.<br>
It was no marvel that she was wooly;<br>
for forty years, she went totally nude.<br>
She had two breads of no great size.<br>
On these, she lived for many years.<br>
The first year they became hard<br>
as though they were building stone.<br>
Every day, Mary ate some,<br>
but this was a very poor life.<br>
As soon as she had eaten up all her bread,<br>
then she went wild for the grasses nearby<br>
Like other beasts, she ate them.<br>
She provided herself with nothing else.<br>
She drank from the stream all the time.<br>
She had no other vessel.<br>
On grasses she lived and on roots<br> 
for eighteen years in the wilderness.<br>
Then for twenty years, she only ate<br>
what the angel of God brought to her.<br>
The devil came before her first<br>
He used to annoy her so much<br>
making her remember<br>
whatever she once used to love,<br>
the beautiful delights and the beautiful games<br>
in which she used to take pleasure.<br>
She was so blissful<br>
that she had fogotten all of this.<br>
Never again in her life<br>
did she bring to mind a day of folly.<br>
Mary goes through the wood.<br>
Never did she see a wild beast<br>
nor any living creature.<br>
Through the forest, she goes so secure.<br>
In many places, she was sheltered.<br>
Her life was spiritual.<br>
.....<br>
  </div>
</div>
:::

::: {.portrait-column}
## T-C
<div class="text-container">
  <div class="default-text">
.....<br>
De sa beaute de sa figure<br>
Si cum il est en escripture .<br>
Voil un poi dire le semblant<br>
Ainz co ke jo pas avant .<br>
A iceu tens n'ert si bele femme<br>
kar ele estoit sur tutes gemme .<br>
Onke cuntesse ne reine<br>
N'ot el chief si bele crine .<br>
Rondes avoit les oreilles<br>
Tres blanches erent a merveilles .<br>
Les surcius noirs e avenanz<br>
e les oils clers e suz rianz .<br>
La buche petite par mesure<br>
e simple avoit la regardure .<br>
La face tendre e coluree<br>
Cum rose qui sempres est nee .<br>
Ne ja au nes n'au mentun<br>
N'aparceussez meffacon .<br>
Par sum le col blanc com ermine<br>
Lui undoit la bloie crine .<br>
Chascun des traianz la dame<br>
N'iert pas maire d'une pome .<br>
Suz la gule en la peitrine<br>
ert blanche come fleur d'espine .<br>
Lung braz avoit e blanche mains<br>
Les dois ronz.greilles e pleins .<br>
Gent cors avoit e bien moullez<br>
Desuz l'essele les long costez .<br>
Ne feut trop grant ne trop petite<br>
Sa facon n'iert ja descrite .<br>
Ne la beaute de ceste dame<br>
N'iert ja descrite pur nul aume .<br>
Tant ert cortoise de parler<br>
Riens n'i avoit kamender .<br>
A pleindre fist teu creature<br>
Quant de sun Creatur n'ot cure .<br>
ele recevrit mut presenz<br>
S'en achatot beau vestemenz .<br>
Bons dras avoit e avenanz<br>
Pur menz pleire a ses amanz .<br>
ele n'avoit soign de dras de leine<br>
Par nul des jurs de la sumeine .<br>
Ainz vesteit bliauz de osterin<br>
e affublout mantel d'ermin .<br>
Sollers bien peinz de cordewan<br>
Chaucot trestuz les jurs del an .<br>
Trestuz cous de la cite<br>
L'amoient pur la beaute .<br>
Li ancien hom e li sage<br>
Disoient. hai. queu damage .<br>
Tant mar fu nee la dolente<br>
Tant fet a pleindre sa juvente .<br>
Mar feut onke la sue vie<br>
Quant si est pleine de folie .<br>
Tuz diseient par la citez<br>
k'ele estoit de grant parentez .<br>
kar a tuz respont par reison<br>
e tant ert bele de fascon .<br>
ke li fiz d'un empereur<br>
La peust prendre a gran honur .<br>
.....<br>
Tant alad ke jurs ke nuiz<br>
Od feims od seifs & od dur liz .<br>
ke tant parfond feut en boscage<br>
Tote devint illoec salvage .<br>
mes ele ne s'obliat mie<br>
De deprier saincte Marie .<br>
sovent li membre de l'ymage<br>
k'ele avoit mis en hostage .<br>
si drapel furent tost usez<br>
e si souler tut deramez .<br>
kant li drapel erent rumpu<br>
Le cors de lui remist tut nu .<br>
La char de lui mua colur<br>
k'einz ert blanche come flur .<br>
ke de l'yver ke de l'este<br>
Tut li nercirent li coste .<br>
Colur muat la bloie crine<br>
Blanche devint com ermine .<br>
La face lui estoit bruillee<br>
Del grant soleil e de gelee .<br>
La buche li ert entenvie<br>
e d'environ tote en nercie .<br>
e tant avoit neir le menton<br>
come co feust chief d'un tison .<br>
Teint e nerci erent li oil<br>
Rien n'i ot ore d'orgoil .<br>
se vos regardisez s'oreille<br>
mut vos serroit grant merveille .<br>
car megres estoit e descrue<br>
e de blanc peil tote mossue<br>
Noire e mossue ert la peitrine<br>
L'escorce semblout d'espine .<br>
N'avoit plus char en sa triant<br>
Ne mes ke n'ad en un gant .<br>
Les braz les mains e les lung dois<br>
Avoit plus noirs ke nule poiz .<br>
Les ungles avoit ele mut grenz<br>
Si les retaillot de ses denz .<br>
Li ventre tut lui ert caeiz<br>
Guere ne mangot. co ert droiz .<br>
Les piez lui erent escrevez<br>
en plusur lius furent nafrez .<br>
k'ele ne se gardoit d'espine<br>
kant ele alot par la guastine .<br>
Co lui ert vis son escient<br>
Pur voir de co ne failli nient .<br>
k'un de ses pechiez chaeit<br>
kant une espine la puigneit .<br>
Pur co feut ele mut lee<br>
kant ele suffri teu haschee .<br>
N'ert merveille se feust nercie<br>
ke mut demenot aspre vie .<br>
plus de quarante anz ala nue<br>
Ne fu merveille s'ert mossue .<br>
Povre despense avoit od lui<br>
Ore ait de lui Jhesu merci .<br>
Dous pains avoit ne guere granz<br>
De ces se garit plusurs anz .<br>
Tut al premor devindrent dur<br>
Cum s'il feusent fet de mur .<br>
Chescun jor en usout Marie<br>
mes co ert petite partie .<br>
kant ele out son pain use<br>
Doncs arracot l'erbe du pre .<br>
Com autre beste la mangot<br>
De rien ne se desconfortout .<br>
Adenz leveit un rosel<br>
Dont beut n'ot autre vessel .<br>
Ne fet a pleindre le pechie<br>
Dont le cors fu si chastie .<br>
D'erbe vesquit e de racine<br>
Dis e ut. anz en la gastine .<br>
pus fu trente anz onc ne manga<br>
si l'angle Deu ne lui porta .<br>
Diables la veneient esprimer<br>
Sovent la soleient assaer .<br>
Tut co lui firent remembrer<br>
k'ele soleit ja dis amer .<br>
Les bons mangers e les beau lius<br>
Ou ele soleit fere ses gius .<br>
Lors feut ele si bonureie<br>
ke de rien n'ert attameie .<br>
unk en tote soue vie<br>
Ne lui sovint puis de folie .<br>
Ne puis en trestut le boscage<br>
Ne vit guere beste sauvage .<br>
N'autre vive creature<br>
Par la forest vait tute sure .<br>
en plusur lius prent son hostal<br>
Sa vie est tute espirital .<br>
.....<br>
  </div>
  <div class="hover-text">
.....<br>
Of her beauty, of her figure<br>
as it is in the written source<br>
I want to say a little about her appearance<br>
before I go on.<br>
At that time, there was no woman so beautiful<br>
for she was a gem above them all.<br>
Never countess nor queen<br>
had on her head such beautiful hair.<br>
She had round ears.<br>
They were very marvelously white,<br>
her eyebrows black and becoming,<br>
and her eyes bright and overjoyed,<br>
her little mouth mild,<br>
and she had a simple gaze,<br>
her face tender and blushing<br>
like a rose that is always in bloom.<br>
Indeed neither on her nose nor on her chin<br>
would you be aware of any defect.<br>
Along her neck was white like ermine.<br>
There flowed her blonde hair.<br>
Each of the breasts of the lady<br>
was no more than an apple.<br>
Above the cleavage of her chest,<br>
it was white like hawthorn flower.<br>
She had long arms and white hands,<br>
her fingers shapely, slender, and smooth.<br>
She had a fine body and was well molded<br>
from her underarm along her rib.<br>
She was neither too big nor too small.<br>
Her frame could never be described.<br>
Nor could the beauty of this lady<br>
ever be described by any man.<br>
She was so courteous of speech.<br>
There was nothing to improve.<br>
Such a creature makes one lament<br>
when she does not care about her Creator.<br>
She received many presents<br>
and bought herself beautiful garments.<br>
She had good and fitting clothes<br>
to better please her lovers.<br>
She did not care for woollen cloth.<br>
On any of the days of the week,<br>
she wore her own bliaut of fine purple silk<br>
and adorned herself with an ermine mantle.<br>
Well-painted shoes of Cordovan leather,<br>
she put these on all the days of the year.<br>
Every man of the city<br>
loved her for her beauty.<br>
The old men and the wise<br>
would say, "Ah! What a shame!<br>
Alas was born suffering!<br>
There is much to bemoan of her youth.<br>
Alas evermore, her life<br>
is so full of folly."<br>
Everyone in the city would say<br>
that she was of great parentage<br>
for she answered all with reason<br>
and had such a beautiful frame<br>
that the son of an emperor<br>
could have taken her with great honor.<br>
.....<br>
So she went in the day as in the night<br>
hungry, thirsty, and on hard beds.<br>
She was so deep in the wood<br>
that she became entirely wild there,<br>
but she never forgot<br>
to pray to saint Mary.<br>
Often she remembered the image<br>
on which she had made her pledge.<br>
Soon her clothes were worn out<br>
and soon her soles were stripped.<br>
As her clothes were in tatters,<br>
her body was left totally naked.<br>
Her own flesh changed color,<br>
that which before was white like a flower.<br>
From the winter and from the summer<br>
her sides blackened entirely.<br>
The color of her blonde hair changed.<br>
It turned white like ermine.<br>
Her face was burned<br>
by the blazing sun and by the frost.<br>
Her mouth was thinned<br>
and all around it blackened,<br>
and her chin was so black<br>
it was like the head of a firebrand.<br>
Tinted and blackened were her eyes.<br>
There was not any pride there now.<br>
If you saw her ears,<br>
they would really be to you a great marvel<br>
for they were skinny and cracked<br>
and all wooly with white hairs.<br>
Black and wooly was her chest.<br>
It seemed like thorny bark.<br>
She had no more flesh in her breast,<br>
no more than there is in a glove.<br>
Her arms, her hands, and her long fingers<br>
were blacker than any pitch.<br>
She had such large nails.<br>
So she reshaped them with her teeth.<br>
Her stomach was all sunken.<br>
She hardly ate, so that was right.<br>
Her feet were split.<br>
In many places, they were wounded<br>
for she did not protect herself from thorns<br>
as she went through the wilderness.<br>
It seemed to her, in her mind,<br>
for truly, about this, she was not wrong at all,<br>
that one of her sins fell away<br>
when a thorn pricked her.<br>
For this, she was so pleased.<br>
As she suffered such hardship,<br>
it was no wonder that she was blackened<br>
for she led such a severe life.<br>
After more than forty years in the nude,<br>
it was no wonder she was wooly.<br>
She had poor provisions with her.<br>
Pray, may Jesus have mercy on her.<br>
She had two breads of no great size.<br>
On these she sustained herself for many years.<br>
They all became hard in the first year<br>
as though they were made from a wall.<br>
Each day, Mary ate some,<br>
but this was a small portion.<br>
As soon as she had eaten up her bread,<br>
then she gathered the grass nearby.<br>
Like other beasts she ate it.<br>
She provided herself with nothing else.<br>
Prone, she drew from a stream.<br>
Like so, she drank. She had no other vessel.<br>
She does not bemoan her sins<br>
as her body was so chastised.<br>
On grass she lived and on roots<br>
for eighteen years in the wilderness.<br>
Then for thirty years, she never ate<br>
but what the angel of God brought to her.<br>
Devils came to approach her.<br>
Often they used to tempt her,<br>
making her remember all<br>
that she once used to love.<br>
The good eats and the beautiful places<br>
where she was used to playing her games.<br>
Now, she was so blissful<br>
that nothing hurt her.<br>
Never, in all her life,<br>
did she think, then, of folly.<br>
Nor, then, in all the wood,<br>
did she see wild beasts at all.<br>
nor any other living creature.<br>
Through the forest, she goes totally sure.<br>
In many places, she takes shelter.<br>
Her life is entirely spiritual.<br>
.....<br>
  </div>
</div>
:::

::: {.portrait-column}
## T-D
<div class="text-container">
  <div class="default-text">
.....<br>
De sa bealte & de sa figure<br>
Si cum est en l'escripture<br>
voil un poi dire le semblant<br>
einz que jeo trespas avant<br>
en cel tens ne en cel regne<br>
Ne vit unc home plus bele femme<br>
Ne cuntesse ne raine.<br>
N'out onkes tele meschine<br>
roundes avoit les oreilles<br>
Mais blanches erent a merveilles<br>
les sorciz neirs & avenanz<br>
les oilz neirs & sorianz<br>
la bouche brieve & par mesure<br>
& pie la regardeure<br>
la face tendre & coloree<br>
cumme rose qui senpres est nee<br>
ja el nes ne el mentun<br>
N'i veist l'un mesfacun<br>
par sun le col blanc cum ermine<br>
li undout la bloie crine<br>
chascun des traianz a la dune<br>
N'ert mie greignor d'une pume<br>
Soz la gorge en la poitrine<br>
ere blanche cumme flor d'espine<br>
blans bras aveit & beles mains<br>
& les deis luncs gresles & pleins<br>
N'ert trop grande ne trop petite<br>
ja sa facun n'iert deserite<br>
ja la bealte de ceste dune<br>
N'iert escrite por nul home<br>
tant ert corteise de parler<br>
rien n'i aveit que amender<br>
a plaindre fait tel creature<br>
Quant del Creator n'aveit cure<br>
ele recevoit or & argent<br>
Si achatout bons garnemenz<br>
bons dras aveit & avenanz<br>
por miex plesir a ses amanz<br>
ele n'out cure de dras de leine<br>
al peor jor de la semeine<br>
Vesteit bons bliaus d'osturin<br>
& afubla mantel hermin<br>
Soulers bien pains de cordouen<br>
chaucout a toz les jors de l'an<br>
li citeen de la cite<br>
l'amouent tuit por sa bealte<br>
li anciem home & li sage<br>
disoient tuit Deus quel damage<br>
Mar fu unques la dolente<br>
tant fait a plaindre sa jovente<br>
Mar fu unques la soue vie<br>
Quant si est pleine de folie<br>
tuit disoient par la cite<br>
Que ele ert de mult halt parente<br>
car a toz rosponeit raisun<br>
& tant ert bele de facun<br>
ke le fiz d'un enpereor<br>
la peust prendre par honor<br>
.....<br>
tant erra par jor. & par nuit<br>
o faim. & o sei. & o dur lit<br>
& tant fu en cel boscage<br>
tote devint iloc salvage<br>
mais ele ne s'oublia mie<br>
de deprier sainte Marie<br>
sovent lui membre de l'ymage<br>
Que ele aveit mis en ostage<br>
Ses soulers furent tuit uses<br>
& si drapel tuit descires<br>
Quant si drapel furent rumpu<br>
le cors de lui remist tot nu<br>
la char de lui mua color<br>
Qui ainz ert blanche cumme flor<br>
Que o l'ivern. ke o l'este<br>
tuit li nercirent li coste<br>
color mua sa bloie crigne<br>
blanche devint cumme ermigne<br>
la face out desus bruslee<br>
del soleil. & de la gelee<br>
la bouche li fu atenvie<br>
& envirun la char nercie<br>
tant par esteit noir sun mentun.<br>
cum ceo fust le chief d'un tisun<br>
& nerci erent si oil<br>
N'i aveit ore point d'orguil<br>
Se vous veisses sa oreille<br>
mult vous semblast grant merveille<br>
car mesgre esteit. & detrevee<br>
& de blanc peil avirunee<br>
N'aveit plus char en sun traiant<br>
Ne mais cum il a en un gant<br>
les bras. les mains. & les deiz<br>
aveit plus neirs que nule peiz<br>
les ongles aveit ele grenz<br>
ele les taillout o les denz<br>
le ventre lui ert tot dechaet<br>
car povre despense i meteit<br>
les piez li erent decrevez<br>
en plusors lieus erent nafrez<br>
car ele ne se gardout de espine<br>
Quant ele alout par la gastine<br>
mais ceo li ert vis son encient<br>
& ele n'i failli de nient<br>
ke un peche de lui chaeit<br>
Quant une espine la poingneit<br>
por ceo esteit ele lee<br>
Quant ele soffri une haschee<br>
N'ert pas merveille s'ele ert nercie<br>
car ele demenout aspre vie<br>
plus de quarante ans ala nue<br>
N'ert merveille s'ele ert mossue<br>
povre despense aveit o lui<br>
ore ait Jesus de lui merci<br>
deus pains aveit ne gueres granz<br>
de cels vesqui plusors anz<br>
el premier en devindrent dur<br>
cumme ceo fussent pieres de mur<br>
chascun jor en usout Marie<br>
mais ceo ert petite partie<br>
& quant ele out son pain use<br>
Si esracout l'erbe del pre<br>
cumme altre beste la manjout<br>
& de rien ne se desconfortout<br>
a denz beveit del ruissel<br>
ele naveit altre vaissel<br>
Ne fait a plaindre le pechie<br>
dunt le cors fu si chastie<br>
d'erbes viveit. & de racines<br>
dis. & set anz. en la gastine<br>
puis fu trente anz unc ne manja<br>
Se li angres Deu ne lui porta<br>
deable lui vint de premier<br>
Sovent la soloit essaier<br>
tot ceo lui faisoit remembrer<br>
Que ele soloit jadis amer<br>
les bons mangiers. & les lieus<br>
ou ele sout faire ses gieus<br>
ore fu issi beneuree<br>
Que de tot ceo fu obliee<br>
& en tote la soue vie<br>
Ne lui sovint puis de la folie<br>
& unc puis en tot le boscage<br>
Ne vit beste salvage<br>
Ne altre vive creature<br>
par la forest vait tote seure<br>
en plusors lieus prent son ostal<br>
Sa vie esteit esperital<br>
.....<br>
  </div>
  <div class="hover-text">
.....<br>
Of her beauty and of her figure<br>
as it is in the written source<br>
I want to say a little about her appearance<br>
before I go too far.<br>
At that time and in that reign,<br>
no man ever saw a more beautiful woman.<br>
No countess or queen<br>
ever had such a daughter.<br>
She had round ears,<br>
what's more, they were marvelously white,<br>
her eyebrows black and becoming,<br>
her eyes black and smiling,<br>
her mouth small and mild,<br>
and pious her gaze,<br>
her face tender and blushing<br>
like a rose that is always in bloom.<br>
Indeed neither on her nose nor on her chin<br>
was seen a defect.<br>
Along her neck was white like ermine.<br>
There flowed her blonde hair.<br>
Each of the breasts of the lady<br>
was not a bit bigger than an apple.<br>
Above the cleavage of her chest,<br>
it was white like hawthorn flower.<br>
She had white arms and white hands,<br>
and long, slender, and smooth fingers.<br>
She was neither too big nor too small.<br>
Her frame could never be described.<br>
The beauty of this lady<br>
could never be written by any man.<br>
She was so courteous in speech.<br>
There was nothing to improve.<br>
Such a creature makes one lament<br>
when she does not care about the Creator.<br>
She received gold and silver<br>
and bought good garments.<br>
She had good and fitting clothes<br>
to better please her lovers.<br>
She did not care for woollen cloth.<br>
On the worst day of the week,<br>
she wore a fine purple silk bliaut<br>
and adorned herself with an ermine mantle.<br>
Well-painted shoes of Cordovan leather,<br>
she put these on all the days of the year.<br>
The citizens of the city<br>
loved her entirely for her beauty.<br>
The old men and the wise<br>
all would say, "God, what a shame!<br>
Alas evermore, the suffering!<br>
There is much to bemoan of her youth.<br>
Alas evermore, her life<br>
is so full of folly."<br>
Everyone in the city would say<br>
that she was of such high parentage<br>
for she answered all with reason<br>
and had such a beautiful frame<br>
that the son of an emperor<br>
could have taken her with honor.<br>
.....<br>
So she roamed by day and by night,<br>
hungry and thirsty and on hard beds,<br>
and so she was in this wood.<br>
She became entirely wild there,<br>
but she never forgot<br>
to pray to saint Mary.<br>
Often, she remembers the image<br>
on which she had made her pledge.<br>
Her soles were all worn out,<br>
and soon her clothes were torn up.<br>
As her clothes were in tatters,<br>
her body was left totally naked.<br>
Her own flesh changed color,<br>
that which before was white like a flower.<br>
From the winter and from the summer<br>
her sides blackened entirely.<br>
The color of her blonde hair changed.<br>
It turned white like ermine.<br>
Her face was burned up<br>
from the sun and from the frost.<br>
Her mouth was thinned,<br>
and her flesh around it blackened.<br>
Her chin was so black all over.<br>
It was like the head of a firebrand,<br>
and black were her eyes.<br>
There was not a shred of pride now.<br>
If you saw her ears,<br>
they would really seem to you a great marvel<br>
for they were skinny and cracked<br>
and covered in white hair.<br>
She had no more flesh in her breast,<br>
no more than there is in a glove.<br>
Her arms, her hands, and her fingers<br>
were blacker than any pitch.<br>
She had large nails.<br>
She shaped them with her teeth.<br>
Her stomach was all sunken<br>
for she put poor provisions in there.<br>
Her feet were split<br>
and, in many places, were wounded<br>
for she did not protect herself from thorns<br>
as she went through the wilderness.<br>
But it seemed to her, in her mind,<br>
and she was not wrong about this at all,<br>
that a sin fell away from her<br>
when a thorn pricked her.<br>
For this, she was pleased.<br>
As she suffered hardship,<br>
it was no wonder she was blackened<br>
for she led a severe life.<br>
After more than forty years in the nude,<br>
it was no wonder she was wooly.<br>
She had poor provisions with her.<br>
Pray, may Jesus have mercy on her.<br>
She had two breads of no great size.<br>
On these, she lived for many years.<br>
In the first year, they became hard<br>
as though they were building stones.<br>
Each day, Mary ate some,<br>
but this was a small portion.<br>
And as soon as she had eaten up her bread,<br>
then she plucked the grass nearby.<br>
Like other beasts, she ate it.<br>
And she provided herself with nothing else.<br>
Prone, she drank from the stream.<br>
She had no other vessel.<br>
She does not bemoan her sins<br>
as her body was so chastised.<br>
On grasses she lived and on roots<br>
for seventeen years in the wilderness.<br>
Then, for thirty years, she never ate<br>
but what the angel of God brought to her.<br>
The devil came to her first.<br>
Often he used to tempt her,<br>
making her remember all<br>
that she once used to love.<br>
The good eats and the places<br>
where she was used to playing her games.<br>
Now, she was so blissful<br>
as she had forgotten all of this.<br>
And in all her life,<br>
she never thought of folly.<br>
And never then in all the wood<br>
did she see any wild beast<br>
nor any other living creature<br>
Through the forest, she goes totally sure.<br>
In many places, she takes shelter.<br>
Her life was spiritual.<br>
.....<br>
  </div>
</div>
:::

::: {.portrait-column}
## T-E
<div class="text-container">
  <div class="default-text">
.....<br>
de sa bieute de sa figure<br>
Si com il est en escripture<br>
Voil -i- poi dire le samblant<br>
ancois que jo trespas avant<br>
En icel tans ne en cel regne<br>
N'en ot onques plus bele feme<br>
onques comtesse ne roine<br>
Nen ot el chief plus bele crigne<br>
rondes avoit les oreilles<br>
& blances erent a merveilles<br>
les sorcils nois & avenans<br>
& les ioex vairs & molt rians<br>
La bouche bele & par mesure<br>
& pieue la regardeure<br>
la face tenre & coloree<br>
comme rose novele nee<br>
Ne ja el nes ne el menton<br>
Ne parceuscies mesfacon<br>
Le col avoit blanc com ermine<br>
Loiet estoit sa blonde crine<br>
N'iert mie greindres d'une pome<br>
L'un des traians de cele domme<br>
desus la boce en la poitrine<br>
Ert si blance com flor d'espine<br>
blans bras avoit & blances mains<br>
les dois reons greilles & plains<br>
Gent cors avoit & bien molle<br>
Sus l'asoele lanc le coste<br>
Ne trop grande ne trop petite<br>
Ja sa facon n'en ert descrite<br>
la grans biautes de ceste dame<br>
N'iert toute escrite par nul homme<br>
Tant ert cortoise de parler<br>
Rien n'i avoit que amender<br>
a plaindre fait tel creature<br>
Quant de son Creator n'a cure<br>
Ele recevoit grans presens<br>
S'en achatoit biaus garnemens<br>
biaus dras avoit & avenans<br>
por bien plaisir a ses amans<br>
N'avoit pas soing de dras de laine<br>
Al pior jor de la semaine<br>
vestoit bon bliaut ostorin<br>
Si afubloit mantel ermin<br>
Sollers bien pains de cordoan<br>
chaucoit a tus les jors del an<br>
li citeain de la cite<br>
l'amoient tot por sa biaute<br>
li ancien home & li sage<br>
disoient tot que cert damage<br>
tant par mar fu ceste dolente<br>
molt fait a plaindre sa jovente<br>
mar fu onques la soie vie<br>
Quant si est plaine de folie<br>
tot disoient par la cite<br>
Qu'ele ert de haut parente<br>
Car a tos respondoit raison<br>
& molt ert de bele facon<br>
li fiex a -i- empereor<br>
Le peust prendre par honor<br>
.....<br>
tant ala par jor & par nuis<br>
par bos par plains & par larris<br>
& tant par font vint el boscage<br>
Que tot devint iluec salvage<br>
mais ele ne s'oblioit mie<br>
de proier a sainte Marie<br>
Sovent li menbroit del image<br>
Que ele avoit mis en ostage<br>
Si drapel furent tost use<br>
& si sollers tost desrame<br>
Quant si drapel furent ronpu<br>
li cors de li remest tot nu<br>
la sieue char mua color<br>
devant ert blance comme flor<br>
Quant .i. iver i ot este<br>
tot li noircirent li coste<br>
molt li mua la blonde crine<br>
blance devint com .i. ermine<br>
del soleil & de la gelee<br>
li fu la face molt bruslee<br>
Sa bouche fu atenevie<br>
& environ sa char noircie<br>
itant avoit noir le menton<br>
comme ce fust chies d'un tison<br>
tot li erent noir oi li oil<br>
N'avoit ore .i. point d'orgoil<br>
Se vos en veiscies l'oreille<br>
molt vos venist a grant merveille<br>
Qui maigre estoit & decreue<br>
& de blanc poil tote molsue<br>
Noire & molsue ert sa poitrine<br>
bien resambloit escorce d'espine<br>
N'avoit de char en ses traians<br>
Nient plus qu'il est en .i. gans<br>
les bras les mains & les lons dois<br>
Avoit plus noirs que n'en est pois<br>
molt par avoit les ongles grans<br>
as dens les ront qu'ele ot trencans<br>
li ventres li ert agaris<br>
car n'avoit nul de ses delis<br>
li pie li erent decreve<br>
& environ tot denavre<br>
Ele ne se gardoit d'espine<br>
Quant ele aloit par la gastine<br>
Ce li ert vis son escient<br>
del bien faisoit petit u nient<br>
Quant une espine le poignoit<br>
En un de ses pies li chaoit<br>
de co estoit ele molt lie<br>
Quant ele avoit la grant hascie<br>
N'estoit merveille s'iert noircie<br>
car molt demenoit aspre vie<br>
plus de .xl. ans a la nue<br>
N'iert par merveille s'iert mossue<br>
povre despens avoit od li<br>
Damedex ait de li merci<br>
.ii. pains avoit ne gaires grans<br>
de ces vesqui par pluisors ans<br>
le premer an devindrent dur<br>
com ce fuissent pieres de mur<br>
chascun jor en usoit Marie<br>
mais co ert petite partie<br>
Quant ele ot tot son pain use<br>
donques aquelt l'erbe del pre<br>
com autre beste le mangoit<br>
de rien ne se recomfortoit<br>
as dens bevoit dou ruissel<br>
Car n'i avoit autre vaiscel<br>
Ne fait a plaindre li pechiet<br>
dont li cors est si castiet<br>
d'erbe vesqui & de racine<br>
dis & set anz en la gastine<br>
puis fu .xxx. anz que ne manga<br>
Se l'angles Deu ne l'aporta<br>
dyable vint a li de premier<br>
Sovent le soloit assaier<br>
tot ce li faisoit ramenbrer<br>
Qu'ele ja dis soloit amer<br>
les biaus delis & les bels lieus<br>
ou ele seut faire ses gieus<br>
ore fu ele boneuree<br>
Quant de tot ce fu obliee<br>
Ainc gaires puis en tote sa vie<br>
Ne li sovint puis de folie<br>
Ne ainc en trestot le boscage<br>
Ne vit gaires beste salvage<br>
Ne autre vive creature<br>
par la forest vait tote nue<br>
En pluisors lieus prist son ostal<br>
Sa vie estoit esperital<br>
.....<br>
  </div>
  <div class="hover-text">
.....<br>
Of her beauty, of her figure<br>
as it is in the written source<br>
I want to say a little about her appearance<br>
before I go too far.<br>
At that time and in that reign,<br>
there was never a more beautiful woman.<br>
Never countess nor queen<br>
had on her head more beautiful hair.<br>
She had round ears,<br>
and they were marvelously white,<br>
her eyebrows black and becoming,<br>
and her eyes sparkling and joyful,<br>
her mouth beautiful and mild,<br>
and pious her gaze,<br>
her face tender and blushing<br>
like a freshly-bloomed rose.<br>
Indeed neither on her nose nor on her chin<br>
might you perceive any defect.<br>
Her neck was white like ermine.<br>
Long was her blonde hair.<br>
Not a bit bigger than an apple were<br>
either of the breasts of this lady.<br>
Above the bump of her chest,<br>
it was as white as hawthorn flower.<br>
She had white arms and white hands,<br>
her fingers shapely, slender, and smooth.<br>
She had a fine body and was well molded<br>
from her underarm along her rib.<br>
Neither too big nor too small,<br>
her frame could never be described.<br>
The great beauty of this lady<br>
could not be written fully by any man<br>
She was so courteous in speech.<br>
There was nothing to improve.<br>
Such a creature makes one lament<br>
when she does not care about her Creator.<br>
She received great presents,<br>
and bought herself beautiful garments.<br>
She had beautiful and fitting clothes<br>
to please her lovers well.<br>
She did not care for woollen cloth.<br>
On the worst day of the week,<br>
she wore a fine purple silk bliaut<br>
and adorned herself with an ermine mantle.<br>
Well-painted shoes of Cordovan leather,<br>
she put these on all the days of the year.<br>
The citizens of the city<br>
loved her entirely for her beauty.<br>
The old men and the wise<br>
all would say that it was a shame.<br>
"Alas for this suffering!<br>
There is much to bemoan of her youth.<br>
Alas evermore, her life<br>
is so full of folly."<br>
Everyone in the city would say<br>
that she was of high parentage<br>
for she answered all with reason<br>
and had such a beautiful frame.<br>
The son of an emperor<br>
could have taken her with honor.<br>
.....<br>
So she went by day and by night<br>
through woods, through plains, and through hills,<br>
and so deeply she went into the wood<br>
that she became entirely wild there,<br>
but she never forgot<br>
to pray to saint Mary.<br>
Often she remembered the image<br>
on which she had made her pledge.<br>
Soon her clothes were worn out,<br>
and soon her soles were stripped.<br>
As her clothes were in tatters,<br>
her body was left totally naked.<br>
Her own flesh changed color.<br>
Before, it was white like a flower.<br>
In winter as in summer,<br>
her sides blackened entirely.<br>
Her blonde hair changed greatly.<br>
It turned white like an ermine<br>
from the sun and from the frost.<br>
Her face was so burned.<br>
Her mouth was thinned,<br>
and her flesh around it blackened.<br>
Her chin was so black.<br>
It was like the head of a firebrand.<br>
All black were her eyes now.<br>
She had, now, not a shred of pride.<br>
If you saw her ears,<br>
you would come upon a great marvel<br>
that was skinny and cracked<br>
and all wooly with white hairs.<br>
Black and wooly was her chest.<br>
It so ressembled thorny bark.<br>
She did not have flesh in her breasts,<br>
nothing more than there is in a glove.<br>
Her arms, her hands, and her long fingers<br>
were blacker than pitch.<br>
She had such large nails<br>
on her slicing teeth she made them round.<br>
Her stomach was sunken<br>
for she had none of her delights.<br>
Her feet were split<br>
and wounded all over.<br>
She did not protect herself from thorns<br>
as she went through the wilderness.<br>
It seemed to her, in her mind,<br>
that it would do little or no good<br>
for as a thorn pricked her<br>
in one of her feet, it would fall away.<br>
For this, she was so pleased.<br>
As she bore great hardship,<br>
it was no wonder she was blackened<br>
for she led a very severe life.<br>
After more than forty years in the nude,<br>
it was no wonder she was wooly.<br>
She had poor provisions with her.<br>
May God have mercy on her.<br>
She had two breads of no great size.<br>
On these she lived for many years.<br>
The first year, they became hard<br>
as though they were building stones.<br>
Each day, Mary ate some,<br>
but this was a small portion.<br>
As soon as she had eaten up all her bread,<br>
then she gathered the grass nearby.<br>
Like other beasts, she ate it.<br>
She provided herself with nothing else.<br>
Prone, she drank from the stream<br>
for there was no other vessel.<br>
She does not bemoan her sins<br>
as her body is so chastised.<br>
On grass she lived and on roots<br>
for seventeen years in the wilderness.<br>
Then, for thirty years, she ate only<br>
what the angel of God brought to her.<br>
The devil came to her first.<br>
Often he used to tempt her,<br>
making her remember all<br>
that she once used to love.<br>
The beautiful delights and the beautiful places<br>
where she was used to playing her games.<br>
Now, she was blissful<br>
as she had forgotten all of this<br>
before long. Then for all her life,<br>
she never thought of folly.<br>
Never in all the wood<br>
did she see any wild beasts at all<br>
nor any other living creature.<br>
Through the forest, she goes utterly naked.<br>
In many places, she took shelter.<br>
Her life was spiritual.<br>
.....<br>
  </div>
</div>
:::

::: :::