---
title: "Chapter 1. On Digital Editing"
---

More than one hundred and twenty years ago, a manuscript fragment containing some thirty-eight lines of Anglo-Norman verse was pulled from the Qubbat Al-Khazna (The Dome of the Treasury) of the Umayyad Mosque in Damascus by German philologists granted permission to study this archive during the state visit of Wilhelm II to the Levant in the fall of 1898 (Margoliouth 400). Along with the vast collection of other manuscripts preserved there — each containing texts copied in Arabic, Greek, Latin, Hebrew, Aramaic, Coptic, Armenian, and Georgian (Giannini & Minervini 343-344) — this fragment of Old French containing verses from Version T of *La Vie de sainte Marie l’Égyptienne* was examined by these eager philologists who carefully smoothed out the water-damaged fragment and adhered tabs to its edges so that it might be pinned down and properly photographed for transcription and further study. The Swiss-German philologist Adolf Tobler examined the fragment and published an edition of the text in 1903 before the fragment was reportedly returned to Damascus in 1909. Today, the whereabouts of this T fragment are unknown, but the memory of its existence survives in the Staatsbibliothek of Berlin via the preservation of these early twentieth-century photographs and the witness of Tobler’s edition. These photographs are now labeled MSS simulata orientalia 6 — with the T fragment appearing in photographs 101 (recto) and 89 (verso) — and are available for consultation both in-person in the reading room of the Oriental and East Asia Department and online via the Staatsbibliothek’s Digitized Collections. The memory of this lost fragment is the only textual evidence we have that Version T of *La Vie de sainte Marie l’Égyptienne *travelled as far as the Middle East. We cannot know exactly how or why this witness to the T-poem made its way over to the Qubbat Al-Khazna,[^51] but because we know *of *this fragment, we know that it did. The fact of this text’s movement as made evident by the photographs and edition of the now-lost T fragment broadens the context of this saint’s Life and situates it in a larger multicultural and multilingual history.[^52]

Peter Dembowski — who offers the variants of T-F^2^ to readers through the paratext of his 1977 edition of Version T — notes that although this fragment is undoubtedly a copy of the T-poem, “il ne paraît suivre de près aucune des versions connues de notre poème” (27), making it a rather unique copy to consider. And yet, no one working on the French tradition of Mary the Egyptian has made use of this fragment in their analyses. I offer the case of T-F^2^, then, as an opportunity to evaluate the way in which scholars currently discover, search for, study, edit, and share medieval texts today. I invite us all to take stock of our current practices, think about how we can find solutions to the most fundamental challenges to conducting our research, and look optimistically to a future of manuscript studies empowered by digital methods.

The process of tracking down and working on T-F^2^ for this dissertation may sound familiar to anyone with special collections experience. As Bridget Whearty describes in *Digital Codicology: Medieval Books and Modern Labor *(2022):

> Before you can lay hands on a manuscript, you must first know that it exists. You have to also know enough about it to be able to determine if its contents are worth studying — not in the abstract sense that any medieval manuscript is a piece of shared cultural heritage and therefore worth studying in a general way, but in the targeted sense of whether or not a particular text is relevant to your immediate line of inquiry. (163)

Dembowski’s edition acknowledges the existence of T-F^2^ and directs interested readers to Tobler’s 1903 edition, but these editors do not fully agree on their transcriptions of the fragment and neither editor is able to report the fragment’s present location — or the location of any surrogates for the fragment — with any greater detail than Damascus as its place of recovery. Without the fragment itself or at least images of the fragment, it is impossible to verify these editors’ transcriptions — a necessary step in producing a new T edition. Digging deeper into the story of the Qubbat Al-Khazna collection eventually leads to the scholarship of Radiciotti and D’Ottone (2008), which sheds more light on the collection of manuscripts in general but still does not address T-F^2^’s current location. Finally, Giannini and Minervini (2020) provide a more comprehensive analysis of the Old French fragments extracted from the Damascus collection, and they report that T-F^2^ is considered lost. It is because of Giannini and Minervini that I finally became aware of the original photographs currently housed in the Staatsbibliothek and of their digital surrogates now available online; to my knowledge, no prior scholar mentioned the photographic record, even though the images were made at the turn of the nineteenth to twentieth centuries. Buoyed by the existence of these digitized images, I transcribed the fragment for myself, feeling I was, at last, able to enter into a proper editorial conversation with both Tobler and Dembowski concerning T-F^2^.

But using the digitized images alone, I was still unable to replicate either editor’s transcription in full, and suspecting the original photographs could provide greater clarity, I traveled to Berlin. Confronted with a more tangible presence of the fragment in the reading room — even if only an old photograph of the fragment — I felt a profound connection to this artifact and to the centuries-long web of transmission that had brought this twelfth-century text to my twenty-first-century attention.[^53] I was pleased to see that the color contrast was, in fact, a bit clearer — though still mostly illegible in parts — in the material photographs than in the current digitization of the photographs online. In the reading room — knowing that I had limited time with the photographs — I found myself looking more closely and more urgently than I ever had before at the digitized images. It was in the reading room that I noticed the way the philologists had used tabs and little nails to pin the fragment down. Handling the photograph, I was struck by the thought that I was now handling photos produced by someone whose hands presumably touched T-F^2^, and in taking a few pictures of the photo with my iPhone,[^54] I replicated this former photographer’s ritual of remediation.[^55] To be sure, my interaction with the photograph was more gentle — sans glue or nails or bright lights — but the previous photographer and I (and the medieval copyist before us) shared like missions: to create a visual record of this text, to study and edit its contents, and to share its knowledge with others.[^56]

What if the German philologists had never taken these photographs? We might then have no proof that Version T was ever present in the Middle East, and therefore would be left with a far narrower conception of this text’s audience and transmission. What if the Staatsbibliothek did not digitize these photographs or prohibited interested scholars from consulting them, or — even worse — discarded them? No one would ever be able to verify the work of Tobler or Dembowski, and T-F^2^ would be even more of a ghost than it already is.[^57] Although T-F^2^ offers few lines, making it less helpful as a stand-alone witness to the text of Version T, the *fact *of T-F^2^'s existence is important to keep in mind as scholars attempt to determine this text’s purpose, its message, its audience. Giving this fragment scholarly attention opens up the conversation around T to consider the unknown traveler who carried this text apparently in writing — but perhaps mostly in their mind — on their journey east, and keeping this unknown traveler in our mind prevents us from narrowing this text's possibilities.[^58] Individual manuscript copies, however small, have stories that helpfully complicate our narratives of the past and its literature.[^59]

I provide this anecdote of working on T-F^2^ to highlight the fact that access to the ‘originals’ is still necessary and is often preferable, but also that remediation — by way of photographic reproduction, digitization, and/or editing — is just as critically important. Digitization and editing each act as forms of secondhand preservation — particularly valuable in the unfortunate event of a lost original.[^60] And digitization and editing work together ensure our texts remain discoverable and accessible and researchable. In this chapter, I survey the ongoing scholarly conversations concerning the influence of the digital turn on medieval manuscript studies — particularly addressing debates concerning manuscript digitization and questions on the function of digital editions. As I discuss below, digitization and digital editing are by no means meant to replace material sources but rather provide us with still more avenues for making meaningful scholarly inquiries and for ensuring the longevity of our sources even after the material itself has vanished.

## New Philology and the Digital Turn: Opportunities and Anxieties

The call of New Philology — issued more than thirty years ago —[^61] demanded medievalists move away from the hypothesizing work of the text-critical approach in favor of studying texts as they are actually attested in the extant manuscript record. Calling it a “postmodern return to the origins of medieval studies” (7) in his introduction to the movement, Stephen G. Nichols insisted that we welcome the plurality of medieval culture by positioning plurality at the core of our methods:

> If we accept the multiple forms in which our artifacts have been transmitted, we may recognize that medieval culture did not simply live with diversity, it cultivated it. The ‘new’ philology of the last decade or more reminds us that, as medievalists, we need to embrace the consequences of that diversity, not simply to live with it, but to situate it squarely within our methodology. (8-9)

Contemporaneous with the rise of Digital Humanities, I would argue that adherents to New Philology have benefited greatly from the digital advancements that have made it increasingly feasible to embrace variance.

To fully embark on the New Philology turn, scholars require access to surviving copies of medieval texts, including fragmentary ones. And so, the digitization of manuscripts becomes imperative for comprehensive research, as most scholars cannot afford the time and resources necessary to physically explore every relevant scrap of parchment and paper worldwide. Libraries around the world are striving to make their special collections both discoverable and remotely accessible to researchers and educators, but this is a massive undertaking that requires significant time, funding, and collaboration across institutions. The Bibliothèque nationale de France (BnF), for example, established its digital library, Gallica, in 1997 and has since digitized and made freely available millions of documents,[^62] and in North America, Digital Scriptorium — a growing consortium of U.S. institutions with premodern manuscripts — is pushing to create a national catalog where researchers can find documents pertinent to their work all in one digital space. An even greater challenge in terms of discoverability and accessibility is piecing together the many fragments of premodern manuscripts that have been scattered about the world over time, but the digital lab Fragmentarium has created a platform in which scholars may digitally reunite fragments to gain insights that would otherwise be nearly impossible for researchers to see in the real world. More and more, scholars are able to do in the digital space what they have rarely, if ever, been able to do in prestigious and private reading rooms: compare manuscripts side-by-side, zoom in far closer than would normally be permissible, and spend long hours with ‘manuscripts’ all while enjoying a coffee.[^63] Countless members of library staff labor every day to make this digital revolution possible, and this labor is only just beginning to be recognized as itself invaluable intellectual labor.[^64]

And yet, these major developments in digitization over the past several decades bring with them major anxieties as some scholars continue to cry out for the preservation of more traditional methods. Writing in defense of reading on a human scale and at a human pace, Ryan Szpiech provides a thorough manifesto in “Cracking the Code: Reflections on Manuscripts in the Age of Digital Books” (2014) on the primacy of reading physical manuscripts over any other format.[^65] Embracing fetishism and railing against utility,[^66] Szpiech perceives the manuscript to be an “anti-book” (87) ever capable of resisting any digital methods to contain it.[^67] Szpiech insists he is no “Luddite” (87); rather, he argues, “If our goal is dialogue, engagement, contemplation, or reading — reading for meaning, for inspiration, for cadence, for form, for beauty, or for any other intangible good — then electronic tools are of only limited use, and may just as well prove a hindrance.” (87). And even more relevant to the work of this dissertation, Szpiech writes vehemently against the production of digital editions and digital facsimiles:

> Unlike the critical edition, which has the unlikely virtue of being dry and difficult to use (and thus at least never truly threatening to replace the manuscript with the sign of itself), and unlike the printed facsimile, which has the virtue of requiring the reader to use it more or less as he or she would use the manuscript itself (and thus provoking no essential imbalance in power between the knower and the known), the digital edition and the digital facsimile bedazzle the reader and create interpretive disequilibrium with the effectiveness and intensity of their simulation. Just as Google Books does not simply strive to augment the reading of a book but to actually replace the reader’s book with the searcher’s book, so the ultimate goal of digital editions and digital facsimiles, I believe, is not only to reflect the “original,” to “capture” or “recapture” it, but to effectively replace it with a better image of itself. Whereas philology (like fetishism) creates a “desire for presence,” digital philology creates a simulacrum or iconic replacement for this presence. I see the ultimate danger of the latter as its guileful power to make us prefer it over the real that it represents, and to forget the real entirely before its coded perfection. The injunction from Kings against graven images rings in my ears, and I choose a fetishism of the frail human object over an idolatry of the power of the machine. (93-94)

It is difficult in some ways to counter Szpiech’s arguments. His elegizing of the physical manuscript resonates with anyone who has experienced the tactile and intellectual thrill of handling one. Yet his rhetoric ultimately relies on the false assumption that digital resources are produced for the purpose of wholly usurping manuscripts rather than simply supplementing their various limitations. While I share Szpiech’s desire to cultivate reverence for the material manuscript and believe digital tools should encourage curiosity for the original object, I reject the idea that physical proximity is the only true path to meaningful engagement, and I find Szpiech’s model an exclusionary gesture that runs contrary to the ethos of intellectual generosity on which our field depends.[^68] His claim that digital resources merely “bedazzle” overlooks the real practical barriers — geographic, institutional, financial, pedagogical, and corporeal — that prevent most readers from ever encountering manuscripts in the flesh. Moreover, to frame digital remediation as a threat to knowledge rather than an expansion of it either implies that engagement with medieval manuscripts should be limited exclusively to experts who do have the means and ability to interact with them directly or assumes an imagined universal reader who sees, travels, deciphers, and handles manuscripts with equal ease to such experts. In reality, digitized manuscripts, digital editions, and other digital materials, are not idolatries but invitations — entry points that democratize access, foster inquiry, and supplement rather than supplant the “frail human object” that Szpiech and I both venerate.

Szpiech’s article articulates many of the key concerns scholars have raised in response to the increased use of digital methods in manuscript studies. Each of these concerns — about the idolization of digital technologies, the perceived loss of materiality, the instability of new forms of media, and the fear of displacement by machines — invite response and clarification. Many digitally-inclined medievalists have already addressed these anxieties. In the following list, I highlight these ongoing arguments and advocate for a more positive outlook:

### 1. Fetishism and Idolatry

In response to the digital turn, scholars like Szpiech turned toward fetishizing the physical manuscript. Whearty captures this reactionary impulse with clarity:

> As a response to the perceived threat of media extinction, researchers rushed to emphasize the unique sensory experiences of the material book — smell, sound, touch — as both aesthetic experience and scholarly data. Bookish objects that did not smell, sound, or feel the same as the material book (and that therefore lacked those familiar data) could be an amusement or a threat, but they could not be “real” books. (*Digital Codicology *12).

The impulse to fetishize the material object frames digital and physical formats as oppositional, implying that one must necessarily displace the other. But this dichotomy fails to account for the ways in which digital and material forms serve complementary purposes.[^69] As Lit has observed, the experience of engaging with a digitized manuscript is not lesser or counterfeit, but simply different:

> ...it is not like using digitized manuscripts will get you none or only a shadow of the experience you would get from handling the real artifact. Rather, you simply get another experience. … I therefore conclude that discussions on the relationship between digitized and material manuscripts have brought us little to nothing. It is neither correct to see digitized manuscripts as better than their material counterparts, nor is it correct to see them as worse than them. (Lit 62)[^70]

The digital manuscript is not a replacement for the physical one, but a tool that can generate further interest in it, supplement its accessibility, and even reveal aspects not immediately visible to the naked eye. Nichols provides a helpful comparison, likening the process of digitization to the production of modern digital recordings of classical music:

> They are neither copies, nor forgeries, nor clones threatening to usurp the rightful place of the manuscript they preserve in images. Strictly speaking they are, like the digital sound recording of Beethoven’s Sixth Symphony, a digital recording of the manuscript with vision replacing sound. Precisely because they attest the existence of the manuscript so perfectly, they acknowledge their secondary status as record. They do not conceal their status as a dynamic transposition of an historical artifact into a preservation format that also realizes a mandate as important for libraries as preservation: public access. Whereas in the past, only a privileged few could view, read, and study these artifacts, now they are widely available to scholars, students, and those who are merely curious. (*From Parchment to Cyberspace* 53)[^71]

Why should medieval manuscripts be uniquely sacralized, as though they lose all value when transposed into a different medium? And is it really true that access to a digital copy or edition discourages desire for the material object?

Highlighting the sort of gateway drug effect that pulls many modern readers into medieval literature and eventually into manuscript studies, Michelle Warren writes in *Holy Digital Grail: A Medieval Book on the Internet* (2022), “The first medieval book most people read is a modern edition” (193) and “The first medieval manuscript most people open is likely a web page” (238). Somewhat counterintuitively, surrogates for the medieval manuscript are what bring people into the reading room, not shoo them away from it. The modern edition (print or digital) and the modern facsimile (print or digital) are most often the *first* interaction one might have with a medieval text, not the last.

This was certainly the case in my own experience with T-F^2^. It was *because* the Staatsbibliothek had digitized the early twentieth-century photographs of the lost fragment that I became aware of its continued — if mediated — existence. And it was because I first engaged with the fragment digitally — transcribing it, comparing my transcription with earlier editions, puzzling over its illegibility — that I eventually sought out the photographs in person. That decision was fueled not by a sense of disconnection, but by a desire cultivated through virtual access. The surrogate did not replace the original; it intensified my desire to encounter the material trace more directly.[^72] But I recognize that I am among a privileged minority of scholars with the institutional support, training, and funding necessary to make that journey. For many, the digital surrogate is not a stepping stone to the reading room — it *is* the reading room. And this is not a failure of the digital, but its power: it allows more people to engage with medieval materials than ever before, often in greater detail and with fewer logistical obstacles.[^73]

It is a valid concern that the increased prevalence of digital surrogates might make libraries reluctant to grant access to original materials,[^74] but when access to the original is truly required — when scholarly questions demand material consultation — libraries most often do continue to honor that need, balancing their dual missions of preserving the objects they curate and supporting intellectual inquiry. The availability of alternative forms of access serves to protect the precious manuscript from unnecessary handling, and scholars benefit from taking advantage of both the manuscript and its copies. Rather than seeing digital, print, and manuscript media as steps in a teleological chain or rungs in a hierarchy, we would do better to view them as simultaneous, coexisting forms — each with distinct affordances, each capable of fulfilling different needs. Digital formats are not a threat, but rather, an extension of the original, a record of the material object, and an invitation to look more closely — both at what we might feel in our hands and what we might only glimpse through glass.[^75]

### 2. (Im)material and (In)human

A common anxiety about digital materials is that they are somehow less ‘real’ — immaterial, disembodied, or inhuman. But Whearty reminds us that this is an illusion, and she draws our attention to the ever-present human labors behind all technologies, “The digital presents itself as immaterial, unmediated, unproduced by human laborers. But that is a lie. Humans are always there. They always have been” (*Digital Codicology* 120). Digital manuscripts may lack the tactile qualities of parchment, but they are no less material. They reside on physical servers, require environmental infrastructure, and are shaped at every stage by human labor and interpretation. Whearty identifies the roots of this misunderstanding in two late twentieth-century rhetorics, “... first, that digital things are disembodied, with no real physical form; and second, that analog books are under threat of extinction from these disembodied digital forms” (*Digital Codicology *11), and she memorably answers these concerns writing, “Pixels can represent parchment, but they cannot *become it*” (*Digital Codicology *12). Whearty’s distinction here is essential. The digital does not erase the material; it reconstitutes it. Recognizing the digital as materially grounded and human-produced for human purposes allows us to move beyond unproductive debates over what is and is not ‘real.’

Similarly, the term ‘ghost’ is used frequently in discussions of digitized manuscripts by detractors and supporters of digitization alike. In the chapter “The Ghost in the Machine: Digital Avatars of Medieval Manuscripts” (2008), Siân Echard argues that we have not learned to see through the illusion of the digital facsimile in the same way that we have print editions:

> The screenic presentation seen by Cerquiglini as liberating also haunts us with the substitution of one body for another — a substitution that happened in the world of the printed edition, too, but which we have there at least learned to recognize. The trick with the digital facsimile is that the language of reality and presence, allied with the public mantra of accessibility, implies a kind of transparency, when what is offered is in fact an opaque simulacrum, one that is ‘uncannily’ familiar. (215)

I am skeptical of the idea that we have learned to recognize and separate print editions from their ‘original’ source manuscripts in a truly meaningful way when print editions are most frequently the sole source of our literary scholarship. It is true that editions do not attempt to *be* the source manuscript in the same sense that digital facsimiles might, but most readers of editions tend to believe that they are faithful representations of the ‘true’ immaterial text — truer even than the messy medieval manuscript copy — as editors typically attempt to promote the authority of their editions by downplaying the intervention of their editing. Every edition is a fabrication, the product of an editor’s labor, but editions are subjected to far less questioning than digitized manuscripts seem to be. Tamsyn Mahoney-Steel rightly acknowledges the ghostly relationship between our sources and our editions:

> Latent within our theories of editing and efforts as editors is an unnecessary dualism. Just as philosophers have posited and tried to overcome mind-body and mind-world dualism, so we can posit and attempt to surmount such a rift between the edition and its source. Whether or not we subscribe to Bédier’s idea of the ‘best text’, or Karl Lachmann’s stemmatics, the text, in some fashion or another, hovers at our shoulder like a ghostly entity, demanding to be perfectly rendered and expressed in our edition. We console ourselves that a one-to-one translation from source to edition is never possible, and that somehow with each attempt at editing we must try to come closer to the source, even though like Achilles we can never pass the tortoise. (136)

Either by way of digitization or editing, we may try to come ever closer to our source material, but we know we can never match it. We cannot ask any one iteration or format to do everything, but approaching our source material in multiple ways can help to fill in the inevitable gaps that emerge between the ‘original’ and its representation. In her blog “The Uncanny Valley and the Ghost in the Machine” (2018), Dot Porter encourages us to think practically about the work we do with these resources,

> ... I do a lot of thinking about what it is we do. And there’s a question, one question that keeps me up at nights [*sic*] and drives the focus of my current research. The question comes out of a statement and that statement is: The digitized manuscript is not the manuscript itself. … If the digitized manuscript isn’t the manuscript, then what is it? This is not actually the question that keeps me up nights, because although this is interesting, it’s not *practical* or *useful* for me. My job is to make these things available so you can use them. So the question that actually keeps me up at night is: If a digitized manuscript isn’t a manuscript, how can we present it in ways that explore aspects of the original’s manuscript-ness, ethically and with care, while both pushing and respecting the boundaries of technology? Although this practice of thinking about what it means to digitize a manuscript and what that becomes seems really philosophical, this is really [a] practical question. (Porter’s emphasis)

Porter underscores the need for digital practices that are critically self-aware, technically thoughtful, and above all, aligned with the curator’s joint missions of care and preservation, outreach and engagement, and research and scholarship. Echoing this constructive outlook, Deborah McGrady, in her work on the digitized Machaut corpus, urges us to consider the benefits of these disembodied representations, “While we may lament that the digitized manuscript ghosts the book, we may need to stop and consider how digital matter can also enliven texts by providing unprecedented access to textual bodies and by resuscitating the desires that shaped the medieval reading experience” (22-23). McGrady is right to highlight the unprecedented access afforded by digitized manuscripts — a level of access that positions modern readers in front of the ‘manuscript’ in ways no textual edition alone could replicate — and Porter is right to insist on the value of practical, ethically grounded thinking. Taken together, their work reclaims the figure of the ‘ghostly’ virtual manuscript not as a sign of absence, but as a reminder of presence. Digital surrogates are perhaps less so ghosts than they are astral projections — emanations of the material codex that preserve its likeness while traversing space and time, allowing the ‘manuscript’ to appear in many places at once. These surrogates remain tethered to their physical originals, dependent on the same human and institutional labors that sustain their material existence, yet they also invite new encounters and new communities of readers.

Tied up in this anxiety of immateriality is the question of accessibility. As I have already suggested in this chapter, supplemental digital materials provide greater access to the medieval manuscript and the texts they contain, but what is meant by ‘access’? Some might dismiss the practical benefits of readily available digital resources as a matter of mere convenience, but I wish to make a clear distinction between convenience and accessibility: Is it merely for the sake of *convenience* that we build ramps at the entrances of buildings? No. It is for the sake of *accessibility*. Convenience makes what is already serviceable to most people smoother or faster to use. Accessibility, by contrast, extends entry to those who would otherwise be excluded altogether. Yes, digital resources are making manuscript research more *convenient* for those who were already in the privileged position to regularly consult manuscripts in person, but digital resources are also making manuscript research *possible* for those who might otherwise never have such an opportunity. What digital access enables is not just efficiency but inclusion, and the implications of that widening access have yet to be fully realized in our scholarship. Accessibility, in this context, is not merely the physical availability of source material but also the rendering of that source material intellectually understandable to broader swaths of users.[^76] Good digital work does not aim to strip away context or reduce texts to machine-readable data just for the sake of doing so. On the contrary, digitized manuscripts and digital editions both ideally offer layered environments in which readers can pose more — and more varied — humanities questions. In other words, access is not about proximity — it is about participation. As Whearty argues, access must be understood as a set of layered affordances:

> In the ‘decade of digitization,’ digital ‘access’ was not developed as some bait-and-switch, telling certain kinds of end users that they ought to content themselves with just looking at photographs and descriptive metadata displayed on modern screens. … Rather, ‘access’ was seen as a series of tiered tools through which larger and more diverse populations of end users could become more involved in the work of book history: reading, touching, and building things; verifying with their own eyes inherited editorial wisdom; and subjecting claims to sustained, communal scrutiny. Ultimately, recovering these older understandings of ‘access’ — as the intertwined abilities to make, read, explore; to engage; to weigh and agree, or disagree and critique — shows a different past to digital manuscript projects. It also suggests a different future. Rather than quibbling over whether research done using digital manuscripts is or is not real, rigorous work (that horse has left the barn and cannot be returned: people *are* using digital manuscript projects as sources for their scholarship), we might synthesize and revise this constellation of older, more focused definitions: to have access to information about whether something exists, to have access to the training to do the work we feel called to do, to have the ability to participate and lead as well as consume and follow, to be able to collaborate, critique, and work together to see old things anew. (*Digital Codicology *167; Whearty’s emphasis)

Framed in this way, digital access is not a poor, virtual substitute for the ‘real thing,’ but a means of broadening what counts as legitimate scholarly inquiry. Rather than reducing complex humanities work to brute computation, good digital work amplifies texts, making them more searchable, retrievable, discoverable, legible, comprehensible. Digital methods are not about turning manuscripts into cold, uninterpretable data. They are about opening the archive, structuring its materials thoughtfully, and inviting in more humans to read texts and ask and answer human questions.

### 3. Ephemeral and Error-prone

Critics of digital scholarship often point to its ephemerality: websites break, formats go obsolete, links rot, and platforms collapse. Such impermanence, however, is not unique to the digital. Print and manuscript objects degrade, fall out of circulation, and are shaped by schools of thought that over time become outmoded and expire. The instability of media — whether parchment, paper, or pixel — is not a modern phenomenon but a long-standing feature of intellectual history. Longevity is not a reason to avoid digital methods but a reason to remain reflexive and iterative in our approaches. Nothing lasts forever. A lack of longevity does not mean that something may not be worth doing in the present, and relatedly, trying and failing in the present is how we progress in the future.

In “Adam Scriveyn in Cyberspace: Loss, Labour, Ideology, and Infrastructure in Interoperable Reuse of Digital Manuscript Metadata” (2018), Whearty insists that to give end users the appearance of permanence and perfection in a digital project — to mimic the illusion of authority print editions typically convey — should not be the goal: “...hiding our ghosts contributes to an incorrect impression that all digital manuscripts can be all things, to all people, in the first iteration” (195). We cannot anticipate the demands of all future scholars and general readers who may encounter our work, and we cannot provide everything to everyone, but as long as we, digital humanists, make our methods, our data, and our decisions transparent and reproducible, we will provide users with what Whearty has reframed as “raw materials that are passed on to the future, an archive of labor, into which someone may yet breathe new, unexpected life” (*Digital Codicology* 211).[^77] Sustainability, in this model, does not mean building something that lasts forever. It means building something that can be learned from and revised as needed.

Whearty warns that the real danger to scholarly trust in the digital is not error or deterioration, but the invisible correction — silent changes to digital objects that create a “crisis of authenticity” (*Digital Codicology* 228) and obscure what came before:

> My objection is less that updates happen, or even that updates overwrite earlier copies: it is the silence with which these updates occur. *That *I would argue is the real risk to authenticity posed by digital manuscripts. It is not that digital manuscripts somehow chip away their hard-copy exemplars’ unique auras or destroy some underlying foundation of the “real.” It is not even that institutions and experts can enter into a digital manuscript and alter its structures and content: that’s been happening to analog manuscripts for as long as analog manuscripts have existed. It’s that when changes are made to digital manuscripts, they should not be invisible. (*Digital Codicology *201; Whearty’s emphasis)

Whearty calls for greater transparency in how digital projects evolve. Her ideal solution is the use of Version Control Systems (VCSs) like Git,[^78] but she also suggests low-tech interventions as simple as giving born-digital files clear version numbers to indicate change over time (*Digital Codicology *231). By openly acknowledging the emendation of glitches and gaps, Whearty argues that we will prevent not just the reinvention of wheels but especially of “broken wheels” (*Digital Codicology* 207).

Just as reproducibility has become a concern in the sciences, we face a similar ongoing crisis in medieval manuscript studies.[^79] The long history of warring editorial practices is marked by the unending desire to address the reader’s lack of confidence in the editions available.[^80] How can any given reader feel totally assured of the editor’s work? In the absence of more widespread public access to manuscripts, their surrogate images, and clearer documentation of editorial decision-making, readers are typically left to accept the existing editions of medieval texts based on their faith in the editor alone. As Françoise Vieillard and Olivier Guyotjeannin advise in their *Conseils pour l’édition des textes médiévaux* (2001), the editor must make their decisions clear to the reader via the introduction to the edition and additional notes so that the reader is in a position to judge the editor’s work.[^81] But how can any reader truly judge the work of the editor if they do not have access to the source manuscripts themselves? Cerquiglini writes that readers of print editions have no other recourse but to accept the editor’s work with “la générosité loyale” (112), but digital methods offer the potential to break these epistemic barriers.

As Peter Robinson has observed, “In the days of the print edition, one could only raise such questions by, effectively, redoing all the editor’s work.” (“Electronic Editions” 7). And as I have experienced myself in working through Tobler and Dembowski’s previous editions of T-F^2^, truly verifying an edition requires hunting down either the original manuscripts or images of it, transcribing and editing it anew, effectively replicating their editorial labors. Whereas Dembowski provides his transcription of T-F^2^ in his extensive variance notes — which must be manually reconstructed by the reader — and Tobler simply claims in his introduction that he has inserted a ‘few missing letters’,[^82] my digital edition of T-F^2^ (available in Appendix 2) is able to connect readers to the digitized surrogate images of the fragment and to present T-F^2^ with more clearly established levels of editorial intervention that may be understood without requiring the reader to decipher and piece together encoded notes.[^83] The progress made here is not some radical change to the way we transcribe and edit texts, but rather in the reader’s ability to reasonably recognize and verify the editor’s work and to feel more confident in the text presented. As Lit has argued, “A more obvious breakthrough, already gained, is that editions can now be based much easier on manuscript witnesses from all corners of the world, and it is fairly easy to check existing editions against actual manuscript evidence” (98). With the increased adoption of digitization and digital editing, we can do more to address the crisis of confidence in our readers, and as Lit further argues, these methods enable readers to then assess our scholarly arguments with greater scrutiny, “...whereas before we could not expect our readers to have access to the manuscripts in order to fact-check our argumentation” (100). If we can more rigorously evaluate our editions via increased access to medieval manuscripts and their digital surrogates, then we can feel more confident in the validity of all our scholarly output resulting from such editions. When images are publicly available, and editions are designed for interrogation and interaction, manuscript studies as an endeavor becomes more reproducible and transparent — without sacrificing complexity or rigor. This is not a lowering of standards (with flashy, bedazzling webpages replacing paper books); it is a raising of standards as we hold ourselves evermore accountable to the scrutiny of our readers.

### 4. Automation and Augmentation

One final concern to address is the prevalent fear that machines will replace human intellectual work, but digital tools are not autonomous agents poised to displace us. They are instruments of human creation — powerful only in the hands of those who learn to wield them effectively.[^84]

Though he welcomes advancements in automation, Lit specifically addresses the need for human thought and judgement even in seemingly straightforward fields like paleography:

> ... paleography is not hard enough to be fully automatized, but not soft enough to disregard automated analysis. I think, then, that automated text recognition, when it is advanced enough to be implemented into our normal workflow, will be a great help for editors, but it remains only that — a help. (117)

Though transcription may seem ripe for automation, “...transcription itself is not an objective task but can be considered an editorial task dependent on the editor’s erudition” (Lit 172). For example, Alpo Honkapohja’s *Digital Medievalist* article “Digital Approaches to Manuscript Abbreviations” (2021) presents the many complications associated with extracting insights from scribal abbreviations via digitally encoded transcriptions and how these complications necessitate human intervention. First, both the paleographic appearance of abbreviations and their intended expansions may vary greatly over time and context, and even individual scribal abbreviations may give conflicting instructions on how they should be expanded and understood by the reader. Second, normalizing text transcriptions — standard practice in modern editing — leads to the loss of potentially valuable information that could, for example, be used by paleographers to date and localize source manuscripts. And finally, while automatically generated data may be a useful research tool, Honkapohja cautions, “The risk is that automatic processes might generate huge quantities of bad data” (para. 58). At every stage, informed human judgement is essential to producing good data and using that good data to ask and answer human questions. And despite the many challenges associated with such research, Honkapohja suggests we are moving toward “something of a golden age for this fascinating area of study” (para. 58).

Even prior to the digital turn, Foulet and Speer likewise rejected any tendencies toward excessive automation in the editing process:

> A purely mechanical system of editing (even if such a thing exists) is inappropriate for Old French Texts; hence the editor’s informed judgment or subjectivity must play a crucial role in each stage of the editing process. Any edition is a conjecture; it also constitutes a critical interpretation of the text. (38)

Digital methods will never erase the need for human expertise. On the contrary, they will always demand it. Decisions about transcription, editing, markup, visualization, and design all depend on scholarly judgment, and adopting new methods does not mean we throw away useful traditional methods and knowledge. We have, rather, the opportunity to revisit and refine our practices with new tools and techniques. The very act of doing digital work forces us to rethink our methodology and ‘do the work’ of critically thinking about what we are doing and why we are doing it. And simply, “Sometimes, ‘doing the same thing faster’ is indeed a revolution … because we do things that otherwise would not be done. In this sense, much is already accomplished when we can look more closely at what we can already see” (Warren “Situating Digital Archives” 173).

Rather than entrenching ourselves in old workflows, digital methods invite us to shed some of the constraints inherited from the print paradigm and reconsider the goals and structures of our editorial practices. Andrew Prescott captures this well when he writes:

> It is not the digital image which is rootless but rather the printed editions on which we have previously relied. Digitization enables scholars to reintegrate text and manuscript. Medieval manuscripts fuse text and image in ways that challenge our logocentric ways of thinking. Digitization enables us to once again view text as image. (46)

Indeed, the limitations of print — linearity, singularity, invisibility of variance — have long shaped modern expectations of what a ‘text’ is.[^85] As Farkas Gábor Kiss et al. note in “Old Light on New Media: Medieval Practices in the Digital Age” (2013), many digital editions still cling to the constraints of print as the greater exploration of new digital formats continues to emerge:

> The text as a singular, self-identical subject is primarily a product of the printing press, which restricted the number of circulating variants and obfuscated the diversity of manuscript culture. The digital environment does not require such parsimonious handling of surviving sources, as it has the potential to represent texts in a way that reflects their medieval existence. Yet, it seems that this potential remains unexploited in many digital editions that still carry on the burdensome heritage of the printed book. (18)

Kiss et al. understand that embracing both digital methods and the New Philology movement comes with intimidating challenges, but they are adamant that scholars must push through this moment of transition from print to truly digital editions so that we might thoughtfully engage with all available textual witnesses and place more power in the hands of our readers.[^86] As Kiss et al. argue, the digital edition has the potential to more closely mirror medieval modes of reading, which were often fluid and open (22); non-linear (23-24); interactive of text, image, and sound (24-25); complex in reception (25-27); scalable in information (27-28); and composed of composite textual features (28-29).[^87] What they propose — and what I take as a helpful model for the edition produced in this dissertation — is a more expansive editorial approach than print may typically afford, one that embraces variance and offers readers multiple legitimate pathways through the text. In this dissertation, each manuscript witness of Version T is presented on a more equal footing to provide a fuller picture of the T corpus. Readers can encounter the text of each manuscript copy as desired and plainly understand my editorial decisions without deciphering dense paratextual notes. The goal is not to hide my intervention as a digital editor but to make my interventions more immediately apparent, obvious, and legible so that readers may have a greater sense of confidence in the validity of the texts presented.[^88]

Editions — print and digital editions — of medieval texts are highly mediated works, but digital editions offer functionality capable of more fully presenting the variance of medieval texts than traditional print editions.[^89] Paradoxically, it is by embracing variance (by embracing the digital) that we find a greater sense of stability within the texts — even the infamously variable poetic works — of the manuscript age. By allowing readers to explore multiple manuscript witnesses side by side, to follow points of variation through visualizations, and to see editorial decisions foregrounded rather than hidden, the digital edition can offer a more honest — and more philologically responsible — account of the medieval text. This vision aligns with Nichols’s concept of the ‘mutable stability’ of medieval texts:

> Poetic structure in the manuscript age is dynamic; it constantly accommodates the stress of modification without losing its ability to adjust to load changes or to suffer any reduction in performance or loss of identity. That is the basis for the medieval paradox I call ‘mutable stability.’ (*From Parchment to Cyberspace* 94)[^90]

According to this line of thinking, then, the goal of the most useful form of digital edition should be not to recover a lost original — the textual critic’s goal — or flatten manuscript variance into a single idealized form. Rather, it should be to embrace the dynamics of manuscript transmission, to give readers tools to explore that variance meaningfully, and to reflect the complex textual realities of the Middle Ages.[^91] Nichols critiques the modern tendency of the print edition to strip away the very elements that make a work medieval:

> Armed with information about the manuscript tradition, textual scholars could then produce a critical edition. But in the quest to recreate an authentic text of the work, everything that made it a truly *medieval* artifact was jettisoned. By virtue of presenting the text as a printed book, the critical edition necessarily modernizes medieval works. … however, anyone reading such a text would have only the vaguest idea that the printed version represented scores of manuscript copies all differing in a variety of ways from it (and from each other). (*From Parchment to Cyberspace* 2; Nichols’s emphasis)

Although traditional print editing practices generally do an excellent job of transmitting medieval texts to modern readers, I would argue that their main flaw is that they are too clean, too streamlined. Our desire for tidiness, our expectation that there is one singular authoritative Text to be reproduced, distorts the reality of medieval texts that survive in material manuscripts where there is almost never an ‘original’ version and where practically speaking there is no such thing as a ‘final’ copy. Modern editing methods are great for the production of static print editions (that can only be so large and can only be reedited and reprinted every so often), but by applying digital editing approaches, we might ironically be able to engage with these medieval texts more completely. We can create editions that embrace variety and reflect the animate nature of these texts that were meant to live in circulation, copied and edited from one hand to the next. Digital editions, then, may at least be conceived of as augmentations to the more familiar print edition.

To conclude this list, digital resources, such as full-color images of digitized manuscripts and digitally searchable metadata, have augmented our ability to access and study manuscripts. Yet, this shift does not render the methods and materials of the past obsolete by any means. Microfilms, for example, remain valuable when direct access to the original manuscript is impossible, and the in-person consultation of manuscripts continues to provide insights that digital surrogates do not replicate or replace. Digital resources enhance our ability to conduct thorough research, while print resources retain their value, particularly in times when digital access is compromised. Clearly, the work we are doing is largely unchanged — like turn-of-the-twentieth-century German philologists who examined the Damascus fragments, we, humans, continue to photograph, label, transcribe, edit and publish our manuscript material — but it is undeniable that the possibility to access even basic information at unprecedented speeds that once required extensive travel and time-consuming digging is enabling researchers to continue doing the work that we love, only augmented. Ultimately, I agree with Lit’s optimistic conclusion, “It has never been a better time to be studying ancient manuscripts” (291).

## Conclusion

In his contribution to the 2007 volume *Digital Philology and Medieval Texts*, Peter Robinson suggests that editions must do all of the following:

> Present a text; Present the different historical forms of the text; Present the differences between the historical forms of the text; Explain the relationship between the different historical forms; Explain how the editor edited; Let the reader test the editor’s methods and conclusions. (“Electronic Editions” 1-2)

He goes on to argue that print editions are only *maybe* better than digital editions at doing the first thing: presenting a text. Essentially, digital editions allow us to make editions that are better at creating visualizations, visualizations that enable readers to *see* what they might otherwise be blind to in a traditional print edition. The editing practices of this dissertation seek to meet Robinson’s criteria:

**1. Present a text, and present the different historical forms of the text:** Each manuscript witness of Version T is edited — with clearly delineated layers of editorial intervention — and presented in full in Appendix 2, giving greater visibility to even modest witnesses to the text like fragment T-F2.[^92]

**2. Present the different historical forms of the text, and present the differences between the historical forms of the text:** Appendix 1 provides a thorough description and transmission history of each manuscript witness of Version T, placing each manuscript in context.

**3. Explain the relationship between the different historical forms:**[^93] Chapter 3 of this dissertation focuses on comparing the T portraits across the corpus, illuminating textual variance and the literary implications of that variance in detail.

**4. Explain how the editor edited:** While Chapter 1 has provided rationale for the use of digital methods and the format of a digital edition, Chapter 2 details my exact editing methods.

**5. Let the reader test the editor’s methods and conclusions:** This dissertation invites readers to evaluate my editorial rationale and interpretive claims in multiple ways. Digital facsimiles of the T manuscripts are provided where available (Appendix 2), and each edited transcription in Appendix 2 offers distinct layers of editorial intervention (explained in Chapter 2), allowing readers to clearly differentiate between my own editorial choices and what the medieval scribe actually copied. English translations and enhanced visualizations of the T portraits (available in Chapter 2) enable readers to more easily trace both continuity and variance across the copies. Together these resources create a solid foundation for readers to further scrutinize the close reading presented in Chapter 3.

This dissertation embraces recent advancements in digital methods to try to achieve the mandates of the New Philology movement: to treat manuscript witnesses with respect, to foreground textual variance, and to invite readers into the complexity rather than smooth it away. While no single edition can be all things to all readers, this one seeks to align its priorities with the best guidance of digital medievalists working today, and to return to Foulet and Speer’s best advice for editing Old French texts, “In other words, editing is not a science, but an art” (39).

[^51]: [](#ftnt_ref51) Paolo Radiciotti and Arianna D’Ottone suggest the fragment made its way to the region in the later twelfth-century just prior to the fall of Baldwin IV’s reign over the kingdom of Jerusalem, and although they cannot offer a more concrete origin story, they note that the presence of Old French fragments saved among the other language documents, demonstrates a multicultural respect for sacred texts in the region at that time (58).
[^52]: [](#ftnt_ref52) Gabriele Giannini and Laura Minervini point to the cultural significance of this manuscript’s presence in Damascus, “The small, humble manuscript in which the Old French poem about St. Mary of Egypt was copied was apparently aimed at a different audience: the story of the Egyptian prostitute who chose, after visiting the Church of the Holy Sepulchre in Jerusalem, to become a penitent hermit in the Transjordanian desert, had an immediate appeal among Western pilgrims on their way to the holy places. The saint, moreover, was venerated in the Orthodox and Coptic churches, thus representing an element of cultural convergence between the Franks and the local Christians” (346).
[^53]: [](#ftnt_ref53) While most scholars tend to write about the emotional connection we feel to our material manuscripts, Whearty insists on our surrogates’ ability to pull on our heartstrings: “There is no standard for documenting the affective charge behind a digitization. Nevertheless, affect is an important part of this tale. One of the substantial threads running through medievalist-authored commentary on digitization is how affective, sensual connection drives intellectual discovery when working with hard-copy books. Digital manuscripts, in these comparisons, are often held up as lacking that powerful emotional-intellectual resonance … But this opposition denies the ways that affective connection to an analog object can (occasionally) drive a digitization. … All digital manuscripts are made by real people, each with their own intellectual *and * affective responses to the objects of their labor. Even in the midst of workflows that emphasize systematic digitization, human elements and human emotions remain.” (*Digital Codicology* 53; Whearty’s emphasis)
[^54]: [](#ftnt_ref54) Initially, I was discouraged from taking my own pictures of the photographs because of the digitized images available, but after demonstrating the greater clarity my smartphone images provided me and the way in which I could better capture the physical scale of the photographs with my own images, I was permitted to take a few pictures for research purposes before the end of a too-brief visit.
[^55]: [](#ftnt_ref55) Here, I borrow from Bolter and Grusin’s use of the term ‘remediation’ in *Remediation: Understanding New Media* (1999). They offer multiple definitions of the term, restating its logic in multiple ways, but particularly useful to keep in mind for this chapter they write, “Remediation as the mediation of mediation. Each act of mediation depends on other acts of mediation. Media are continually commenting on, reproducing, and replacing each other, and this process is integral to media. Media need each other in order to function as media at all” (55).
[^56]: [](#ftnt_ref56) “Dig into the network of copying and transformation that binds together the digital copies, with their analog chromolithographic copies, with *their * analog manuscript copies, and it becomes clear that there are only copies of copies; each a unique object with its own story to tell about technology, transformation, transmission, and labor, generally uncredited and unseen.” (*Digital Codicology* xviii; Whearty’s emphasis)
[^57]: [](#ftnt_ref57) The term ‘ghost’ is often used in relation to digital materials. I discuss its use in more detail below in the section “(Im)material and (In)human.”
[^58]: [](#ftnt_ref58) In *The Fluid Text* (2002), John Bryant emphasizes the cultural value of perceiving texts as migratory, “What makes a fluid text fluid is its fluidity. This tautology is meant to stress an obvious point easily missed: When we read a fluid text, we are comparing the versions of a text, which is to say we are reading the differences between the versions, which is to say we are reading distance traveled, difference, and change. We are reading the energy of a culture that makes the change, an energy that has measurable meaning in our analysis of culture” (62-63).
[^59]: [](#ftnt_ref59) Stephen G. Nichols criticizes the ‘chain analogy’ of textual transmission: “While it’s true that vernacular works were transmitted longitudinally throughout the Middle Ages, the process was stochastic and contingent, rather than orderly or symmetrical. … We should not be surprised, then, to discover that each manuscript version of a literary work had a story to tell about itself, a story conveying something about the social, economic, and cultural conditions leading to the creation of that particular manuscript and its choice of text(s). Viewed from this perspective, the manuscript is no less dynamic and complex, but the dynamism and complexity are distributed differently” (*From Parchment to Cyberspace* 57).
[^60]: [](#ftnt_ref60) “Lost books and destroyed files *are * the long history of medieval manuscripts” (*Digital Codicology* 118; Whearty’s emphasis).
[^61]: [](#ftnt_ref61) New Philology (or New Medievalism) gained prominence in the late eighties and early nineties with publications like Bernard Cerquiglini’s *Éloge de la variante: Histoire critique de la philologie *(1989) and the 1990 January issue of * Speculum*edited by Stephen G. Nichols.
[^62]: [](#ftnt_ref62) In the third chapter of his *Among Digitized Manuscripts: Philology, Codicology, Paleography in a Digital World*(2020), L.W.C. van Lit assesses twenty digital libraries and claims the BnF and the Staatsbibliothek zu Berlin are tied in first place for the quality of their digital repositories (73-101).
[^63]: [](#ftnt_ref63) Even the manuscript researcher’s experience of browsing has changed. In his chapter “Ways of Seeing Manuscripts: Exploring Parker 2.0” featured in *Medieval Manuscripts in the Digital Age* (2021), Andrew Prescott argues in favor of digital collections, “It is a common lament that e-books deprive us of the pleasure of browsing along the shelf. This may be true of printed books, but manuscript scholars rarely have the opportunity to browse along the shelves of a manuscript collection. A major advantage of having a collection like the Parker Library available in digital form is that it gives us the opportunity to browse and dip into unfamiliar manuscripts. With a digital manuscript library, we can browse through manuscripts in a way that security and conservation considerations otherwise make impossible” (43).
[^64]: [](#ftnt_ref64) Whearty’s *Digital Codicology* (2022) provides an insightful ethnography on digitization, revealing the complexities and decision-making processes involved in this transformative practice, physically how this work is done, what is prioritized during the process, what data we cling to, and what data we let go of due to various restraints. She reminds us, “Server space is finite. Curation is not the same as hoarding. Not everything can — or should — be saved” (230).
[^65]: [](#ftnt_ref65) “Because of this living variance, manuscripts have become bastions of an intuitive human sense of knowing and thinking that I see as under threat in a world of readily available information” (88).
[^66]: [](#ftnt_ref66) “Fetishism? Indeed, for such reverence affords me a wormhole by which to escape from any utilitarian hegemony that might attempt to mechanize the manuscript matrix…” (90).
[^67]: [](#ftnt_ref67) “Of course, the manuscript has always had this magical nature — it has always taunted the critical edition from an untraversable distance with a complexity irreducible to any systematic editorial plan. But as I read it—slowly, haltingly, with difficulty—under the new powerful banner of mechanized algorithms and text searchability, the manuscript’s humble imperfection erupts before me in a brilliant display of recalcitrant dignity, bathed in a numinous aura of the unknowable” (95).
[^68]: [](#ftnt_ref68) I borrow this phrase “exclusionary gesture” from historian Leonora Neville. During her appearance on the Medieval Institute of the University of Notre Dame’s podcast *Meeting in the Middle Ages*, Neville commented that necessitating the command of dead medieval languages while discrediting the academic value of editions and translations as gateways into research is an “exclusionary gesture” (00:50:20 - 00:54:14).
[^69]: [](#ftnt_ref69) Whearty highlights the need for a specifically digital codicology to resolve the issue of solely defining digital objects by way of negation: “Over the past forty years, research in the humanities has been transformed by the digitization of a wide array of cultural heritage objects — including pre- and nonprint medieval texts. As this transformation has occurred, a consensus has emerged concerning what digitized books are *not* — they are not perfect surrogates for or transparent windows to their analog originals. Less ink has been spilled and fewer pixels illuminated concerning what digital manuscripts *are* ” (*Digital Codicology* 2).
[^70]: [](#ftnt_ref70) Echoing this view, Abigail Robertson argues that the digital manuscript is not a poor substitute, but a powerful complement to its material counterpart: “It is reductive to view the digital manuscript as ‘less than’ or even as a replacement or understudy for the physical object; instead, the digital manuscript ought to be conceived of as a complement to the physical object. This digital complement can certainly ‘replace’ the physical one for those without interest in or access to visiting the material object itself, but the digital complement allows us to study the manuscript in ways that augment the investigation of the physical object” (34).
[^71]: [](#ftnt_ref71) Françoise Vieillard and Olivier Guyotjeannin share this musical comparison in their *Conseils pour l’édition des textes médiévaux* (2001): “Une cantate de Bach exécuté avec des violons d’époque et un jeune garçon à la place de la soprane, mais dans un auditorium climatisé plutôt que dans une église glaciale éclairée aux bougies, ne sera jamais une reproduction, elle restera une (ré)interprétation. L’éditeur, lui aussi, (ré)interprète ; il tranche des points douteux (et d’ailleurs baisse parfois les bras) ; il donne à lire une nouvelle version de l’œuvre ou de l’acte, à un public dont il faut espérer qu’il dépassera le cercle des spécialistes partageant ses intérêts propres, eux-mêmes ‘datés’ par l’état de la science. Jamais il ne pourra se substituer au manuscrit, au feuillet de parchemin, à ce qu’il entrouve sur la perception des lettres et des mots, des inflexions et des pauses d’une lecture.” (14)
[^72]: [](#ftnt_ref72) Bryant argues that one important purpose of an edition — regardless of its format — is to inspire such engagement, “Finally, both screen and book versions should encourage readers to get into the real world, of which both screen and book are mere facsimiles” (165).
[^73]: [](#ftnt_ref73) As Nafde and Gorst note, access is no longer confined to the privileged few with institutional proximity to elite collections: “Digitizing the manuscripts makes possible not only remote access but also multiple simultaneous access. Now, however, medieval paleography and original transcriptions need not be the purview of a limited number of people located in the golden triangle of Cambridge, Oxford, and London” (149).
[^74]: [](#ftnt_ref74) Lit concedes this point, “Whatever happens, it does seem that digitization has become an unstoppable force and more and more students and scholars are seeking out digitized manuscripts, often preferring them over material manuscripts. At the same time libraries are noticeably making it more difficult or even impossible to see the material manuscript, arguing that the digital surrogate will do. A fair evaluation of the digital materiality of digitized manuscripts is therefore crucial, in order to make use of them in an appropriate manner” (101).
[^75]: [](#ftnt_ref75) “With the advantages and drawbacks to digital ‘surrogacy’ now in sight, researchers today are primed to turn their inquiries about re-production back onto the embodiment of images and texts across bibliographic media — not from manuscript to print (and to pixel), but as them at once.” (Drimmer 107)
[^76]: [](#ftnt_ref76) Whearty offers this more capacious definition, “Accessibility does not just mean putting photographs of manuscripts on the web. Nor should it mean wrapping digital manuscripts exclusively in the jargons of traditional codicology and bibliography. It means surrounding digitized manuscripts with information that can act as a doorway in for new users” (*Digital Codicology* 202-203).
[^77]: [](#ftnt_ref77) We cannot fully anticipate what future trends will emerge, but as Roman Fritschi suggests, we may be confident that digital access is reshaping the way we work and the questions we are capable of pursuing, “Easy access to manuscript sources will probably shape the way in which medievalists work in the coming years. Not only will the development of suitable tools create new opportunities for digital paleography, but access to extensive collections of digital manuscripts will give rise to new areas of inquiry, which have scarcely been conceivable so far. The easier it becomes to access digital manuscripts, and the simpler it becomes for researchers to use digital manuscripts in their preferred working environments, the greater the interest will be in this type of source” (250).
[^78]: [](#ftnt_ref78) Git is the Version Control System that I have used to track revisions and manage the files of the digital edition in this dissertation. Git is free and open-source software and is currently the most widely used source-code management tool among developers. It allows users to track and document changes to their files over time, and it enables the collaboration of multiple users on a shared project.
[^79]: [](#ftnt_ref79) In his introduction to *The Paleography of Gothic Manuscripts*(2001), Albert Derolez similarly points to the “present-day crisis of paleography” (2). He argues in favor of implementing quantitative approaches in conjunction with more traditional descriptive methods as a way of disrupting the authoritarian nature of the discipline that would otherwise be dominated by the few elite experts able to gain the ambiguous “paleographer’s eye” (2) over many years of direct contact with manuscripts. Much like print editions, “The method applied hitherto to paleographical handbooks has produced an authoritarian discipline, the pertinence of which depends on the authority of the author and the faith of the reader” (9).
[^80]: [](#ftnt_ref80) In Part 1 (“A Historical Orientation”) of their guide *On Editing Old French Texts *(1979), Alfred Foulet and Mary Speer describe the “crisis of confidence” (19-28) that has essentially been in effect since Joseph Bédier published his new edition of the* Lai de l’Ombre* in 1913, which cast doubt on the former Lachmannian method. Bédier essentially advised that editors be governed by an attitude of both distrust in oneself and trust in the medieval scribe, altering the text of the manuscript as little as possible and only making corrections in some appendix (Speer “Old French Literature” 397-398). In 1995, Mary Speer concluded, “In Old French editing, there are no mechanical systems, and there will likely be no definitive editions, only renewed attempts to represent in a convenient format for a particular audience an approximation of what the editor defines as the truth (or truths) about a certain text” (“Old French Literature” 404).
[^81]: [](#ftnt_ref81) “Une fois ses décisions prises, il doit les appliquer avec cohérence et mettre le lecteur en état de juger de la méthode suivie** **: il ne devra jamais hésiter à exposer et justifier en note, et éventuellement dans l’introduction, les choix opérés” (18).
[^82]: [](#ftnt_ref82) “Den Text von Damascus gebe ich ohne alle Zutat, nur daß ich j und i, v und u sondere und ein paar fehlende Buchstaben einschalte” (Tobler 967). Though he follows standard editing practices, arguably Tobler does more than add a few missing letters. In 27 of the 38 lines of this fragment, he adds letters and spaces to expand scribal abbreviations, to regularize word spacing, and to fill in for physical gaps in the fragment, but most of these additions are not made totally clear to the reader. In this print edition, the reader is not able to determine what has been added by the editor and what is actually present in the material source.
[^83]: [](#ftnt_ref83) I describe these editing methods in detail in Chapter 2 of this dissertation.
[^84]: [](#ftnt_ref84) The fear that machines will replace human scholars often conceals a more personal discomfort: a reluctance to adapt, to learn new tools, and to alter familiar workflows. Lit pushes manuscript scholars to push themselves outside of their comfort zones but insists it is not necessary to master it all, “The two most important lessons to draw from this and the previous chapters are that technology only remains as powerful as the user wielding it and that we do not need to know everything — just those aspects that help us build a solution. This is why it is very important to keep an open and creative mind” (226).
[^85]: [](#ftnt_ref85) While Bolter and Grusin see the promise of ‘immediacy’ supposedly offered by digital media as a problematic illusion (*Remediation* 45-46), they nevertheless acknowledge that new forms of media arise due to the shortcomings of previous forms of media: “Each new medium is justified because it fills a lack or repairs a fault in its predecessor, because it fulfills the unkept promise of an older medium. (Typically, of course, users did not realize that the older medium had failed in its promise until the new one appeared.)” (60).
[^86]: [](#ftnt_ref86) “Obviously, editors fear leaving behind the security offered by a printable version. This is a moment of transition. … All textual witnesses and all variant readings have equal rights and equal chances to be represented, and the choice belongs to readers” (20).
[^87]: [](#ftnt_ref87) “The illusion of the existence of a text as a definable and stable entity disappears: meaning is constantly being created and recreated during the complex process of reading, in the minds of individual readers and through their cooperation, just as it happened in the monasteries, studia, and universities of the Middle Ages” (Kiss et al 30).
[^88]: [](#ftnt_ref88) Skeptical of the argument that digital surrogates have the potential to more closely mirror medieval modes of reading, Heather Bamford and Emily Francomano caution “...as digital philologists, we should be aware that we are creating, not reproducing or straightforwardly representing, manuscript cultures. We should also acknowledge that while we may share some aspects of medieval manuscript culture with historical medieval readers and writers, they had no analogous experience of the digital environments medievalists inhabit today. What we are doing is a sort of virtual neomedievalism, a learned, creative anachronism. If we are willing to entertain the notion that there is such a thing as digital-medieval manuscript culture, then, our practice as its creators and transmitters should be transparent, in short, recognized as the multitemporal remediation that it is” (41).
[^89]: [](#ftnt_ref89) “For the last two hundred years or so, medieval literary works have been subject to the mediation of text editors. The public at large could read medieval literature in editions, or in translations based upon them. And, in consequence, they saw only the verbal text, since that’s what text editors considered essential. … For what the critical edition has provided all these years is an ideal version of a poetic work that — like God in medieval theology — exists everywhere in its manuscript exemplars, and nowhere as an independent entity. In the spirit of Voltaire’s *mot * about God, since the work couldn’t be definitely located, scholars had to invent it. For as long as the manuscripts were scattered in rare book repositories all over the world, that was fine. Better to have an ideal work, than nothing. But now that we can see and study a whole series of authentic manuscript versions of the work we need to rethink the relationship between the manuscripts and our definition (and understanding) of ‘the medieval literary work’” (*From Parchment to Cyberspace* 198-199).
[^90]: [](#ftnt_ref90) Nichols’s ‘mutable stability’ is an echo of Paul Zumthor’s earlier theorization of ‘*mouvance*’ in which a medieval text is a complex unit constituted by the collection of its many material (written) and immaterial (oral) versions, “L’œuvre est fondamentalement mouvante” (73).
[^91]: [](#ftnt_ref91) Bryant affirms the ability of the ‘fluid text’ edition to connect modern readers to a time different from their own: “...readers will no longer take the text as ‘timeless’ and hence allow it to become merely a reflection of their immediate, idiosyncratic sensibility; rather, they will begin to see the mutable aesthetic object as a function of a past that is both alien to and yet potentially inclusive of themselves. This automatic distancing between text and reader heightens the historicity of the reading experience” (124).
[^92]: [](#ftnt_ref92) All extant manuscript witnesses are presented apart from copy T-L, which I have only had limited access to due to circumstances (the funeral of Queen Elizabeth II in 2022 and the cyberattack on the British Library in 2023) that I describe in Appendix 1.
[^93]: [](#ftnt_ref93) Robinson makes it clear that the explanation of the relationship between the different historical forms is what differentiates a digital edition from an archive: “My own view is this: if all the edition does is present all the information it is not an edition at all. It is an archive, an inert pile of dead data awaiting human intelligence to breathe life into it” (“Electronic Editions” 5). In agreement with Robinson, Kiss et al. make it clear that digital editing does not mean sacrificing the scholarly work of traditional editing by simply throwing everything at the reader: “The coexistence of multiple layers of information can easily dumbfound readers and users, especially if they are newly approaching the field. To prevent that bafflement, each witness should not be merely supplied, but also affixed with a certain value, in relations to other witnesses or an imaginary original text. This will preserve the readers’ choice but also empower them to deploy as much, or as little, editorial input as they wish” (Kiss et al 27). Digital editors still have the responsibility to contextualize each witness to a text, which I provide in Appendix 1 of this dissertation, but they also have the responsibility to provide readers with the fullest picture of the text as possible, which I provide in Appendix 2, since editors cannot anticipate all the desires and needs of all readers.
