# Conclusion 
## Process over Product

Numerous challenges persist that demand increasingly nuanced editorial choices to enable modern readers to appreciate the full complexity of Mary the Egyptian as she is depicted across the T corpus. First, there are many scribal choices and errors and corrections that can complicate the transcription and text encoding process described in this dissertation. For example, there is a powerful moment in which Mary the Egyptian tells Zozimas that he will find her dead or alive when next they meet (vv.1259-1260), and in copy T-B, the scribe has written these existential options on top of one another within the same ruled line like this:  


> Del flu[n]c Jordan ne pas la rive. puis me trovras $\begin{array}{c} \text{u vive} \\ \text{u morte} \end{array}$ (vv.1179-1180 in T-B)

It is as though the scribe wanted to emphasize this simultaneous, ambiguous state for Mary as both alive and dead at once. Yes, it is possible this was merely a choice made for the sake of maintaining the spacing of the line, but because Manuscript B was so carefully copied otherwise, I see potential here to read this juxtaposition as intentional. Regardless of the scribe’s unknowable intentions, we are nevertheless left with the question of how to best encode this line given the present limitations of TEI’s functionality. We have the text “u vive” written above “u morte” within the same ruled line, a scribal choice that would go unacknowledged in a traditional print edition, while a digital edition may offer more options in how to render this copy, potentially even in a dynamic way. Similarly, we often find in the T manuscripts moments where the scribe has offered corrections to their own copying. In T-E, we have a couplet (vv.1021-1022 in T-E) whose lines appear in reverse order, and the scribe has offered a correction with the letters “b” and “a” at the end of the lines:  

> d[on]t est venue & de q[ue]l t[er]e **b**\
> Zosimas li p[ri]st a enq[ue]rre **a**\

In a more complex digital edition, moments like these could be rendered in a dynamic way with these lines swapping places back and forth on the screen automatically so that digital readers may see both the error and the scribe’s correction existing together nearly simultaneously.  

T-B presents another particularly striking example of scribal intervention that would most likely go unnoticed by the reader of a more traditional edition. It is significantly shorter than Dembowski’s base text (T-A) — shorter by about 200 verses in total — and closer examination reveals that the scribe did not shorten the text evenly throughout. Instead, the omissions become more and more pronounced toward the end of the narrative as though the scribe had nearly finished copying and suddenly realized they were rapidly running out of room. This phenomenon is observable in the Portraits alone as T-B is missing only four verses from Portrait 1 and sixteen verses from Portrait 2. While Dembowski’s print edition notes these omissions in the endnotes, it is difficult for even the most attentive of readers to visualize the spacing of these omissions without alternative visualizations such as the color coding I have applied to the Portraits in this digital edition. By leveraging digital editing methods, features like the structure and pacing of omissions may be made far more readily apparent and accessible to modern readers. In this way, readers may not only be made aware of the fact of omitted verses, but they might more easily understand the rationale behind such scribal omissions. Has the T-B scribe omitted this or that verse due to an objection with its content or poetic value? Or — as is likely the case here — has the scribe simply found themselves pressed for space and possibly pressed for time?  

In the digital edition of T-E in the appendix of this dissertation, it is similarly obvious that there are significant chunks of the text — at least sixty verses in total — now missing due to someone having cut out the miniature that would have appeared on folio 117 verso. This cutting is obvious and dramatic in the manuscript itself, but when we consider Dembowski’s print edition, the absence is only granted two brief mentions in the variation endnotes,^[“…E, *ce ms. a une coupure qui, à partir de ce vers, va jusqu’au v.*1268 —” (Dembowski 104n1236) and “: *une coupure dans* E —” (Dembowski 105n1289-1318).] preventing the loss of this material from being immediately felt by the reader. Dembowski makes this loss of text known but not *apparent*. We, the modern readers of the print edition, do not immediately envision this loss. But when encoded as an XML file and rendered as a digital book with each missing verse given space to draw our attention, these missing chunks become clear, recognizable disruptions that welcome further reflection. The obvious absence of these verses, I hope, strikes the digital reader with the same sort of shock and curiosity that one might experience when flipping through the mutilated manuscript in the reading room or when clicking through the digitized images of the manuscript’s online surrogate. I would love for the reader of my edition to come across unanticipated details like this and feel provoked to seek out the manuscript (either via its digitized reproduction or the material original). Instead of neglecting copy T-E from our reading entirely due to the damage it has suffered to only a single folio, we might take this textual witness into greater account in the digital space.  

The editing practice of this dissertation has been driven by questions like: How can manuscript copies be presented so that editorial choices are both transparent and enhance the reader’s trust, without detracting from a fluid and pleasurable reading experience? How can the benefits of data visualization be maximized without overstepping as editor? And how can readers be invited to make their own choices without totally removing the editor’s guiding hand? Balancing these questions requires an ongoing process of calibration and recalibration, and the shift from print to digital does not magically solve every challenge. For example, working digitally does not free us from the physical limitations inherent in traditional print media; rather, it transforms such constraints. While digital editions escape the binding dimensions of print, they introduce other limitations related to screen size — This digital edition has not been optimized for a mobile user, but should it be? —, and the human capacity to focus on only one thing at a time remains an unavoidable issue. These sorts of factors compel us to consider how editions are structured, ensuring they remain comprehensive yet navigable without overwhelming the reader. Although it is possible to create an incredibly massive digital document, the actual utility of any edition is bound by the human end user's ability and desire to read it. And although my digital edition offers one viable approach to addressing these challenges, it is my hope that the methods described here will only encourage the production of future, improved iterations.^[Whearty helpfully models the humility digital humanities scholars must adopt in attempting such projects that must explore possibilities and welcome future improvements, “I hoped, fiercely, that in the next iteration of DMS-Index a new, more skilled contributor would come along to correct my errors and improve my work” (Whearty 204).] To this end, in producing this digital edition, I have prioritized the use of methods and tools that are widely available with low barriers to entry for scholars without extensive digital resources or technical training, inviting others to continue the work of refining the processes of digital editing.  

All of this is a fruitful process, but an imperative for better editing outcomes, whether traditional print or digital editing, is increased transparency throughout as well as thoughtful and helpfully inventive visualizations. A great deal of work remains to be done to bring about a full edition and translation of the T corpus in its entirety, but in sharing the foundational stages of these efforts, I hope others may likewise see the value in rendering the complexities of our medieval texts both human- and machine-readable and in exposing the choices we make as editors to broader scrutiny along the way. The methods I propose exploring are not a cure-all for the inherent issue of mediation that occurs when a premodern text is represented to a modern audience in any format. However, I propose an editing practice that would give the modern reader more agency and clarity in their reading experience and bring the reader closer to the text in question as a body of texts, all the while acknowledging that bridging the gap between modern reader and premodern manuscript is an asymptotic endeavor. We may inch ever closer to one-to-one engagement with the imagined ‘original text’ of the T-poet, but no single, static edition could give full voice to a text as layered as the matrix that is *La Vie de sainte Marie l’Égyptienne*.  


