---
title: "Introduction"
---

::: {.quote-table}
| *Il sunt del cunte forsveié * | *Nos conteurs se fourvoient* |
| --- | --- |
| *E de la verur esluingné, * | *et s’éloignent de la vérité* |
| *E se de ço ne volent granter,* | *et, s’ils ne veulent pas en convenir,* |
| *Ne voil vers eus estriver ;* | *je ne veux pas en débattre avec eux.* |
| *Tengent le lur e jo le men :* | *Ils n’ont qu’à s’en tenir à leur version, moi je m’en tiens à la mienne :* |
| *La raisun s’i pruvera ben !* | *on verra bien qui a raison !* |
|  | - *Le Roman de Tristan par Thomas* |
|  | Edited and translated by Philippe Walter, 1989 |
|  | vv.881-886 |
:::

## Of Scholars, Librarians, and Manuscripts

Consider the case of Erik Rankka (1914-2009), former Docent of Uppsala University in Sweden and editor of *Li ver del juïse: Sermon en vers du XII^e^ siècle* (1982) whose edition intersects with this dissertation through his work on three manuscripts in the Version T corpus (T-B, T-D, and T-F^1^). On October 25th, 1977, Rankka used his typewriter to draft a letter to the librarian of the John Rylands Library in Manchester, requesting a microfilm copy of MS French 6 and any other information regarding the manuscript that they might provide.[^1] He signed this letter and with it included a letter of endorsement from his colleague Professor Kurt Baldinger and a copy of the 1923 *Romania* article by Fawtier and Fawtier-Jones in support of his request. Presumably, sometime later, Rankka received his requested microfilm,[^2] so that he might study MS French 6 from the comfort of the library at Uppsala and possibly inform a future visit to Manchester in person. Similarly, on August 14th, 2021, I used my Macbook Air to submit a digital inquiry to the Manchester Digital Collections website, asking if French 6 had been digitized. On August 17th, Special Collections Librarian Charlotte Hoare supplied me, via email, with a link to the full color digitization of French 6 as well as the digitized 1930 handlist by Moses Tyson describing the manuscript.[^3] Like Rankka, who worked remotely on his edition thanks to his microfilm copy, I was able to inform this project from a distance before justifying an in-person visit to the John Rylands in September 2022, where I was welcomed and encouraged by their kind and knowledgeable staff.

Central to both these narratives is a profound indebtedness to the work of those — librarians, curators, catalogers, and the many manuscript scholars who come before us — whose dedication ensures the preservation, accessibility, and comprehensibility of manuscript collections, thereby fundamentally enabling all associated research. The intellectual labor involved in maintaining these objects and curating these collections is not merely administrative; it embodies a deep engagement with the artifacts under our care and represents an essential component of our scholarly ecosystem. Librarians protect and maintain manuscript collections; catalogers render these collections searchable and individual manuscripts discoverable; editors and translators ensure that the texts within these manuscripts are made legible to a wider audience; and other scholars, of course, build on this groundwork to make insightful contributions that highlight the significance of these manuscripts and inform the collecting choices and other work of the librarians and so on. The cycle continues. All of this shared attention augments a manuscript’s value — both its monetary and its incalculable cultural value — and likewise augments the value we place on the texts recorded within these manuscripts. The manuscripts we choose to devote our time and attention to ultimately shape our perceptions of the medieval past and its literature, of its people and its diverse productions. All of those involved, therefore, in the maintenance, curation, and study of medieval manuscripts bear a significant responsibility to preserve and make clear what these objects are and what they might tell us. It is through the meticulous care and collaborative spirit of every person involved in this cycle of scholarship that our field continues to thrive and evolve. Inalienable from our scholarly endeavors are the human relationships formed between researchers and the custodians of our research objects, ensuring that our field not only persists but flourishes.

Furthermore, this comparison between the work of Rankka and myself illustrates how the fundamental procedures we follow — reaching out to special collections librarians, arranging access, and consulting materials — have changed little over time. However, the tools at our disposal have become more diverse and sophisticated. Manuscript research has undergone significant developments over the past several decades, particularly with the advent of digital technologies. The digital turn has made many manuscripts and their associated metadata available online, allowing researchers to conduct much of their work from locations far removed from the special collections reading room, while in no way diminishing the valuable insights that can only come from consulting manuscripts and their curators in person. Even email has accelerated correspondences between special collections librarians and researchers, making it easier than ever to access materials and arrange visits. And yet, it is important to remember that, despite these new developments, the work of manuscript scholars today remains fundamentally the same, and it is this fundamental continuity in combination with the adoption of helpful innovation that is essential to the production of thorough research that builds over time. While our tools may change, the collaborative and human foundations of manuscript research remain constant. The same intellectual labor — careful cataloging, skilled preservation, informed interpretation — continues to sustain our field. Digital technologies do not replace this labor; they extend it. To embrace digital methods is not to abandon traditional scholarship or the relationships that make it possible, but to carry them forward with new capacities. Digital scholarship, at its best, strengthens our ability to ask and answer humanities questions. Manuscripts are not just data; they are objects of care — preserved, interpreted, and made both available and meaningful through the enduring efforts of those who steward them.
  \
  \
With this in mind, I enter the manuscript studies ecosystem through this dissertation, viewing editing, in particular, as an instrumental, yet often underappreciated, element that not only reproduces texts but actively reshapes scholarly conversations. In his seminal work *Éloge de la variante* (1989), Bernard Cerquiglini underscores the major — and often contentious — influence of editing on linguistic and literary interpretation:

> L’histoire des méthodes proposées pour l’édition des textes médiévaux de langue romane est curieusement pleine de bruit et de fureur. Symptôme des enjeux de cette activité qui prépare ce qui sera la matière du discours grammatical et littéraire, donnant à lire, informant cette lecture. Mais aussi secrètement formée par elle : la critique textuelle, discipline rigoureuse et austère, est la praxis non dite de la théorie littéraire. La philologie est en cela redoutable : portant un masque candide, elle manipule des faits. (73)

Despite the centrality of editing to the ways we access and understand medieval texts, editors and translators often remain in the background, perceived as passive intermediaries rather than active contributors to the formation of knowledge. In reality, editors exert a great deal of largely invisible power — deciding which texts are most worthy of our attention and why, lowering the barriers to new research of old texts, shaping both the selection of works available to us and how we might read those works as we craft our teaching curricula. Stephen G. Nichols, reflecting on the relationship between editions, course content, and research, writes in *From Parchment to Cyberspace* (2016):

> Soon it dawned on me that the versions of medieval literature used in my courses and research were far more mediated than I’d thought. For the best of scholarly reasons — at least according to the lights of the time — editions inserted themselves between what medieval people read, and what my students and I were reading. We were very far from the medieval culture we thought we were studying. (2)

Here, Nichols calls attention to the filtering effect of editorial practice: what appears as a faithful window into the past is, in fact, a carefully constructed frame. This realization demonstrates the almost shocking extent to which editorial choices sway the formation of the medieval canon — what we teach, what we cite, and what we choose to study. Michelle Warren makes a similar point in *Holy Digital Grail* (2022) where she draws attention to the reciprocal relationship between our publishing practices and canon formation:

> Publishing decisions directly influence the canon of medieval literature by shaping what can be widely read, taught, and studied. Conversely, the established canon motivates publishing decisions: famous authors have steady markets. The history of publishing thus turns into the history of the canon. Editions, though, tend to have long shelf lives. … As a result, editions informed by outdated practices remain authoritative amid even the most recent scholarship. (193)

In this light, the longstanding authority of older editions — not infrequently governed by assumptions we might now consider outdated — continues to shape the boundaries of the field. And so, it is the flawed perception of editors as neutral transmitters of texts that must be re-examined so that what we read, study and teach remains aligned with the most current and rigorous understandings available to us.

In taking the form of a digital edition, this dissertation seeks to disrupt the pervasive view in academia that editors and translators are merely conveying texts with minimal scholarly intervention and even without doing challenging, intellectual labor. As an editor, I seek to make Version T of *La Vie de sainte Marie l’Égyptienne* more legible to a wider audience, and as a *digital* editor, I advocate for the adoption of innovative methods to both strengthen and complicate our analysis of medieval texts, furthering the perpetual reexamination of our editing practices.

In structuring this dissertation, I offer an edition of a text with a robust justification for its digital format. Each chapter builds on the last to address current challenges and opportunities in digitizing and digitally editing medieval manuscripts (Chapter 1), provide a more transparent view of the editorial process (Chapter 2), and demonstrate through a close literary analysis how such an edition can reshape our understanding of the text (Chapter 3). As a whole, this dissertation not only serves as an academic study of a single text but also as an experimental model for future projects, taking advantage of digital tools to foster a more dynamic interaction between the text, its various manuscript witnesses, and the modern reader. By integrating new and old methods, my dissertation lays a new stepping stone in the path of research into Version T of *La Vie de sainte Marie l’Égyptienne*, encouraging further exploration of this surprising text. My approach builds upon the work of previous specialists but also sets the stage for future researchers to continue our shared analysis of this text and its material manuscripts through digital means.

## Why Version T?

The twelfth-century Anglo-Norman verse redaction of the Life of Mary the Egyptian known as Version T was written by an anonymous poet in the vernacular and appears to have had a considerable influence on the saint’s cult more broadly in the West. Version T tells the story of Mary, a penitent saint who began her life as a Christian girl from a high-class home. Despite this privileged upbringing, the T-poet notes that she was “badly taught,”[^4] and at the age of twelve, she decides to leave her home and potential marriage prospects in favor of a life alone in Alexandria where she takes up sex work. For years, her many lovers lavish her with fine gifts and shed one another’s blood at her doorstep. Eventually, Mary travels by boat to Jerusalem with a group of pilgrims, paying for her passage with the gift of her body. While in the holy land, Mary experiences a great epiphany. She renounces her former way of life, adopts the Virgin as her guarantor, and flees to the desert beyond the river Jordan with only three loaves of bread and the clothes on her back. Living out the rest of her days as an ascetic, she trades soft beds for hard stone, she grazes on grass and drinks directly from streams, her clothes disintegrate and are replaced by her enveloping, white hair, and her skin blackens. Yet in spite of these harsh conditions, the T-poet portrays her as being perfectly content in her asceticism; in the wilderness, she is provided for[^5] and lives undisturbed by any beast.[^6] Ultimately, she is met by Zozimas (sometimes Zo*s*imas), a holy man who witnesses her many miracles, learns a profound lesson in humility through the model of this Desert Mother, and shares the story of her life with the brothers of his monastery just as the T-poet transmits this saint’s Life to the reader.

But why does Version T, among all the various French accounts of Mary’s life, merit particular attention at all?[^7] To begin with, it is the most substantial and well-crafted verse redaction of the legend in the French tradition, consisting of about 1,532 octosyllabic verses in rhyming couplets.[^8] Another distinct feature of Version T is the shift in focus from the holy man Zozimas to Mary the Egyptian herself. Other language traditions — such the Old English, which is considered the earliest Western vernacular redaction (Magennis,* Old English Life* 1) — concentrate largely on Zozimas’s humble ventures. In the introduction to his edition, Hugh Magennis writes:

> ...the Old English *Life of St. Mary of Egypt* betrays no indications of anxiety or reticence in transmitting the saint’s sense of her own sinfulness or in detailing the extent of that sinfulness, nor does it seek to downplay the gender issues that are inherent in the received legend, in which Mary, a woman, is presented as a figure of authority and a teacher to Zosimas, while he, though a priest, defers to her spiritual superiority. The *Life of St Mary of Egypt* portrays a spiritually-empowered female, who has lived independent of the guidance of men to an extent unparalleled elsewhere in Old English writings about saints. (2-3)

Though I am not at all opposed to viewing Mary the Egyptian as a ‘spiritually-empowered female,’ I am somewhat skeptical of this characterization being equally applied to versions in which she is not even the central character of the narrative.[^9] Version T pulls Mary the Egyptian from the margins of her own legend and makes her the central protagonist. This major narrative shift was clearly an intentional, meaningful choice on the part of the T-poet, and it warrants more analysis than it has received.

Although Version T has been described as the “apex of the legend’s development” by Duncan Robertson (*Medieval Saints’ Lives *119), it has received relatively little scholarly attention in comparison to contemporary texts of other genres.[^10] A good number of pieces have been written addressing Rutebeuf’s later French version (Version R) of the saint’s legend,[^11] but Peter Dembowski, who does not include R in his edition*,* portrays R as merely a reshuffling of T with some two hundred verses inserted from Version O (*Marie L’Égyptienne *22-23).[^12] We might suspect that Version R’s relative popularity among modern scholars stems in part from the fact that we can attach the name of Rutebeuf to the text, reading the narrative through the self-acknowledged intentions of that known author who embeds himself within it,[^13] but also, thanks to the work of Michel Zink, Version R is the only French version of the Life of Mary the Egyptian that has been published in translation, making it far more accessible to modern readers. Similarly, ample scholarship has been produced focusing on the Old English verse redaction, and we might draw some connection between this scholarly interest and the availability of the Old English poem thanks to the Magennis edition, which includes a modern English parallel-text translation.[^14] A great deal of scholarship has been published addressing the legend in the many other vernacular languages as well,[^15] especially the Spanish tradition, which is itself believed to make use of Version T as its source.[^16] There are only a handful, though, of articles and chapters that focus wholly and directly on T.[^17] These include editor of Version T Peter Dembowski’s discussion of the poem’s use of Anglo-Norman language;[^18] five pieces written by Duncan Robertson over several decades primarily concerned with the way the T-poet is able to render the Life into vernacular verse without sacrificing its spiritual core;[^19] a section of a chapter on gender in hagiography by Simon Gaunt in his monograph *Gender and Genre in Medieval French Literature* (1995);[^20] Cary Howie’s article addressing the relationship between the visibility of saintly bodies and notions of conversion;[^21] and portions of Emma Campbell’s *Medieval Saints’ Lives: The Gift, Kinship and Community in Old French Hagiography* (2008).[^22] These scholars of Version T have come to somewhat differing conclusions about the text, but overall, there has been a unified fixation on Mary the Egyptian’s sexuality as the key to understanding her legend.

Robertson considers the translation of the saint’s Life into the French vernacular a signal of a renewal of interest in her Life. He points to the period as one in which the act of reading became particularly pertinent to spirituality, in which there was an upsurge in Marian devotion, and in which hagiography was influenced by “poets and romancers” (“Poem and Spirit” 306) to suit the tastes of a lay audience. He insists that the text is not a vulgarization of the saint’s Life; rather the poet demonstrates a clear sense of orthodoxy (“Poem and Spirit” 316). For Robertson, the content and rhetoric of the text when combined become a “manifestation of Grace” (“Poem and Spirit” 319), exemplifying the paradoxical nature of Mary the Egyptian as a holy sinner. She invokes the Virgin, who “is not merely a person but an incarnate formal principle, the universal reconciliation of contraries — nothing more and nothing less than poetry itself” (“Poem and Spirit” 318). His assessment, however, is not shared by Simon Gaunt who emphasizes the sexual pleasure the text may have been intended to arouse in a male audience at the expense of women:

> The men reading this text can enjoy both the titillating spectacle of the adventures of the comely and sexy harlot, and then the physical degradation of that very same body as it is punished, largely for the desire it aroused in them. The text appeals to the libido of the men in the audience by playing on the desire of the male characters for Marie and by offering an erotic description of her body, but it then enables them to feel morally uplifted by the tale and in so doing it parallels the sadism of virgin-martyr narratives. The implied male audience has its cake and eats it: it watches a holy strip show in which the stripper is first allowed to do her act, and is then punished for her lack of shame, allowing the male audience to enjoy the show, then to feel righteous. The popularity of the legend of Marie l'Egyptienne is no doubt due to more than the medieval reader's taste for narratives about repentance. (219)

In response to this quite provocative framing of the narrative and Gaunt’s otherwise dismissive characterization of female saints’ Lives, Robertson counters the view that hagiography largely demonizes and punishes women with a more nuanced stance on the genre:

> Saintly women are a much more varied lot than Gaunt’s commentary might lead one to suppose. And their vocational chastity can take on a variety of individual meanings. … These women are all autonomous, active figures — not victims or objects but subjects of religious experiences, who invoke the reader’s interest, concern, sympathy, admiration, empathy, and eventual imitation. (“‘Cume lur cumpaine et lur veisine’” 15-16)

Robertson’s vision for Anglo-Norman hagiography invites us to read the Life of Mary the Egyptian — and in particular Version T of the *Vie* — as a text meant to draw in a mixed audience of men and women and clerics and lay people alike.[^23] The audience — either reading or hearing the verses of the T-poet — is given permission to comfortably identify with Mary the Egyptian as both sinner and saint through both an intellectual and emotional arousal, and in identifying with this complex, powerful figure, the audience may further identify with the Virgin and Christ himself.

Gaunt’s reading has also been addressed directly by both Howie and Campbell who, like Robertson, take interest in the eroticism of T and come to somewhat different conclusions. In his article, Howie cites the above description from Gaunt, but he instead argues that Gaunt, “... only addresses half of the text’s erotic charge. I would argue that the strip show, in Marie’s life, does not stop at her conversion. As this encounter with Zosimas more than amply suggests, the text’s scandal is that of an *eroticized penitent body*” (324; Howie’s emphasis). For Howie, T is a challenging, masterful text because it is recognizably erotic throughout the entire narrative, not only when Mary is in the throes of her former *mestier* but also in the midst of her asceticism. Far more important than the sexual desire that her body excites is the religious desire she likewise provokes. Howie notes the throughline running from her public prostitution to her private asceticism, writing, “It is not just that Mary arouses the desire of her viewer; she arouses the desire to see, a desire for visual plenitude which will only ever be frustrated and enticed by her constant turnings, between enclosure and exposure, between part and whole” (331). Howie helpfully complicates Gaunt’s reading by extending desire to include Mary in her penitent form, but I do find Howie’s analysis to fixate somewhat too much on Mary’s genitals,[^24] and in both Gaunt and Howie, we can see a scholarly conversation that approaches the Life of Mary the Egyptian from a mostly heteronormative bias that assumes a male reader’s desire for the female body.

Building on Gaunt and Howie, Campbell leverages the wider corpus of the French tradition of Mary the Egyptian to queer our reading of Mary’s body and the discourse surrounding her body, demonstrating the indeterminacy of both the messages of this text and the audiences of this text — audiences who, according to Campbell, formed a larger, complex community.[^25] Campbell sees Mary’s nakedness before Zosimas’s gaze as mirroring the “verbal striptease” (162) of her confessions,[^26] and she considers this scene of their initial meeting to remain “residually attached to the titillation that this relationship was originally designed to produce” (162) — meaning a desire for salvation above all else through humility. But much like Robertson, Campbell also reframes Mary the Egyptian’s relationship with her audience in a compelling way:

> Mary’s redefined relationship to the social world is one that involves the confirmation of male community rather than its dissolution, the setting of Christian example rather than its corruption. It is a relationship that once again exposes Mary to a male public, *yet in a transformed, strictly disembodied form: the final contact between Mary and her male admirers is ultimately maintained not through her body but through the text of her life. *(164; my emphasis)

When Zozimas discovers the deceased body of Mary the Egyptian — identified for him clearly for the first time thanks to the miraculous note left beside her corpse that reads, “Zozimas, take the body of Mary, / and bury it with God’s help. / When you have buried it, / pray for her by your mercy” (vv.1387-1390)[^27] —, the reader is simultaneously struck in parallel by this experience of revelation, reading the miraculous note through Zozimas’s eyes.[^28] Exposed to the reader thanks to the language of the T-poet, Mary the Egyptian is transmuted; her being has been made interpretable in textual form as a readable corpus in contrast with her former body, which at one time was ‘knowable’ only sexually. Following her burial, Zozimas is ready to unveil her story to others:

::: {.quote-table}
| Zosimas conmence a parler, | Zosimas begins to speak, |
| --- | --- |
| Il ne se volra mais celer. | He does not want to conceal |
| De l‘Egyptiene Marie | Mary the Egyptian: |
| Lor raconte toute le vie, | He tells them her whole life (vv.1501-1504) |
:::

This conclusion sets off a *mise en abyme* of storytelling: Zozimas is finally free to tell Mary the Egyptian’s story to his brotherhood who will, in turn, improve the lives of others in the retelling of it; the anonymous T-poet has recounted the narrative to the reader who will likewise feel compelled to share the narrative of Zozimas telling the story of Mary the Egyptian who — prior to all of this — has told* her story* to Zozimas. As the reader recognizes him or herself as a member of this knowledge loop, they encounter the complicated layers embedded within Version T. That layering not only invites repeated telling and retelling but also exemplifies the dynamic interaction between text, interpretation, and transmission.

Such a structure makes Version T an all the more ideal candidate for an experimental edition that leverages the nuances of its textual variations across its manuscript witnesses. The close consideration of individual manuscript copies further complicates our understanding of Version T and may even help to explain how this narrative has been received so contrastingly by previous scholars. Over the course of the scholarly conversation outlined above, we can see a shared fascination with the eroticism of T, but something somewhat lacking from this decades-long dialogue is a more explicit regard for the individual source manuscripts and their influence.

Although Gaunt, Howie, and Campbell are all engaging with overlapping source material — Gaunt, Howie, and Campbell all make some use of Dembowski’s edition of T, and Gaunt and Campbell each explore Version R through separate editions.[^29] — each of these scholars is relying on a slightly different group of texts (different editions and manuscript copies) to inform their analyses, which could be one source of the differences in their readings. The base text of Dembowski’s edition of T is Paris, Bibliothèque nationale de France (BnF) MS Français 23112 also known as copy A, or T-A. Gaunt uses Dembowski’s Versions T and O (326n51), and Howie uses Dembowski’s T (322n13), so they are both effectively using Manuscript A. But while Gaunt explores multiple versions of the text for the sake of demonstrating his general view of hagiography as fundamentally misogynist,[^30] Howie’s more narrow focus on Version T (which he places in conversation with *La Vie de saint Jehan Bouche d’Or*) ultimately brings him to see the body of our saint as ever shimmering on the threshold of visibility, defying fixity.[^31] Campbell brings an added layer of precision to her queer reading, specifying her use especially of Oxford Bodleian Library MS Canonici Misc. 74 (copy T-B),[^32] but also the Manchester John Rylands University Library MS French 6 fragment (copy T-F¹), *and* Paris BnF MS Français 19525 (copy T-D) in her discussions of Version T.[^33] These scholars are all basing their analyses on different copies of T (or adding in another version of the legend for consideration), and so, are formulating variant conclusions about the figure of Mary using different source material. When we are literally not on the same page of parchment, we are at risk of talking past one another.

## Cross-Copy Reading & The Difference It Makes

Paying attention to the different manuscripts of T, — with the many alterations in details that they include, elide, and emphasize — allows us to build upon current readings of the French Mary the Egyptian, of her body, her beauty, and her holiness. While much of the existing scholarship on Version T relies on Dembowski’s edition — and thus largely relies on Manuscript A (Paris BnF MS fr. 23112) — this dissertation seeks to enrich the present conversation by engaging more comprehensively with the array of manuscript copies available. The exploration of Version T in this dissertation aims not just to add another voice to the existing scholarship but to reshape the present conversation by foregrounding a greater level of scrutiny to the text across its manuscript witnesses. In doing so, I seek to open up new avenues for reading Mary with fresh eyes. By thoroughly examining the full body of textual evidence available, we may enjoy an increased level of confidence and clarity in our scholarly conclusions.

To provide a clear example of the benefit of cross-copy reading and the difference it makes in our analyses, I turn to the work of Élisabeth Pinto-Mathieu. In her comparative analysis of the Lives of Mary the Egyptian, Mary Magdalene, and Thaïs, Pinto-Mathieu highlights the challenge of navigating the diverse and evolving hagiographic traditions across languages and centuries.[^34] Pinto-Mathieu seeks textual stability in her article by centering the *Legenda aurea*, arguing that vernacular versions of hagiographic texts tend to be “pures traductions d’une tradition latine souvent plus érudite” (90) anyway, but she does at various points also make use of the many French versions of the Mary the Egyptian *Vie*, including in particular Version T. In the article, Pinto-Mathieu does mention two specific manuscripts of Version T — BnF MS fr. 23112, or T-A, and MS Canonici Misc. 74, or T-B (100n15&16) — but these copies are only referenced specifically in order to indicate T’s placement chronologically in the broader French tradition so that Pinto-Mathieu might use Version T to explore a feature entirely absent from the Latin tradition: the portraits of Mary the Egyptian — one describing her body during her sexually promiscuous phase and one describing her body as an ascetic in the desert.

Pinto-Mathieu makes the argument that Mary’s body (in Version T) is initially beautiful and desirable and sensual and later becomes ugly, frightening, and generally husk-like as a result of her harsh penance — an argument that is commonly repeated in work on Mary the Egyptian, and even specifically in Version T scholarship, without much variation.[^35] She suggests that the presence of the first portrait depicting Mary’s initial beauty is only added by the T-poet so that her later more mysterious figure might appear all the more shocking for the reader: “Le portrait physique ne s’imprègne de la poésie courtoise et érotique à la mode que par jeu littéraire, pour préfigurer un second portrait, celui de la noirceur saisissante” (101).[^36] In support of this argument, she writes that one need only look to a single detail within the portraits to understand the function of these portraits: Mary the Egyptian’s breasts. She points to the use of the word *mameles* (v.177) in the first portrait and the use of the word *traians* (v.643) in the second, suggesting the former is far more sensual than the latter. She writes, “Les ‘mameles,’ terme consacré de l’érotique courtoise, se réduisent à la fonction de ‘traians’; elles ne relèvent plus que de l’anatomie” (103n19). She is suggesting that Mary the Egyptian was once sensual and becomes merely physical, and is certainly physically undesirable, having shed the erotic function of this part of her body. Regardless of which version of the legend one reads — according to Pinto-Mathieu — the message is uncomplicatedly the same: “Qu'elle gomme le portrait, comme le fera Jacques de Voragine, ou bien qu'elle en joue, le travaille et l'exhibe par des procédés d'écriture spéculaire, l'hagiographie des pécheresses repenties du XIII^e^ siècle n'aspire qu'à prôner le renoncement à la chair” (103).

In fact, if we consider the verses describing Mary the Egyptian’s breasts across the extant manuscript copies, the word *mameles* is *only *used in manuscripts T-A and T-B, and manuscript T-B omits the verse that would use *traians* in the second portrait entirely, whereas every other whole copy — the fragments are, unfortunately, missing these passages of the text— uses the term *traians* for *both *portraits.

> T-A: “Les **mameles** de cele dame” (v.177) → “N’avoit plus char en ses **traians**” (v.643)  
T-B: “& si avoit beles **mameles**” (v.171) → [verse omitted in B]  
T-C: “Chascun des **traianz** la dame” (v.179) → “N’avoit plus char en sa **triant**” (v.655)  
T-D: “chascun des **traianz** a la dune” (v.175) → “N’aveit plus char en sun **traiant**” (v.645)  
T-E: “L’un des **traians** de cele domme” (v.178) → “N’avoit de char en ses **traians**” (v.645)  
T-L: “Cacune **traiant** de la dome” → “N’avoit plus char en son **traiant**”[^37]  
T-F^1^: [offers only the first 10.5 verses of Portrait 1]  
T-F^2^: [both portraits missing]  

When reading across the T corpus, instead of relying solely on one manuscript copy, we can see that this particular argument of Mary’s supposedly degraded beauty may be called into question. How valid is it to say that the once erotic, sensual, sinful Mary the Egyptian is no longer desirable, or even touchable, in her more purified ascetic form if we find a consistent use of *traians* regardless of Mary’s state of being? The difference of a single word in a single manuscript may seem significant, but when examined more closely, it can reveal how seemingly stable arguments rely on incomplete evidence.

I might just as easily draw a completely contrasting conclusion regarding Mary’s sensuality using the evidence of a single word found only in a single manuscript copy of T. If I were to base my reading solely on manuscript T-C, for example, I could — by the same method — come to the conclusion that Mary’s initial form is one that is hard and threatening while her ascetic form is soft and inviting. In manuscript T-C, Mary the Egyptian is compared to a precious stone in the first portrait — a *gemme*[^38] — a descriptor not found in any of the other Version T manuscript copies. A gem is a precious thing, but it is also a hard, unliving stone, an object that men might kill one another to possess — as Mary’s many lovers in fact do— suggesting that during her sexual career, Mary exists in an objectified, lifeless state; she is beautiful but cold, unfeeling, and unapproachable. In contrast, while living spiritually in the desert, Mary is, according to every single manuscript copy, *mossue*, sometimes even in multiple lines,[^39] which may be interpreted in this context as “mossy,” “fuzzy,” “shaggy,” “bushy,” “wooly,” “furry,” or simply “hairy.” Thus, in the second portrait, Mary is undeniably pilose, perhaps even invitingly touchable. In light of this evidence, which of these Marys — the sinner or the saint — is more approachable? And what might this shift in perspective tell us about her legend and the wide array of people who encountered it? A single word in a single verse of a single manuscript may justify the raising of a question, but it will rarely provide sufficient footing for a confident interpretive claim. However, the sum total of hundreds of such pieces of textual evidence gathered across the full corpus of extant manuscripts will offer a far more stable and persuasive foundation for an argument.

As I will discuss at greater length in Chapter 1, typically, the purpose of an edition is to provide readers with a tidied up version of a text — to provide the sort of seemingly stable homogeneity Pinto-Mathieu describes seeking in her article — but this process of tidying can conceal the meaningful ‘clutter’ present in the many source manuscripts, leading to potential misrepresentations of existing material evidence in favor of a more digestible text abstracted from the manuscript record.[^40] In Chapter 2 of this dissertation, I offer digital editions of the two T portraits from each of the available manuscript copies with unique English translations for each copy; these editions and translations serve as the basis for the cross-copy close reading of the portraits performed in Chapter 3. Making these edited and translated portraits more readily available is also intended to invite my readers to approach the arguments I make in this dissertation with greater scrutiny as I believe reading across the full T corpus will lead to stronger arguments and more open, complex scholarly conversations. Pinto-Mathieu’s approach retains value in that articles like hers laid the groundwork in the late 1990s for giving literary attention to medieval texts written about — and possibly written by and for — women, and in particular for giving literary attention to hagiographical texts. But now that we have more tools — digitization and digital editing — to create editions that offer more in the way of visualizing and untangling the manuscript copies, future scholarship will be able to make greater use of the nuances of manuscript traditions and produce more solid, careful readings.

## Why a *Digital* Edition of Version T?

At the conclusion of *Éloge de la variante *(1989), Cerquiglini recognizes the worthy efforts of recent editors — naming Peter Dembowski’s *La Vie de sainte Marie l’Égyptienne* among others (112)[^41] — to push the limits of print to convey manuscript variance. Characterizing such print editions as “Tentatives sympathiques, fort utiles, qui traduisent un besoin, mais laissent insatisfait” (112), Cerquiglini insists, “La solution est ailleurs” (112); the solution — for Cerquiglini — lies with the then quite recent progress of the computer screen. Cerquiglini excitedly praises the computer’s potential to provide readers with far more data than one might reasonably set down in print without ruining the reading experience, but more profoundly, he sees the most novel technical contribution of the computer to be its potential to reconnect modern readers intellectually and emotionally to a medieval understanding of texts and their movement:

> Car l’ordinateur, par son écran dialogique et multidimensionnel, simule la mobilité incessante et joyeuse de l’écriture médiévale, comme il restitue la prodigieuse faculté de mémoire de son lecteur, mémoire qui définit sa réception esthétique, fonde le plaisir qu’il y prend. (114-115)

Rather than conceptualizing Version T as a singular ‘text,’ we might helpfully enrich our reading experience and our scholarship by engaging with the fact that Version T survives in eight distinct, yet interrelated, manuscripts (six complete copies and two fragments).[^42] We might highlight the nuances presented by each manuscript that would typically remain obscured through the medium of a traditional print edition.[^43] And I am not alone in thinking that Version T, in particular, merits a new edition — one that does more to render individual copies and their correlations plainly visible for the reader.

Duncan Robertson, himself, put out the call for a new edition of T in his 1998 study “The Anglo-Norman Verse Life of St. Mary the Egyptian,” in which he offers a systematic study of all the extant T manuscripts, providing a valuable update to Dembowski’s previous work.[^44] In this article, Robertson proposes a roadmap to future editors for how best to approach a new edition of Version T in a way that offers improved visualizations of the full corpus of manuscript transcriptions to facilitate a more complex reading without excessively burdening the reader, writing, “Ideally, the reader should be spared the painful task of reconstituting them from lists of variants” (“The Anglo-Norman Verse Life” 41) — a clear critique of the traditional method of noting variants as paratextual material to be deciphered by only the most attentive of readers, which we see in most print editions, including Dembowski’s.[^45] Robertson, of course, praises Dembowski’s edition — an edition that remains an invaluable resource for scholars of the French Mary the Egyptian tradition — but he makes its limitations clear:

> The problem is that in passage after passage, the A text blurs the sense and muffles the expressive rhetoric of the poem. It does so, moreover, in the course of a normalizing, Picardizing campaign, which effectively severs the poem’s textual connection to the Anglo-Norman manuscript tradition (still present in A’s immediate source), and thereby removes it from the literary affinities that constitute its true native milieu. (“The Anglo-Norman Verse Life” 41)

Evidently relying exclusively on a single manuscript witness is too restrictive, which might lead some to favor the composite editing method in which multiple copies are assembled by the editor to make a sort of Franken-edition — or perhaps an attempt is made to reconstruct the ‘Original’ text — but Robertson likewise denounces this method, “Not only would such a construction have no documentary validity, but also it would falsify the inherent plurality of this textual tradition” (“The Anglo-Norman Verse Life” 40). If a composite edition will not do, then editors are left, once again, with selecting a particular manuscript to serve as the base text or editing a limited number of copies in parallel. While practical, considering the restrictions of the print medium, selecting a single copy, or even a few copies, fails to represent the poem comprehensively.[^46] How, then, can we offer the plenitude of the Version T corpus to readers while acknowledging the fact that a reader can only read one line at a time?

To overcome these challenges, the method Robertson proposes is an “editorial grid” system in which the text is presented with some of its variants laid out in parallel on the page, selectively highlighting apparent differences in repetition, rhyme, and sequence — three characteristics Robertson identifies as being particularly meaningful attributes of the T poem (“The Anglo-Norman Verse Life” 31). Roberson’s solution would allow the editor to make key moments of variance much clearer, but at the time he proposed it, the physical limitations of print still meant that such an edition would not allow for fully edited comparable transcriptions of all eight manuscript copies to be laid out together for the reader, and the reader would still be reliant on the editor’s judgement in selecting which moments of the text are worthy of a more attentive reading across the copies.

Despite Cerquiglini’s great enthusiasm for the potential of computers to resolve all of our editorial needs in the late 1980s, the adoption of digital methods in premodern textual editing has been slow to take hold. Robertson’s call for a new edition appeared at the cusp of the wider digital turn of the late 1990s at which time digital methods were not nearly as accessible to individual humanities scholars as they are now in the 2020s, and so, Robertson did not entertain the possibility of a digital edition, but I would argue that his proposal is essentially a proto-digital edition whose scale has been reduced to meet the physical constraints of the printed page. The present digital edition has been greatly informed by Robertson’s recommendations for a more selective depiction of textual variance,[^47] but my ambition for this digital edition is to do what was not nearly as possible — but was clearly desired — only a few decades ago: provide full edited transcriptions of every T manuscript, which the reader may find in Appendix 2 of this dissertation, and eventually, full English translations of every copy — an ambition I will pursue beyond the scope of this dissertation.[^48]

In agreement with Cerquiglini and Robertson, I believe there is a great necessity to take a closer look at Version T, not as a singular text, but rather as a group of texts existing simultaneously in the eight extant manuscript copies that we have of T. The Life of Mary the Egyptian of Version T is not fully conveyed in any one copy or another, but in all of them at once. Strengthening our relationship with the source manuscripts of Version T forces us to reevaluate the way we think about Mary the Egyptian and the broader implications of her legend. By offering access to Version T as a corpus of variant texts and material contexts, this edition invites readers to experience what John Bryant calls a ‘fluid-text moment’ or the jarring realization of textual instability that challenges and enriches our understanding of medieval literature.[^49] I am not arguing, however, that it is the responsibility of every single medievalist to track down and personally consult every single manuscript copy of any text they ever work on. We cannot all be Christopher de Hamel, globe-trotting around with direct access to the most precious manuscripts in the world.[^50] Rather, I believe more can reasonably be done to reform the way we edit and disseminate medieval texts through the application of digital methods that facilitate clearer visualizations of texts and their traditions, grounded in their manuscript witnesses. Advancements in our editing practices will improve the quality of our scholarship by pushing us to be more meticulously evidence-based in our analyses, and expanding the accessibility of medieval texts through open-access editions and translations will equip us with the tools we need to reach modern readers where they are. By addressing the complexities and specificities of the manuscript tradition of Version T, this dissertation not only responds to Robertson's specific call for a new editorial approach but also pushes the boundaries of how medieval French texts are presently edited and understood in the digital age, inspired by Cerquiglini’s hope for a new *édition écranique*. The result is an edition that respects the inherent plurality of the work and provides a foundation for future scholarship to build upon, ensuring that the unique voices of the manuscripts are preserved and appreciated in their full historical and literary value.

## Structure

Chapter 1, “On Digital Editing,” lays the theoretical foundation for the project by critically evaluating the way in which scholars currently discover, search for, study, edit, and share lesser known medieval texts, offering a brief case study of the now-lost manuscript fragment of Version T of *La Vie de sainte Marie l’Égyptienne* known as T-F^2^. While digitization has made strides, there is still significant room for improvement in accessibility and preservation through digital methods like digital editing, with editions serving as supplemental resources for better accessing and understanding the material manuscripts as well as the texts they contain. Examining the limitations of traditional print critical editions, Chapter 1 advocates for digital editing grounded in material manuscript sources in alignment with the New Philology movement. Addressing common counterarguments to digital methods, this chapter proposes approaches to enhance scholarly visualization and engagement with pre-modern texts.

Divided into two parts, Chapter 2 “An Approach to Editing Version T,” outlines the development and execution of the digital edition begun in this dissertation — a digital edition that renders both editorial intervention and the variance among manuscript copies more readable and thus more informative for scholarly interpretation. Part 1 of Chapter 2 details the process of transcribing, editing, and encoding all the available manuscript copies of Version T — material provided in Appendix 2 of this dissertation. This part introduces a novel multi-column format for the digital edition, which displays the text at various levels of editorial intervention, ranging from ‘Nearly Diplomatic’ to ‘Extensive.’ This presentation style makes plain the mediating hand of the editor and encourages readers to consider editions to be active reinterpretations of original texts, rather than mere reproductions. Part 2 offers a digital edition of the two portraits of Mary the Egyptian found in Version T with English translations of each extant copy. By narrowing in on the portraits alone, this part provides a more targeted case study for what is possible when further visualization methods are applied, demonstrating the potential of digital editions to make plain the textual variance present across manuscript copies in a more legible format than one might find in a traditional print edition. The presentation of these portraits is designed to facilitate reading across the manuscript copies and supports the analysis performed in Chapter 3. Additionally, the availability of these portraits in translation further promotes the accessibility of this text to a wider reading audience.

Chapter 3, “A Cross-Copy Close Reading,” demonstrates the critical value of conducting a literary analysis across the different manuscript copies of Version T, specifically through a detailed examination of the text’s two portraits of Mary the Egyptian. By tracing both the continuity and variance of poetic elements such as negation, color imagery, and metaphor across the manuscripts, this close reading enriches existing interpretations of Mary, particularly regarding the controversial nature of her desirability and the theological function of her *Vie*.

Following the conclusion to this dissertation, which addresses some of the unresolved challenges raised by the work, Appendix 1, “The Manuscripts,” provides a comprehensive examination of the manuscript corpus preserving Version T. Drawing on my direct observations of all accessible manuscripts, as well as catalog records, digitizations and microfilm reproductions, and other foundational scholarship such as Peter Dembowski’s edition, I consolidate the available scattered metadata and offer detailed commentary on the location, condition, and accessibility of these eight known copies, including the two fragments. By briefly addressing the challenges of manuscript access — including personal experiences with the recent disruptions at the British Library — this study underscores the importance of supplemental resources for advancing scholarship. By bringing together this information in a single resource, this appendix not only aids researchers facing barriers to direct access but also highlights new avenues for future investigation into the material and textual history of Version T.

The final component of this dissertation — Appendix 2, “Edited Transcriptions” — is an experimental digital edition in which interested readers may explore the entirety of the extant Version T corpus. The format of Appendix 2 seeks to explicitly show readers the mediating hand of the editor in rendering the contents of these eight manuscripts for a modern audience by presenting each T copy with varying levels of editorial intervention, which may be freely navigated by the reader as desired. The inclusion of this appendix is meant to demonstrate to readers the extensive work that has already been done in transcribing and editing the full T corpus, while also acknowledging what remains to be done, namely additional revision and full English translations of every manuscript copy. Where available, links to the digital facsimiles of several T manuscripts (T-A, T-D, T-E, T-F^1^, and T-F^2^) are provided, but future iterations of this project would ideally seek to integrate these digitizations more fully with the aim of further bridging the gap between the medieval source and the modern reader. Together, Chapters 1 and 2 and Appendix 2 articulate a vision of editorial work that is rigorous, continuous, and transparent.

Finally, as the entirety of this dissertation is presented as a digital document authored using the publishing system Quarto — a new open-source publishing system made by developers of the programming language R —, readers may see how the very format of this dissertation is in alignment with its arguments. By adopting a digital format that facilitates the integration of static and dynamic content, this dissertation embodies the push for more digitally forward editions and scholarship and reflects a commitment to leveraging contemporary technology to enhance the accessibility, visualization, and interpretation of medieval texts.

[^1]: [](#ftnt_ref1) Special Collections Manuscript Curator and Archivist at the John Rylands Library Elizabeth Gow kindly supplied me with a pdf scan of this letter via email on August 24th, 2024.
[^2]: [](#ftnt_ref2) According to Gow, The John Rylands no longer has a microfilm copy of French 6, and Uppsala University is not in possession of such a microfilm or any of Rankka’s papers. Uppsala Special Collections Archivist Ina-Maria Jansson did, however, supply me with Rankka’s obituary, which describes Rankka’s commitment to editing and translating works of medieval French literature into Swedish through the later years of his life (personal correspondence via email 8-13 Aug 2024).
[^3]: [](#ftnt_ref3) It is possible that Rankka was supplied with this same handlist, but he does not include it in the bibliography of his edition.
[^4]: [](#ftnt_ref4) “Mais malement fu enseignie” (v.60). Unless otherwise indicated, all quotations of Version T in this dissertation will be taken from manuscript copy T-A (Paris, Bibliothèque nationale de France, Français 23112), which is the base text of Peter Dembowski’s edition of Version T in *La Vie de sainte Marie l’Égyptienne: Versions en ancien et en moyen français* (1977). > The term ‘verse’ is used in this dissertation to refer to the the single metrical unit of poetry, and ‘line’ refers to a single row of text copied within a manuscript. All translations, unless otherwise stated, are my own.
[^5]: [](#ftnt_ref5) “D’erbe vesqui & de rachines / Xvii. ans. par les gastines / Puis fu .xxx. ans onc ne manga / Se angeles ne li aporta” // “On grass she lived and on roots / for seventeen years in the wilderness. / Then for thirty years, she ate nothing / unless an angel brought it to her.” (vv.681-684)
[^6]: [](#ftnt_ref6) “Ne ainc en trestot le boscaige / Ne li vint puis beste salvaige / Ne autre vive creature / Par le gaut va toute seure” // “Never in all the wood / did any wild beast come to her thereafter / nor any other living creature. / Through the forest, she goes totally assured.” (vv.695-698)
[^7]: [](#ftnt_ref7) Version T is one of about a dozen versions in the French tradition alone. The other versions — as described by Dembowski — are X, V, W, N, O, O1, Z, U, Y, L1, L2, L3, and R. Version T is considered one of the earliest of these, dating at least to the late twelfth century according to Alfred T. Baker and confirmed by Dembowski (17). Version X was believed by > Hermann Knust to be the source for T, but Paul Meyer correctly judged — according to Dembowski (17) — the inverse to be the case. Dembowski suggests X was likely written soon after T though probably near start of the thirteenth century (17). Version V, dating to the fifteenth century, likely derives from X as Dembowski notes the two share the unique accusation of incest as being among Mary the Egyptian’s many sins (18). Dembowski dates Version W — a short Anglo-Norman poem likely translated from a Latin source — to the end of the twelfth century, making it a rough contemporary of Version T (18). Dembowski repeats Hilding> Kjellman’s assessment that Version N likely dates to somewhere between 1230 and 1250 based on a linguistic study of the collection of miracles of the Virgin in which N is included (19). Dembowski says that the N poet was likely following a Latin prose source, but he cannot exclude the possibility that the N poet had access to Version T too due to some resemblance between some of their verses (18-19). Version O is the translation of an unidentified Latin version of Sophronius and the primary source of Version R (19). Based on the linguistic evidence, Dembowski would not date Version O any later than 1250. Version O> 1> is a significantly abridged redaction of Version O, which Dembowski chose to feature separately “de ne pas trop encombrer l’appareil critique et ne pas le rendre à peu inutilisable” (20). According to Dembowski, Version Z is contemporary with O but was likely the translation of a simpler, more concise Latin text (20). Version U is of a similar type to O and Z — though less than half the length of O —, dating to the second half of the thirteenth century (20-21). Version Y is about a third of the length of Version O and dates to the mid-fifteenth century (21). Finally, L> 1> , L> 2> , and L> 3> are French translations of the > Golden Legend> of Jacobus de Voragine (21) with L> 1> dating to the end of the thirteenth century (263), L> 2> to the second quarter of the fourteenth century (269), and L> 3> anterior to the fifteenth century (275).
[^8]: [](#ftnt_ref8) Other than Version R, which is of comparable length but is a derivative of T, Version W, which is made up of only 140 lines, and Version N, which consists of 407 lines, all of the other surviving versions in the French tradition are written in prose.
[^9]: [](#ftnt_ref9) The French versions that are narratively centered on Mary are T, X, V, W, N, and R — all of these apparently deriving structurally from T —, and the versions that are narratively centered on her counterpart Zosimas are O, Z, U, Y, and L.
[^10]: [](#ftnt_ref10) Simon Gaunt makes it clear that the discrepancy between texts that were most popular among medieval readers and those that are most popular among modern readers is in large part caused by the skewed production of modern editions: “Hagiography is good for medievalists. I do not thereby mean that the texts are necessarily good for their souls (though they may be), but rather that saints’ lives offer a useful corrective to the reading experience of most modern readers of vernacular medieval literature, which is often grounded almost entirely in profane texts. … The profane texts students of Old French and Occitan mostly read represent a tiny proportion of the texts produced in medieval France and Occitania. Even in the vernacular the quantity of religious texts which has survived is far greater than their availability in modern editions suggests and vernacular hagiography was at least as popular as other literary genres, if not more so. Modern views of medieval vernacular writing are skewed by the marginalization of hagiography” (180).
[^11]: [](#ftnt_ref11) These include > Dawson (2003) & (2005),> Delfin (1989), Foehr-Janssens (2000), Karras (1990), Mariani (2017), Nash (1971), and > Uhlig (2010).
[^12]: [](#ftnt_ref12) In her article “Rutebeuf’s Contribution to the Saint Mary the Egyptian Legend” (1971), Suzanne Nash likewise describes R as a simplification of T, “The prayer in *T * is far more complicated. Not only does it reveal a feminine mind analysing her own sinfulness, but it is a*tour de force * of persuasive rhetoric” (699n12; Nash’s emphasis). According to Nash’s assessment, the verse of R relies more heavily on poetic devices of repetition to imitate the kinetic experience of Catholic ritual in order to excite a lay audience that “was not especially learned” (697). Thus, Nash supposes that the audience’s experience of R* * becomes more ritualistic than didactic (697). If we follow Nash’s assessment that T is far more literarily complex and didactic than R, then who exactly was the intended readership of T? And what exactly were they meant to glean from its highbrow style and its elevated didacticism? Scholars of Version T have come to somewhat differing conclusions to these questions, which I will discuss further below, but overall, scholarship on T has been predominantly fixated on Mary the Egyptian’s sexuality as the key to approaching the answers.
[^13]: [](#ftnt_ref13) Emma Campbell recounts how Rutebeuf describes the labor of his rewriting of the saint’s *Vie* as an act of penance in imitation of Mary’s own labors (176).
[^14]: [](#ftnt_ref14) An English translation of Paul the Deacon’s Latin Life of Saint Mary of Egypt was also published by Benedicta Ward in her *Harlots of the Desert: A Study of Repentance in Early Monastic Sources *(1987), which may have also contributed to the quantity of English language scholarship on the legend in general. The essay collection* The Legend of Mary of Egypt in Medieval Insular Hagiography* (1996) and several other pieces (Chase [1986], Heron [2000], Karras [1996], Lees & Overing [2001] Magennis [1985], and Scheil [2000]) on the topic of the insular tradition predate the Magennis edition, but appearing after the Magennis edition, we have seven more articles concerning the Old English verse: Black (2011) & (2017), Blud (2017), Cotter-Lynch (2021), Maslanka (2013), Szarmach (2013), and Watt & Lees (2011).
[^15]: [](#ftnt_ref15) By my count, 35 articles have been published concerning the Mary the Egyptian legend in the Bulgarian, Croatian, Dutch, German, Greek, Irish, Italian, Norse, and Spanish traditions. These include Acquafredda (2008), Beresford (2020), Bisanti (2013), Cortina (1980), Delmas (1900) & (1901), De Vleeschauwer (1998), Di Giorgi (2000), Dimitrova (1995), Eidinow (2019), Faccon (1998), Francomano (2014), Grieve (2000), Kaltsogianni (2011), Kersten (1992), Maier (1984), Miller (2003), Mirachvili-Springer (2012), Noret (1987), Ó Laoghaire (1990), Petrova (1999), Petrović (2005), Posa (1999), Scarborough (2013), Seidenspinner-Núñez (1992), Villani (1994), Walsh (1989), and eight more articles by Zubillaga alone.
[^16]: [](#ftnt_ref16) In the introduction to his edition, Dembowski writes “T a sûrement servi de source directe à d’autres versions vernaculaires (notamment à la prose *X *, au poème* R *, à la paraphrase franco-vénitienne et à la* Vida* espagnole)” (16).
[^17]: [](#ftnt_ref17) There are other publications that make use of Version T indirectly. As mentioned above, Nash (1971), Uhlig (2010), and Mariani (2017) are primarily fixated on Version R, but each of them do also make use of Version T for the sake of comparison. Uhlig, in particular, is admirably precise in specifying the exact verses from each version she uses to draw her conclusions, though she makes no reference to particular manuscripts, relying entirely on Dembowski’s edition. Cazelles (1979) discusses the French tradition of the legend more generally. She makes use of Versions T, W, N, O, and R to consider how these different versions render Mary the Egyptian a figure one might view as a model (or not) for “perfectionnement” (14). Ultimately, she does not believe the Life allows the reader to identify with Mary, writing, “Proche de Dieu et non du monde, Marie reste un mirage” (22). Karras’s hefty article “Holy Harlots: Prostitute Saints in Medieval Legend” (1990) is similarly a more indirect treatment of Version T. She considers five different saints (Mary the Egyptian, Thaïs, Pelagia, Afra, and Mary Magdalene), and in her analysis of Mary the Egyptian, she makes use of Versions R and T while also making reference to the differences that may be found in other language traditions such as Latin, German, English, and Scottish. McCulloch (1982) makes use of Dembowski’s then recent edition to draw parallels between the T-poet’s portraits of Mary the Egyptian and Villon’s portraits of the Belle Heaulmière, which is her primary focus. Rudder (1982) focusses on Version X, claiming that because X is written in prose it reduces the stylistic elements present in T in favor of a greater emphasis on the deeper, religious teachings of the text — an analysis I do not support as Version T is considered the source of Version X and as T’s stylistic elements are what make its didactic messaging all the more powerful for instructing a lay audience. Pinto-Mathieu (1998) is mainly working from Jacobus de Voragine’s *Golden Legend *, finding a preference for redactions with a structural focus on Zozimas (106-107). Pinto-Mathieu does, however, make use of Dembowski’s edition of T to make certain points, which I will explore further below. Finally, Sargent’s research is fixated entirely on the development and influence of Version T, which she wholeheartedly endorses writing, “No other version of the* Life of St. Mary the Egyptian* advances beyond the development represented by T” (261). Sargent’s work is a dissertation — directed by Duncan Robertson — from the late 1970s, which does not appear to have resulted in any subsequent publications.
[^18]: [](#ftnt_ref18) “Le poème anonyme sur sainte Marie l’Égyptienne: Est-il anglo-norman?” (1981)
[^19]: [](#ftnt_ref19) In “Poem and Spirit” (1980), Robertson argues that the T-poet makes use of the rhetoric of the romance genre without vulgarizing it, taking clear inspiration from Bernard of Clairvaux, “For the French poet also the meaning of words is inseparable from feeling. … he has ‘translated’ the saint’s life into the barbarous language of love” (316). Then, in “Twelfth-Century Literary Experience” (1987), Robertson disagrees with Cazelles’s assessment that the reader cannot identify with Mary the Egyptian, claiming that Cazelles’s interpretation is more appropriate for the thirteenth-century versions, “But our 12th-century poem is another matter. It represents an exceptional moment in literary history, one of fervor and emotional immediacy. 12th-century saints’ lives present themselves insistently as experience, not other or alien, but very much our own” (77). Robertson’s monograph *The Medieval Saints’ Lives*(1995) and article “The Anglo-Norman Verse Life” (1998) are particularly useful in understanding Version T’s place in the larger history of the legend and within the genre of hagiography. Finally, “‘Cume lur cumpaine et lur veisine’” (2001) examines the complex fellowship among women in Anglo-Norman hagiography.
[^20]: [](#ftnt_ref20) Gaunt pays particular attention to Mary the Egyptian in the section “*Clergie*, Community and Gender” in the chapter “Saints, Sex, and Community: Hagiography” (212-233).
[^21]: [](#ftnt_ref21) “As the Saint Turns: Hagiography at the Threshold of the Visible” (2005)
[^22]: [](#ftnt_ref22) In particular, Campbell addresses Version T in the section titled “Queer Community in the Life of Mary the Egyptian: the *T* Version” (157-164) within the chapter “Queer Community” (149-178), which also includes some discussion of Version R (164-178).
[^23]: [](#ftnt_ref23) “They [women saints] propose to break the barriers that normally separate the human world from the divine, and also those that separate men from women, and clerics from laity. The women saints, in short, illustrate and confirm the writers’ faith in the text as a instrument capable of conveying the fullness of religious experience to auditors, who are included within it as fully qualified communicants. They speak to the readers, and pray with them, in their own language, in a poetic yet ‘neighborly’ discourse, stripped of the grammatical protocol, but ornamented with rhyme and rhetoric: an idiom in which female spirituality could be validated, and rendered anew” (“‘Cume lur cumpaine et lur veisine’” 23)
[^24]: [](#ftnt_ref24) Howie writes, “... it’s difficult to see anything other than Marie’s genitalia on display throughout the poem” (325). In Chapter 3 of this dissertation, I provide a close reading of the T portraits of Mary that departs from Howie’s emphasis on that one *partie* of her body, focusing instead on her hair, skin, feet, and breasts.
[^25]: [](#ftnt_ref25) Campbell finds that the genre of medieval saints’ Lives lends itself well to queer readings as these texts “provide a framework for communal identification that is never actualized within the text itself” (156). Pointing, for example, to the use of the ‘we’ pronoun evoked in the closing prayers associated with saints’ Lives and to the depiction of mass conversions commonly found in the Lives of martyrs, Campbell argues, “The narrative composition of such communities in saints’ lives therefore suggests a structure that permits — and possibly even invites — queer desires and identifications” (156).
[^26]: [](#ftnt_ref26) Howie also playfully nods toward Gaunt’s image of the strip show when discussing Zozimas’s discovery of Mary the Egyptian’s corpse, “The naked saint, before her death, only does a solo show” (328).
[^27]: [](#ftnt_ref27) “Zosimas pren le cors Marie / Sil ensevli o Dieu aie / Quant tu l’aras enseveli / Prie por li par te merchi” (vv.1387-1390).
[^28]: [](#ftnt_ref28) Campbell comments on this moment further, “...visual contemplation of the body becomes contemplation of divine text. Indeed, Mary is not just named by the divine *escrit*, she becomes it. … Rather than simply being discarded, the body is thus textualized in a way that resists more pessimistic and dualist assessments of the relationship between body and soul” (173). It is via this thread of Mary’s textual body that I would most like to enter the scholarly conversation with my own work, both in the production of this digital edition and through the analysis I offer of the T portraits in Chapter 3 of this dissertation.
[^29]: [](#ftnt_ref29) Gaunt uses Michel Zink’s edition of R, while Campbell uses the Bastin and Faral edition of R.
[^30]: [](#ftnt_ref30) “In examining various versions of *Sainte Marie l’Égyptienne * I have taken an extreme example in order to illustrate my view that some saints’ lives are intended primarily for men and make no direct appeal to women. However, I suggested earlier in this chapter not only that hagiography was read by women, but also that one could speculate as to how it might have been received and used by some women. I see no reason why women should not have wanted to read narratives about repentant whores, but as with narratives about virgin martyrs, I would argue that if to a certain extent such narratives were empowering for some women, this would entail the internalization of an extremely contemptuous and negative view of the female body. Whereas the male poet and the men in the audience can displace sinful desires and anxieties onto women’s bodies in the*Marie l’Égyptienne* narratives, women readers are implicitly enjoined to contemplate their own bodies as the incarnation of sin and as a threat not only to their own spiritual well-being, but to that of all the men they encounter. Paradoxically they are also invited to view their bodies as the source of their salvation if they are prepared to submit them to extreme punishment. Religious symbols are indeed complex.” (Gaunt 227-228)
[^31]: [](#ftnt_ref31) “For our saints, the assembly of the body-in-pieces into a statuesque fixity is not yet necessarily complete, much less owned. There is still, and I would argue that perhaps there is indefinitely, the flailing of limbs en route to stasis. At the threshold of the visible, at the threshold of the visceral, the saint is always turning” (345-346).
[^32]: [](#ftnt_ref32) Campbell links this copy (T-B) of Mary the Egyptian’s Life to other neighboring saints’ Lives — specifically *Alexis * and*Euphrosine* — found in the same manuscript, comparing each saints’ rejections of family and society (159).
[^33]: [](#ftnt_ref33) These manuscript copies are specified in the primary sources of her bibliography (253). Campbell also briefly traces the use of the label ‘confession’ to categorize Mary’s recounting of her life to Zozimas across several French versions (T, X, V, N, and W) to note the instability of this categorization of Mary’s speech (161n33).
[^34]: [](#ftnt_ref34) “L'éparpillement extrême des textes hagiographiques, leur évolution au fil du temps ou de la géographie, le caractère souvent inédit des manuscrits risquaient de grever cette analyse comparative en la privant de l'homogénéité nécessaire à toute entreprise littéraire ou stylistique” (89-90).
[^35]: [](#ftnt_ref35) Gaunt describes Mary’s penitent body as ‘hideous’ twice in his chapter: “As an old and hideous naked woman…” (214); “Later descriptions of Marie as a hideous wild woman…” (219). And Emma Campbell refers to Mary the Egyptian’s penitent body as “characterized by physical ugliness” (160) for example. However, Robertson finds beauty in Mary’s penitent form, “The second *descriptio * describes*beauty* as much as does the first” (“Poem and Spirit” 321).
[^36]: [](#ftnt_ref36) The reader of Zozimas-centered versions of the legend is denied this transformation as Mary the Egyptian is only encountered in her ascetic form. Pinto-Mathieu describes how Jacobus de Voragine actively denies Mary the Egyptian any redeeming aesthetic qualities, presenting her exclusively as “un diable noirci” (100).
[^37]: [](#ftnt_ref37) Dembowski provides these variants in his edition (75n177; 88n643).
[^38]: [](#ftnt_ref38) “A iceu tens n’ert si bele femme / kar ele estoit sur tutes gemme” (vv.163-164 of T-C)
[^39]: [](#ftnt_ref39) In T-A, she is called *mossue * once: “N’iert merveille se iert moussue” (v. 664). In T-B, she is called *mossue * twice and *polhue * once: “& de blanc poilh tote mossue / Noire & polhue ert la poitrine … N’ert mervelhe s’ele ert mossue” (vv.590-591 & 607 of T-B). In T-C, she is called*mossue * three times: “e de blanc peil tote mossue / Noire e mossue ert la peitrine … Ne fu merveille s’ert mossue” (vv.652-653 & 676 of T-C). She is only called*mossue * once in copies T-D and T-E: “N’ert merveille s’ele ert mossue” (v.666 of T-D); “N’iert par merveille si ert molsue” (v.666 of T-E). And although I cannot personally confirm the full verse as it is written in T-L due to my lack of access to the British Library, Dembowski notes the presence of*mossue* as a variation present in this copy as well (88n641).
[^40]: [](#ftnt_ref40) On the issue of ‘clutter,’ Tufte argues, “‘Clutter’ in data graphics is evidence that your models don’t fit the data – and that you know it. You also know that your summary graphics cover up contrary data and depict dubious thresholds not present in the data set. Such cheats are obvious and easily detected, and damage your credibility” (Tufte 101). In traditional editions, ‘clutter’ is tucked away in the extensive paratextual notes — if such notes are included at all — that the interested reader must then decode in order to fully grasp both the source material and the editor’s interventions in order to craft well-founded arguments on the available textual data.
[^41]: [](#ftnt_ref41) Cerquiglini also mentions Jean Rychner’s *Le Lai de Lanval *(1958) and Willem Noomen and Nico Van den Boogaard’s* Nouveau Recueil complet des fabliaux* (1983).
[^42]: [](#ftnt_ref42) These copies have been given the labels A, B, C, D, E, L, F1, and F2. Alfred T. Baker is responsible for labeling the many versions and manuscript copies of the French Mary the Egyptian legend with their current sigla in his 1916 edition. Dembowski uses Baker’s system in his own 1977 edition, building on Baker’s labeling where appropriate. For example, T-F1 was unknown to Baker, and so, Dembowski is responsible for lettering the T fragments with superscript numbers. I follow Dembowski’s labels, and I provide more in-depth descriptions of each of the T copies in Appendix 1 of this dissertation.
[^43]: [](#ftnt_ref43) We do currently have several print editions of Version T of the Life of Mary the Egyptian, each selecting a different manuscript as their choice of base text. As mentioned above, Dembowski’s *La Vie de sainte Marie l’Égyptienne: Versions en ancien et en moyen français *(1977) opts for copy T-A as its base text; Michèle Cruz-Sáenz offers an edition of copy T-B in her* The Life of Saint Mary of Egypt: An Edition and Study of the Medieval French and Spanish Verse Redactions *(1979). Prior to these 1970s editions, Baker published his critical edition — which is a composite of several T manuscripts — beside an edited transcript of manuscript copy T-C in an issue of the* Revue des langues romanes*(1916), and Matthew Cooke published his edition — “très inexactement transcrit” according to Dembowski (16) — of T-C in 1852.
[^44]: [](#ftnt_ref44) Robertson’s article was written with the approval of Peter Dembowski who Robertson acknowledges from the outset, “I wish to thank Peter F. Dembowski for his critical reading of this article, and for his patient counsel throughout all my hagiographical researches” (“The Anglo-Norman Verse” 13).
[^45]: [](#ftnt_ref45) Cerquiglini demonstrates the difficulty of reconstructing variants from such a critical apparatus in *Éloge de la variante* (1989). Armed with an editor’s encoded notes as well as pencil and paper, “Le lecteur patient, et indocile, mal satisfait de l'unicité qu'on lui offre, en retire quelques fragments, des lambeaux, des éclats, mais non pas cet autre du texte que l'apparat critique a pour fonction secrète d'éparpiller sourdement” (106).
[^46]: [](#ftnt_ref46) Robertson makes this argument particularly in reference to the T corpus, but he notes that this criticism may validly be leveled against *any * edition of almost*any * text from the Old French canon: “For this work and for most others in the Old French canon, modern editors have chosen rather to present editions based on single manuscripts, emending these as little as possible. … The problem inherent in this approach (by no means unique to*St. Mary the Egyptian*) is that no one of the extant manuscripts adequately represents the poem. In all except A and C, large gaps caused by omissions or mutilations appear in the final pages. All of them, with the possible exception of L, show extensive interventions performed by the individual scribes, voluntarily or no. This factor visibly affects A and B as well as C — more so perhaps than their respective editions acknowledge” (“The Anglo-Norman Verse Life” 31). Similarly, Arthur Bahr calls the traditional practice of choosing only one manuscript as the base text for an edition an “ascetic” practice that limits our understanding of the miscellaneous (191).
[^47]: [](#ftnt_ref47) In Chapter 2 of this dissertation, I narrow my reader’s focus to consider the features of the two portraits of Mary the Egyptian, providing edited transcriptions of each T copy as well as English translations unique to each of these copies.
[^48]: [](#ftnt_ref48) Robinson — himself a digital editor of medieval manuscripts — cautions against this sort of work, “Making a real electronic scholarly edition is far, far harder than writing a book, and takes far, far longer. Anyone who has had anything to do with electronic editions will tell you this. … If this is what you want to do, here is what I will tell you. Sell the family dog. Lock the door to your study and don’t come out for twenty years” (“The Ends of Editing” 20).
[^49]: [](#ftnt_ref49) Bryant’s *The Fluid Text: A Theory of Revision and Editing for Book and Screen* (2002) provides a useful starting point for rethinking our approach to editing as one that should convey the fluidity of texts to the reader and not merely a polished final product: “Typically, textual scholars are content to showcase the clear reading text they have labored to produce, relegating the textual apparatus, which contains the evidence of textual fluidity, to a secondary position for readers to inspect, if they desire. Thus, learning about the text is optional, and this is (perhaps) acceptable, if all you want to do is read a single, fixed text. But in reading a fluid text, learning about the text (that is, its variants) is not optional. Not only must the reader read self-consciously but the editor must make the edition aware of itself, and readably so. The apparatus must be more visible, and enticing. It must teach readers how to read what they are reading” (122-123). Bryant’s own digital editing work is the Melville Electronic Library, which seeks to present the works of Melville to online users as products of long revision by many hands, Melville’s and others.
[^50]: [](#ftnt_ref50) As Andrew Prescott argues, insisting on the direct consultation of original manuscripts is highly impractical for most researchers, “Although digitized manuscripts promote a wider public appreciation of medieval manuscripts, they are nevertheless for de Hamel ultimately ‘rootless and untied to any place’. De Hamel’s insistence on consulting the original manuscript is, in the context of the celebrity manuscripts featured in his book, absurd, since virtually nobody can have any hope of handling any of the manuscripts de Hamel discusses. Every manuscript scholar will agree that it is hazardous to rely on digital images alone, but there are few scholars who could follow in de Hamel’s footsteps by obtaining permission to handle the Gospels of St Augustine, the Codex Amiatinus, and the Book of Kells. They have to use whatever digital surrogates are available” (40).
