---
title: "The Portraits (with Visualizations)"
format:
  html:
    page-layout: full
---

Here the T portraits are again laid out side by side but now with the addition of visual aids that make it easier to more immediately recognize the continuities and variances across each of the copies. Each color highlights specific features that are discussed extensively in Chapter 3 of this dissertation: the red blocks indicate where couplets are lacking from each copy; the yellow sections mark alterations in sequence; green highlights particularly unique verse construction or word choice; blue denotes the use of negation; and purple draws attention to mentions of color. These color-coded annotations draw on data visualization techniques to facilitate cross-copy close reading.

<div class="visualization-legend">
  <h3>Key</h3>
  <ul>
    <li><span class="legend-swatch empty-line"></span> Lacking verses</li>
    <li><span class="legend-swatch sequence-change"></span> Sequence changes</li>
    <li><span class="legend-swatch unique-verse"></span> Unique features</li>
    <li><span class="legend-swatch negation"></span> Negated phrasing</li>
    <li><span class="legend-swatch color-word"></span> Color imagery</li>
  </ul>
</div>

To read these passages in translation, hover over each column with your cursor.

::: {.column-page-outset}
::: {layout="[[20,20,20,20,20]]"}

::: {.portrait-column}
## T-A
<div class="text-container">
  <div class="default-text">
.....<br>
<span class="verse-line"><span class="line-number">157</span>De se biauté de se figure<br></span>
<span class="verse-line">Si com ele est en escriture<br></span>
<span class="verse-line">Vueil -i- peu dire le samblant<br></span>
<span class="verse-line">Anchois que je trespas avant<br></span>
<span class="verse-line">Car a cel tans en icel regne<br></span>
<span class="verse-line"><span class="line-number">162</span><span class="negation">Ne</span> vit <span class="negation">nus</span> hom plus bele feme<br></span>
<span class="verse-line"><span class="negation">Ne onc</span> contesse <span class="negation">ne</span> roine<br></span>
<span class="verse-line">Nen ot el front plus bele crine<br></span>
<span class="verse-line">Reondes avoit les oreilles<br></span>
<span class="verse-line">Mais <span class="color-word">blanches</span> erent a merveilles<br></span>
<span class="verse-line"><span class="line-number">167</span><span class="sequence-change">Les iex <span class="color-word">clers</span> & sosrians<br></span></span>
<span class="verse-line"><span class="sequence-change">les sorchix <span class="color-word">noir</span> & avenans<br></span></span>
<span class="verse-line">bouche petite par mesure<br></span>
<span class="verse-line">& <span class="unique-verse">le pié &</span> le regardeure<br></span>
<span class="verse-line">Le face tenrre & <span class="color-word">coloree<br></span></span>
<span class="verse-line"><span class="line-number">172</span><span class="color-word">Com le rose qui sempre est nee<br></span></span>
<div class="empty-line"></div>
<div class="empty-line"></div>
<span class="verse-line"><span class="negation">Ja</span> el nés <span class="negation">ne</span> el menton<br></span>
<span class="verse-line"><span class="folio-number">335vb</span><span class="negation">N'</span>aperceussiés mesfaichon<br></span>
<span class="verse-line">En som le col <span class="color-word">blanc com ermine<br></span></span>
<span class="verse-line">li undoit le <span class="color-word">bloie</span> crine<br></span>
<span class="verse-line"><span class="line-number">177</span>Les mameles de cele dame<br></span>
<span class="verse-line"><span class="negation">N'estoient menrres</span> d'une pome<br></span>
<span class="verse-line">Desous le goule en le poitrine<br></span>
<span class="verse-line">Ert <span class="color-word">blanche conme flor d'espine<br></span></span>
<span class="verse-line"><span class="color-word">blans bras</span> avoit & <span class="color-word">blances mains<br></span></span>
<span class="verse-line"><span class="line-number">182</span>Les dois reons grailles & plains<br></span>
<span class="verse-line">Gent cors avoit & bien mollé<br></span>
<span class="verse-line">Sous l'aissele lonc le costé<br></span>
<span class="verse-line"><span class="negation">El n'iert trop grant ne trop petite<br></span></span>
<span class="verse-line"><span class="negation">Ja</span> se faichon <span class="negation">n'</span>en iert escrite<br></span>
<span class="verse-line"><span class="line-number">187</span><span class="negation">Ja</span> le biauté de ceste dame<br></span>
<span class="verse-line"><span class="negation">Nen</span> iert escrite par <span class="negation">nul</span> home<br></span>
<span class="verse-line">Tant iert cortoise de parler<br></span>
<span class="verse-line"><span class="negation">Riens n'</span>i avoit que amender<br></span>
<span class="verse-line">A plaindre fait tel criaature<br></span>
<span class="verse-line"><span class="line-number">192</span>Quant del Creator <span class="negation">n'</span>avoit cure<br></span>
<span class="verse-line">El recevoit plusors presens<br></span>
<span class="verse-line">S'en acatoit bons vestemens<br></span>
<span class="verse-line">Bons dras avoit . & avenans<br></span>
<span class="verse-line">Por mix plaisir a ses amans<br></span>
<span class="verse-line"><span class="line-number">197</span>Ele <span class="negation">n'</span>avoit soing de dras de lainne<br></span>
<span class="verse-line">Au pior jor de le semainne<br></span>
<span class="verse-line">Bon bliaut avoit <span class="color-word">d'ostorin<br></span></span>
<span class="verse-line">& affubloit mantel d'ermin<br></span>
<span class="verse-line">Soullers <span class="color-word">bien pains</span> de cordovam<br></span>
<span class="verse-line"><span class="line-number">202</span>Cauchoit a tous les jors de l'an<br></span>
<span class="verse-line">Li citoien de le cité<br></span>
<span class="verse-line">L'amoient tout por se biauté<br></span>
<span class="verse-line">Li anchien home & li saige<br></span>
<span class="verse-line">disoient tout Dex quel damage<br></span>
<span class="verse-line"><span class="line-number">207</span>Com mar fu onc ceste dolante<br></span>
<span class="verse-line">Tant fait a plaindre se jovente<br></span>
<span class="verse-line">Tant mar fu onques le siue vie<br></span>
<span class="verse-line">Quant si est plainne de folie<br></span>
<span class="verse-line">Tout disoient par le cité<br></span>
<span class="verse-line"><span class="line-number">212</span>Qu'ele estoit de haut parenté<br></span>
<span class="verse-line">Car a tos respondoit raison<br></span>
<span class="verse-line"><span class="folio-number">336ra</span>& tant iert bele de fachon<br></span>
<span class="verse-line">ke li fix d'un empereor<br></span>
<span class="verse-line">Le peust prendre a grant honor<br></span>
.....<br>
<span class="verse-line"><span class="folio-number">338va</span>Tant ala par jor & par nuit<br></span>
<span class="verse-line">A faim & a soif & a dur lit<br></span>
<span class="verse-line">Que tant parfont fu el boscaige<br></span>
<span class="verse-line">Toute devint illuec salvaige<br></span>
<span class="verse-line">Mais ele <span class="negation">ne</span> s'oublioit <span class="negation">mie</span><br></span>
<span class="verse-line"><span class="line-number">618</span>De deprier sainte Marie<br></span>
<span class="verse-line">Sovent li menbroit de l'ymaige<br></span>
<span class="verse-line">Que ele avoit mis en ostaige<br></span>
<span class="verse-line">Si souller furent tout usé<br></span>
<span class="verse-line">& tout si drapel deschiré<br></span>
<span class="verse-line"><span class="line-number">623</span><span class="sequence-change">Li cors de li remaint tout nu<br></span></span>
<span class="verse-line"><span class="sequence-change"><span class="negation">N'</span>avoit drapel <span class="negation">ne</span> fust rompu<br></span></span>
<span class="verse-line">Li chars de li <span class="color-word">mua coulor<br></span></span>
<span class="verse-line">Qui ains iert <span class="color-word">blance conme flor<br></span></span>
<span class="verse-line">Que por yver que por esté<br></span>
<span class="verse-line"><span class="line-number">628</span>Tout li <span class="color-word">noircirent</span> li costé<br></span>
<span class="verse-line"><span class="color-word">Coulor mua se bloie crine<br></span></span>
<span class="verse-line"><span class="color-word">Blanche devint com une hermine<br></span></span>
<div class="empty-line"></div>
<div class="empty-line"></div>
<span class="verse-line">Le bouce li fu tenevie<br></span>
<span class="verse-line">& environ toute <span class="color-word">noirchie<br></span></span>
<span class="verse-line"><span class="line-number">633</span>& avoit tant <span class="color-word">noir</span> le menton<br></span>
<span class="verse-line"><span class="unique-verse">Conme s'il fust <span class="color-word">taint de carbon</span><br></span></span>
<span class="verse-line"><span class="unique-verse">Atenergé</span> furent li oel<br></span>
<span class="verse-line"><span class="negation">N'</span>i avoit ore <span class="negation">point d'</span>orguel<br></span>
<span class="verse-line">Se vos veissiés les oreilles<br></span>
<span class="verse-line"><span class="line-number">638</span>Molt par vos presist grans merveilles<br></span>
<span class="verse-line">Car <span class="color-word">noire</span> estoit & decrevee<br></span>
<span class="verse-line"><span class="unique-verse">Le <span class="color-word">blanche</span> char toute muee<br></span></span>
<span class="verse-line"><span class="color-word">Noire</span> & <span class="unique-verse">muee</span> ert le poitrine<br></span>
<span class="verse-line">A escorce samblant d'espine<br></span>
<span class="verse-line"><span class="line-number">643</span><span class="negation">N'</span>avoit <span class="negation">plus</span> char en ses traians<br></span>
<span class="verse-line"><span class="negation">Ne mais</span> com il a en uns gans<br></span>
<span class="verse-line">Les bras les mains & les lons dois<br></span>
<span class="verse-line">Avoit <span class="color-word">plus noirs que nule pois<br></span></span>
<span class="verse-line">Ongles avoit longes & grans<br></span>
<span class="verse-line"><span class="line-number">648</span>Ele les retailloit a ses dens<br></span>
<span class="verse-line">Li ventres li estoit caoit<br></span>
<span class="verse-line">Petit de despensse i metoit<br></span>
<span class="verse-line">Li pié li erent decrevé<br></span>
<span class="verse-line">En plusors lius erent navré<br></span>
<span class="verse-line"><span class="folio-number">338vb</span>Car ele <span class="negation">ne</span> se gardoit d'espine<br></span>
<span class="verse-line">Quant ele aloit par le gastine<br></span>
<span class="verse-line">Che li ert vis sien esciant<br></span>
<span class="verse-line">Que ele <span class="negation">n'</span>i failloit <span class="negation">nient</span><br></span>
<span class="verse-line">C'uns de ses pekiés li caoit<br></span>
<span class="verse-line"><span class="line-number">658</span>Quant une espine le pongnoit<br></span>
<span class="verse-line">Por chou estoit ele molt lie<br></span>
<span class="verse-line">Quant ele souffroit le hasquie<br></span>
<span class="verse-line"><span class="negation">N'est merveille</span> se iert <span class="color-word">noirchie<br></span></span>
<span class="verse-line">Car molt demenoit aspee vie<br></span>
<span class="verse-line"><span class="line-number">663</span>Plus de xl. ans ala nue<br></span>
<span class="verse-line"><span class="negation">N'iert merveille</span> se iert moussue<br></span>
<span class="verse-line">Povre despense avoit o li<br></span>
<span class="verse-line">Or ait Jhesus de li merchi<br></span>
<span class="verse-line">.ii. pains avoit <span class="negation">ne gaires grans<br></span></span>
<span class="verse-line"><span class="line-number">668</span>De chiaus vesqui par plusors ans<br></span>
<span class="verse-line">El premier an devinrrent dur<br></span>
<span class="verse-line">Com se fust pierre de mur<br></span>
<span class="verse-line">Cascun jor en usoit Marie<br></span>
<span class="verse-line">Mais che iert petite partie<br></span>
<span class="verse-line"><span class="line-number">673</span>Quant ele ot tot son pain usé<br></span>
<span class="verse-line">Puis esrachoit l'erbe del pré<br></span>
<span class="verse-line">Quant autre beste le mengoit<br></span>
<span class="verse-line"><span class="negation">de rien ne</span> se confortoit<br></span>
<span class="verse-line"><span class="unique-verse">As mains</span> buvoit l'iaue el ruissel<br></span>
<span class="verse-line"><span class="line-number">678</span>Quant ele <span class="negation">n'</span>avoit autre vaissel<br></span>
<span class="verse-line"><span class="negation">Ne</span> font a plaindre li pechié<br></span>
<span class="verse-line">Dont li cors fu si castié<br></span>
<span class="verse-line">D'erbe vesqui & de rachines<br></span>
<span class="verse-line">Xvii. ans. par les gastines<br></span>
<span class="verse-line"><span class="line-number">683</span>Puis fu .xxx. ans <span class="negation">onc ne</span> menga<br></span>
<span class="verse-line">Se angeles ne li aporta<br></span>
<span class="verse-line">Li Diables le an premier<br></span>
<span class="verse-line">Le soloit sovent essaier<br></span>
<span class="verse-line">Tout che li faisoit remembrer<br></span>
<span class="verse-line"><span class="line-number">688</span>Qu'ele soloit tos jors amer<br></span>
<span class="verse-line">Les bons mengiers & les biax lieus<br></span>
<span class="verse-line">Ou ele soloit faire les geus<br></span>
<span class="verse-line">Or fu ichi boneuree<br></span>
<span class="verse-line">Qu'ele de tout fu obliee<br></span>
<span class="verse-line"><span class="folio-number">339ra</span><span class="negation">Onques puis</span> en toute se vie<br></span>
<span class="verse-line"><span class="negation">Ne</span> li souvint <span class="negation">mais</span> de folie<br></span>
<span class="verse-line"><span class="negation">Ne ainc</span> en trestot le boscaige<br></span>
<span class="verse-line"><span class="negation">Ne</span> li vint <span class="negation">puis</span> beste salvaige<br></span>
<span class="verse-line"><span class="negation">Ne</span> autre vive creature<br></span>
<span class="verse-line"><span class="line-number">698</span>Par le gaut va toute seure<br></span>
<span class="verse-line">En plusors lius prist son ostel<br></span>
<span class="verse-line">Se vie ert tote esperitel<br></span>
.....<br>
  </div>
  <div class="hover-text">
.....<br>
<span class="verse-line"><span class="line-number">157</span>Of her beauty, of her figure<br></span>
<span class="verse-line">(as it is in the written source)<br></span>
<span class="verse-line">I want to say a little — how they appeared —<br></span>
<span class="verse-line">before I go too far.<br></span>
<span class="verse-line">For at that time in that realm,<br></span>
<span class="verse-line"><span class="line-number">162</span><span class="negation">no</span> man <span class="negation">ever</span> saw a more beautiful woman.<br></span>
<span class="verse-line"><span class="negation">Never</span> countess <span class="negation">nor</span> queen<br></span>
<span class="verse-line">had over her brow more beautiful hair.<br></span>
<span class="verse-line">She had round ears.<br></span>
<span class="verse-line">What's more, they were marvelously <span class="color-word">white</span>,[^1]<br></span>
<span class="verse-line"><span class="line-number">167</span><span class="sequence-change">her eyes <span class="color-word">bright</span> and smiling,<br></span></span>
<span class="verse-line"><span class="sequence-change">her eyebrows <span class="color-word">black</span> and becoming,<br></span></span>
<span class="verse-line">her small mouth well-proportioned,<br></span>
<span class="verse-line">and <span class="unique-verse">her foot and</span> her expression,[^2]<br></span>
<span class="verse-line">her face tender and <span class="color-word">blushing<br></span></span>
<span class="verse-line"><span class="line-number">172</span><span class="color-word">like the rose that has just bloomed.<br></span></span>
<div class="empty-line"></div>
<div class="empty-line"></div>
<span class="verse-line"><span class="negation">Indeed neither</span> on her nose <span class="negation">nor</span> on her chin<br></span>
<span class="verse-line"><span class="folio-number">335vb</span>would you notice <span class="negation">any</span> defect.<br></span>
<span class="verse-line">Above the neck that was as <span class="color-word">white as ermine</span>,<br></span>
<span class="verse-line">there flowed her <span class="color-word">blonde</span> hair.<br></span>
<span class="verse-line"><span class="line-number">177</span>The breasts of this lady<br></span>
<span class="verse-line">were <span class="negation">no smaller</span> than an apple.<br></span>
<span class="verse-line">Below her throat on her chest,<br></span>
<span class="verse-line">it was <span class="color-word">white like a hawthorn flower</span>.<br></span>
<span class="verse-line">She had <span class="color-word">white arms</span> and <span class="color-word">white hands</span>,<br></span>
<span class="verse-line"><span class="line-number">182</span>her fingers shapely, slender, and smooth.<br></span>
<span class="verse-line">She had a fine body and was well molded<br></span>
<span class="verse-line">from her underarm along her side.<br></span>
<span class="verse-line"><span class="negation">She was neither too big nor too small.<br></span></span>
<span class="verse-line">Her form could <span class="negation">never</span> be written down.<br></span>
<span class="verse-line"><span class="line-number">187</span>The beauty of this lady<br></span>
<span class="verse-line">could <span class="negation">never</span> be written down by <span class="negation">any</span> man.<br></span>
<span class="verse-line">She was so courteous of speech;<br></span>
<span class="verse-line">there was <span class="negation">nothing</span> to improve.<br></span>
<span class="verse-line">Such a creature makes one lament<br></span>
<span class="verse-line"><span class="line-number">192</span>when she <span class="negation">does not</span> care about the Creator.<br></span>
<span class="verse-line">She received many presents<br></span>
<span class="verse-line">and bought herself good garments.<br></span>
<span class="verse-line">She had good and fitting clothes<br></span>
<span class="verse-line">to better please her lovers.<br></span>
<span class="verse-line"><span class="line-number">197</span>She <span class="negation">did not</span> care for woollen cloth<br></span>
<span class="verse-line">on the worst day of the week.<br></span>
<span class="verse-line">She had a fine <span class="color-word">purple silk</span> bliaut<br></span>
<span class="verse-line">and adorned herself with an ermine mantle.<br></span>
<span class="verse-line"><span class="color-word">Well-painted</span> shoes of Cordovan leather<br></span>
<span class="verse-line"><span class="line-number">202</span>she wore all the days of the year.<br></span>
<span class="verse-line">The citizens of the city<br></span>
<span class="verse-line">loved her entirely for her beauty.<br></span>
<span class="verse-line">The aged men and the wise<br></span>
<span class="verse-line">would all say, "God, what a shame!<br></span>
<span class="verse-line"><span class="line-number">207</span>Oh alas evermore for this sufferer!<br></span>
<span class="verse-line">There is much to bemoan of her youth.<br></span>
<span class="verse-line">Oh alas evermore for her life<br></span>
<span class="verse-line">as it is so full of folly."<br></span>
<span class="verse-line">Everyone in the city would say<br></span>
<span class="verse-line"><span class="line-number">212</span>that she was of high parentage<br></span>
<span class="verse-line">for she answered all with reason<br></span>
<span class="verse-line"><span class="folio-number">336ra</span>and had such a beautiful form<br></span>
<span class="verse-line">that the son of an emperor<br></span>
<span class="verse-line">could have taken her with great honor.[^3]<br></span>
.....<br>
<span class="verse-line"><span class="folio-number">338va</span>She went so long by day and by night,<br></span>
<span class="verse-line">hungry and thirsty and on hard beds.<br></span>
<span class="verse-line">There she was so deep in the wood<br></span>
<span class="verse-line">that she became entirely wild,<br></span>
<span class="verse-line">but she <span class="negation">never</span> forgot<br></span>
<span class="verse-line"><span class="line-number">618</span>to pray to saint Mary.<br></span>
<span class="verse-line">Often, she remembered the image,<br></span>
<span class="verse-line">which she had taken as a guarantor.<br></span>
<span class="verse-line">Her shoes were worn out,<br></span>
<span class="verse-line">and her clothes were all torn up.<br></span>
<span class="verse-line"><span class="line-number">623</span><span class="sequence-change">Her body was left totally naked.<br></span></span>
<span class="verse-line"><span class="sequence-change">She <span class="negation">did not</span> have clothing that was <span class="negation">not</span> in tatters.<br></span></span>
<span class="verse-line">Her own flesh <span class="color-word">changed color</span>,<br></span>
<span class="verse-line">that which before was <span class="color-word">white like a flower</span>.<br></span>
<span class="verse-line">From winter as from summer,<br></span>
<span class="verse-line"><span class="line-number">628</span>her sides <span class="color-word">blackened</span> entirely.<br></span>
<span class="verse-line"><span class="color-word">The color of her blonde hair changed.<br></span></span>
<span class="verse-line"><span class="color-word">It turned white like an ermine</span>.<br></span>
<div class="empty-line"></div>
<div class="empty-line"></div>
<span class="verse-line">Her mouth was thinned,<br></span>
<span class="verse-line">and all around it <span class="color-word">blackened</span>,<br></span>
<span class="verse-line"><span class="line-number">633</span>and her chin was as <span class="color-word">black<br></span></span>
<span class="verse-line"><span class="unique-verse">as if it were <span class="color-word">tainted with charcoal</span>.<br></span></span>
<span class="verse-line"><span class="unique-verse">Thinned</span> were her eyes.<br></span>
<span class="verse-line">There was <span class="negation">not a shred</span> of pride there now.<br></span>
<span class="verse-line">If you saw her ears,<br></span>
<span class="verse-line"><span class="line-number">638</span>it would appear to you a great marvel<br></span>
<span class="verse-line">for they were <span class="color-word">black</span> and cracked.[^4]<br></span>
<span class="verse-line"><span class="unique-verse">Her <span class="color-word">white</span> flesh changed entirely<br></span></span>
<span class="verse-line"><span class="color-word">Black</span> and <span class="unique-verse">changed</span> was her chest.<br></span>
<span class="verse-line">It seemed like thorny bark.<br></span>
<span class="verse-line"><span class="line-number">643</span>There was <span class="negation">no more</span> flesh in her breasts,<br></span>
<span class="verse-line"><span class="negation">no more</span> than there is in a glove.<br></span>
<span class="verse-line">Her arms, her hands, and her long fingers<br></span>
<span class="verse-line">were <span class="color-word">blacker than any pitch.<br></span></span>
<span class="verse-line">She had long and large nails.<br></span>
<span class="verse-line"><span class="line-number">648</span>She reshaped them with her teeth.<br></span>
<span class="verse-line">Her stomach was sunken.<br></span>
<span class="verse-line">She put few provisions in there.<br></span>
<span class="verse-line">Her feet were split.[^4]<br></span>
<span class="verse-line">In many places, they were wounded<br></span>
<span class="verse-line"><span class="folio-number">338vb</span>for she did <span class="negation">not</span> protect herself from thorns<br></span>
<span class="verse-line">as she went through the wilderness.<br></span>
<span class="verse-line">It seemed to her, in her mind,<br></span>
<span class="verse-line">she was <span class="negation">not</span> wrong about this <span class="negation">at all</span>,<br></span>
<span class="verse-line">that one of her sins fell away<br></span>
<span class="verse-line"><span class="line-number">658</span>when a thorn pricked her.<br></span>
<span class="verse-line">For this, she was so pleased<br></span>
<span class="verse-line">as she suffered hardship.<br></span>
<span class="verse-line"><span class="negation">It was no marvel</span> that she was <span class="color-word">blackened<br></span></span>
<span class="verse-line">for she led such a severe life.<br></span>
<span class="verse-line"><span class="line-number">663</span>For more than forty years, she went about nude:<br></span>
<span class="verse-line"><span class="negation">it was no marvel</span> she was woolly.<br></span>
<span class="verse-line">She had poor provisions with her.<br></span>
<span class="verse-line">Now may Jesus have mercy on her.<br></span>
<span class="verse-line">She had two loaves of <span class="negation">no great size</span>.<br></span>
<span class="verse-line"><span class="line-number">668</span>On these, she lived for many years.<br></span>
<span class="verse-line">In the first year, they became hard<br></span>
<span class="verse-line">as though they were building stones.<br></span>
<span class="verse-line">Each day, Mary ate some,<br></span>
<span class="verse-line">but this was a small portion.<br></span>
<span class="verse-line"><span class="line-number">673</span>As soon as she had eaten up all her bread,<br></span>
<span class="verse-line">then she plucked the grass of the field.<br></span>
<span class="verse-line">Like other beasts she ate it.<br></span>
<span class="verse-line">She sought <span class="negation">no</span> other comfort.<br></span>
<span class="verse-line"><span class="unique-verse">With her hands,</span> she drank the water from the stream<br></span>
<span class="verse-line"><span class="line-number">678</span>as she had <span class="negation">no</span> other vessel.<br></span>
<span class="verse-line"><span class="negation">Not</span> to be lamented are the sins<br></span>
<span class="verse-line">that chastised the body so.<br></span>
<span class="verse-line">On grass she lived and on roots<br></span>
<span class="verse-line">for seventeen years in the wilderness.<br></span>
<span class="verse-line"><span class="line-number">683</span>Then for thirty years, she ate <span class="negation">nothing<br></span></span>
<span class="verse-line">unless an angel brought it to her.<br></span>
<span class="verse-line">In the first year, the Devil<br></span>
<span class="verse-line">often used to tempt her,<br></span>
<span class="verse-line">making her remember all<br></span>
<span class="verse-line"><span class="line-number">688</span>that she used to always love:<br></span>
<span class="verse-line">the good foods and the fine places<br></span>
<span class="verse-line">where she was used to playing games.<br></span>
<span class="verse-line">Now, she felt so blessed<br></span>
<span class="verse-line">that she had forgotten all.<br></span>
<span class="verse-line"><span class="folio-number">339ra</span><span class="negation">Never more</span> in all her life<br></span>
<span class="verse-line"><span class="negation">did</span> she think <span class="negation">ever</span> of folly.<br></span>
<span class="verse-line"><span class="negation">Never</span> in all the wood<br></span>
<span class="verse-line"><span class="negation">did any</span> wild beast come to her <span class="negation">thereafter<br></span></span>
<span class="verse-line"><span class="negation">nor any</span> other living creature.<br></span>
<span class="verse-line"><span class="line-number">698</span>Through the forest, she goes totally assured.<br></span>
<span class="verse-line">In many places, she took shelter.<br></span>
<span class="verse-line">Her life was entirely spiritual.<br></span>
.....<br>
  </div>
</div>
:::

::: {.portrait-column}
## T-B
<div class="text-container">
  <div class="default-text">
.....<br>
<span class="verse-line"><span class="line-number">149</span>de sa biaté de sa figure.<br></span>
<span class="verse-line">si com ele est en l'escriture<br></span>
<span class="verse-line">Vos vuel dire de se senblant.<br></span>
<span class="verse-line">ançois que je trespas avant<br></span>
<span class="verse-line">Ans en cest mont ne en cest renne.<br></span>
<span class="verse-line"><span class="line-number">154</span><span class="negation">Ne</span> vit <span class="negation">nuz</span> hom plus bele femme<br></span>
<span class="verse-line"><span class="negation">Onques</span> duçoise <span class="negation">ne</span> roine.<br></span>
<span class="verse-line"><span class="negation">nen</span> ot el cief plus bele crine<br></span>
<span class="verse-line">Reondes avoit les orelhes.<br></span>
<span class="verse-line">Mais <span class="color-word">blanches</span> erent a mervelhes<br></span>
<span class="verse-line"><span class="line-number">159</span>Les sorciz <span class="color-word">noirs</span> & avenanz.<br></span>
<span class="verse-line">& les olz <span class="color-word">clers</span> & sorrianz<br></span>
<span class="verse-line"><span class="sequence-change">La face tenre en <span class="unique-verse">celee.ee.</span><br></span></span>
<span class="verse-line"><span class="sequence-change"><span class="color-word">Com la rose ki or est nee</span><br></span></span>
<span class="verse-line"><span class="unique-verse">Les dens ot <span class="color-word">blans</span> & bien menuz.<br></span></span>
<span class="verse-line"><span class="line-number">164</span><span class="unique-verse">plus bele boce <span class="negation">ne</span> vit <span class="negation">nuz</span><br></span></span>
<span class="verse-line"><span class="sequence-change">mut avoit piue regardure.<br></span></span>
<span class="verse-line"><span class="sequence-change">& <span class="color-word">cler</span> le vis & le faiture<br></span></span>
<span class="verse-line"><span class="sequence-change">Je cui el neis ne el menton.<br></span></span>
<span class="verse-line"><span class="sequence-change"><span class="negation">n'</span>avoit <span class="negation">un point de</span> mesfaçon<br></span></span>
<div class="empty-line"></div>
<div class="empty-line"></div>
<span class="verse-line"><span class="line-number">169</span><span class="sequence-change">Soz la boce sor le poitrine.<br></span></span>
<span class="verse-line"><span class="sequence-change">ert <span class="color-word">plus blanche ke flors d'espine</span><br></span></span>
<span class="verse-line"><span class="sequence-change">& si avoit beles mameles.<br></span></span>
<span class="verse-line"><span class="sequence-change">mut bien seans petiz & beles<br></span></span>
<span class="verse-line"><span class="sequence-change"><span class="color-word">blans bras</span> avoit & <span class="color-word">blanches mains</span>.<br></span></span>
<span class="verse-line"><span class="line-number">174</span><span class="sequence-change">& les dois grailes lons & plains<br></span></span>
<span class="verse-line"><span class="folio-number">110v</span><span class="sequence-change">Gent cors avoit & bien moleit.<br></span></span>
<span class="verse-line"><span class="sequence-change">desoz l'aisselle & le costeit<br></span></span>
<span class="verse-line"><span class="sequence-change">tant ert cortoise de parler<br></span></span>
<span class="verse-line"><span class="sequence-change"><span class="negation">n'</span>i avoit <span class="negation">rien</span> ke amendeir<br></span></span>
<span class="verse-line"><span class="line-number">179</span><span class="sequence-change"><span class="negation">N'ert pas trop grant ne trop petite</span>.<br></span></span>
<span class="verse-line"><span class="sequence-change"><span class="negation">Ja</span> se façons <span class="negation">n'</span>en iert descrite<br></span></span>
<span class="verse-line"><span class="sequence-change">Ja le beaté de ceste <span class="unique-verse">toise</span>.<br></span></span>
<span class="verse-line"><span class="sequence-change"><span class="negation">N'</span>iert descrite se <span class="negation">n'</span>i at <span class="unique-verse">proise</span><br></span></span>
<span class="verse-line">a plendre fait tel creature.<br></span>
<span class="verse-line"><span class="line-number">184</span>cant de se Creator n'at cure<br></span>
<span class="verse-line">ele recivoit grans presenz.<br></span>
<span class="verse-line">s'en achatoit chier garnimenz<br></span>
<span class="verse-line">bon dras avoit & avenanz.<br></span>
<span class="verse-line">por miez plaissir a ses amanz<br></span>
<span class="verse-line"><span class="line-number">189</span>& <span class="negation">ne</span> <span class="unique-verse">vestoit</span> <span class="negation">pas</span> dras de laine.<br></span>
<span class="verse-line">Le peior jor de la samaine<br></span>
<span class="verse-line">Vestoit bon bliat <span class="color-word">d'osterlin</span>.<br></span>
<span class="verse-line">& affiebloit mantel d'ermin<br></span>
<span class="verse-line">Solers <span class="color-word">biens poins</span> de corduan.<br></span>
<span class="verse-line"><span class="line-number">194</span>chaçoit par toz les jors de l'an<br></span>
<span class="verse-line">Li citain de la citeit.<br></span>
<span class="verse-line">L'amoient tuit por sa bialteit<br></span>
<span class="verse-line">& li viel home & li sage.<br></span>
<span class="verse-line">disoient tuit Deus kel damage<br></span>
<span class="verse-line"><span class="line-number">199</span>tant mar fut iceste dolente.<br></span>
<span class="verse-line">mut fait a plendre sa jovente<br></span>
<span class="verse-line">mar fut onques la sue vie.<br></span>
<span class="verse-line">que tant est plane de folie<br></span>
<div class="empty-line"></div>
<div class="empty-line"></div>
<span class="verse-line">car a toz respondoit raison.<br></span>
<span class="verse-line"><span class="line-number">204</span>tant ert de bele afaitison<br></span>
<span class="verse-line">Que li fiz d'un empereor.<br></span>
<span class="verse-line">la poist prendre par honor<br></span>
.....<br>
<span class="verse-line"><span class="line-number">567</span>tant errat <span class="unique-verse">par nuiz & par dis.</span><br></span>
<span class="verse-line">a fain a soit & a durs lis<br></span>
<span class="verse-line">Que tant i fut en le boscage.<br></span>
<span class="verse-line">qu'ele devint tote salvage<br></span>
<div class="empty-line"></div>
<div class="empty-line"></div>
<div class="empty-line"></div>
<div class="empty-line"></div>
<span class="verse-line">Senpres furent si drap useit.<br></span>
<span class="verse-line"><span class="line-number">572</span>& soi soler tot depaneit<br></span>
<div class="empty-line"></div>
<div class="empty-line"></div>
<span class="verse-line"><span class="sequence-change">tant par l'iver tant par l'esteit.<br></span></span>
<span class="verse-line"><span class="sequence-change">tot li <span class="color-word">noicirent</span> li costeit<br></span></span>
<span class="verse-line"><span class="sequence-change">Se tenre car <span class="color-word">muat color</span>.<br></span></span>
<span class="verse-line"><span class="sequence-change">qui ans eret <span class="color-word">blance cum florr</span><br></span></span>
<span class="verse-line"><span class="line-number">577</span><span class="color-word">Color muat sa bele crine.<br></span></span>
<span class="verse-line"><span class="color-word">blance devint conme l'ermine<br></span></span>
<span class="verse-line">desoz la face eret <span class="color-word">brulee</span>.<br></span>
<span class="verse-line">del soloilh & de la jalee<br></span>
<span class="verse-line"><span class="folio-number">114r</span>La boche li ert atenevie.<br></span>
<span class="verse-line"><span class="line-number">582</span>& environ la cars <span class="color-word">norcie</span><br></span>
<span class="verse-line">& tant avoit <span class="color-word">noir</span> le menton.<br></span>
<span class="verse-line"><span class="color-word">com se fuist li chies d'un tison<br></span></span>
<span class="verse-line"><span class="unique-verse">atenevit</span> erent li oilh.<br></span>
<span class="verse-line">or <span class="negation">n'</span>i avoit <span class="negation">il point d'</span>orgoilh<br></span>
<span class="verse-line"><span class="line-number">587</span>se vos en veissiez l'orelhe<br></span>
<span class="verse-line">mut vos venist a grant mervelhe<br></span>
<span class="verse-line">car maigre ert mut & degregue.<br></span>
<span class="verse-line">& de <span class="color-word">blanc</span> poilh tote mossue<br></span>
<span class="verse-line"><span class="color-word">Noire</span> & polhue ert la poitrine.<br></span>
<span class="verse-line"><span class="line-number">592</span>sembloit scorce de <span class="color-word">noire</span> spine<br></span>
<div class="empty-line"></div>
<div class="empty-line"></div>
<div class="empty-line"></div>
<div class="empty-line"></div>
<span class="verse-line"><span class="sequence-change">Li ventres li ert toz caoiz.<br></span></span>
<span class="verse-line"><span class="sequence-change"><span class="negation">nient ne</span> manjoit & si ert droiz<br></span></span>
<span class="verse-line"><span class="sequence-change">Les ongles avoit ele granz.<br></span></span>
<span class="verse-line"><span class="sequence-change">ele les retalloit az danz<br></span></span>
<span class="verse-line"><span class="line-number">597</span>Les piez maigres & decrevez.<br></span>
<span class="verse-line">& par plusors lius mut navrez<br></span>
<span class="verse-line">car ele <span class="negation">nes</span> gardoit d'espine.<br></span>
<span class="verse-line">cant el aloit par le gastine<br></span>
<span class="verse-line">Ans li ert vis son escient.<br></span>
<span class="verse-line"><span class="line-number">602</span>& ele <span class="negation">ni</span> faloit <span class="negation">nient<br></span></span>
<span class="verse-line"><span class="sequence-change">cant une spine li poindoit.<br></span></span>
<span class="verse-line"><span class="sequence-change">uns des pechiez jus li chaoit<br></span></span>
<div class="empty-line"></div>
<div class="empty-line"></div>
<div class="empty-line"></div>
<div class="empty-line"></div>
<span class="verse-line"><span class="sequence-change"><span class="negation">Ne</span> fat a plaindre li pechiez.<br></span></span>
<span class="verse-line"><span class="sequence-change">dont li cors est si castoiez<br></span></span>
<span class="verse-line"><span class="line-number">607</span><span class="sequence-change"><span class="negation">N'ert mervelhe</span> s'ele ert mossue.<br></span></span>
<span class="verse-line"><span class="sequence-change">karante ans alat tote nue<br></span></span>
<div class="empty-line"></div>
<div class="empty-line"></div>
<span class="verse-line">Dous pains avoit <span class="negation">ne gaire granz</span>.<br></span>
<span class="verse-line">de ces viscat par plusors anz<br></span>
<span class="verse-line">Le premier an devinrent dur.<br></span>
<span class="verse-line"><span class="line-number">612</span>com ce fust piere de mur<br></span>
<span class="verse-line">cascun jor en usoit Marie.<br></span>
<span class="verse-line">mais ce astoit mut <span class="unique-verse">povre vie</span><br></span>
<span class="verse-line">cant ele ot toz ses pains useiz.<br></span>
<span class="verse-line">puis esragat herbes des prez<br></span>
<span class="verse-line"><span class="line-number">617</span>com altre beste le manjoit.<br></span>
<span class="verse-line"><span class="negation">de rien ne</span> se desconfortoit<br></span>
<span class="verse-line">Adés bevoit ens el ruisel.<br></span>
<span class="verse-line">ele <span class="negation">n'</span>avoit altre vaissel<br></span>
<span class="verse-line">d'erbes vivoit & de racines.<br></span>
<span class="verse-line"><span class="line-number">622</span>dis & uit ans par la gastines<br></span>
<span class="verse-line">Puis fut vint ans <span class="negation">que ne</span> manja.<br></span>
<span class="verse-line">sel angeles Deu ne li porta<br></span>
<span class="verse-line">Diables li vint devant premier.<br></span>
<span class="verse-line">qui mut le soloit <span class="unique-verse">anoier</span><br></span>
<span class="verse-line"><span class="line-number">627</span>qui li faissoit ramembrer.<br></span>
<span class="verse-line">kanque soloit jadis ameir<br></span>
<span class="verse-line">Les biaz deliz & les biaz <span class="unique-verse">giuz.</span><br></span>
<span class="verse-line">u soloit faire ses <span class="unique-verse">deduiz</span><br></span>
<span class="verse-line">Mut fut bieneuree.<br></span>
<span class="verse-line"><span class="line-number">632</span>ki de tot ce fut obliee<br></span>
<span class="verse-line"><span class="negation">unques puis</span> en la sue vie.<br></span>
<span class="verse-line"><span class="negation">Ne</span> li menbra jor de folie<br></span>
<span class="verse-line">Marie vat par le boscage.<br></span>
<span class="verse-line"><span class="negation">Onques n'</span>i vit beste salvage<br></span>
<span class="verse-line"><span class="line-number">637</span><span class="negation">Ne nule</span> vive creature.<br></span>
<span class="verse-line">par le forest vat bien segure<br></span>
<span class="verse-line"><span class="folio-number">114v</span>en plusors lius fut ses ostaz.<br></span>
<span class="verse-line">sa vie astoit spirituaz<br></span>
.....<br>
  </div>
  <div class="hover-text">
.....<br>
<span class="verse-line"><span class="line-number">149</span>Of her beauty, of her figure<br></span>
<span class="verse-line">(as it is in the written source)<br></span>
<span class="verse-line">and about her appearance, I want to tell you<br></span>
<span class="verse-line">before I go too far.<br></span>
<span class="verse-line">In this world or in this realm,<br></span>
<span class="verse-line"><span class="line-number">154</span><span class="negation">no</span> man <span class="negation">ever</span> saw a more beautiful woman.<br></span>
<span class="verse-line"><span class="negation">Never did</span> a duchess <span class="negation">or</span> a queen<br></span>
<span class="verse-line"><span class="negation">have</span> on her head more beautiful hair.<br></span>
<span class="verse-line">She had round ears.<br></span>
<span class="verse-line">What's more, they were marvelously <span class="color-word">white</span>,[^1]<br></span>
<span class="verse-line"><span class="line-number">159</span>her eyebrows <span class="color-word">black</span> and becoming,<br></span>
<span class="verse-line">and her eyes <span class="color-word">bright</span> and smiling,<br></span>
<span class="verse-line"><span class="sequence-change">her face tender and <span class="unique-verse">covered</span><br></span></span>
<span class="verse-line"><span class="sequence-change"><span class="color-word">like the rose that has only just bloomed</span>.<br></span></span>
<span class="verse-line"><span class="unique-verse">Her teeth were <span class="color-word">white</span> and quite small.<br></span></span>
<span class="verse-line"><span class="line-number">164</span><span class="unique-verse">A more beautiful mouth <span class="negation">no one ever</span> saw.<br></span></span>
<span class="verse-line"><span class="sequence-change">She had such a pleasing expression,[^2]<br></span></span>
<span class="verse-line"><span class="sequence-change">and her look and her features <span class="color-word">bright</span>.<br></span></span>
<span class="verse-line"><span class="sequence-change">I believe on her nose and on her chin<br></span></span>
<span class="verse-line"><span class="sequence-change">there was <span class="negation">no</span> defect <span class="negation">at all</span>.<br></span></span>
<div class="empty-line"></div>
<div class="empty-line"></div>
<span class="verse-line"><span class="line-number">169</span><span class="sequence-change">Below her mouth on her chest,<br></span></span>
<span class="verse-line"><span class="sequence-change">it was <span class="color-word">whiter than a hawthorn flower</span>,<br></span></span>
<span class="verse-line"><span class="sequence-change">and of course she had beautiful breasts,<br></span></span>
<span class="verse-line"><span class="sequence-change">very well set, small, and beautiful.<br></span></span>
<span class="verse-line"><span class="sequence-change">She had <span class="color-word">white arms</span> and <span class="color-word">white hands</span>,<br></span></span>
<span class="verse-line"><span class="line-number">174</span><span class="sequence-change">and her fingers slender, long, and smooth.<br></span></span>
<span class="verse-line"><span class="folio-number">110v</span><span class="sequence-change">She had a fine body and was well molded<br></span></span>
<span class="verse-line"><span class="sequence-change">beneath her underarm and her side.<br></span></span>
<span class="verse-line"><span class="sequence-change">She was so courteous of speech;<br></span></span>
<span class="verse-line"><span class="sequence-change">there was <span class="negation">nothing</span> to improve.<br></span></span>
<span class="verse-line"><span class="line-number">179</span><span class="sequence-change"><span class="negation">She was neither too big nor too small.</span><br></span></span>
<span class="verse-line"><span class="sequence-change">Her frame could <span class="negation">never</span> be described.<br></span></span>
<span class="verse-line"><span class="sequence-change">The beauty of these <span class="unique-verse">proportions</span>[^5]<br></span></span>
<span class="verse-line"><span class="sequence-change">could <span class="negation">not</span> be described <span class="negation">without</span> <span class="unique-verse">praise</span>.<br></span></span>
<span class="verse-line">Such a creature makes one lament<br></span>
<span class="verse-line"><span class="line-number">184</span>when she does not care about her Creator.<br></span>
<span class="verse-line">She received great presents<br></span>
<span class="verse-line">and bought herself expensive garments.<br></span>
<span class="verse-line">She had good and fitting clothes<br></span>
<span class="verse-line">to better please her lovers,<br></span>
<span class="verse-line"><span class="line-number">189</span>and she <span class="negation">did not</span> <span class="unique-verse">wear</span> woollen cloth<br></span>
<span class="verse-line">on the worst day of the week.<br></span>
<span class="verse-line">She wore a fine <span class="color-word">purple silk</span> bliaut<br></span>
<span class="verse-line">and adorned herself with an ermine mantle.<br></span>
<span class="verse-line"><span class="color-word">Well-painted</span> shoes of Cordovan leather<br></span>
<span class="verse-line"><span class="line-number">194</span>she wore all the days of the year.<br></span>
<span class="verse-line">The citizens of the city<br></span>
<span class="verse-line">loved her entirely for her beauty,<br></span>
<span class="verse-line">and the old men and the wise<br></span>
<span class="verse-line">would all say, "God, what a shame!<br></span>
<span class="verse-line"><span class="line-number">199</span>Oh alas for this sufferer!<br></span>
<span class="verse-line">There is much to bemoan of her youth.<br></span>
<span class="verse-line">Alas evermore for her life,<br></span>
<span class="verse-line">which is so full of folly."<br></span>
<div class="empty-line"></div>
<div class="empty-line"></div>
<span class="verse-line">As she answered all with reason<br></span>
<span class="verse-line"><span class="line-number">204</span>and had such a beautiful frame,<br></span>
<span class="verse-line">that the son of an emperor<br></span>
<span class="verse-line">could have taken her with honor.[^3]<br></span>
.....<br>
<span class="verse-line"><span class="line-number">567</span>She roamed so long <span class="unique-verse">by night and by day</span>,<br></span>
<span class="verse-line">hungry, thirsty, and on hard beds.<br></span>
<span class="verse-line">There she was in the wood so long<br></span>
<span class="verse-line">that she became entirely wild.<br></span>
<div class="empty-line"></div>
<div class="empty-line"></div>
<div class="empty-line"></div>
<div class="empty-line"></div>
<span class="verse-line">Soon, her clothes were worn out,<br></span>
<span class="verse-line"><span class="line-number">572</span>and soon, her soles were torn up.<br></span>
<div class="empty-line"></div>
<div class="empty-line"></div>
<span class="verse-line"><span class="sequence-change">As much from winter as from summer,<br></span></span>
<span class="verse-line"><span class="sequence-change">her sides <span class="color-word">blackened</span> entirely.<br></span></span>
<span class="verse-line"><span class="sequence-change">Her tender flesh <span class="color-word">changed color</span>,<br></span></span>
<span class="verse-line"><span class="sequence-change">which before was <span class="color-word">white like a flower</span>.<br></span></span>
<span class="verse-line"><span class="line-number">577</span><span class="color-word">The color of her beautiful hair changed.<br></span></span>
<span class="verse-line"><span class="color-word">It turned white like the ermine.<br></span></span>
<span class="verse-line">Under that, her face was <span class="color-word">burned<br></span></span>
<span class="verse-line">from the sun and from the frost.<br></span>
<span class="verse-line"><span class="folio-number">114r</span>Her mouth was thinned,<br></span>
<span class="verse-line"><span class="line-number">582</span>and her flesh around it <span class="color-word">blackened,<br></span></span>
<span class="verse-line">and her chin was so <span class="color-word">black<br></span></span>
<span class="verse-line"><span class="color-word">as if it were the head of a firebrand.<br></span></span>
<span class="verse-line"><span class="unique-verse">Thinned</span> were her eyes.<br></span>
<span class="verse-line">There was <span class="negation">not a shred</span> of pride there now.<br></span>
<span class="verse-line"><span class="line-number">587</span>If you saw her ears,<br></span>
<span class="verse-line">it would occur to you a great marvel<br></span>
<span class="verse-line">for they were so skinny and deteriorated[^4]<br></span>
<span class="verse-line">and all woolly with <span class="color-word">white</span> hairs.<br></span>
<span class="verse-line"><span class="color-word">Black</span> and hairy was her chest.<br></span>
<span class="verse-line"><span class="line-number">592</span>It seemed like <span class="color-word">black</span> thorny bark.<br></span>
<div class="empty-line"></div>
<div class="empty-line"></div>
<div class="empty-line"></div>
<div class="empty-line"></div>
<span class="verse-line"><span class="sequence-change">Her stomach was all sunken.<br></span></span>
<span class="verse-line"><span class="sequence-change">She ate <span class="negation">nothing</span> and so that was right.<br></span></span>
<span class="verse-line"><span class="sequence-change">She had large nails.<br></span></span>
<span class="verse-line"><span class="sequence-change">She reshaped them with her teeth.<br></span></span>
<span class="verse-line"><span class="line-number">597</span>Her feet were skinny and split,[^4]<br></span>
<span class="verse-line">and, in many places, were deeply wounded<br></span>
<span class="verse-line">for she <span class="negation">did not</span> protect them from thorns<br></span>
<span class="verse-line">as she went through the wilderness.<br></span>
<span class="verse-line">So it seemed to her, in her mind,<br></span>
<span class="verse-line"><span class="line-number">602</span>and she was <span class="negation">not</span> wrong about this <span class="negation">at all</span>,<br></span>
<span class="verse-line"><span class="sequence-change">as a thorn pricked her,<br></span></span>
<span class="verse-line"><span class="sequence-change">one of her sins fell down from her.<br></span></span>
<div class="empty-line"></div>
<div class="empty-line"></div>
<div class="empty-line"></div>
<div class="empty-line"></div>
<span class="verse-line"><span class="sequence-change">She <span class="negation">does not</span> bemoan her sins<br></span></span>
<span class="verse-line"><span class="sequence-change">as her body is so chastised.<br></span></span>
<span class="verse-line"><span class="line-number">607</span><span class="sequence-change"><span class="negation">It was no marvel</span> that she was woolly;<br></span></span>
<span class="verse-line"><span class="sequence-change">for forty years, she went totally nude.<br></span></span>
<div class="empty-line"></div>
<div class="empty-line"></div>
<span class="verse-line">She had two loaves of <span class="negation">no great size</span>.<br></span>
<span class="verse-line">On these, she lived for many years.<br></span>
<span class="verse-line">The first year they became hard<br></span>
<span class="verse-line"><span class="line-number">612</span>as though they were building stone.<br></span>
<span class="verse-line">Every day, Mary ate some,<br></span>
<span class="verse-line">but this was a very <span class="unique-verse">poor life</span>.<br></span>
<span class="verse-line">As soon as she had eaten up all her bread,<br></span>
<span class="verse-line">then she plucked the grasses of the fields[^6]<br></span>
<span class="verse-line"><span class="line-number">617</span>Like other beasts, she ate them.<br></span>
<span class="verse-line"><span class="negation">None</span> of this bothered her.<br></span>
<span class="verse-line">From then on, she drank from the stream.<br></span>
<span class="verse-line">She had <span class="negation">no</span> other vessel.<br></span>
<span class="verse-line">On grasses she lived and on roots<br></span> 
<span class="verse-line"><span class="line-number">622</span>for eighteen years in the wilderness.<br></span>
<span class="verse-line">Then for twenty years, she <span class="negation">only</span> ate<br></span>
<span class="verse-line">what the angel of God brought to her.<br></span>
<span class="verse-line">The Devil came before her first.<br></span>
<span class="verse-line">He used to <span class="unique-verse">annoy</span> her so much,<br></span>
<span class="verse-line"><span class="line-number">627</span>making her remember<br></span>
<span class="verse-line">whatever she once used to love:<br></span>
<span class="verse-line">the fine delights and the fine <span class="unique-verse">games</span><br></span>
<span class="verse-line">in which she used to take <span class="unique-verse">pleasure</span>.<br></span>
<span class="verse-line">She felt so blessed<br></span>
<span class="verse-line"><span class="line-number">632</span>when she had forgotten all of this.<br></span>
<span class="verse-line"><span class="negation">Never more</span> in her life<br></span>
<span class="verse-line"><span class="negation">did</span> she remember a day of folly.<br></span>
<span class="verse-line">Mary goes through the wood.<br></span>
<span class="verse-line"><span class="negation">Never</span> did she see a wild beast<br></span>
<span class="verse-line"><span class="line-number">637</span><span class="negation">nor any</span> living creature.<br></span>
<span class="verse-line">Through the forest, she goes in all security.<br></span>
<span class="verse-line"><span class="folio-number">114v</span>In many places, she was sheltered.<br></span>
<span class="verse-line">Her life was spiritual.<br></span>
.....<br>
  </div>
</div>
:::

::: {.portrait-column}
## T-C
<div class="text-container">
  <div class="default-text">
.....<br>
<span class="verse-line"><span class="line-number">159</span>De sa beauté de sa figure<br></span>
<span class="verse-line">Si cum il est en escripture .<br></span>
<span class="verse-line">Voil un poi dire le semblant<br></span>
<span class="verse-line">Ainz ço ke jo pas avant .<br></span>
<span class="verse-line"><span class="unique-verse">A iceu tens <span class="negation">n'</span>ert si bele femme<br></span></span>
<span class="verse-line"><span class="line-number">164</span><span class="unique-verse">kar ele estoit sur tutes gemme .<br></span></span>
<span class="verse-line"><span class="negation">Onke</span> cuntesse <span class="negation">ne</span> reine<br></span>
<span class="verse-line"><span class="negation">N'</span>ot el chief si bele crine .<br></span>
<span class="verse-line">Rondes avoit les oreilles<br></span>
<span class="verse-line">Tres <span class="color-word">blanches</span> erent a merveilles .<br></span>
<span class="verse-line"><span class="folio-number">38v</span>Les surcius <span class="color-word">noirs</span> e avenanz<br></span>
<span class="verse-line">e les oils <span class="color-word">clers</span> e suz rianz .<br></span>
<span class="verse-line">La buche petite par mesure<br></span>
<span class="verse-line">e <span class="unique-verse">simple</span> avoit la regardure .<br></span>
<span class="verse-line">La face tendre e <span class="color-word">coluree<br></span></span>
<span class="verse-line"><span class="line-number">174</span><span class="color-word">Cum rose qui sempres est nee .<br></span></span>
<div class="empty-line"></div>
<div class="empty-line"></div>
<span class="verse-line"><span class="negation">Ne ja</span> au nés <span class="negation">n'</span>au mentun<br></span>
<span class="verse-line"><span class="negation">N'</span>aparceussez meffaçon .<br></span>
<span class="verse-line">Par sum le col <span class="color-word">blanc com ermine<br></span></span>
<span class="verse-line">Lui undoit la <span class="color-word">bloie</span> crine .<br></span>
<span class="verse-line"><span class="line-number">179</span>Chascun des traianz la dame<br></span>
<span class="verse-line"><span class="negation">N'iert pas maire</span> d'une pome .<br></span>
<span class="verse-line">Suz la gule en la peitrine<br></span>
<span class="verse-line">ert <span class="color-word">blanche come fleur d'espine</span> .<br></span>
<span class="verse-line"><span class="unique-verse">Lung braz</span> avoit e <span class="color-word">blanche mains</span><br></span>
<span class="verse-line"><span class="line-number">184</span>Les dois ronz.greilles e pleins .<br></span>
<span class="verse-line">Gent cors avoit e bien moullez<br></span>
<span class="verse-line">Desuz l'essele les long costez .<br></span>
<span class="verse-line"><span class="negation">Ne feut trop grant ne trop petite<br></span></span>
<span class="verse-line">Sa façon <span class="negation">n'</span>iert <span class="negation">ja</span> descrite .<br></span>
<span class="verse-line"><span class="line-number">189</span><span class="negation">Ne</span> la beauté de ceste dame<br></span>
<span class="verse-line"><span class="negation">N'</span>iert <span class="negation">ja</span> descrite pur <span class="negation">nul</span> <span class="unique-verse">aume</span> .<br></span>
<span class="verse-line">Tant ert cortoise de parler<br></span>
<span class="verse-line"><span class="negation">Riens n'</span>i avoit k'amender .<br></span>
<span class="verse-line">A pleindre fist teu creature<br></span>
<span class="verse-line"><span class="line-number">194</span>Quant de sun Creatur <span class="negation">n'</span>ot cure .<br></span>
<span class="verse-line"><span class="folio-number">39r</span>ele recevrit mut presenz<br></span>
<span class="verse-line">S'en achatot beau vestemenz .<br></span>
<span class="verse-line">Bons dras avoit e avenanz<br></span>
<span class="verse-line">Pur menz pleire a ses amanz .<br></span>
<span class="verse-line"><span class="line-number">199</span>ele <span class="negation">n'</span>avoit soign de dras de leine<br></span>
<span class="verse-line">Par <span class="negation">nul</span> des jurs de la sumeine .<br></span>
<span class="verse-line">Ainz vesteit bliauz de <span class="color-word">osterin<br></span></span>
<span class="verse-line">e affublout mantel d'ermin .<br></span>
<span class="verse-line">Sollers <span class="color-word">bien peinz</span> de cordewan<br></span>
<span class="verse-line"><span class="line-number">204</span>Chaucot trestuz les jurs del an .<br></span>
<span class="verse-line">Trestuz cous de la cité<br></span>
<span class="verse-line">L'amoient pur la beauté .<br></span>
<span class="verse-line">Li ancien hom e li sage<br></span>
<span class="verse-line">Disoient. hai. queu damage .<br></span>
<span class="verse-line"><span class="line-number">209</span>Tant mar fu nee la dolente<br></span>
<span class="verse-line">Tant fet a pleindre sa juvente .<br></span>
<span class="verse-line">Mar feut onke la sue vie<br></span>
<span class="verse-line">Quant si est pleine de folie .<br></span>
<span class="verse-line">Tuz diseient par la citez<br></span>
<span class="verse-line"><span class="line-number">214</span>k'ele estoit de grant parentez .<br></span>
<span class="verse-line">kar a tuz respont par reison<br></span>
<span class="verse-line">e tant ert bele de fasçon .<br></span>
<span class="verse-line">ke li fiz d'un empereur<br></span>
<span class="verse-line">La peust prendre a gran honur .<br></span>
.....<br>
<span class="verse-line"><span class="line-number">623</span>Tant alad ke jurs ke nuiz<br></span>
<span class="verse-line">Od feims od seifs & od dur liz .<br></span>
<span class="verse-line">ke tant parfond feut en boscage<br></span>
<span class="verse-line">Tote devint illoec salvage .<br></span>
<span class="verse-line">mes ele <span class="negation">ne</span> s'obliat <span class="negation">mie</span><br></span>
<span class="verse-line"><span class="line-number">628</span>De deprier saincte Marie .<br></span>
<span class="verse-line">sovent li membre de l'ymage<br></span>
<span class="verse-line">k'ele avoit mis en hostage .<br></span>
<span class="verse-line">si drapel furent tost usez<br></span>
<span class="verse-line">e si souler tut deramez .<br></span>
<span class="verse-line"><span class="line-number">633</span>kant li drapel erent rumpu<br></span>
<span class="verse-line">Le cors de lui remist tut nu .<br></span>
<span class="verse-line">La char de lui <span class="color-word">mua colur<br></span></span>
<span class="verse-line">k'einz ert <span class="color-word">blanche come flur</span> .<br></span>
<span class="verse-line"><span class="folio-number">47v</span>ke de l'yver ke de l'esté<br></span>
<span class="verse-line"><span class="line-number">638</span>Tut li <span class="color-word">nercirent</span> li costé .<br></span>
<span class="verse-line"><span class="color-word">Colur muat la bloie crine<br></span></span>
<span class="verse-line"><span class="color-word">Blanche devint com ermine .<br></span></span>
<span class="verse-line">La face lui estoit <span class="color-word">bruillee<br></span></span>
<span class="verse-line">Del grant soleil e de gelee .<br></span>
<span class="verse-line"><span class="line-number">643</span>La buche li ert entenvie<br></span>
<span class="verse-line">e d'environ tote <span class="color-word">ennercie</span> .<br></span>
<span class="verse-line">e tant avoit <span class="color-word">neir</span> le menton<br></span>
<span class="verse-line"><span class="color-word">come ço feust chief d'un tison .<br></span></span>
<span class="verse-line"><span class="color-word">Teint e nerci</span> erent li oil<br></span>
<span class="verse-line"><span class="line-number">648</span><span class="negation">Rien n'</span>i ot ore d'orgoil .<br></span>
<span class="verse-line">se vos regardisez s'oreille<br></span>
<span class="verse-line">mut vos serroit grant merveille .<br></span>
<span class="verse-line">car megres estoit e descrue<br></span>
<span class="verse-line">e de <span class="color-word">blanc</span> peil tote mossue<br></span>
<span class="verse-line"><span class="line-number">653</span><span class="color-word">Noire</span> e mossue ert la peitrine<br></span>
<span class="verse-line">L'escorce semblout d'espine .<br></span>
<span class="verse-line"><span class="negation">N'</span>avoit <span class="negation">plus</span> char en sa triant<br></span>
<span class="verse-line"><span class="negation">Ne mes ke n'</span>ad en un gant .<br></span>
<span class="verse-line">Les braz les mains e les lung dois<br></span>
<span class="verse-line"><span class="line-number">658</span>Avoit <span class="color-word">plus noirs ke nule poiz .<br></span></span>
<span class="verse-line">Les ungles avoit ele mut grenz<br></span>
<span class="verse-line">Si les retaillot de ses denz .<br></span>
<span class="verse-line">Li ventre tut lui ert caeiz<br></span>
<span class="verse-line">Guere ne mangot. ço ert droiz .<br></span>
<span class="verse-line"><span class="folio-number">48r</span>Les piez lui erent escrevez<br></span>
<span class="verse-line">en plusur lius furent nafrez .<br></span>
<span class="verse-line">k'ele <span class="negation">ne</span> se gardoit d'espine<br></span>
<span class="verse-line">kant ele alot par la guastine .<br></span>
<span class="verse-line">Ço lui ert vis son escient<br></span>
<span class="verse-line"><span class="line-number">668</span>Pur voir de ço <span class="negation">ne</span> failli <span class="negation">nient</span> .<br></span>
<span class="verse-line">k'un de ses pechiez chaeit<br></span>
<span class="verse-line">kant une espine la puigneit .<br></span>
<span class="verse-line">Pur ço feut ele mut lee<br></span>
<span class="verse-line">kant ele suffri teu haschee .<br></span>
<span class="verse-line"><span class="line-number">673</span><span class="negation">N'ert merveille</span> se feust <span class="color-word">nercie<br></span></span>
<span class="verse-line">ke mut demenot aspre vie .<br></span>
<span class="verse-line">plus de quarante anz ala nue<br></span>
<span class="verse-line"><span class="negation">Ne fu merveille</span> s'ert mossue .<br></span>
<span class="verse-line">Povre despense avoit od lui<br></span>
<span class="verse-line"><span class="line-number">678</span>Ore ait de lui Jhesu merci .<br></span>
<span class="verse-line">Dous pains avoit <span class="negation">ne guere granz<br></span></span>
<span class="verse-line">De ces se garit plusurs anz .<br></span>
<span class="verse-line">Tut al premor devindrent dur<br></span>
<span class="verse-line">Cum s'il feusent fet de mur .<br></span>
<span class="verse-line"><span class="line-number">683</span>Chescun jor en usout Marie<br></span>
<span class="verse-line">mes ço ert petite partie .<br></span>
<span class="verse-line">kant ele out son pain usé<br></span>
<span class="verse-line">Doncs arracot l'erbe du pré .<br></span>
<span class="verse-line">Com autre beste la mangot<br></span>
<span class="verse-line"><span class="line-number">688</span><span class="negation">De rien ne</span> se desconfortout .<br></span>
<span class="verse-line"><span class="folio-number">48v</span>Adenz leveit un rosel<br></span>
<span class="verse-line">Dont beut n'ot autre vessel .<br></span>
<span class="verse-line"><span class="negation">Ne</span> fet a pleindre le pechié<br></span>
<span class="verse-line">Dont le cors fu si chastié .<br></span>
<span class="verse-line"><span class="line-number">693</span>D'erbe vesquit e de racine<br></span>
<span class="verse-line">Dis e ut. anz en la guastine .<br></span>
<span class="verse-line">pus fu trente anz <span class="negation">onc ne</span> manga<br></span>
<span class="verse-line">si l'angle Deu ne lui porta .<br></span>
<span class="verse-line">Diables la veneient esprimer<br></span>
<span class="verse-line"><span class="line-number">698</span>Sovent la soleient assaer .<br></span>
<span class="verse-line">Tut ço lui firent remembrer<br></span>
<span class="verse-line">k'ele soleit ja dis amer .<br></span>
<span class="verse-line">Les bons mangers e les beau lius<br></span>
<span class="verse-line">Ou ele soleit fere ses gius .<br></span>
<span class="verse-line"><span class="line-number">703</span>Lors feut ele si bonureie<br></span>
<span class="verse-line"><span class="unique-verse">ke de <span class="negation">rien n'</span>ert attameie .<br></span></span>
<span class="verse-line"><span class="negation">unk</span> en tote soue vie<br></span>
<span class="verse-line"><span class="negation">Ne</span> lui sovint <span class="negation">puis</span> de folie .<br></span>
<span class="verse-line"><span class="negation">Ne puis</span> en trestut le boscage<br></span>
<span class="verse-line"><span class="line-number">708</span><span class="negation">Ne</span> vit <span class="negation">guere</span> beste sauvage .<br></span>
<span class="verse-line"><span class="negation">N'</span>autre vive creature<br></span>
<span class="verse-line">Par la forest vait tute sure .<br></span>
<span class="verse-line">en plusur lius prent son hostal<br></span>
<span class="verse-line">Sa vie est tute espirital .<br></span>
.....<br>
  </div>
  <div class="hover-text">
.....<br>
<span class="verse-line"><span class="line-number">159</span>Of her beauty, of her figure<br></span>
<span class="verse-line">(as it is in the written source)<br></span>
<span class="verse-line">I want to say a little — how they appeared —<br></span>
<span class="verse-line">before I go on.<br></span>
<span class="verse-line"><span class="unique-verse">At that time, there was <span class="negation">no</span> woman so beautiful<br></span></span>
<span class="verse-line"><span class="line-number">164</span><span class="unique-verse">for she was a gem above them all.<br></span></span>
<span class="verse-line"><span class="negation">Never</span> countess <span class="negation">nor</span> queen<br></span>
<span class="verse-line"><span class="negation">had</span> on her head such beautiful hair.<br></span>
<span class="verse-line">She had round ears.<br></span>
<span class="verse-line">They were very marvelously <span class="color-word">white,<br></span></span>
<span class="verse-line"><span class="folio-number">38v</span>her eyebrows <span class="color-word">black</span> and becoming,<br></span>
<span class="verse-line">and her eyes <span class="color-word">bright</span> and overjoyed,<br></span>
<span class="verse-line">her small mouth well-proportioned,<br></span>
<span class="verse-line">and she had a <span class="unique-verse">simple</span> expression,[^2]<br></span>
<span class="verse-line">her face tender and <span class="color-word">blushing<br></span></span>
<span class="verse-line"><span class="line-number">174</span><span class="color-word">like a rose that has just bloomed.<br></span></span>
<div class="empty-line"></div>
<div class="empty-line"></div>
<span class="verse-line"><span class="negation">Indeed neither</span> on her nose <span class="negation">nor</span> on her chin<br></span>
<span class="verse-line">would you notice <span class="negation">any</span> defect.<br></span>
<span class="verse-line">Above the neck that was <span class="color-word">as white as ermine,<br></span></span>
<span class="verse-line">there flowed her <span class="color-word">blonde</span> hair.<br></span>
<span class="verse-line"><span class="line-number">179</span>Each of the breasts of the lady<br></span>
<span class="verse-line">was <span class="negation">no bigger</span> than an apple.<br></span>
<span class="verse-line">Below her throat on her chest,<br></span>
<span class="verse-line">it was <span class="color-word">white like a hawthorn flower.<br></span></span>
<span class="verse-line">She had <span class="unique-verse">long arms</span> and <span class="color-word">white hands</span>,<br></span>
<span class="verse-line"><span class="line-number">184</span>her fingers shapely, slender, and smooth.<br></span>
<span class="verse-line">She had a fine body and was well molded<br></span>
<span class="verse-line">from her underarm along her side.<br></span>
<span class="verse-line"><span class="negation">She was neither too big nor too small.<br></span></span>
<span class="verse-line">Her form could <span class="negation">never</span> be described.<br></span>
<span class="verse-line"><span class="line-number">189</span><span class="negation">Nor</span> could the beauty of this lady<br></span>
<span class="verse-line"><span class="negation">ever</span> be described by <span class="negation">any</span> <span class="unique-verse">soul</span>.<br></span>
<span class="verse-line">She was so courteous of speech;<br></span>
<span class="verse-line">there was <span class="negation">nothing</span> to improve.<br></span>
<span class="verse-line">Such a creature makes one lament<br></span>
<span class="verse-line"><span class="line-number">194</span>when she <span class="negation">does not</span> care about her Creator.<br></span>
<span class="verse-line"><span class="folio-number">39r</span>She received many presents<br></span>
<span class="verse-line">and bought herself beautiful garments.<br></span>
<span class="verse-line">She had good and fitting clothes<br></span>
<span class="verse-line">to better please her lovers.<br></span>
<span class="verse-line"><span class="line-number">199</span>She <span class="negation">did not</span> care for woollen cloth<br></span>
<span class="verse-line">on <span class="negation">any</span> of the days of the week.<br></span>
<span class="verse-line">She wore, instead, a bliaut of fine <span class="color-word">purple silk<br></span></span>
<span class="verse-line">and adorned herself with an ermine mantle.<br></span>
<span class="verse-line"><span class="color-word">Well-painted</span> shoes of Cordovan leather,<br></span>
<span class="verse-line"><span class="line-number">204</span>she wore all the days of the year.<br></span>
<span class="verse-line">Every man of the city<br></span>
<span class="verse-line">loved her for her beauty.<br></span>
<span class="verse-line">The aged men and the wise<br></span>
<span class="verse-line">would say, "Ah! What a shame!<br></span>
<span class="verse-line"><span class="line-number">209</span>Oh alas was born the sufferer!<br></span>
<span class="verse-line">There is much to bemoan of her youth.<br></span>
<span class="verse-line">Alas evermore for her life<br></span>
<span class="verse-line">as it is so full of folly."<br></span>
<span class="verse-line">Everyone in the city would say<br></span>
<span class="verse-line"><span class="line-number">214</span>that she was of great parentage<br></span>
<span class="verse-line">for she answered all with reason<br></span>
<span class="verse-line">and had such a beautiful form<br></span>
<span class="verse-line">that the son of an emperor<br></span>
<span class="verse-line">could have taken her with great honor.[^3]<br></span>
.....<br>
<span class="verse-line"><span class="line-number">623</span>She went so long in the day as in the night,<br></span>
<span class="verse-line">hungry, thirsty, and on hard beds<br></span>
<span class="verse-line">that she was so deep in the wood<br></span>
<span class="verse-line">that she became entirely wild,<br></span>
<span class="verse-line">but she <span class="negation">never</span> forgot<br></span>
<span class="verse-line"><span class="line-number">628</span>to pray to saint Mary.<br></span>
<span class="verse-line">Often, she remembered the image,<br></span>
<span class="verse-line">which she had taken as a guarantor.<br></span>
<span class="verse-line">Her clothes were worn out,<br></span>
<span class="verse-line">and her soles were stripped.<br></span>
<span class="verse-line"><span class="line-number">633</span>As her clothes were in tatters,<br></span>
<span class="verse-line">her body was left totally naked.<br></span>
<span class="verse-line">Her own flesh <span class="color-word">changed color,<br></span></span>
<span class="verse-line">that which before was <span class="color-word">white like a flower.<br></span></span>
<span class="verse-line"><span class="folio-number">47v</span>From the winter and from the summer<br></span>
<span class="verse-line"><span class="line-number">638</span>her sides <span class="color-word">blackened</span> entirely.<br></span>
<span class="verse-line"><span class="color-word">The color of her blonde hair changed.<br></span></span>
<span class="verse-line"><span class="color-word">It turned white like ermine.<br></span></span>
<span class="verse-line">Her face was <span class="color-word">burned<br></span></span>
<span class="verse-line">by the blazing sun and by the frost.<br></span>
<span class="verse-line"><span class="line-number">643</span>Her mouth was thinned<br></span>
<span class="verse-line">and all around it <span class="color-word">blackened,<br></span></span>
<span class="verse-line">and her chin was so <span class="color-word">black<br></span></span>
<span class="verse-line"><span class="color-word">it was like the head of a firebrand.<br></span></span>
<span class="verse-line"><span class="color-word">Tinted and blackened</span> were her eyes.<br></span>
<span class="verse-line"><span class="line-number">648</span>There was <span class="negation">not any</span> pride there now.<br></span>
<span class="verse-line">If you saw her ears,<br></span>
<span class="verse-line">it would be a great marvel to you<br></span>
<span class="verse-line">for they were skinny and shrunken[^4]<br></span>
<span class="verse-line">and all woolly with <span class="color-word">white</span> hairs.<br></span>
<span class="verse-line"><span class="line-number">653</span><span class="color-word">Black</span> and woolly was her chest.<br></span>
<span class="verse-line">It seemed like thorny bark.<br></span>
<span class="verse-line">She had <span class="negation">no more</span> flesh in her breast,<br></span>
<span class="verse-line"><span class="negation">no more</span> than there is in a glove.<br></span>
<span class="verse-line">Her arms, her hands, and her long fingers<br></span>
<span class="verse-line"><span class="line-number">658</span>were <span class="color-word">blacker than any pitch.<br></span></span>
<span class="verse-line">She had such large nails,<br></span>
<span class="verse-line">so she reshaped them with her teeth.<br></span>
<span class="verse-line">Her stomach was all sunken.<br></span>
<span class="verse-line">She hardly ate, so that was right.<br></span>
<span class="verse-line"><span class="folio-number">48r</span>Her feet were split.[^4]<br></span>
<span class="verse-line">In many places, they were wounded<br></span>
<span class="verse-line">for she <span class="negation">did not</span> protect herself from thorns<br></span>
<span class="verse-line">as she went through the wilderness.<br></span>
<span class="verse-line">It seemed to her, in her mind,<br></span>
<span class="verse-line"><span class="line-number">668</span>for truly, about this, she was <span class="negation">not</span> wrong <span class="negation">at all</span>,<br></span>
<span class="verse-line">that one of her sins fell away<br></span>
<span class="verse-line">when a thorn pricked her.<br></span>
<span class="verse-line">For this, she was so pleased.<br></span>
<span class="verse-line">As she suffered such hardship,<br></span>
<span class="verse-line"><span class="line-number">673</span><span class="negation">it was no marvel</span> that she was <span class="color-word">blackened<br></span></span>
<span class="verse-line">for she led such a severe life.<br></span>
<span class="verse-line">For more than forty years, she went about nude:<br></span>
<span class="verse-line"><span class="negation">it was no marvel</span> she was woolly.<br></span>
<span class="verse-line">She had poor provisions with her.<br></span>
<span class="verse-line"><span class="line-number">678</span>Now may Jesus have mercy on her.<br></span>
<span class="verse-line">She had two loaves of <span class="negation">no great size</span>.<br></span>
<span class="verse-line">On these she sustained herself for many years.<br></span>
<span class="verse-line">They all became hard in the first year<br></span>
<span class="verse-line">as though they were made from a wall.<br></span>
<span class="verse-line"><span class="line-number">683</span>Each day, Mary ate some,<br></span>
<span class="verse-line">but this was a small portion.<br></span>
<span class="verse-line">As soon as she had eaten up her bread,<br></span>
<span class="verse-line">then she plucked the grass of the field.<br></span>
<span class="verse-line">Like other beasts she ate it.<br></span>
<span class="verse-line"><span class="line-number">688</span><span class="negation">None</span> of this bothered her.<br></span>
<span class="verse-line"><span class="folio-number">48v</span>Prone, she drew from a stream.<br></span>
<span class="verse-line">Like so, she drank. She had no other vessel.<br></span>
<span class="verse-line"><span class="negation">Not</span> to be lamented is the sin<br></span>
<span class="verse-line">that chastised the body so.<br></span>
<span class="verse-line"><span class="line-number">693</span>On grass she lived and on roots<br></span>
<span class="verse-line">for eighteen years in the wilderness.<br></span>
<span class="verse-line">Then for thirty years, she <span class="negation">never</span> ate<br></span>
<span class="verse-line">but what the angel of God brought to her.<br></span>
<span class="verse-line">Devils came to approach her.<br></span>
<span class="verse-line"><span class="line-number">698</span>Often, they used to tempt her,<br></span>
<span class="verse-line">making her remember all<br></span>
<span class="verse-line">that she once used to love:<br></span>
<span class="verse-line">the good foods and the fine places<br></span>
<span class="verse-line">where she was used to playing her games.<br></span>
<span class="verse-line"><span class="line-number">703</span>Now, she felt so blessed<br></span>
<span class="verse-line"><span class="unique-verse">that <span class="negation">nothing</span> hurt her.<br></span></span>
<span class="verse-line"><span class="negation">Never</span>, in all her life,<br></span>
<span class="verse-line"><span class="negation">did</span> she think, <span class="negation">then</span>, of folly.<br></span>
<span class="verse-line"><span class="negation">Nor, then,</span> in all the wood,<br></span>
<span class="verse-line"><span class="line-number">708</span><span class="negation">did</span> she see wild beasts <span class="negation">at all</span>.<br></span>
<span class="verse-line"><span class="negation">nor any</span> other living creature.<br></span>
<span class="verse-line">Through the forest, she goes totally assured.<br></span>
<span class="verse-line">In many places, she takes shelter.<br></span>
<span class="verse-line">Her life is entirely spiritual.<br></span>
.....<br>
  </div>
</div>
:::

::: {.portrait-column}
## T-D
<div class="text-container">
  <div class="default-text">
.....<br>
<span class="verse-line"><span class="line-number">155</span>De sa bealté & de sa figure<br></span>
<span class="verse-line">Si cum est en l'escripture<br></span>
<span class="verse-line">voil un poi dire le semblant<br></span>
<span class="verse-line">einz que jeo trespas avant<br></span>
<span class="verse-line">en cel tens ne en cel regne<br></span>
<span class="verse-line"><span class="line-number">160</span><span class="negation">Ne</span> vit <span class="negation">unc</span> home plus bele femme<br></span>
<span class="verse-line"><span class="folio-number">16va</span><span class="negation">Ne</span> cuntesse <span class="negation">ne</span> raine.<br></span>
<span class="verse-line"><span class="negation">N'</span>out <span class="negation">onkes</span> tele meschine<br></span>
<span class="verse-line">roundes aveit les oreilles<br></span>
<span class="verse-line">Mais <span class="color-word">blanches</span> erent a merveilles<br></span>
<span class="verse-line"><span class="line-number">165</span>les sorciz <span class="color-word">clers</span> & avenanz<br></span>
<span class="verse-line">les oilz <span class="color-word">neirs</span> & sorianz<br></span>
<span class="verse-line">la bouche brieve & par mesure<br></span>
<span class="verse-line">& pie la regardeure<br></span>
<span class="verse-line">la face tendre & <span class="color-word">coloree<br></span></span>
<span class="verse-line"><span class="line-number">170</span><span class="color-word">cumme rose qui senpres est nee<br></span></span>
<div class="empty-line"></div>
<div class="empty-line"></div>
<span class="verse-line"><span class="negation">ja</span> el nés <span class="negation">ne</span> el mentun<br></span>
<span class="verse-line"><span class="negation">N'</span>i veist l'un mesfaçun<br></span>
<span class="verse-line">par sun le col <span class="color-word">blanc cum ermine<br></span></span>
<span class="verse-line">li undout la <span class="color-word">bloie</span> crine<br></span>
<span class="verse-line"><span class="line-number">175</span>chascun des traianz a la dune<br></span>
<span class="verse-line"><span class="negation">N'ert mie greignor</span> d'une pume<br></span>
<span class="verse-line">Soz la gorge en la poitrine<br></span>
<span class="verse-line">ere <span class="color-word">blanche cumme flor d'espine<br></span></span>
<span class="verse-line"><span class="color-word">blans bras</span> aveit & <span class="unique-verse">beles</span> mains<br></span>
<span class="verse-line"><span class="line-number">180</span>& les deis luncs gresles & pleins<br></span>
<div class="empty-line"></div>
<div class="empty-line"></div>
<span class="verse-line"><span class="negation">N'ert trop grande ne trop petite<br></span></span>
<span class="verse-line"><span class="negation">ja</span> sa façun <span class="negation">n'</span>iert deserite<br></span>
<span class="verse-line"><span class="negation">ja</span> la bealté de ceste dune<br></span>
<span class="verse-line"><span class="negation">N'</span>iert escrite por <span class="negation">nul</span> home<br></span>
<span class="verse-line"><span class="line-number">185</span>tant ert corteise de parler<br></span>
<span class="verse-line"><span class="negation">rien n'</span>i aveit que amender<br></span>
<span class="verse-line">a plaindre fait tel creature<br></span>
<span class="verse-line">Quant del Creator <span class="negation">n'</span>aveit cure<br></span>
<span class="verse-line"><span class="unique-verse">ele recevoit <span class="color-word">or</span> & <span class="color-word">argent</span><br></span></span>
<span class="verse-line"><span class="line-number">190</span>Si achatout bons garnemenz<br></span>
<span class="verse-line">bons dras aveit & avenanz<br></span>
<span class="verse-line">por miex plesir a ses amanz<br></span>
<span class="verse-line"><span class="folio-number">16vb</span>ele <span class="negation">n'</span>out cure de dras de leine<br></span>
<span class="verse-line">al peor jor de la semeine<br></span>
<span class="verse-line"><span class="line-number">195</span>Vesteit bons bliaus <span class="color-word">d'osturin</span><br></span>
<span class="verse-line">& afubla mantel hermin<br></span>
<span class="verse-line">Soulers <span class="color-word">bien pains</span> de cordoven<br></span>
<span class="verse-line">chaucout a toz les jors de l'an<br></span>
<span class="verse-line">li citeen de la cité<br></span>
<span class="verse-line"><span class="line-number">200</span>l'amouent tuit por sa bealté<br></span>
<span class="verse-line">li anciem home & li sage<br></span>
<span class="verse-line">disoient tuit Deus quel damage<br></span>
<span class="verse-line">Mar fu unques la dolente<br></span>
<span class="verse-line">tant fait a plaindre sa jovente<br></span>
<span class="verse-line"><span class="line-number">205</span>Mar fu unques la soue vie<br></span>
<span class="verse-line">Quant si est pleine de folie<br></span>
<span class="verse-line">tuit disoient par la cité<br></span>
<span class="verse-line">Que ele ert de mult halt parenté<br></span>
<span class="verse-line">car a toz rosponeit raisun<br></span>
<span class="verse-line"><span class="line-number">210</span>& tant ert bele de façun<br></span>
<span class="verse-line">ke le fiz d'un enpereor<br></span>
<span class="verse-line">la peust prendre par honor<br></span>
.....<br>
<span class="verse-line"><span class="line-number">615</span>tant erra par jor. & par nuit<br></span>
<span class="verse-line">o faim. & o sei. & o dur lit<br></span>
<span class="verse-line">& tant fu en cel boscage<br></span>
<span class="verse-line">tote devint iloc salvage<br></span>
<span class="verse-line">mais ele <span class="negation">ne</span> s'oublia <span class="negation">mie<br></span></span>
<span class="verse-line"><span class="line-number">620</span>de deprier sainte Marie<br></span>
<span class="verse-line">sovent lui membre de l'ymage<br></span>
<span class="verse-line">Que ele aveit mis en ostage<br></span>
<span class="verse-line">Ses soulers furent tuit usés<br></span>
<span class="verse-line">& si drapel tuit descirés<br></span>
<span class="verse-line"><span class="line-number">625</span>Quant si drapel furent rumpu<br></span>
<span class="verse-line">le cors de lui remist tot nu<br></span>
<span class="verse-line">la char de lui <span class="color-word">mua color<br></span></span>
<span class="verse-line">Qui ainz ert <span class="color-word">blanche cumme flor<br></span></span>
<span class="verse-line">Que o l'ivern. ke o l'esté<br></span>
<span class="verse-line"><span class="line-number">630</span>tuit li <span class="color-word">nercirent</span> li costé<br></span>
<span class="verse-line"><span class="color-word">color mua sa bloie crigne<br></span></span>
<span class="verse-line"><span class="color-word">blanche devint cumme ermigne<br></span></span>
<span class="verse-line">la face out desus <span class="color-word">bruslee<br></span></span>
<span class="verse-line">del soleil. & de la gelee<br></span>
<span class="verse-line"><span class="line-number">635</span>la bouche li fu atenvie<br></span>
<span class="verse-line">& envirun la char <span class="color-word">nercie<br></span></span>
<span class="verse-line">tant par esteit <span class="color-word">neir</span> sun mentun.<br></span>
<span class="verse-line"><span class="color-word">cum ceo fust le chief d'un tisun<br></span></span>
<span class="verse-line">& <span class="color-word">nerci</span> erent si oil<br></span>
<span class="verse-line"><span class="line-number">640</span><span class="negation">N'</span>i aveit ore <span class="negation">point d'</span>orguil<br></span>
<span class="verse-line"><span class="folio-number">20rb</span>Se vous veissés sa oreille<br></span>
<span class="verse-line">mult vous semblast grant merveille<br></span>
<span class="verse-line">car mesgre esteit. & decrevee<br></span>
<span class="verse-line">& de <span class="color-word">blanc</span> peil <span class="unique-verse">avirunee</span><br></span>
<div class="empty-line"></div>
<div class="empty-line"></div>
<span class="verse-line"><span class="line-number">645</span><span class="negation">N'</span>aveit <span class="negation">plus</span> char en sun traiant<br></span>
<span class="verse-line"><span class="negation">Ne mais</span> cum il a en un gant<br></span>
<span class="verse-line">les bras. les mains. & les deiz<br></span>
<span class="verse-line">aveit <span class="color-word">plus neirs que nule peiz<br></span></span>
<span class="verse-line">les umgles aveit ele grenz<br></span>
<span class="verse-line"><span class="line-number">650</span>ele les taillout o les denz<br></span>
<span class="verse-line">le ventre lui ert tot dechaet<br></span>
<span class="verse-line">car povre despense i meteit<br></span>
<span class="verse-line">les piez li erent decrevez<br></span>
<span class="verse-line">en plusors lieus erent nafrez<br></span>
<span class="verse-line"><span class="line-number">655</span>car ele <span class="negation">ne</span> se gardout de espine<br></span>
<span class="verse-line">Quant ele alout par la gastine<br></span>
<span class="verse-line">mais ceo li ert vis son encient<br></span>
<span class="verse-line">& ele <span class="negation">n'</span>i failli de <span class="negation">nient<br></span></span>
<span class="verse-line">ke un peché de lui chaeit<br></span>
<span class="verse-line"><span class="line-number">660</span>Quant une espine la poingneit<br></span>
<span class="verse-line">por ceo esteit ele lee<br></span>
<span class="verse-line">Quant ele soffri une haschee<br></span>
<span class="verse-line"><span class="negation">N'ert pas merveille</span> s'ele ert <span class="color-word">nercie<br></span></span>
<span class="verse-line">car ele demenout aspre vie<br></span>
<span class="verse-line"><span class="line-number">665</span>plus de quarante ans ala nue<br></span>
<span class="verse-line"><span class="negation">N'ert merveille</span> s'ele ert mossue<br></span>
<span class="verse-line">povre despense aveit o lui<br></span>
<span class="verse-line">ore ait Jesus de lui merci<br></span>
<span class="verse-line">deus pains aveit <span class="negation">ne gueres granz<br></span></span>
<span class="verse-line"><span class="line-number">670</span>de cels vesqui plusors anz<br></span>
<span class="verse-line">el premier en devindrent dur<br></span>
<span class="verse-line">cumme ceo fussent pieres de mur<br></span>
<span class="verse-line"><span class="folio-number">20va</span>chascun jor en usout Marie<br></span>
<span class="verse-line">mais ceo ert petite partie<br></span>
<span class="verse-line"><span class="line-number">675</span>& quant ele out son pain usé<br></span>
<span class="verse-line">Si esracout l'erbe del pré<br></span>
<span class="verse-line">cumme altre beste la manjout<br></span>
<span class="verse-line">& <span class="negation">de rien ne</span> se desconfortout<br></span>
<span class="verse-line">a denz beveit del ruissel<br></span>
<span class="verse-line"><span class="line-number">680</span>ele <span class="negation">n'</span>aveit altre vaissel<br></span>
<span class="verse-line"><span class="negation">Ne</span> fait a plaindre le pechié<br></span>
<span class="verse-line">dunt le cors fu si chastié<br></span>
<span class="verse-line">d'erbes viveit. & de racines<br></span>
<span class="verse-line">dis. & set anz. en la gastine<br></span>
<span class="verse-line"><span class="line-number">685</span>puis fu trente anz <span class="negation">unc ne</span> manja<br></span>
<span class="verse-line">Se li angres Deu ne lui porta<br></span>
<span class="verse-line">Deable lui vint de premier<br></span>
<span class="verse-line">Sovent la soloit essaier<br></span>
<span class="verse-line">tot ceo lui faisoit remembrer<br></span>
<span class="verse-line"><span class="line-number">690</span>Que ele soloit jadis amer<br></span>
<span class="verse-line">les bons mangiers. & les lieus<br></span>
<span class="verse-line">ou ele sout faire ses gieus<br></span>
<span class="verse-line">ore fu issi beneuree<br></span>
<span class="verse-line">Que de tot ceo fu obliee<br></span>
<span class="verse-line"><span class="line-number">695</span>& en tote la soue vie<br></span>
<span class="verse-line"><span class="negation">Ne</span> lui sovint <span class="negation">puis</span> de la folie<br></span>
<span class="verse-line">& <span class="negation">unc puis</span> en tot le boscage<br></span>
<span class="verse-line"><span class="negation">Ne</span> vit beste salvage<br></span>
<span class="verse-line"><span class="negation">Ne</span> altre vive creature<br></span>
<span class="verse-line"><span class="line-number">700</span>par la forest vait tote seure<br></span>
<span class="verse-line">en plusors lieus prent son ostal<br></span>
<span class="verse-line">Sa vie esteit esperital<br></span>
.....<br>
  </div>
  <div class="hover-text">
.....<br>
<span class="verse-line"><span class="line-number">155</span>Of her beauty and of her figure<br></span>
<span class="verse-line">(as it is in the written source)<br></span>
<span class="verse-line">I want to say a little — how they appeared —<br></span>
<span class="verse-line">before I go too far.<br></span>
<span class="verse-line">At that time and in that realm,<br></span>
<span class="verse-line"><span class="line-number">160</span><span class="negation">no</span> man <span class="negation">ever</span> saw a more beautiful woman.<br></span>
<span class="verse-line"><span class="folio-number">16va</span><span class="negation">No</span> countess <span class="negation">or</span> queen<br></span>
<span class="verse-line"><span class="negation">ever had</span> such a daughter.<br></span>
<span class="verse-line">She had round ears.<br></span>
<span class="verse-line">What's more, they were marvelously <span class="color-word">white,[^1]<br></span></span>
<span class="verse-line"><span class="line-number">165</span>her eyebrows <span class="color-word">bright</span> and becoming,<br></span>
<span class="verse-line">her eyes <span class="color-word">black</span> and smiling,<br></span>
<span class="verse-line">her mouth small and well-proportioned,<br></span>
<span class="verse-line">and pleasing her expression,[^2]<br></span>
<span class="verse-line">her face tender and <span class="color-word">blushing<br></span></span>
<span class="verse-line"><span class="line-number">170</span><span class="color-word">like a rose that has just bloomed.<br></span></span>
<div class="empty-line"></div>
<div class="empty-line"></div>
<span class="verse-line"><span class="negation">Indeed neither</span> on her nose <span class="negation">nor</span> on her chin<br></span>
<span class="verse-line">was seen a defect.<br></span>
<span class="verse-line">Above the neck that was <span class="color-word">as white as ermine,<br></span></span>
<span class="verse-line">there flowed her <span class="color-word">blonde</span> hair.<br></span>
<span class="verse-line"><span class="line-number">175</span>Each of the breasts of the lady<br></span>
<span class="verse-line">was <span class="negation">not a bit bigger</span> than an apple.<br></span>
<span class="verse-line">Below her throat on her chest,<br></span>
<span class="verse-line">it was <span class="color-word">white like a hawthorn flower.<br></span></span>
<span class="verse-line">She had <span class="color-word">white arms</span> and <span class="unique-verse">beautiful</span> hands,<br></span>
<span class="verse-line"><span class="line-number">180</span>and long, slender, and smooth fingers.<br></span>
<div class="empty-line"></div>
<div class="empty-line"></div>
<span class="verse-line"><span class="negation">She was neither too big nor too small.<br></span></span>
<span class="verse-line">Her form could <span class="negation">never</span> be described.<br></span>
<span class="verse-line">The beauty of this lady<br></span>
<span class="verse-line">could <span class="negation">never</span> be written down by <span class="negation">any</span> man.<br></span>
<span class="verse-line"><span class="line-number">185</span>She was so courteous of speech;<br></span>
<span class="verse-line">there was <span class="negation">nothing</span> to improve.<br></span>
<span class="verse-line">Such a creature makes one lament<br></span>
<span class="verse-line">when she <span class="negation">does not</span> care about the Creator.<br></span>
<span class="verse-line"><span class="unique-verse">She received <span class="color-word">gold</span> and <span class="color-word">silver</span><br></span></span>
<span class="verse-line"><span class="line-number">190</span>and bought good garments.<br></span>
<span class="verse-line">She had good and fitting clothes<br></span>
<span class="verse-line">to better please her lovers.<br></span>
<span class="verse-line"><span class="folio-number">16vb</span>She <span class="negation">did not</span> care for woollen cloth<br></span>
<span class="verse-line">on the worst day of the week.<br></span>
<span class="verse-line"><span class="line-number">195</span>She wore a fine <span class="color-word">purple silk</span> bliaut<br></span>
<span class="verse-line">and adorned herself with an ermine mantle.<br></span>
<span class="verse-line"><span class="color-word">Well-painted</span> shoes of Cordovan leather,<br></span>
<span class="verse-line">she wore all the days of the year.<br></span>
<span class="verse-line">The citizens of the city<br></span>
<span class="verse-line"><span class="line-number">200</span>loved her entirely for her beauty.<br></span>
<span class="verse-line">The aged men and the wise<br></span>
<span class="verse-line">all would say, "God, what a shame!<br></span>
<span class="verse-line">Alas evermore for the sufferer!<br></span>
<span class="verse-line">There is much to bemoan of her youth.<br></span>
<span class="verse-line"><span class="line-number">205</span>Alas evermore for her life<br></span>
<span class="verse-line">as it is so full of folly."<br></span>
<span class="verse-line">Everyone in the city would say<br></span>
<span class="verse-line">that she was of very high parentage<br></span>
<span class="verse-line">for she answered all with reason<br></span>
<span class="verse-line"><span class="line-number">210</span>and had such a beautiful form<br></span>
<span class="verse-line">that the son of an emperor<br></span>
<span class="verse-line">could have taken her with honor.[^3]<br></span>
.....<br>
<span class="verse-line"><span class="line-number">615</span>She roamed so long by day and by night,<br></span>
<span class="verse-line">hungry and thirsty and on hard beds,<br></span>
<span class="verse-line">and she was in this wood so long<br></span>
<span class="verse-line">that she became entirely wild there,<br></span>
<span class="verse-line">but she <span class="negation">never</span> forgot<br></span>
<span class="verse-line"><span class="line-number">620</span>to pray to saint Mary.<br></span>
<span class="verse-line">Often, she remembers the image,<br></span>
<span class="verse-line">which she had taken as a guarantor.<br></span>
<span class="verse-line">Her soles were all worn out,<br></span>
<span class="verse-line">and her clothes were torn up.<br></span>
<span class="verse-line"><span class="line-number">625</span>As her clothes were in tatters,<br></span>
<span class="verse-line">her body was left totally naked.<br></span>
<span class="verse-line">Her own flesh <span class="color-word">changed color,<br></span></span>
<span class="verse-line">that which before was <span class="color-word">white like a flower.<br></span></span>
<span class="verse-line">From the winter and from the summer<br></span>
<span class="verse-line"><span class="line-number">630</span>her sides <span class="color-word">blackened</span> entirely.<br></span>
<span class="verse-line"><span class="color-word">The color of her blonde hair changed.<br></span></span>
<span class="verse-line"><span class="color-word">It turned white like ermine.<br></span></span>
<span class="verse-line">Her face was <span class="color-word">burned up<br></span></span>
<span class="verse-line">from the sun and from the frost.<br></span>
<span class="verse-line"><span class="line-number">635</span>Her mouth was thinned,<br></span>
<span class="verse-line">and her flesh around it <span class="color-word">blackened.<br></span></span>
<span class="verse-line">Her chin was so <span class="color-word">black</span> all over.<br></span>
<span class="verse-line"><span class="color-word">It was like the head of a firebrand,<br></span></span>
<span class="verse-line">and <span class="color-word">black</span> were her eyes.<br></span>
<span class="verse-line"><span class="line-number">640</span>There was <span class="negation">not a shred</span> of pride there now.<br></span>
<span class="verse-line"><span class="folio-number">20rb</span>If you saw her ears,<br></span>
<span class="verse-line">it would seem to you a great marvel<br></span>
<span class="verse-line">for they were skinny and cracked[^4]<br></span>
<span class="verse-line">and with <span class="color-word">white</span> hair <span class="unique-verse">all around</span>.<br></span>
<div class="empty-line"></div>
<div class="empty-line"></div>
<span class="verse-line"><span class="line-number">645</span>She had <span class="negation">no more</span> flesh in her breast,<br></span>
<span class="verse-line"><span class="negation">no more</span> than there is in a glove.<br></span>
<span class="verse-line">Her arms, her hands, and her fingers<br></span>
<span class="verse-line">were <span class="color-word">blacker than any pitch.<br></span></span>
<span class="verse-line">She had large nails.<br></span>
<span class="verse-line"><span class="line-number">650</span>She shaped them with her teeth.<br></span>
<span class="verse-line">Her stomach was all sunken<br></span>
<span class="verse-line">for she put poor provisions in there.<br></span>
<span class="verse-line">Her feet were split[^4]<br></span>
<span class="verse-line">and, in many places, were wounded<br></span>
<span class="verse-line"><span class="line-number">655</span>for she <span class="negation">did not</span> protect herself from thorns<br></span>
<span class="verse-line">as she went through the wilderness.<br></span>
<span class="verse-line">But it seemed to her, in her mind,<br></span>
<span class="verse-line">and she was <span class="negation">not</span> wrong about this <span class="negation">at all</span>,<br></span>
<span class="verse-line">that a sin fell away from her<br></span>
<span class="verse-line"><span class="line-number">660</span>when a thorn pricked her.<br></span>
<span class="verse-line">For this, she was pleased.<br></span>
<span class="verse-line">As she suffered hardship,<br></span>
<span class="verse-line"><span class="negation">it was no marvel</span> she was <span class="color-word">blackened<br></span></span>
<span class="verse-line">for she led a severe life.<br></span>
<span class="verse-line"><span class="line-number">665</span>For more than forty years, she went about nude:<br></span>
<span class="verse-line"><span class="negation">it was no marvel</span> she was woolly.<br></span>
<span class="verse-line">She had poor provisions with her.<br></span>
<span class="verse-line">Now may Jesus have mercy on her.<br></span>
<span class="verse-line">She had two loaves of <span class="negation">no great size</span>.<br></span>
<span class="verse-line"><span class="line-number">670</span>On these, she lived for many years.<br></span>
<span class="verse-line">In the first year, they became hard<br></span>
<span class="verse-line">as though they were building stones.<br></span>
<span class="verse-line"><span class="folio-number">20va</span>Each day, Mary ate some,<br></span>
<span class="verse-line">but this was a small portion.<br></span>
<span class="verse-line"><span class="line-number">675</span>And as soon as she had eaten up her bread,<br></span>
<span class="verse-line">then she plucked the grass of the field.<br></span>
<span class="verse-line">Like other beasts, she ate it.<br></span>
<span class="verse-line">And <span class="negation">none</span> of this bothered her.<br></span>
<span class="verse-line">Prone, she drank from the stream.<br></span>
<span class="verse-line"><span class="line-number">680</span>She had <span class="negation">no</span> other vessel.<br></span>
<span class="verse-line"><span class="negation">Not</span> to be lamented is the sin<br></span>
<span class="verse-line">that chastised the body so.<br></span>
<span class="verse-line">On grasses she lived and on roots<br></span>
<span class="verse-line">for seventeen years in the wilderness.<br></span>
<span class="verse-line"><span class="line-number">685</span>Then, for thirty years, she <span class="negation">never</span> ate<br></span>
<span class="verse-line">but what the angel of God brought to her.<br></span>
<span class="verse-line">The Devil came to her at first.<br></span>
<span class="verse-line">Often, he used to tempt her,<br></span>
<span class="verse-line">making her remember all<br></span>
<span class="verse-line"><span class="line-number">690</span>that she once used to love:<br></span>
<span class="verse-line">the good foods and the places<br></span>
<span class="verse-line">where she was used to playing her games.<br></span>
<span class="verse-line">Now, she felt so blessed<br></span>
<span class="verse-line">as she had forgotten all of this.<br></span>
<span class="verse-line"><span class="line-number">695</span>And in all her life,<br></span>
<span class="verse-line">she <span class="negation">never</span> thought <span class="negation">then</span> of folly.<br></span>
<span class="verse-line">And <span class="negation">never then</span> in all the wood<br></span>
<span class="verse-line">did she see <span class="negation">any</span> wild beast<br></span>
<span class="verse-line"><span class="negation">nor any</span> other living creature<br></span>
<span class="verse-line"><span class="line-number">700</span>Through the forest, she goes totally assured.<br></span>
<span class="verse-line">In many places, she takes shelter.<br></span>
<span class="verse-line">Her life was spiritual.<br></span>
.....<br>
  </div>
</div>
:::

::: {.portrait-column}
## T-E
<div class="text-container">
  <div class="default-text">
.....<br>
<span class="verse-line"><span class="line-number">157</span>de sa bieuté de sa figure<br></span>
<span class="verse-line">Si com il est en escripture<br></span>
<span class="verse-line">Voil -i- poi dire le samblant<br></span>
<span class="verse-line">ançois que jo trespas avant<br></span>
<span class="verse-line">En icel tans ne en cel regne<br></span>
<span class="verse-line"><span class="line-number">162</span><span class="negation">N'en</span> ot <span class="negation">onques</span> plus bele feme<br></span>
<span class="verse-line"><span class="negation">onques</span> comtesse <span class="negation">ne</span> roine<br></span>
<span class="verse-line"><span class="negation">N'en</span> ot el chief plus bele crigne<br></span>
<span class="verse-line">roondes avoit les oreilles<br></span>
<span class="verse-line">& <span class="color-word">blances</span> erent a merveilles<br></span>
<span class="verse-line"><span class="line-number">167</span>les sorcils <span class="color-word">noirs</span> & avenans<br></span>
<span class="verse-line">& les ioex <span class="color-word">vairs</span> & molt rians<br></span>
<span class="verse-line">La bouche bele & par mesure<br></span>
<span class="verse-line">& pieue la regardeure<br></span>
<span class="verse-line">la face tenre & <span class="color-word">coloree<br></span></span>
<span class="verse-line"><span class="line-number">172</span><span class="color-word">comme rose novele nee<br></span></span>
<div class="empty-line"></div>
<div class="empty-line"></div>
<span class="verse-line"><span class="negation">Ne ja</span> el nés <span class="negation">ne</span> el menton<br></span>
<span class="verse-line"><span class="negation">Ne</span> parceusciés mesfaçon<br></span>
<span class="verse-line">Le col avoit <span class="color-word">blanc com ermine<br></span></span>
<span class="verse-line">Loiet estoit sa <span class="color-word">blonde</span> crine<br></span>
<span class="verse-line"><span class="line-number">177</span><span class="sequence-change"><span class="negation">N'iert mie graindres</span> d'une pome<br></span></span>
<span class="verse-line"><span class="sequence-change">L'un des traians de cele domme<br></span></span>
<span class="verse-line">desus la boce en la poitrine<br></span>
<span class="verse-line">Ert si <span class="color-word">blance com flor d'espine<br></span></span>
<span class="verse-line"><span class="color-word">blans bras</span> avoit & <span class="color-word">blances mains<br></span></span>
<span class="verse-line"><span class="line-number">182</span>les dois reons grailles & plains<br></span>
<span class="verse-line">Gent cors avoit & bien mollé<br></span>
<span class="verse-line">Sus l'asoele lanc le costé<br></span>
<span class="verse-line"><span class="negation">Ne trop grande ne trop petite<br></span></span>
<span class="verse-line"><span class="negation">Ja</span> sa façon <span class="negation">n'</span>en ert descrite<br></span>
<span class="verse-line"><span class="line-number">187</span>la grans biautés de ceste dame<br></span>
<span class="verse-line"><span class="negation">N'</span>iert toute escrite par <span class="negation">nul</span> homme<br></span>
<span class="verse-line">Tant ert cortoise de parler<br></span>
<span class="verse-line"><span class="negation">Rien n'</span>i avoit que amender<br></span>
<span class="verse-line">a plaindre fait tel creature<br></span>
<span class="verse-line"><span class="line-number">192</span>Quant de son Creator <span class="negation">n'</span>a cure<br></span>
<span class="verse-line">Ele recevoit grans presens<br></span>
<span class="verse-line">S'en achatoit biaus garnemens<br></span>
<span class="verse-line">biaus dras avoit & avenans<br></span>
<span class="verse-line">por bien plaisir a ses amans<br></span>
<span class="verse-line"><span class="line-number">197</span><span class="negation">N'</span>avoit <span class="negation">pas</span> soing de dras de laine<br></span>
<span class="verse-line">Al pior jor de la semaine<br></span>
<span class="verse-line">vestoit bon bliaut <span class="color-word">ostorin<br></span></span>
<span class="verse-line">Si afubloit mantel ermin<br></span>
<span class="verse-line"><span class="folio-number">114rd</span>Sollers <span class="color-word">bien pains</span> de cordoan<br></span>
<span class="verse-line"><span class="line-number">202</span>chaucoit a tus les jors de l'an<br></span>
<span class="verse-line">li citeain de la cité<br></span>
<span class="verse-line">l'amoient tot por sa biauté<br></span>
<span class="verse-line">li ancien home & li sage<br></span>
<span class="verse-line">disoient tot que c'ert damage<br></span>
<span class="verse-line"><span class="line-number">207</span>tant par mar fu ceste dolente<br></span>
<span class="verse-line">molt fait a plaindre sa jovente<br></span>
<span class="verse-line">mar fu onques la soie vie<br></span>
<span class="verse-line">Quant si est plaine de folie<br></span>
<span class="verse-line">tot disoient par la cité<br></span>
<span class="verse-line"><span class="line-number">212</span>Qu'ele ert de haut parenté<br></span>
<span class="verse-line">Car a tos respondoit raison<br></span>
<span class="verse-line">& molt ert de bele façon<br></span>
<span class="verse-line">li fiex a -i- empereor<br></span>
<span class="verse-line">Le peust prendre par honor<br></span>
.....<br>
<span class="verse-line"><span class="line-number">613</span>tant ala par jor & par nuis<br></span>
<span class="verse-line"><span class="unique-verse">par bos par plains & par larris<br></span></span>
<span class="verse-line">& tant par font vint el boscage<br></span>
<span class="verse-line">Que tot devint iluec salvage<br></span>
<span class="verse-line">mais ele <span class="negation">ne</span> s'oblioit <span class="negation">mie</span><br></span>
<span class="verse-line"><span class="line-number">618</span>de proier a sainte Marie<br></span>
<span class="verse-line">Sovent li menbroit del ymage<br></span>
<span class="verse-line">Que ele avoit mis en ostage<br></span>
<span class="verse-line">Si drapel furent tost usé<br></span>
<span class="verse-line">& si sollers tost desramé<br></span>
<span class="verse-line"><span class="line-number">623</span>Quant si drapel furent ronpu<br></span>
<span class="verse-line">li cors de li remest tot nu<br></span>
<span class="verse-line">la sieue char <span class="color-word">mua color<br></span></span>
<span class="verse-line">devant ert <span class="color-word">blance comme flor<br></span></span>
<span class="verse-line">Quant .i. iver i ot esté<br></span>
<span class="verse-line"><span class="line-number">628</span>tot li <span class="color-word">noircirent</span> li costé<br></span>
<span class="verse-line">molt li mua la <span class="color-word">blonde</span> crine<br></span>
<span class="verse-line"><span class="color-word">blance devint com .i. ermine<br></span></span>
<span class="verse-line"><span class="sequence-change">del soleil & de la gelee<br></span></span>
<span class="verse-line"><span class="sequence-change">li fu la face molt <span class="color-word">bruslee<br></span></span></span>
<span class="verse-line"><span class="line-number">633</span>Sa bouche fu atenevie<br></span>
<span class="verse-line">& environ sa char <span class="color-word">noircie<br></span></span>
<span class="verse-line">itant avoit <span class="color-word">noir</span> le menton<br></span>
<span class="verse-line"><span class="color-word">comme ce fust chies d'un tison<br></span></span>
<span class="verse-line">tot li erent <span class="color-word">noir</span> ci li oil<br></span>
<span class="verse-line"><span class="line-number">638</span><span class="negation">N'</span>avoit ore <span class="negation">.i. point d'</span>orgoil<br></span>
<span class="verse-line">Se vos en veisciés l'oreille<br></span>
<span class="verse-line">molt vos venist a grant merveille<br></span>
<span class="verse-line">Qui maigre estoit & decreue<br></span>
<span class="verse-line">& de <span class="color-word">blanc</span> poil tote molsue<br></span>
<span class="verse-line"><span class="line-number">643</span><span class="color-word">Noire</span> & molsue ert sa poitrine<br></span>
<span class="verse-line">bien resambloit escorce d'espine<br></span>
<span class="verse-line"><span class="negation">N'</span>avoit <span class="negation">de</span> char en ses traians<br></span>
<span class="verse-line"><span class="negation">Nient plus</span> qu'il est en .i. gans<br></span>
<span class="verse-line">les bras les mains & les lons dois<br></span>
<span class="verse-line"><span class="line-number">648</span>Avoit <span class="color-word">plus noirs que n'en est pois<br></span></span>
<span class="verse-line">molt par avoit les ongles grans<br></span>
<span class="verse-line"><span class="unique-verse">as dens les ront qu'ele ot trençans<br></span></span>
<span class="verse-line"><span class="folio-number">115va</span>li ventres li ert <span class="unique-verse">agaris<br></span></span>
<span class="verse-line"><span class="unique-verse">car <span class="negation">n'avoit nul</span> de ses delis<br></span></span>
<span class="verse-line"><span class="line-number">653</span>li pié li erent decrevé<br></span>
<span class="verse-line">& environ tot denavré<br></span>
<span class="verse-line">Ele <span class="negation">ne</span> se gardoit d'espine<br></span>
<span class="verse-line">Quant ele aloit par la gastine<br></span>
<span class="verse-line">Ce li ert vis son escient<br></span>
<span class="verse-line"><span class="line-number">658</span>del bien faisoit <span class="negation">petit u nient<br></span></span>
<span class="verse-line"><span class="sequence-change">Quant une espine le poignoit<br></span></span>
<span class="verse-line"><span class="sequence-change">En un de ses piés li chaoit<br></span></span>
<span class="verse-line">de ço estoit ele molt lie<br></span>
<span class="verse-line">Quant ele avoit la grant hascie<br></span>
<span class="verse-line"><span class="line-number">663</span><span class="negation">N'estoit merveille</span> si ert <span class="color-word">noircie<br></span></span>
<span class="verse-line">car molt demenoit aspre vie<br></span>
<span class="verse-line">plus de .xl. ans ala nue<br></span>
<span class="verse-line"><span class="negation">N'iert par merveille</span> si ert molsue<br></span>
<span class="verse-line">povre despens avoit od li<br></span>
<span class="verse-line"><span class="line-number">668</span><span class="unique-verse">Damedex</span> ait de li merci<br></span>
<span class="verse-line">.ii. pains avoit <span class="negation">ne gaires grans</span><br></span>
<span class="verse-line">de ces vesqui par pluisors ans<br></span>
<span class="verse-line">le premer an devindrent dur<br></span>
<span class="verse-line">com ce fuissent pieres de mur<br></span>
<span class="verse-line"><span class="line-number">673</span>chascun jor en usoit Marie<br></span>
<span class="verse-line">mais ço ert petite partie<br></span>
<span class="verse-line">Quant ele ot tot son pain usé<br></span>
<span class="verse-line">donques <span class="unique-verse">aquelt</span> l'erbe del pré<br></span>
<span class="verse-line">com autre beste le mangoit<br></span>
<span class="verse-line"><span class="line-number">678</span><span class="negation">de rien ne</span> se recomfortoit<br></span>
<span class="verse-line">as dens bevoit dou ruissel<br></span>
<span class="verse-line">Car <span class="negation">n'</span>i avoit autre vaiscel<br></span>
<span class="verse-line"><span class="negation">Ne</span> fait a plaindre li pechiet<br></span>
<span class="verse-line">dont li cors est si castiet<br></span>
<span class="verse-line"><span class="line-number">683</span>d'erbe vesqui & de racine<br></span>
<span class="verse-line">dis & set anz en la gastine<br></span>
<span class="verse-line">puis fu .xxx. anz <span class="negation">que ne</span> manga<br></span>
<span class="verse-line">Se l'angles Deu ne l'aporta<br></span>
<span class="verse-line">Dyable vint a li de premier<br></span>
<span class="verse-line"><span class="line-number">688</span>Sovent le soloit assaier<br></span>
<span class="verse-line">tot ce li faisoit ramenbrer<br></span>
<span class="verse-line">Qu'ele jadis soloit amer<br></span>
<span class="verse-line">les biaus delis & les bels lieus<br></span>
<span class="verse-line">ou ele seut faire ses gieus<br></span>
<span class="verse-line"><span class="line-number">693</span>ore fu ele boneuree<br></span>
<span class="verse-line">Quant de tot ce fu obliee<br></span>
<span class="verse-line"><span class="negation">Ainc gaires</span> puis en tote sa vie<br></span>
<span class="verse-line"><span class="negation">Ne</span> li sovint <span class="negation">puis</span> de folie<br></span>
<span class="verse-line"><span class="negation">Ne ainc</span> en trestot le boscage<br></span>
<span class="verse-line"><span class="line-number">698</span><span class="negation">Ne</span> vit <span class="negation">gaires</span> beste salvage<br></span>
<span class="verse-line"><span class="negation">Ne</span> autre vive creature<br></span>
<span class="verse-line">par la forest vait <span class="unique-verse">tote nue<br></span></span>
<span class="verse-line"><span class="folio-number">115vb</span>En pluisors lieus prist son ostal<br></span>
<span class="verse-line">Sa vie estoit esperital<br></span>
.....<br>
  </div>
  <div class="hover-text">
.....<br>
<span class="verse-line"><span class="line-number">157</span>Of her beauty, of her figure<br></span>
<span class="verse-line">(as it is in the written source)<br></span>
<span class="verse-line">I want to say a little — how they appeared —<br></span>
<span class="verse-line">before I go too far.<br></span>
<span class="verse-line">At that time and in that realm,<br></span>
<span class="verse-line"><span class="line-number">162</span>there was <span class="negation">never</span> a more beautiful woman.<br></span>
<span class="verse-line"><span class="negation">Never</span> countess <span class="negation">nor</span> queen<br></span>
<span class="verse-line"><span class="negation">had</span> on her head more beautiful hair.<br></span>
<span class="verse-line">She had round ears,<br></span>
<span class="verse-line">and they were marvelously <span class="color-word">white,<br></span></span>
<span class="verse-line"><span class="line-number">167</span>her eyebrows <span class="color-word">black</span> and becoming,<br></span>
<span class="verse-line">and her eyes <span class="color-word">sparkling</span> and joyful,<br></span>
<span class="verse-line">her mouth beautiful and well-proportioned,<br></span>
<span class="verse-line">and pleasing her expression,[^2]<br></span>
<span class="verse-line">her face tender and <span class="color-word">blushing<br></span></span>
<span class="verse-line"><span class="line-number">172</span><span class="color-word">like a freshly-bloomed rose.<br></span></span>
<div class="empty-line"></div>
<div class="empty-line"></div>
<span class="verse-line"><span class="negation">Indeed neither</span> on her nose <span class="negation">nor</span> on her chin<br></span>
<span class="verse-line">might you perceive <span class="negation">any</span> defect.<br></span>
<span class="verse-line">Her neck was <span class="color-word">white like ermine.<br></span></span>
<span class="verse-line">Long was her <span class="color-word">blonde</span> hair.[^7]<br></span>
<span class="verse-line"><span class="line-number">177</span><span class="sequence-change"><span class="negation">Not a bit bigger</span> than an apple was<br></span></span>
<span class="verse-line"><span class="sequence-change">either of the breasts of this lady.<br></span></span>
<span class="verse-line">Below her mouth on her chest,[^8]<br></span>
<span class="verse-line">it was <span class="color-word">as white as a hawthorn flower.<br></span></span>
<span class="verse-line">She had <span class="color-word">white arms</span> and <span class="color-word">white hands,<br></span></span>
<span class="verse-line"><span class="line-number">182</span>her fingers shapely, slender, and smooth.<br></span>
<span class="verse-line">She had a fine body and was well molded<br></span>
<span class="verse-line">from her underarm along her side.<br></span>
<span class="verse-line"><span class="negation">Neither too big nor too small,<br></span></span>
<span class="verse-line">her frame could <span class="negation">never</span> be described.<br></span>
<span class="verse-line"><span class="line-number">187</span>The great beauty of this lady<br></span>
<span class="verse-line">could <span class="negation">not</span> be written down fully by <span class="negation">any</span> man.<br></span>
<span class="verse-line">She was so courteous of speech;<br></span>
<span class="verse-line">there was <span class="negation">nothing</span> to improve.<br></span>
<span class="verse-line">Such a creature makes one lament<br></span>
<span class="verse-line"><span class="line-number">192</span>when she <span class="negation">does not</span> care about her Creator.<br></span>
<span class="verse-line">She received great presents,<br></span>
<span class="verse-line">and bought herself beautiful garments.<br></span>
<span class="verse-line">She had beautiful and fitting clothes<br></span>
<span class="verse-line">to please her lovers well.<br></span>
<span class="verse-line"><span class="line-number">197</span>She <span class="negation">did not</span> care for woollen cloth<br></span>
<span class="verse-line">on the worst day of the week.<br></span>
<span class="verse-line">She wore a fine <span class="color-word">purple silk</span> bliaut<br></span>
<span class="verse-line">and adorned herself with an ermine mantle.<br></span>
<span class="verse-line"><span class="folio-number">114rd</span><span class="color-word">Well-painted</span> shoes of Cordovan leather,<br></span>
<span class="verse-line"><span class="line-number">202</span>she wore all the days of the year.<br></span>
<span class="verse-line">The citizens of the city<br></span>
<span class="verse-line">loved her entirely for her beauty.<br></span>
<span class="verse-line">The aged men and the wise<br></span>
<span class="verse-line">all would say that it was a shame.<br></span>
<span class="verse-line"><span class="line-number">207</span>"Oh alas for this sufferer!<br></span>
<span class="verse-line">There is much to bemoan of her youth.<br></span>
<span class="verse-line">Alas evermore for her life<br></span>
<span class="verse-line">as it is so full of folly."<br></span>
<span class="verse-line">Everyone in the city would say<br></span>
<span class="verse-line"><span class="line-number">212</span>that she was of high parentage<br></span>
<span class="verse-line">for she answered all with reason<br></span>
<span class="verse-line">and had such a beautiful frame.<br></span>
<span class="verse-line">The son of an emperor<br></span>
<span class="verse-line">could have taken her with honor.[^3]<br></span>
.....<br>
<span class="verse-line"><span class="line-number">613</span>She went so long by day and by night,<br></span>
<span class="verse-line"><span class="unique-verse">through woods, through plains, and through hills,<br></span></span>
<span class="verse-line">and so deeply she went into the wood<br></span>
<span class="verse-line">that she became entirely wild there,<br></span>
<span class="verse-line">but she <span class="negation">never</span> forgot<br></span>
<span class="verse-line"><span class="line-number">618</span>to pray to saint Mary.<br></span>
<span class="verse-line">Often, she remembered the image,<br></span>
<span class="verse-line">which she had taken as a guarantor.<br></span>
<span class="verse-line">Her clothes were worn out,<br></span>
<span class="verse-line">and her soles were stripped.<br></span>
<span class="verse-line"><span class="line-number">623</span>As her clothes were in tatters,<br></span>
<span class="verse-line">her body was left totally naked.<br></span>
<span class="verse-line">Her own flesh <span class="color-word">changed color.<br></span></span>
<span class="verse-line">Before, it was <span class="color-word">white like a flower.<br></span></span>
<span class="verse-line">When she had been there for one winter,<br></span>
<span class="verse-line"><span class="line-number">628</span>her sides <span class="color-word">blackened</span> entirely.<br></span>
<span class="verse-line">Her <span class="color-word">blonde</span> hair changed greatly.<br></span>
<span class="verse-line"><span class="color-word">It turned white like an ermine<br></span></span>
<span class="verse-line"><span class="sequence-change">from the sun and from the frost.<br></span></span>
<span class="verse-line"><span class="sequence-change">Her face was very <span class="color-word">burned.<br></span></span></span>
<span class="verse-line"><span class="line-number">633</span>Her mouth was thinned,<br></span>
<span class="verse-line">and her flesh around it <span class="color-word">blackened.<br></span></span>
<span class="verse-line">Her chin was so <span class="color-word">black<br></span></span>
<span class="verse-line"><span class="color-word">it was like the head of a firebrand.<br></span></span>
<span class="verse-line">All <span class="color-word">black</span> were her eyes now.<br></span>
<span class="verse-line"><span class="line-number">638</span>She had, now, <span class="negation">not a shred</span> of pride.<br></span>
<span class="verse-line">If you saw her ears,<br></span>
<span class="verse-line">it would occur to you a great marvel<br></span>
<span class="verse-line">for they were skinny and shrunken[^4]<br></span>
<span class="verse-line">and all woolly with <span class="color-word">white</span> hairs.<br></span>
<span class="verse-line"><span class="line-number">643</span><span class="color-word">Black</span> and woolly was her chest.<br></span>
<span class="verse-line">It so resembled thorny bark.<br></span>
<span class="verse-line">She <span class="negation">did not</span> have flesh in her breasts,<br></span>
<span class="verse-line"><span class="negation">nothing more</span> than there is in a glove.<br></span>
<span class="verse-line">Her arms, her hands, and her long fingers<br></span>
<span class="verse-line"><span class="line-number">648</span>were <span class="color-word">blacker than pitch.<br></span></span>
<span class="verse-line">She had such large nails<br></span>
<span class="verse-line"><span class="unique-verse">she ripped them with her sharp teeth.<br></span></span>
<span class="verse-line"><span class="folio-number">115va</span>Her stomach was <span class="unique-verse">emaciated</span>[^9]<br></span>
<span class="verse-line"><span class="unique-verse">for she had <span class="negation">none</span> of her delights.<br></span></span>
<span class="verse-line"><span class="line-number">653</span>Her feet were split[^4]<br></span>
<span class="verse-line">and wounded all over.<br></span>
<span class="verse-line">She <span class="negation">did not</span> protect herself from thorns<br></span>
<span class="verse-line">as she went through the wilderness.<br></span>
<span class="verse-line">It seemed to her, in her mind,<br></span>
<span class="verse-line"><span class="line-number">658</span>that it would do <span class="negation">little or no good<br></span></span>
<span class="verse-line"><span class="sequence-change">for as a thorn pricked her<br></span></span>
<span class="verse-line"><span class="sequence-change">in one of her feet, it would fall away.<br></span></span>
<span class="verse-line">For this, she was very pleased.<br></span>
<span class="verse-line">As she bore great hardship,<br></span>
<span class="verse-line"><span class="line-number">663</span><span class="negation">it was no marvel</span> she was <span class="color-word">blackened<br></span></span>
<span class="verse-line">for she led a very severe life.<br></span>
<span class="verse-line">For more than forty years, she went about nude:<br></span>
<span class="verse-line"><span class="negation">it was no marvel</span> she was woolly.<br></span>
<span class="verse-line">She had poor provisions with her.<br></span>
<span class="verse-line"><span class="line-number">668</span>May <span class="unique-verse">God</span> have mercy on her.<br></span>
<span class="verse-line">She had two loaves of <span class="negation">no great size</span>.<br></span>
<span class="verse-line">On these she lived for many years.<br></span>
<span class="verse-line">The first year, they became hard<br></span>
<span class="verse-line">as though they were building stones.<br></span>
<span class="verse-line"><span class="line-number">673</span>Each day, Mary ate some,<br></span>
<span class="verse-line">but this was a small portion.<br></span>
<span class="verse-line">As soon as she had eaten up all her bread,<br></span>
<span class="verse-line">then she <span class="unique-verse">gathered</span> the grass of the field.<br></span>
<span class="verse-line">Like other beasts, she ate it.<br></span>
<span class="verse-line"><span class="line-number">678</span>She sought <span class="negation">no other</span> relief.<br></span>
<span class="verse-line">Prone, she drank from the stream<br></span>
<span class="verse-line">for there was <span class="negation">no</span> other vessel.<br></span>
<span class="verse-line"><span class="negation">Not</span> to be lamented is the sin<br></span>
<span class="verse-line">that chastised the body so.<br></span>
<span class="verse-line"><span class="line-number">683</span>On grass she lived and on roots<br></span>
<span class="verse-line">for seventeen years in the wilderness.<br></span>
<span class="verse-line">Then, for thirty years, she ate <span class="negation">only<br></span></span>
<span class="verse-line">what the angel of God brought to her.<br></span>
<span class="verse-line">The Devil came to her first.<br></span>
<span class="verse-line"><span class="line-number">688</span>Often, he used to tempt her,<br></span>
<span class="verse-line">making her remember all<br></span>
<span class="verse-line">that she once used to love:<br></span>
<span class="verse-line">the fine delights and the fine places<br></span>
<span class="verse-line">where she was used to playing her games.<br></span>
<span class="verse-line"><span class="line-number">693</span>Now, she felt blessed<br></span>
<span class="verse-line">as she had forgotten all of this.<br></span>
<span class="verse-line"><span class="negation">Hardly ever</span> again, for all her life,<br></span>
<span class="verse-line"><span class="negation">did</span> she think <span class="negation">then</span> of folly.<br></span>
<span class="verse-line"><span class="negation">Never</span> in all the wood<br></span>
<span class="verse-line"><span class="line-number">698</span><span class="negation">did</span> she see <span class="negation">any</span> wild beasts <span class="negation">at all<br></span></span>
<span class="verse-line"><span class="negation">nor any</span> other living creature.<br></span>
<span class="verse-line">Through the forest, she goes <span class="unique-verse">utterly naked.<br></span></span>
<span class="verse-line"><span class="folio-number">115vb</span>In many places, she took shelter.<br></span>
<span class="verse-line">Her life was spiritual.<br></span>
.....<br>
  </div>
</div>
:::

:::
:::

[^1]: Some might translate “Mais” at the start of this verse — which appears in copies T-A (v.166), T-B (v.158), and T-D (v.164) — with the conjunction ‘but’ to indicate that the roundness of Mary’s ears is a fault compensated for by the fact that they were marvelously white — as in ‘She had round ears, / but they were marvelously white.' However, this would violate the general rule of thumb for twelfth-century portraits that all of the characteristics of a beautiful person should be positive. Alice Colby writes that ears seldom receive much attention in the portraits of beautiful people and that ears are a feature commonly described in the portraits of ‘ugly creatures’ (96-97), but Mary the Egyptian complicates neat categorization between beauty and ugliness. It is, at least, likely that Mary’s ears are mentioned in Portrait 1 to create a more stark comparison between their initial beauty and their later condition in the desert. Therefore, I have translated *mais* in such a way that conveys the full initial beauty of her ears.
[^2]: Copies T-B (v.165), T-D (v.168), and T-E (v.170) each use a form of the adjective *piu* (pious; compassionate, merciful, benevolent, kind) to describe Mary the Egyptian’s *regardure* (glance, gaze; expression, outward appearance). Although it is a possible translation, ‘pious’ does not seem to be the best choice here as this verse portrays Mary during her most sinful period when she is explicitly indifferent toward God (v.192). Similarly, it seems inappropriate to suggest that Mary would have a ‘compassionate’ look when just before Portrait 1 (vv.126-148), the T-poet recounts Mary’s apparent pleasure at the sight of her many lovers stabbing each other to death at her feet. It may be that this verse foreshadows Mary’s renewed piety and benevolence in the second portrait, but in this moment, Mary’s body and way of being are otherwise only outwardly pleasing, so I have translated the phrase to convey her ‘pleasing expression.’ T-C also offers a challenging verse to interpret, uniquely describing her expression as *simple*, suggesting a plain look of humility, modesty, or innocence, but luckily the Modern English ‘simple’ satisfies these connotations. T-A is the only copy to list Mary’s foot among her positive qualities, suggesting in this verse that she is outwardly pleasing from head to toe.
[^3]: The translation of this verse in each of the copies intentionally leaves room for some ambiguity. While the verb *prendre* in this context may imply ‘to take in marriage,’ the verb also has the undeniable sexual connotation of ‘to take, have sexual intercourse with.’ Whether the poet means that the son of an emperor might have married Mary or only taken her in as his concubine, either way it is clear that the arrangement would be appropriate and honorable. Mary the Egyptian is not your average escort.
[^4]: While copies T-A and T-D end each of these verses — vv.639 & 651 in T-A and vv.643 & 653 in T-D — with the past participle of *decrever* (to smash, break; to crack, split), copies T-C and T-E initially use the past participle of *decrestre* (to decrease; to degrade; to shrink) — v.651 in T-C and v.641 in T-E — in order to meet the demands of the rhyme scheme, which pairs the past participle of *decrestre* with the adjective *mossu* (mossy; woolly; fuzzy). T-B follows the same pattern found in copies T-C and T-E but initially uses "degregue" (v.589 in T-B), which seems to be a misspelling of *degrader* (to degrade; to deteriorate).
[^5]: A *toise* is a unit of measurement of approximately six feet derived from an arm span. The scribe of T-B may be inviting the reader not just to think of Mary the Egyptian’s size but more specifically to consider the proportions of her upper body, which would be accentuated by her *bliaut*. With the end rhyme of “proise” — *proiser* (to value; to prize) in the following verse (v.182 in T-B), it is possible that the scribe is also implying that Mary’s body may be both ‘praised’ for its quality and ‘appraised’ for its worth.
[^6]: Readers might interpret the verb of this verse (v.616 in T-B) as *esrager* (‘to go mad, wild, or rabid’) — as in ‘then she went wild for the grasses of the fields’ — but that interpretation disrupts the otherwise peaceful existence Mary is experiencing the desert. Instead *esracher* (to uproot; to tear out; to pull away) has been applied here in alignment with the same verse as it appears in copies T-A (v.674), T-C (v.686), and T-D (v.676). Uniquely, T-E (v.676) uses the verb *acqueller* (to gather; to seize).
[^7]: It is not totally clear what word the scribe intended to write at the start of this verse (v.176 in T-E) — Dembowski puts a question mark next to the word in the variance notes of his edition (75n176) — but the manuscript clearly reads “Loiet.” It is possible the scribe miscopied an abbreviated form of the verb *ondoier* (to flow; to abound) from an exemplar, which would align well with the same verse as it appears in all other copies — apart from T-B which omits this verse. It could be that the scribe is using the verb *loer* (or *loier*) to say that her hair was ‘praised’ or ‘acclaimed.’ It is also possible — though less likely — that the scribe is using an unusual spelling of *lier*, which uncommonly may be spelled *loier*, meaning ‘bound’ or ‘tied.’ I have translated the word as ‘long’ to keep this verse in alignment with the meaning of the same verse in the other copies while also subtly signaling the uniqueness of this copy. Though “Loiet” is not at all an acceptable spelling of ‘long,’ it seems to me that ‘long’ may be the safest translation as it conveys what would be an expected trait for a beautiful woman’s hair in the context of a twelfth-century portrait: length.
[^8]: All other copies exclusively offer the spelling *bouche* for ‘mouth’ apart from T-B which uses the spelling *boce* twice (vv.164 & 169 of T-B). T-E is somewhat inconsistent, using the spelling *bouche* twice (vv.169 & 633) and *boce* once (v.179). That inconsistency paired with another meaning of *boce* (lump; hump; bump) and the relative ambiguity of *desus*, which could mean either ‘above’ or ‘below,’ allows for an alternative translation that uses Mary’s bust as a point of reference here as opposed to her mouth. The verse could, therefore, read something like 'Above the bump on her chest' (v.179 in T-E). Either way in every copy, this couplet refers to the whiteness of Mary’s décolletage, the space below her mouth and above her bustline.
[^9]: It is difficult to determine the precise meaning of the final word of this verse — "agaris” (v.651 in T-E). All other copies use various spellings of either the verb *chair* or *dechair*, meaning ‘to fall,’ ‘to decline,’ ‘to collapse,’ ‘to decay.’ It is possible that the scribe intended “agaris” to function as an antonym of *garir* (to heal; to protect; to feed), or the scribe might have meant to write an abbreviated variant spelling of *amegrir* (to make thin, lean). I have chosen the translation ‘emaciated’ to capture both the concepts of withering and starving.