# Bibliography {.unnumbered}

## Editions & Translations {.unnumbered}
Baker, Alfred Thomas. “Vie de Sainte Marie L’Egyptienne,” *Revue des langues romanes*, LIX (1916-1917), pp. 145-401. [edition]

Cooke, Matthew. *Robert Grossetete’s Chasteau d’Amour to Which Are Added ‘La Vie de sainte Marie Egyptienne’ and an English Version of the Chasteau d’Amour*. Caxton Society, 1852, pp. 62-113. https://hdl.handle.net/2027/hvd.32044081105124?urlappend=%3Bseq=76%3Bownerid=114643825-80. [edition]

Cruz-Sáenz, Michèle Schiavone. *The Life of Saint Mary of Egypt: An Edition and Study of the Medieval French and Spanish Verse Redactions*. Barcelona, Puvill, 1979. [edition]

Dembowski, Peter F. *La Vie de sainte Marie l’Égyptienne: Versions en ancien et en moyen français*. Geneva, Droz, 1977. [edition]

Magennis, Hugh. *The Old English Life of Saint Mary of Egypt: An Edition of the Old English Text with Modern English Parallel-Text Translation*. University of Exeter Press, 2002. [edition]

Ogden, Amy V., translator. *The Life of Saint Mary the Egyptian*. University of Virginia, 2020. (unpublished). [translation]

Tobler, Adolf. “Bruchstücke altfranzösischer Dichtung aus den in der Kubbet in Damaskus gefundenen Handschriften, 2. Ein Bruchstück eines Lebens der h. Maria aus Aegypten.” *Sitzungsberichte der königlich-preussischen Akademie der Wissenschaften, philosophisch-historische Classe*, LXIII, Berlin, 1903, pp. 966-969. [edition]

## Mary the Egyptian Scholarship
Acquafredda, Marilisa. “Modelli di santità femminile orientale nella Puglia del Medioevo: l'‘eremita penitente’ Maria Egiziaca.” *Archivio storico pugliese*, vol. 61, 2008, pp. 25-58.

Beresford, Andrew M. “Hagiography, corporeality, and the gaze: sexual/ascetic tension in the *Vida de Santa María Egipciaca*.” *Gender and Exemplarity in Medieval and Early Modern Spain*. Eds. Morrás, María, Sanmartín Bastida, Rebeca and Kim, Yonsoo. The Medieval and Early Modern Iberian World; 79. Leiden: Brill, 2020. pp.43-74.

Bisanti, Armando. “La figura di Zosima, padre ‘autorevole’, nella leggenda di Maria Egiziaca.” *Mediaeval Sophia*, vol. 13, 2013, pp. 32-43. https://www.academia.edu/4366218/BISANTI_La_figura_di_Zosima_padre_autorevole_nella_leggenda_di_Maria_Egiziaca. 

Black, John R. “Re-modelling Monastic Holiness: Saints’ Lives and Tensions in Monasticism in Early Medieval England.” *Rewriting Holiness: Reconfiguring Vitae, Re-signifying Cults*. Ed. Gray, Madeleine. King's College London Medieval Studies; 25. London: King's College London, Centre for Late Antique and Medieval Studies, 2017. pp. 51-71.

---. “Stripping the Saint: Formation and Transformation in the Cult of St. Mary of Egypt in Medieval England.” *Medieval Perspectives*, vol. 23, 2011 for 2008, pp. 1-16.

Blud, Victoria. “Speaking Up and Shutting Up: Expression and Suppression in the Old English Mary of Egypt and *Ancrene Wisse*.” *The Unspeakable, Gender, and Sexuality in Medieval Literature, 1000-1400*. D.S. Brewer, 2017, pp. 21-59.

Campbell, Emma. *Medieval Saints’ Lives: The Gift, Kinship and Community in Old French Hagiography*. Boydell & Brewer, 2008.

Cazelles, Brigitte. “Modèle ou Mirage: Marie l’Égyptienne.” *The French Review*, vol. 53, no. 1, American Association of Teachers of French, 1979, pp. 13–22. *JSTOR*, http://www.jstor.org/stable/391272.

Cortina, Lynn Rice. “The Aesthetics of Morality: Two Portraits of Mary of Egypt in the *Vida de Santa María Egipciaca*.” *Hispanic Journal*, vol. 2, no. 1, Fall 1980, pp. 41-45.

Cotter-Lynch, Margaret. “The Gender Genealogy of St. Mary of Egypt.” *Medieval Futurity: Essays for the Future of a Queer Medieval Studies*. Eds. Rogers, William and Roman, Christopher Michael. New Queer Medievalisms; 1. Kalamazoo, Mich.: Medieval Institute Publications, 2021. pp. 131-151. Doi: 10.1515/9781501513701-007

Chase, Colin. “Source Study as a Trick with Mirrors: Annihilation of Meaning in the Old English *Mary of Egypt*.” *Sources of Anglo-Saxon Culture*. Ed. Paul E. Szarmach. Kalamazoo: Medieval Institute Publications, Western Michigan University, 1986. pp. 23-33.

Dawson, Maureen Gillespie. “Hard lessons in Rutebeuf's *Lives of Mary of Egypt and Elizabeth of Hungary*.” *Neophilologus*, vol. 89, no. 3, 2005, pp. 329-341.

---. “Reading conversion in French medieval *saint’s lives*.” *Mediaevalia*, vol. 24, 2003, pp. 325-350.

Delfin, Rafael Robert. “The Devil and His Disciples in the Lives of Six Saints.” *The French Review*, vol. 62, no. 4, Mar. 1989, pp. 591-603. https://www.jstor.org/stable/395741.

Delmas, F. “Encore Sainte Marie l’Égyptienne.” *Revue des études byzantines*, vol. 5, no. 1, Persée - Portail des revues scientifiques en SHS, 1901, pp. 15–17. *Persée*, https://doi.org/10.3406/rebyz.1901.3376. 

---. “Remarques sur la vie de Sainte Marie l’Égyptienne.” *Revue des études byzantines*, vol. 4, no. 1, Persée - Portail des revues scientifiques en SHS, 1900, pp. 35–42. *Persée*, https://doi.org/10.3406/rebyz.1900.3313. 

Dembowski, Peter F. “Le poème anonyme sur sainte Marie L’Égyptienne: Est-il anglo-normand?” *Atti Del XIV Congresso Internazionale Di Linguistica e Filologia Romanza*, vol. 5, 1981, pp. 445–61.

De Vleeschauwer, Els. “Het Leven van Maria van Egypte in de *Bdinski Zbornik* (= Codex Gandavensis 408), ff. 162-191.” *Litterae Hagiologicae: Bulletin d'Hagiologia, Atelier belge d'études sur la sainteté / Aflevering van Hagiologia, Belgische Werkgroep voor Hagiologisch Onderzoek*, vol. 4, 1998, pp. 3-8.

Di Giorgi, Marianna. “Santa Maria Egiziaca tra Oriente e Occidente. La *Vita Sanctae Mariae Aegyptiacae Meretricis* di Paolo Diacono Napoletano.” *Schede medievali*, vol. 38, 2000, pp. 155-197.

Dimitrova, Margaret. “The *Vita Mariae Aegyptiacae* in Medieval and Early Modern Bulgarian Literature.” *Annual of Medieval Studies at CEU*, 1995 for 1993-1994, pp. 108-125.

Eidinow, Esther. “‘With masculine and perfect mind?’ Asceticism and the articulation of the female Christian self.” “*Zu Tisch bei den Heiligen* …”: *Askese, Nahrung und Individualisierung im spätantiken Mönchstum*. Eds. Albrecht, Daniel and Waldner, Katharina. Potsdamer altertumswissenschaftliche Beiträge; 63. Stuttgart: Franz Steiner, 2019. pp. 55-67.

Faccon, Manuela. “Due traduzioni iberiche della *Vida de santa María Egipciaca*: fonti possibili.” *Revista de literatura medieval*, vol. 10, 1998, pp. 83-100.

Foehr-Janssens, Yasmina. “L'antihéroïne est la sainte: à propos de la *Vie de sainte Marie l'Egyptienne*, II.” *PRIS-MA*, vol. 16, no. 1, 2000, pp. 47-59.

Francomano, Emily C. “‘Taking the gold out of Egypt’: Prostitution and the Economy of Salvation in the *Vida de María Egipciaca*.” *Hispanic Review*, vol. 82, no. 4, 2014, pp. 397-420. doi: 10.1353/hir.2014.0030

Gaunt, Simon. “Saints, Sex and Community: Hagiography.” *Gender and Genre in Medieval French Literature*. Cambridge University Press, 1995, pp. 180-233.

Grieve, Patricia E. “Paradise Regained in the *Vida de Santa María Egipçiaca*: Harlots, the Fall of Nations and Hagiographic Currency.” *Translatio Studii: Essays by his Students in Honor of Karl D. Uitti for his Sixty-Fifty Birthday*, ed. Renate Blumensfeld-Kosinski. Rodopi, 2000, pp. 133-154. 

Heron, Onnaca. “The Lioness in the Text: Mary of Egypt as Immasculated Female Saint.” *Quidditas*, vol. 21, 2000, pp. 23-44. *MLA International Bibliography*. http://humanities.byu.edu/rmmra/.

Howie, Cary. “As the Saint Turns: Hagiography at the Threshold of the Visible.” *Exemplaria: A Journal of Theory in Medieval and Renaissance Studies*, vol. 2, no. 2, 2005, pp. 317-346. *MLA International Bibliography*. 

Kaltsogianni, Eleni. “Zur Entstehung der Rede des Manuel II. Palaiologos auf die Heilige Maria von Ägypten [BHG 1044c].” *Parekbolai*, vol. 1, 2011, pp. 37-59.

Karras, Ruth Mazo. “Holy Harlots: Prostitute Saints in Medieval Legend.” *Journal of the History of Sexuality*, vol. 1, no. 1, University of Texas Press, 1990, pp. 3–32. *JSTOR*, http://www.jstor.org/stable/3704459.

---. “Sex, Money, and Prostitution in Medieval English Culture.” *Desire and Discipline: Sex and Sexuality in the Premodern West*. Eds. Murray, Jacqueline and Eisenbichler, Konrad. Toronto: University of Toronto Press, 1996. pp. 201-216. 

Kersten, H. “Van een monnik en een hoer. De legende van Maria Aegyptiaca in de Middelnederlandse verhaaltraditie.” *Literatuur*, vol. 9, no. 4, 1992, pp. 194-202.

Kjellman, Hilding. *La deuxième collection anglo-normande des miracles de la Sainte Vierge*. Slatkine Reprints, 1977.

Knust, Hermann. “Geschichte der Legende der h. Maria Aegyptiaca.” *Geschichte Der Legenden Der H. Katharina Von Alexandrien Und Der H. Maria Aegyptiaca Nebst Unedirten Texten*. Halle a. S.: M. Niemeyer, 1890. pp. 193-228.

Lees, Clare A., and Gillian R. Overing. “Seeing Women: Mary of Egypt (or, What *Did* Zosimus See?).” *Double Agents: Women and Clerical Culture in Anglo-Saxon England*. University of Pennsylvania Press, 2001, pp. 132-151.

Magennis, Hugh. “On the Source of non-Ælfrician Lives in the Old English *Lives of the Saints*, with Reference to the Cotton-Corpus Legendary.” *Notes and Queries*, n.s., vol. 32, no. 3, 1985, pp. 292-299. Doi: 10.1093/notesj/32.3.292

Maier, John R. “Sainthood, Heroism, and Sexuality in the *Estoria de Santa Maria Egipçiaca*.” *Revista canadiense de estudios hispánicos*, vol. 8, no. 3, 1984, pp. 424-435.

Mariani, Daniela. “La chevelure de sainte Marie l’Égyptienne d’après Rutebeuf: Contraste des sources et de la tradition iconographique.” *Perspectives médiévales*, vol. 38, 2017, pp. 1-23. Open Edition Journals, doi:10.4000/peme.12698

Maslanka, Christopher. “From Wench to Wonder Woman: Lenten Discipline and Miraculous Powers in the *South English Legendary*’s Life of Saint Mary of Egypt.” *Essays in Medieval Studies*, vol. 29, 2013, pp. 27-41. Doi: 10.1353/ems.2013.0007

McCulloch, Florence. “Villon’s Portrait of the Belle Heaulmière and Saint Mary the Egyptian.” *Mélanges de Linguistique, de Littérature et de Philologie Médiévales Offerts à J.R. Smeets*, 1982, pp. 187–93.

Meyer, Paul. “Notice du MS. Bibliothèque nationale Français 6447 (Traduction de divers livres de la Bible — Légendes des saints).” *Notices et extraits des manuscrits de la Bibliothèque nationale et autres bibliothèques*, vol. 35, no. 2, Imprimerie nationale, 1896, pp. 435-510. https://gallica.bnf.fr/ark:/12148/bd6t5404189c/f61.item.

Miller, Patricia Cox. “Is There a Harlot in This Text? Hagiography and the Grotesque.” *Journal of Medieval and Early Modern Studies*, vol. 33, no. 3, Sept. 2003, pp. 419–35, https://doi.org/10.1215/10829636-33-3-419. 

Mirachvili-Springer, Nana. “Les pécheresses repenties et les saintes travesties dans l'hagiographie géorgienne.” *Revue des études byzantines*, vol. 70, 2012, pp. 149-174.

Nash, Suzanne. “Rutebeuf’s Contribution to the Saint Mary the Egyptian Legend.” *The French Review*, vol. 44, no. 4, American Association of Teachers of French, 1971, pp. 695–705. *JSTOR*, http://www.jstor.org/stable/385570.

Noret, Jacques. “Un fragment de la *Vie de Marie l'Égyptienne* à New Haven.” *Analecta Bollandiana*, vol. 105, no. 1-2, 1987, pp. 133-134. Doi: 10.1484/J.ABOL.4.03189.

Ó Laoghaire, Diarmuid. “Beatha Eustasius agus Beatha Mhuire Éigiptí.” *Celtica*, vol. 21, 1990, pp. 489-522.

Petrova, Maya. “Holy Harlots from the *Bdinski Sbornik*: Some Observations on the Function of the Lives of Mary of Egypt, Thais and Maria, Abraham's Niece, within the Slavic Tradition.” *Annual of Medieval Studies at CEU*, 1999 for 1997-1998, pp. 273-282.

Petrović, Ivanka. “Les Vitae Patrum dans la littérature croate du Moyen Age.” *Scribere sanctorum gesta: Recueil d'études d'hagiographie médiévale offert à Guy Philippart*. Eds. Renard, Etienne, Trigalet, Michel, Hermand, Xavier and Bertrand, Paul. Hagiologia; 3. Turnhout: Brepols, 2005. pp. 283-307. Doi: 10.1484/M.HAG-EB.3.1722.

Pinto-Mathieu, Elisabeth. “Trois vies de pécheresses repenties: les saintes Marie l’Égyptienne, Marie-Madeleine et Thaïs.” *Revue des sciences humaines*, vol. 251, 1998, pp. 89–109. 

Poppe, Erich, and Bianca Ross. *The Legend of Mary of Egypt in Medieval Insular Hagiography*. Four Courts Press, 1996. 

Posa, Carmel M. “Mary and Zossima: Icons of Mutuality in the Spiritual Journey.” *Tjurunga: Australasian Benedictine Review*, vol. 57, 1999, pp. 5–21. 

Pouvreau, Florent. *Du Poil et de la bête: Iconographie Du Corps Sauvage En Occident à La Fin Du Moyen Âge, XIIIe-XVIe Siècle*. CTHS, 2014.

Robertson, Duncan. “‘Cume lur cumpaine et lur veisine’: women's roles in Anglo-Norman hagiography.” *Reassessing the Heroine in Medieval French Literature*. Ed. Krause, Kathy M.. Gainesville: University Press of Florida, 2001. pp. 13-25. 

---. “Poem and Spirit. The Twelfth-Century French Life of Saint Mary the Egyptian.” *Medioevo Romanzo*, vol. 7, no. 3, 1980, pp. 305–327.

---. “The Anglo-Norman Verse Life of St. Mary the Egyptian.” *Romance Philology*, vol. 52, no. 1, Brepols, 1998, pp. 13–44. *JSTOR*, https://www.jstor.org/stable/44742494. 

---. *The Medieval Saints’ Lives: Spiritual Renewal and Old French Literature*. French Forum, 1995.

---. “Twelfth-Century Literary Experience: The Life of St. Mary the Egyptian.” *Pacific Coast Philology*, vol. 22, no. 1/2, Penn State University Press, 1987, pp. 71–77. JSTOR, https://doi.org/10.2307/1316660.

Rudder, Orlando de. “La version X de *La vie de sainte Marie l'Egyptienne*. Mise en prose et catéchèse.” *Médiévales*, vol. 1, 1982, pp. 39-47. Doi: 10.3406/medi.1982.883.

Rutebeuf. “La Vie de Sainte Marie L’Égyptienne.” *Œuvres complètes*. edited by Michel Zink, Le Livre de Poche, 2001, pp. 453-529.

---. “Vie de Sainte Marie l’Egyptienne.” Œuvres complètes de Rutebeuf. Edited by Julia Bastin and Edmond Faral, vol. 2, 1960, pp. 9-59.

Sargent, Anne Marie. “The Penitent Prostitute: The Tradition and Evolution of the Life of St. Mary the Egyptian.” *Dissertation Abstracts International - A: The Humanities and Social Sciences*, vol. 83, no. 3, 1977, pp. 1375–76. 

Scarborough, Connie L. “Seeing and Believing: the Gaze in the *Vida de Santa María Egipçiaca*.” *La Corónica*, vol. 42, no. 1, 2013, pp. 299-319.

Scheil, Andrew. “Bodies and Boundaries in the Old English Life of St. Mary of Egypt.” *Neophilologus*, vol. 84, no. 1, Jan. 2000. https://doi.org/10.1023/A:1004628602435. 

Seidenspinner-Núñez, Dayle. “The Poetics of (non)Conversion: the *Vida de Santa María Egipçiaca* and *La Celestina*.” *Medievalia et humanistica*, n.s., vol. 18, 1992, pp. 95-128.

Szarmach, Paul E. “More Genre Trouble: the Life of Mary of Egypt.” *Writing Women Saints in Anglo-Saxon England*. Ed. Szarmach, Paul E.. Toronto Anglo-Saxon Series; 14. Toronto: University of Toronto Press, 2013. pp. 140-164.

Uhlig, Marion. “Le Mari de Marie et les figures de la clergie dans *La Vie de sainte Marie l'Egyptienne* de Rutebeuf.” *Revue des Langues romanes*, vol. 114, no. 1, 2010, pp. 179-201.

Villani, Matteo. “L'onomastica femminile nel ducato di Napoli: l'esempio di Maria.” *Mélanges de l'Ecole française de Rome. Moyen Age*, vol. 106, no. 2, 1994, pp. 641-651. Doi: 10.3406/mefr.1994.3393.

Ward, Benedicta. *Harlots of the Desert: A Study of Repentance in Early Monastic Sources*. Mowbray, 1987.

Walsh, Efthalia Makris. “The Ascetic Mother Mary of Egypt.” *The Greek Orthodox Theological Review*, vol. 34, no. 1, 1989. 

Watt, Diane and Clare A. Lees. “Age and Desire in the Old English *Life of St Mary of Egypt*: a Queerer Time and Place?.” *Middle-Aged Women in the Middle Ages*. Ed. Niebrzydowski, Sue. Gender in the Middle Ages. Cambridge: D.S. Brewer, 2011. pp. 53-67.

Zubillaga, Carina. “Categorías espaciales y dicotomías jerárquicas en la definición de la santidad femenina de María Egipciaca.” *Scripta mediaevalia*, vol. 11, no. 1, 2018, pp. 97-115.

---. “El desierto en la leyenda de Santa María Egipciaca.” *Olivar*, vol. 17, no. 26, 2016, pp. 1-9.

---. “El lenguaje del milagro en la *Vida de Santa María Egipciaca*.” *Revista de literatura medieval*, vol. 28, 2016, pp. 293-304.

---. “El papel del biógrafo en la conformación de la figura del santo en la Edad Media: el caso de la leyenda de santa María Egipcíaca.” *Fundación*, vol. 12, 2015, pp. 542-550.

---. “Imaginario y realidad de la muerte de Santa María Egipciaca en el contexto castellano de la crisis del siglo XIV.” *Estudios de historia de España*, vol. 14, 2012, pp. 121-134.

---. “La relación discursiva plegaria-profesía en *La vida de Santa María Egipcíaca*.” *Incipit*, vol. 32-33, 2013 for 2012-2013, pp. 231-246.

---.“La traducción medieval de la santidad femenina: las versiones occidentales francesa e hispánica de la leyenda de Santa María Egipciaca.” *Actas de las XIII Jornadas Internacionales de Estudios Medievales y XXIII Curso de Actualización de Historia Medieval*. Eds. Besarte, Ana and Barreiro, Santiago. Buenos Aires: SAEMED. Sociedad Argentina de Estudios Medievales, 2014. pp. 107-112.

---. “Pecados de juventud: inicios y desvíos de la leyenda medieval de Santa María Egipcíaca en Francia y España.” *Diálogos medievales: Estudios argentinos de literatura francesa*. Eds. Artal Maillie, Susana and Dumas, María. Buenos Aires: Universidad Nacional de General Sarmiento, 2017. pp. 101-106.

## Medievalist Digital Humanities Scholarship, Projects, & Repositories
Bahr, Arthur. “Miscellaneity and Variance in the Medieval Book.” *The Medieval Manuscript Book*, Cambridge University Press, 2015, pp.181-198. [scholarship]

Bamford, Heather and Emily C. Francomano. “On Digital-Medieval Manuscript Culture: A Tentative Manifesto.” *Digital Philology: A Journal of Medieval Cultures*, vol. 7, no.1, Spring 2018, pp. 29-45. [scholarship]

Busch, Hannah and Philipp Hegel. “Automatic Layout Analysis and Storage of Digitized Medieval Books.” *Digital Philology: A Journal of Medieval Cultures*, vol. 6, no. 2, Fall 2017, pp. 196-212. [scholarship]

*Digital Scriptorium 2.0*. https://digital-scriptorium.org/. [repository] 

Drimmer, Sonja. “Introduction: The Manuscript Copy and the Printed Original in the Digital Present.” *Digital Philology: A Journal of Medieval Cultures*, vol. 9, no. 2, Fall 2020, pp. 93-119. [scholarship]

Echard, Siân. “The Ghost in the Machine: Digital Avatars of Medieval Manuscripts.” *Printing the Middle Ages*, University of Pennsylvania Press, 2008, pp.198-216. [scholarship]

Fafinski, Mateusz. “Facsimile Narratives: Researching the Past in the Age of Digital Reproduction.” *Digital Scholarship in the Humanities*, vol. 37, no. 1, April 2022, pp. 94-108. [scholarship]

Foys, Martin, et al. *Old English Poetry in Facsimile 3.0*. Center for the History of Print and Digital Culture, University of Wisconsin-Madison, 2019-present, https://oepoetryfacsimile.org [repository]

Fritschi, Ramona. “e-codices – Virtual Manuscript Library of Switzerland: Great Achievements and Even Greater Challenges to Come.” *Digital Philology: A Journal of Medieval Cultures*, vol.6, no.2, Fall 2017, pp. 244-256. [scholarship]

*Fragmentarium*. Manuscript Research Center - University of Fribourg, 2013-present, https://fragmentarium.ms/. [repository]

Kiss, Farkas Gábor, et al. “Old Light on New Media: Medieval Practices in the Digital Age.” *Digital Philology: A Journal of Medieval Cultures*, vol. 2, no. 1, Spring 2013, pp. 16-34. [scholarship]

Lee, Loren. *dissertation* (Version 1.0.0), GitHub, 2025. https://github.com/leeloren/dissertation. [repository]

---. *marie-legyptienne* (Version 1.0.0), GitHub, 2024. https://github.com/leeloren/marie-legyptienne. [repository]

Lit, L. W. C. van (Lambertus Willem Cornelis). *Among Digitized Manuscripts: Philology, Codicology, Paleography In a Digital World*. Brill, 2020. [scholarship]

*Lives of the Saints: The Medieval French Hagiography Project*. directed by Amy V. Ogden, The Institute for Advanced Technology in the Humanities, 2006, https://frenchsaintslives.org/. Accessed 10 March 2025. [project]

Mahoney-Steel, Tamsyn. “Encoding and Decoding Machaut.” *Meeting the Medieval in a Digital World*, edited by Matthew Evan Davis, Tamsyn Mahoney-Steel, and Ece Turnator, Arc Humanities Press, 2018, pp. 123-142. [scholarship]

Nafde, Aditi and Emma Gorst. “Introduction: The Trials of the Digital Medievalist.” *Digital Philology: A Journal of Medieval Cultures*, vol. 4, no. 2, Fall 2015, pp. 147-159. [scholarship]

Nichols, Stephen G. *From Parchment to Cyberspace: Medieval Literature In the Digital Age*. Peter Lang Publishing, Inc, 2016. [scholarship]

---. “Introduction: Philology in a Manuscript Culture.” *The New Philology*, special issue of *Speculum: A Journal of Medieval Studies*, vol. 65, no.1, 1990, pp. 1-10. [scholarship]

Prescott, Andrew. “Ways of Seeing Manuscripts.” *Medieval Manuscripts in the Digital Age*, Routledge, 2020, pp.37-54. [scholarship]

Robertson, Abigail G. “A Note on Technology and Functionality in Digital Manuscript Studies.” *Medieval Manuscripts in the Digital Age*, Routledge, 2020, pp. 33-36. [scholarship]

Robinson, Peter. “Current issues in making digital editions of medieval texts — or, do electronic scholarly editions have a future?” *Digital Medievalist*, vol.1, no.1, 2005, http://doi.org/10.16995/dm.8. [scholarship]

---. “Electronic editions which we have made and which we want to make.” *Digital Philology and Medieval Texts*, Pacini, 2007, pp. 1-12. [scholarship]

---. “The Ends of Editing.” *Digital Humanities Quarterly*, vol. 3, no. 3, Summer 2009. [scholarship]

---. “How we have been publishing the wrong way, and how we might publish a better way.” *E-Publishing: Politics and Pragmatics*, edited by Gabriel Egan, Medieval and Renaissance Text Series, 2010, pp. 139-155. [scholarship]

*Roman de la Rose Digital Library*. directed by Tamsyn Mahoney-Steel, Stephen G. Nichols, and Sayeed Choudhury, Johns Hopkins Sheridan Libraries, 2007, https://dlmm.library.jhu.edu/romandelarose/. Accessed 10 March 2025. [project]

Szpiech, Ryan. “Cracking the Code: Reflections on Manuscripts in the Age of Digital Books.” *Digital Philology: A Journal of Medieval Cultures*, vol. 3, no. 1, Spring 2014, pp. 75-100. [scholarship]

Warren, Michelle R. *Holy Digital Grail: A Medieval Book on the Internet*, Redwood City: Stanford University Press, 2022. https://doi-org.proxy1.library.virginia.edu/10.1515/9781503631175 [scholarship]

Whearty, Bridget. *Digital Codicology: Medieval Books and Modern Labor*, Redwood City: Stanford University Press, 2022. https://doi-org.proxy1.library.virginia.edu/10.1515/9781503634190 [scholarship]

---. “Adam Scriveyn in Cyberspace: Loss, Labour, Ideology, and Infrastructure in Interoperable Reuse of Digital Manuscript Metadata.” *Meeting the Medieval in a Digital World*, edited by Matthew Evan Davis, Tamsyn Mahoney-Steel, and Ece Turnator, Arc Humanities Press, 2018, pp. 157-201. [scholarship]

## Other Digital Humanities References (Tools & Scholarship)
Allaire, J.J., et al. *Quarto*. Posit, PBC, 2022, https://quarto.org/. [tool]

Bolter, J. David, and Richard Grusin. *Remediation: Understanding New Media*. MIT Press, 1999. [scholarship]

Bryant, John. *The Fluid Text: A Theory of Revision and Editing for Book and Screen*. University of Michigan Press, 2002. [scholarship]

Tufte, Edward. *Seeing With Fresh Eyes: Meaning, Space, Data, Truth*. Graphis Press LLc, 2020. [scholarship]

Xie, Yihui. *bookdown: Authoring Books and Technical Documents with R Markdown*. Chapman & Hall, 2021. https://bookdown.org/yihui/bookdown/. [tool]

## Paris, BnF, Français 23112 (T-A)
Cloetta, Wilhelm. “Poème moral.” *Romanische Forschungen*, vol. 3, edited by Karl Vollmöller, Deichert, 1887, pp. i-x; 1-268. https://resolver.sub.uni-goettingen.de/purl?PPN345572629_0003.

Ginguené, Pierre-Louis. “Poètes français, Thibaut de Vernon, Alfrius et Lambert de Liège.” *Histoire littéraire de la France*, vol. 13, 1814, pp. 112-114. https://gallica.bnf.fr/ark:/12148/bpt6k6269361v/f146.item.r=Histoire%20litteraire%20de%20la%20France%201814%20Ginguene.

“Notice d’un manuscrit françois conservé dans la bibliothèque de Sorbonne.” *Histoire de l’Académie royale des inscriptions et belles-lettres, avec Les Mémoires de Littérature tirés des Registres de cette Acádemie, depuis l’année M. DCCXLIC, jusques & compris l’année M. DCCLI*, volume 23, edited by Charles Le Beau, Imprimerie royale, 1756, pp. 254-261. https://gallica.bnf.fr/ark:/12148/bpt6k57209789/f274.item.

Meyer, Paul. “Notice du MS. Bibliothèque nationale Français 6447 (Traduction de divers livres de la Bible — Légendes des saints).” *Notices et extraits des manuscrits de la Bibliothèque nationale et autres bibliothèques*, vol. 35, no. 2, Imprimerie nationale, 1896, pp. 435-510. https://gallica.bnf.fr/ark:/12148/bd6t5404189c/f61.item.

Omont, Henri. “Manuscrits français de la Bibliothèque nationale.” *Catalogue général des manuscrits français: Anciens petits fonds français*, vol. 2, edited by Ernest Leroux, Bibliothèque nationale, 1902, Manuscript 23112, pp. 64-65. https://hdl.handle.net/2027/hvd.32044050532084.

Rouse, Richard, and Mary Rouse. *Manuscripts and Their Makers: Commercial Book Producers in Medieval Paris, 1200-1500*. Harvey Miller, vol. 1, 2000, p. 375n138.

Section romane, notice de “Paris, Bibliothèque nationale de France, Manuscrits, fr. 23112” dans la base Jonas-IRHT/CNRS (permalink : http://jonas.irht.cnrs.fr/manuscrit/71291).


## Oxford, Bodleian, Canonici Misc. 74 (T-B)
Campbell, Emma. *Medieval Saints’ Lives: The Gift, Kinship and Community in Old French Hagiography*. Boydell & Brewer, 2008, pp. 205-222; 236-237; 240-241.

“Canonici.” Digital Bodleian, https://digital.bodleian.ox.ac.uk/collections/canonici/.

Coxe, Henry Octavius. *Catalogi codicum manuscriptorum Bibliothecæ Bodleianæ pars tertia codices Græcos et Latinos Canonicianos complectens*, vol. 3, Quarto Catalogues, 1854, Manuscript 74, pp. 400; 480-481. https://archive.org/details/CanoniciGreekAndLatin/page/n243/mode/2up.

Ogden, Amy V. *Hagiography, Romance and the Vie de Sainte Eufrosine*. Edward C. Armstrong Monographs, 2003.

Rankka, Erik. *Li ver del juïse: Sermon en vers du XIIe siècle*. University of Uppsala, 1982.

Section romane, notice de “OXFORD, Bodleian Library, Canonici misc. 074” dans la base Jonas-IRHT/CNRS (permalink : http://jonas.irht.cnrs.fr/manuscrit/73461).

*The Life of Saint Eufrosine: In Old French Verse, with English Translation*. edited by Amy V. Ogden, MLA Texts & Translations, 2021.

## Oxford, Corpus Christi College, 232 (T-C)
Coxe, Henry Octavius. *Catalogus codicum mss. qui in collegiis aulisque Oxoniensibus hodic adservantur*, vol. 2, Oxonii, 1852, Manuscript 232, pp. 94-95. https://archive.org/details/cataloguscodicummssquiincoll2/page/n225/mode/2up.

Dee, John. *John Dee’s Diary, Catalogue of Manuscripts and Selected Letters*. edited by James Orchard Halliwell, et al. Cambridge University Press, 2013. https://doi-org.proxy1.library.virginia.edu/10.1017/CBO9781139245791.

---. *The Private Diary of Dr. John Dee, and the Catalogue of his Library of Manuscripts: From the Original Manuscripts in the Ashmolean Museum at Oxford, and Trinity College Library, Cambridge*. edited by James Orchard Halliwell-Phillipps, Camden Society, 1842. https://hdl.handle.net/2027/uc2.ark:/13960/t9183m473.

Section romane, notice de “OXFORD, Corpus Christi College, 232” dans la base Jonas-IRHT/CNRS (permalink : http://jonas.irht.cnrs.fr/manuscrit/73474).

*St Augustine's Abbey, Canterbury*. Corpus of British Medieval Library Catalogues, 13, edited by Barker-Benfield, B. C., vol. 1-3, The British Library, in association with the British Academy, 2008.

Thomson, Rodney M. *A Descriptive Catalogue of the Medieval Manuscripts of Corpus Christi College, Oxford*. D.S. Brewer, 2011, Manuscript 232, pp. 116-117.

## Paris, BnF, Français 19525 (T-D)
Avril, François, and Patricia Danz Stirnemann. *Manuscrits enluminés d’origine insulaire: VIIe-XXe siècle*. Bibliothèque nationale, 1987, no. 107, Manuscript 19525, pp. 67-68.

Delisle, Léopold. *Le Cabinet des manuscrits de la Bibliothèque nationale: Étude sur la formation de ce dépôt comprenant les éléments d’une histoire de la calligraphie de la miniature, de la reliure, et du commerce des livres à Paris avant l’invention de l’imprimerie*, vol. 2, Imprimerie Nationale, 1874, pp. 40-58; 78-99. https://hdl.handle.net/2027/gri.ark:/13960/t7mp83h82.

Omont, Henri. *Catalogue général des manuscrits français. Ancien Saint-Germain français*, vol. 3, Bibliothèque nationale, 1900, Manuscript 19525, pp. 339-341. https://archive.org/details/CatalogueGeneralDesManuscritsAncStGermFr3/page/n353/mode/2up. 

Rankka, Erik. *Li ver del juïse: Sermon en vers du XIIe siècle*. University of Uppsala, 1982.

Guillaume le Clerc de Normandie. *Le Besant de Dieu*. edited by Pierre Ruelle, Éditions de l’Université de Bruxelles, 1973, pp. 12-13.

---. *Le Besant de Dieu*. edited by Ernst Martin, Halle, 1869, pp. i-x. https://hdl.handle.net/2027/hvd.32044087007282.

Section romane, notice de “Paris, Bibliothèque nationale de France, Manuscrits, fr. 19525” dans la base Jonas-IRHT/CNRS (permalink : http://jonas.irht.cnrs.fr/manuscrit/45875).

Söderhjelm, Werner. *De Saint Laurent: Poème Anglo-Normand du XIIe siècle*. H. Welter, 1888. https://hdl.handle.net/2027/hvd.32044087007332.

Wace. *La vie de Sainte Marguerite, poème inédit de Wace précédé de l’histoire de ses transformations et suivi de divers textes inédits et autres et de l’analyse détaillée du mystère de Sainte Marguerite*. edited by Aristide Joy, Vieweg, 1879, pp. 10-12. https://archive.org/details/laviedesaintemar00waceuoft/page/10/mode/2up.

## Paris, BnF, Arsenal 3516 (T-E)
Benedeit. *The Anglo-Norman Voyage of St. Brendan, a Poem of the Early Twelfth Century*. edited by Edwin George Ross Waters, Oxford Clarendon Press, 1928, pp. xviii-xix.

Blacker, Jean, et al. *Wace, the Hagiographical Works: The Conception Nostre Dame and the Lives of St. Margaret and St. Nicholas*. translated with introduction and notes by Jean Blacker, Glyn S. Burgess, and Amy V. Ogden, with original texts included, Brill, 2013. https://ebookcentral-proquest-com.proxy1.library.virginia.edu/lib/uva/detail.action?docID=1214278.

Francis, Elizabeth A. Introduction to Wace’s *La vie de Sainte Marguerite*, edited by Elizabeth, Champion, 1932, pp. iii-xxxii.

Guggenbühl, Claudia. *Recherches sur la composition et la structure du ms. Arsenal 3516*, A. Francke Verlag, 1998.

Laurent, Françoise, et al. Introduction to Wace’s *Vie de sainte Marguerite, Conception Nostre Dame, Vie de Saint Nicolas*, edited and translated by Françoise Laurent, Françoise Le Saux, and Nathalie Bragantini-Maillard, Champion, 2019, pp. 9-69.

Leurquin, Anne-Françoise. “Paris, Bibliothèque de l’Arsenal 3516.” *Album de manuscrits français du XIIIe siècle : mise en page et mise en texte*. edited by Maria Careri, Françoise Fery-Hue, Françoise Gasparri, Geneviève Hasenohr, Gillette Labory, Sylvie Lefèvre, Anne-Françoise Leurquin, Christine Ruby, 2001, pp. 139-141.

Martin, Henry. *Catalogue des manuscript de la Bibliothèque de l’Arsenal*, vol. 3, Plon, 1887, Manuscript 3516, pp. 395-405. https://archive.org/details/cataloguedesmanu03bibl/page/394/mode/2up.

Rouse, Richard, and Mary Rouse. *Manuscripts and Their Makers: Commercial Book Producers in Medieval Paris, 1200-1500*. Harvey Miller, vol. 1, 2000, p. 375n138.

Section romane, notice de “Paris, Bibliothèque de l'Arsenal, 3516” dans la base Jonas-IRHT/CNRS (permalink : http://jonas.irht.cnrs.fr/manuscrit/43012).


## London, British Library, Add. 36614 (T-L)
Ashburnham Library. *Catalogue of the Portion of the Famous Collection of Manuscripts, the Property of the Right Honorable the Earl of Ashburnham, known as The Barrois Collection, which Will Be Sold by Auction*. Sotheby, Wilkinson, & Hodge, 1901, Lot 463, pp. 171-172 with an image of the ivory cover tipped in between pp. 170-171. https://archive.org/details/ashburnhamlibrar00ashbuoft/page/n197/mode/2up.

*Catalogue of Additions to the Manuscripts in the British Museum in the Years MDCCCC - MDCCCCV [1900-1905]*. British Museum, 1907. Manuscript 36614, pp. 156-157. https://archive.org/details/CatalogueOfAdditionsToTheMSS19005/page/n177/mode/2up.

Chrétien de Troyes. *The Continuations of the Old French Perceval of Chrétien de Troyes*. edited by William Roach, 1949, pp. xx-xxii.

Cockburn, Calum. “Our digitised collection keeps on growing.” *Medieval manuscripts blog*, British Library, 18 Jan 2022, https://blogs.bl.uk/digitisedmanuscripts/2022/01/our-digitised-collection-keeps-on-growing.html.

“Learning Lessons from the Cyber-Attack: British Library cyber incident review.” *Knowledge Matters blog*, British Library, 8 March 2024, https://www.bl.uk/home/british-library-cyber-incident-review-8-march-2024.pdf/.

Micha, Alexandre. *La tradition manuscrite des romans de Chrétien de Troyes*. 2nd ed., Droz, 1966, pp.61-62.

Section romane, notice de “LONDON, British Library, Add MS 36614” dans la base Jonas-IRHT/CNRS (permalink : http://jonas.irht.cnrs.fr/manuscrit/30094).

Unknown artist. *panel; casket*. c.10th-11th century, The British Museum, London, Registration number 1901,1230.1. *The British Museum*, https://www.britishmuseum.org/collection/object/H_1901-1230-1.

Williman, Daniel and Karen Corsano. “In the British Royal Library.” *The World Chronicle of Guillaume de Nangis: A Manuscript’s Journey from Saint-Denis to St. Pancras*. New edition ed. Medieval Institute Publications, 2020, pp. 167-173. https://muse.jhu.edu/book/77966. 

## Manchester, John Rylands Library, French 6 (T-F^1^)
Brun, Laurent. “Manuscrit: United Kingdom / London / British Library / Egerton 2710.” *Arlima: Archives de littérature du Moyen Âge*, https://arlima.net/no/4668. 2 June 2024.

Fawtier, R. and E. C. Fawtier-Jones. “Notice du manuscrit *French 6* de la John Rylands Library, Manchester.” *Romania*, vol. 49, 1923, pp. 321-342.

Ker, Neil Ripley. *Medieval manuscripts in British Libraries*. Oxford Clarendon Press, vol. 3, 1983, Manuscript French 6, p.433. https://archive.org/details/medievalmanuscri0003kern/page/432/mode/2up?q=%22fr.+6%22.

Marie-Laure Savoye, notice de “LONDON, British Library, Egerton MS 2710; MANCHESTER, John Rylands University Library, French MS 6” dans la base Jonas-IRHT/CNRS (permalink : http://jonas.irht.cnrs.fr/manuscrit/30588).

Rankka, Erik. *Li ver del juïse: Sermon en vers du XIIe siècle*. University of Uppsala, 1982.

Russell, D. W. and Clive D. Field. “The Manuscript Source of the Fragment, Rylands French MS 6.” *Bulletin of the John Rylands University Library of Manchester*, vol. 71, no. 1, 1989, pp. 41-47. https://luna.manchester.ac.uk/luna/servlet/detail/Manchester~25~25~2057~199917.

Tyson, Moses. “Hand-list of the Collections of French and Italian Manuscripts in the John Rylands Library.” *Bulletin of the John Rylands University Library of Manchester*, vol. 14, no. 2, 1930, Manuscript 6, pp.572-573.

## Berlin, Staatsbibliothek, MSS Simulata Orientalia 6 (T-F^2^)
Giannini, Gabriele and Laura Minervini. “The Old French Texts of the Damascus Qubba.” *The Damascus Fragments: Towards a History of the Qubbat al-khazna Corpus of Manuscripts and Documents*. edited by Arianna d’Ottone Rambach, Konrad Hirschler, and Ronny Vollandt, Ergon Verlag, 2020, pp. 331-362.

Radiciotti, Paolo, and Arianna D’Ottone. “I frammenti della Qubbat al-hazna di Damasco: A proposito di una scoperta sottovalutata.” *Nea Rhome*, vol. 5, 2008, pp. 45-74.

## Old & Middle French Reference Texts
*Anglo-Norman Dictionary (AND2 Online Edition)*, Aberystwyth University, 2021. https://anglo-norman.net/.

Campion, Edmund J. “Early Modern French Literature.” *Scholarly Editing: A Guide to Research*, MLA, 1995, pp. 417-437.

Cerquiglini, Bernard. *Éloge de la variante: Histoire critique de la philologie*. Éditions du Seuil, 1989.

Derolez, Albert. *The Paleography of Gothic Manuscripts*. Cambridge University Press, 2001.

*Dictionnaire du Moyen Français*, version 2020 (DMF 2020). ATILF - CNRS & Université de Lorraine. http://www.atilf.fr/dmf.

Foulet, Alfred and Mary Blakely Speer. *On Editing Old French Texts*. Regents Press of Kansas, 1979.

Godefroy, Frédéric. *Dictionnaire de l’ancienne langue française, et de tous ses dialectes du IXe au XVe siècle*. F. Vieweg, 1881.

Matsumura, Takeshi, and Michel Zink, editor. *Dictionnaire du français médiéval*. Les Belles Lettres, 2015.

Speer, Mary B. “Old French Literature.” *Scholarly Editing: A Guide to Research*, MLA, 1995, pp. 382-416.

## Epigraph
Thomas. “Le Roman de Tristan.” *Tristan et Iseut: Les poèmes français et La saga norroise*. Edited and translated by Philippe Walter, Lettres gothiques, 1989, pp. 329-481.